### ISSUE TITLE
CustomImportOrder not working as expected

### ISSUE THREAD

**Issue by blindahl** [checkstyle/checkstyle#11642] opened 2022-05-15 16:54 UTC
I have read check documentation: https://checkstyle.org/config_imports.html#CustomImportOrder
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```cmd
/var/tmp $ javac YOUR_FILE.java
Yes, no errors

/var/tmp $ cat config.xml
#[[
    <module name="CustomImportOrder">
        <property name="severity" value="error"/>
        <property name="customImportOrderRules" value="STANDARD_JAVA_PACKAGE###THIRD_PARTY_PACKAGE###SPECIAL_IMPORTS###SAME_PACKAGE(3)###STATIC"/>
        <property name="standardPackageRegExp" value="java|javax|jakarta"/>
        <property name="thirdPartyPackageRegExp" value="third.party|se.pkg1.pkgnotx"/>
        <property name="specialImportsRegExp" value="se.pkg1"/>
        <property name="sortImportsInGroupAlphabetically" value="true"/>
        <property name="separateLineBetweenGroups" value="true"/>
    </module> 

]]
```

```cmd
/var/tmp $ type HelloWorld.java
#[[$ type src\se\pkg1\pkgx\HelloWorld.java                                   
package se.pkg1.pkgx;                                                     
                                                                          
import third.party.SomeClassThirdParty;                                                                         
import se.pkg1.pkgnotx.SomeClassY1;                                       
                                                                          
import se.pkg1.pkgx.SomeClassX1;                                          
import se.pkg1.pkgx.SomeClassX2;                                          
                                                                          
class HelloWorld {                                                        
  public static void main(String[] args) {                                
    SomeClassThirdParty someClassThirdParty = new SomeClassThirdParty();  
    someClassThirdParty.noOp();                                           
    SomeClassY1 someClassY1 = new SomeClassY1();                          
    someClassY1.noOp();                                                   
    SomeClassX1 someClassX1 = new SomeClassX1();                          
    someClassX1.noOp();                                                   
    SomeClassX2 someClassX2 = new SomeClassX2();                          
    someClassX2.noOp();                                                   
  }                                                                       
}
]]
```

```cmd
set RUN_LOCALE="-Duser.language=en -Duser.country=US"
java %RUN_LOCALE% -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
```
$ java %run_locale% -jar checkstyle-10.2-all.jar -c config.xml src\se\pkg1\pkgx\HelloWorld.java
Starting audit...
[ERROR] C:\gitco\checkstyle-bug-report\src\se\pkg1\pkgx\HelloWorld.java:4:1: 'se.pkg1.pkgnotx.SomeClassY1' should be separated from previous import group by one line. [CustomImportOrder]
Audit done.
Checkstyle ends with 1 errors.
```
---

**Describe what you expect in detail.**
Expected order I think should be as in HelloWorld.java.

Since _se.pkg1.pkgnotx_ is defined as THIRD_PARTY_PACKAGE I think it should be in THIRD_PARTY_PACKAGE group even though SPECIAL_IMPORTS is defined as _se.pkg1_ since matching against THIRD_PARTY_PACKAGE is more specific than SPECIAL_IMPORTS.

Also SAME_PACKAGE(3) should not be relevant if they are in se.pkg1.pkgx.* only if they are in se.pkg1.*. 

_A side note._
The example codebase is a bit weird where I have _se.pkg1.pkgx_ and _se.pkg1.pkgnotx_ in the same folder structure where _se.pkg1.pkgnotx_ is a dependency from maven, created from another part of my organization so for my team/application's point of view it's considered third party but I get the same behavior in this example codebase as in my regular codebase.
---

**Comment by nick-mancuso** [comment] 2022-05-21 13:27
@blindahl please follow issue template, and make all code examples compilable. We need to be able to readily reproduce your problem in order to approve this issue.

**Comment by blindahl** [comment] 2022-05-21 14:07
> @blindahl please follow issue template, and make all code examples compilable. We need to be able to readily reproduce your problem in order to approve this issue.

Ok, I'll try to reproduce it but do you agree that it is the wrong order or is it me missunderstanding how the CustomImportOrder should work?

**Comment by blindahl** [comment] 2022-05-21 16:41
@nick-mancuso 
Alright, I've reproduced the bug and updated the comment. I've commited my example codebase to my github as well:
https://github.com/blindahl/checkstyle-bug-report

**Comment by romani** [comment] 2022-05-21 18:45
>I have read check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck

Please fix link to make sure you know what you are talking about and you read right document.

**Comment by blindahl** [comment] 2022-05-21 19:26
Updated link. I've read latest documentation and used latest version of Checkstyle as you see in the execution above. As far as I know i understand how CustomImportOrder is intended to work but please correct me if I'm wrong. 

I used original google check but added the modified module definition for CustomImportOrder.

**Comment by blindahl** [comment] 2022-06-05 07:03
Am I interpreting how CustomImportOrder should work or is this sort of an edge case not being handled properly?

**Comment by rnveach** [comment] 2022-06-05 12:42
@blindahl I am not able to reproduce your case.

````
$ cat TestClass.java
package se.pkg1.pkgx;                                                     
                                                                          
import third.party.SomeClassThirdParty;                                   
                                                                          
import se.pkg1.pkgnotx.SomeClassY1;                                       
                                                                          
import se.pkg1.pkgx.SomeClassX1;                                          
import se.pkg1.pkgx.SomeClassX2;                                          
                                                                          
class HelloWorld {                                                        
  public static void main(String[] args) {                                
    SomeClassThirdParty someClassThirdParty = new SomeClassThirdParty();  
    someClassThirdParty.noOp();                                           
    SomeClassY1 someClassY1 = new SomeClassY1();                          
    someClassY1.noOp();                                                   
    SomeClassX1 someClassX1 = new SomeClassX1();                          
    someClassX1.noOp();                                                   
    SomeClassX2 someClassX2 = new SomeClassX2();                          
    someClassX2.noOp();                                                   
  }                                                                       
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
    <module name="CustomImportOrder">
        <property name="severity" value="error"/>
        <property name="customImportOrderRules" value="STANDARD_JAVA_PACKAGE###THIRD_PARTY_PACKAGE###SPECIAL_IMPORTS###SAME_PACKAGE(3)###STATIC"/>
        <property name="standardPackageRegExp" value="java|javax|jakarta"/>
        <property name="thirdPartyPackageRegExp" value="third.party|se.pkg1.pkgnotx"/>
        <property name="specialImportsRegExp" value="se.pkg1"/>
        <property name="sortImportsInGroupAlphabetically" value="true"/>
        <property name="separateLineBetweenGroups" value="true"/>
    </module> 
    </module>
</module>

$ java -jar checkstyle-10.2-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````

**Comment by blindahl** [comment] 2022-06-05 15:50
> @blindahl I am not able to reproduce your case as I get no violations.
> 
> ```
> $ cat TestClass.java
> package se.pkg1.pkgx;                                                     
>                                                                           
> import third.party.SomeClassThirdParty;                                   
>                                                                           
> import se.pkg1.pkgnotx.SomeClassY1;                                       
>                                                                           
> import se.pkg1.pkgx.SomeClassX1;                                          
> import se.pkg1.pkgx.SomeClassX2;                                          
>                                                                           
> class HelloWorld {                                                        
>   public static void main(String[] args) {                                
>     SomeClassThirdParty someClassThirdParty = new SomeClassThirdParty();  
>     someClassThirdParty.noOp();                                           
>     SomeClassY1 someClassY1 = new SomeClassY1();                          
>     someClassY1.noOp();                                                   
>     SomeClassX1 someClassX1 = new SomeClassX1();                          
>     someClassX1.noOp();                                                   
>     SomeClassX2 someClassX2 = new SomeClassX2();                          
>     someClassX2.noOp();                                                   
>   }                                                                       
> }
> 
> $ cat TestConfig.xml
> <?xml version="1.0"?>
> <!DOCTYPE module PUBLIC
>           "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
>           "https://checkstyle.org/dtds/configuration_1_3.dtd">
> 
> <module name="Checker">
>     <property name="charset" value="UTF-8"/>
> 
>     <module name="TreeWalker">
>     <module name="CustomImportOrder">
>         <property name="severity" value="error"/>
>         <property name="customImportOrderRules" value="STANDARD_JAVA_PACKAGE###THIRD_PARTY_PACKAGE###SPECIAL_IMPORTS###SAME_PACKAGE(3)###STATIC"/>
>         <property name="standardPackageRegExp" value="java|javax|jakarta"/>
>         <property name="thirdPartyPackageRegExp" value="third.party|se.pkg1.pkgnotx"/>
>         <property name="specialImportsRegExp" value="se.pkg1"/>
>         <property name="sortImportsInGroupAlphabetically" value="true"/>
>         <property name="separateLineBetweenGroups" value="true"/>
>     </module> 
>     </module>
> </module>
> 
> $ java -jar checkstyle-10.2-all.jar -c TestConfig.xml TestClass.java
> Starting audit...
> Audit done.
> ```

That's really weir. I checked out my repo https://github.com/blindahl/checkstyle-bug-report.git again on another machine, linux this time, ran it with 10.3 and got the same result:
```
checkstyle-bug-report git:(main) ✗ java $RUN_LOCALE -jar checkstyle-10.3-all.jar -c config.xml src/se/pkg1/pkgx/HelloWorld.java
Starting audit...
[ERROR] /home/bear/Documents/GitHub/checkstyle-bug-report/blindahl/checkstyle-bug-report/src/se/pkg1/pkgx/HelloWorld.java:4:1: 'se.pkg1.pkgnotx.SomeClassY1' should be separated from previous import group by one line. [CustomImportOrder]
Audit done.
Checkstyle ends with 1 errors.
```

**Comment by rnveach** [comment] 2022-06-05 17:28
@blindahl I see the issue, your template has the blank line in it while your repo does not.

**Comment by blindahl** [comment] 2022-06-05 17:38
@rnveach 
I'm so sorry for the sloppy bug report resulting in unnecessary work for you. I changed my original post to reflect the same as my repo. With this corrected you should get the same error for my java-file.

**Comment by rnveach** [comment] 2022-06-05 18:03
@blindahl I believe your issue is `specialImportsRegExp`. It matches your `thirdPartyPackageRegExp` exactly.

https://github.com/checkstyle/checkstyle/blob/399f1b48b79731d65e824eb927971ef6174c3463/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.java#L1078
In this scenario, third party is the catch all if nothing else matches. Unfortunately, your regexp matches special and so it feels `se.pkg1.pkgnotx.SomeClassY1` is special and not 3rd party.

https://checkstyle.org/config_imports.html#CustomImportOrder_Notes
> THIRD_PARTY has the least priority

I recommend making special more specific to avoid the confusion. I also recommend remembering all these are regexp, and you should escape the periods and ensure you match the start of the string.

When I swapped special with something else, I get the violation:
````
[ERROR] src\se\pkg1\pkgx\HelloWorld.java:4:1: Wrong lexicographical order for 'se.pkg1.pkgnotx.SomeClassY1' import. Should be before 'third.party.SomeClassThirdParty'. [CustomImportOrder]
````
Which makes sense to me.

**Comment by rnveach** [comment] 2022-06-07 00:19
I am closing this as it doesn't seem like an issue. It can be reopened if an issue is identified.

**Closed by rnveach** 2022-06-07 00:19 UTC

**Comment by blindahl** [comment] 2022-06-07 04:35
Alright, good it's working as expected. Thanks för your time looking into it and clearifying. I'll adjust my regexp matches as recommended as well.
