### ISSUE TITLE
pitest: increase mutation coverage for pitest-checks-coding profile to 100%

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#5008] opened 2017-08-25 19:32 UTC
We should increase coverage for pitest-checks-coding profile up to 100%.
This issue is a subtask of #3708

Current threshold of pitest-checks-coding profile: 95

-------

<a href="https://www.bountysource.com/issues/48651818-pitest-increase-mutation-coverage-for-pitest-checks-coding-profile-to-100">
<img src="https://api.bountysource.com/badge/issue?issue_id=48651818">
</a>

**Comment by rnveach** [comment] 2017-12-05 19:04
Current pitest report: http://rveach.no-ip.org/checkstyle/regression/pitest-reports/5/com.puppycrawl.tools.checkstyle.checks.coding/index.html

**Comment by rnveach** [comment] 2017-12-06 14:20
I am working on this.

**Comment by rnveach** [comment] 2017-12-06 15:46
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/5/com.puppycrawl.tools.checkstyle.checks.coding/FallThroughCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@2ae499cb_400
This item isn't being killed because `Comment.intersects` is too lenient on checking absolute positions. We can give a longer range then the comment is and still get the comment back. We can't add a secondary comment to confuse it because once we find one that hits, we use that and exit the check.

**Comment by rnveach** [comment] 2017-12-06 16:47
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/5/com.puppycrawl.tools.checkstyle.checks.coding/HiddenFieldCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@6a13d885_231
This item isn't killed because we are always sending `processVariable` a lambda token when the method only deals with local variables or parameter definitions. Even changing it to give the method the parameter definition of the lambdas didn't produce any differences in UTs.

**Comment by romani** [comment] 2017-12-07 17:41
Remember that code in Check is likely to be changed to be more exact and strict.

**Comment by rnveach** [comment] 2017-12-07 18:53
@romani Those changes require more than a simple change. They are posted to you to confirm how you want them changed.
HiddenCheck could be changed to send `processVariable` the right token, but I'm not sure if I could make that pass pitest unless your saying the logic of the check doesn't need it.
For FallthroughCheck, are we changing `Comment.intersects` which is API, or are we changing the check to not give the extra addition/subtraction?

**Comment by rnveach** [comment] 2017-12-07 19:14
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/5/com.puppycrawl.tools.checkstyle.checks.coding/VariableDeclarationUsageDistanceCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@555f4051_649
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/5/com.puppycrawl.tools.checkstyle.checks.coding/VariableDeclarationUsageDistanceCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@555f4051_745
My current thought is that `isChild` is taking over for this code since `isChild` doesn't tell it where to stop, so it searches the whole if/else and try/catch structure instead of the single block of the if, else, and catch.

**Comment by rnveach** [comment] 2017-12-07 19:38
http://rveach.no-ip.org/checkstyle/regression/pitest-reports/5/com.puppycrawl.tools.checkstyle.checks.coding/IllegalTypeCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@13c96569_316
This item isn't killed because nothing bad happens from allowing star imports. Class name is erronously made `java.util.` for `java.util.*`. It never gets added to the search queue so it is never found.
I don't know how to fix this other than the fact we remove the check completely.

**Comment by romani** [comment] 2018-03-31 14:19
current level is https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L1841 :
`<mutationThreshold>98</mutationThreshold>`

current uncovered mutations are at: https://github.com/checkstyle/checkstyle/blob/master/.ci/shippable.sh#L54

**Comment by rnveach** [comment] 2019-07-15 13:17
@romani Since this has a bounty and is being worked on, please confirm what 100% means here.
https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L1961-L1962
We had the `REMOVE_CONDITIONALS` mutator removed since it produced too many survivors and you didn't want to add them to the list.

**Comment by romani** [comment] 2019-07-15 13:33
REMOVE_CONDITIONALS should be addressed in separate issues

**Comment by rnveach** [comment] 2019-07-22 19:01
All fixes were merged.

**Closed by rnveach** 2019-07-22 19:01 UTC
Labels: approved, has bounty, miscellaneous
