### ISSUE TITLE
RightCurly: handling of try-with-resources when using 'alone' option

### ISSUE THREAD

**Issue by Kazzer** [checkstyle/checkstyle#3787] opened 2017-02-01 21:18 UTC
/var/tmp $ javac TryRightCurly.java

```bash
```

/var/tmp $ cat TryRightCurly.java 

```java
import java.io.IOException;
import java.io.StringWriter;

final class TryRightCurly
{
    private TryRightCurly()
    {
    }

    public static void main()
    {
        try (StringWriter writer = new StringWriter())
        {
            System.out.println(writer.toString());
        }
        catch (final IOException ioe)
        {
            System.out.println(ioe);
        }
    }
}
```

/var/tmp $ cat config.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="RightCurly">
            <property name="option" value="alone" />
        </module>
    </module>
</module>
```

/var/tmp $ java -jar checkstyle-7.5-all.jar -c config.xml TryRightCurly.java 

```text
Starting audit...
[ERROR] /home/kadeem/Kazzer/scratch/TryRightCurly.java:12:54: '}' at column 54 should be alone on a line. [RightCurly]
Audit done.
Checkstyle ends with 1 errors.
```

---------------

I'm expecting to see no violation from this as the character being referenced at 12:54 is a right parenthesis, not a right curly brace. Behaviour in Checkstyle 7.4 behaved as expected.

/var/tmp $ java -jar checkstyle-7.4-all.jar -c config.xml TryRightCurly.java
```text
Starting audit...
Audit done.
```

**Comment by rnveach** [comment] 2017-02-01 21:21
duplicate of #3776

**Closed by rnveach** 2017-02-01 21:21 UTC
