### ISSUE TITLE
Checker should use UTF-8 encoding by default

### ISSUE THREAD

**Issue by tylercamp** [checkstyle/checkstyle#6204] opened 2018-11-08 16:49 UTC
Sample class:
```
public class Test {
  String X = "ища"; // parser is ok with this line
  String Y = "н"; // parser is ok with this line
  char Y = 'н'; // parser is NOT ok with this line
}
```

Exception:
```
> java -jar checkstyle-8.14-all.jar -c /sun_checks.xml  Test.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing <...>
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:581)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:472)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:226)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TokenStreamRecognitionException occurred while parsing file <...>
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:98)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:181)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:81)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
        ... 4 more
Caused by: line line 4:14: expecting ''', found '½'
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:405)
        at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
        at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:134)
        at antlr.TokenBuffer.fill(TokenBuffer.java:69)
        at antlr.TokenBuffer.LA(TokenBuffer.java:80)
        at antlr.LLkParser.LA(LLkParser.java:52)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3295)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2542)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:634)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:556)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)
        at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:92)
        ... 8 more
Checkstyle ends with 1 errors.
```

---------------

It seems that Unicode is supported in string literals but not character literals. Is this expected behavior? Is there a simple workaround available? Otherwise we'll be filtering files containing any Unicode before scanning, just to be safe, which is undesired.

This uses the Sun checks copy/pasted from [here.](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/sun_checks.xml)

_Originally found while scanning Lucene 4.6.0._

----------

**MIGRATION NOTES**:
if during upgrade to checkstyle 8.32 or higher you got such JavaParser exception, please update you checkstyle config to place in property `charset` value of system property "file.encoding".  See old documentation https://checkstyle.sourceforge.io/version/8.31/config.html#Checker_Properties for previous default value. If you had no such property set in config, please explicitly define it.

**Comment by romani** [comment] 2018-11-08 17:17
We do not support Unicode symbols in names - https://checkstyle.org/writingchecks.html#Limitations but we should support it in string literals.

In worse case , extend limitation list.

**Comment by tylercamp** [comment] 2018-11-08 17:35
Just to clarify - it parses `String X = "ища";` but fails on `char Y = 'н';`.

**Comment by rnveach** [comment] 2018-11-08 18:07
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java.g#L1633

https://github.com/antlr/antlr4/blob/master/doc/unicode.md
> Prior to ANTLR 4.7, generated lexers in most targets only supported part of the Unicode standard (code points up to U+FFFF). As of ANTLR 4.7, the lexers in all language runtimes support the full range of Unicode code points up to U+10FFFF.

We use Antlr 2 for Java, so it may only support very limited unicode, if any.

**Comment by romani** [comment] 2018-11-09 15:37
`н` - is very basic Cyrillic part of alphabet, code is `043D` , should work.
https://www.compart.com/en/unicode/U+043D

**Comment by tylercamp** [comment] 2018-11-09 19:01
I just found that I don't have this issue while running Ubuntu 16.04. On Ubuntu I'm using Java 1.8.0_161, on Windows I'm using 1.8.0_162.

Possibly worth noting:

```> file -i BulgarianStemmer.java
BulgarianStemmer.java: text/plain; charset=utf-8
> file -i ArrayUtil.java
ArrayUtil.java: text/plain; charset=us-ascii```

**Comment by tylercamp** [comment] 2018-11-09 19:13
Adding `-Dfile.encoding=UTF8` to CLI options fixed the issue for me. A better name for this issue may be "detect charset instead of using default"?

**Comment by rnveach** [comment] 2018-11-09 20:06
@tylercamp When you drop `Dfile.encoding=UTF8` and add `charset` to the checker config, does that also solve your issue?
See http://checkstyle.sourceforge.net/config.html#Checker_Properties

**Comment by tylercamp** [comment] 2018-11-09 22:11
@rnveach That also works for me. Automatic encoding detection would be nice but this is a good workaround.

**Comment by rnveach** [comment] 2018-11-09 23:08
> I don't have this issue while running Ubuntu 

https://stackoverflow.com/questions/1006276/what-is-the-default-encoding-of-the-jvm
> for reference, on Linux it's usually "UTF-8", and on Windows it's usually "cp1252"

This is why Linux works and Windows doesn't.

**Comment by romani** [comment] 2018-11-10 06:00
@rnveach , should we make checker encoding to be UTF8 by default ? 
or update Checker to user UTF8 by default? till clearly specified by user.
Code for usage of system default is 10 years old - https://github.com/checkstyle/checkstyle/commit/2e4762f1716c8d12c9652aad68cb4558181bb60c#diff-60eee86917c2c545192f67e60dea9337R104

I still think it is very strange why string values are ok and char is not.

I think detection of encoding is too much for our simple tool.

**Comment by rnveach** [comment] 2018-11-10 13:50
I will see if I can find time to look and see why it fails.

Making config default to UTF8 might be a little late since everyone has their own config. I am fine with changing Checker's internal default to UTF8 if it doesn't cause any problems.

> string values are ok and char is not.

This might be the problem. Windows' default encoding is 1 byte per character. The UTF8 character he uses is 2 bytes for 1 character. Because of the invalid encoding, it thinks he put 2 characters into there, which is invalid for Java.

Example of what Parser sees: char Y = 'HH';
Example of what we see: char Y = 'H';

This is why parser says expecting `'`. It is looking for the end of the character after it found the first byte.

If this is the case, there is no way for us to fix this in the parser. It is all about identifying the right encoding.

**Comment by romani** [comment] 2018-11-10 23:54
There might be nuances with complicated language like Chinese, I remember bunch of issues with it on Windows in cmd terminal

**Comment by nmancus1** [comment] 2020-03-08 20:52
I would like to look at this.  Would it be better to implement our own fix using antlr, or use an existing library to parse and determine encoding?  I found this: https://github.com/albfernandez/juniversalchardet

**Comment by romani** [comment] 2020-03-09 02:47
Utf8 should be enough, please help investigate why it doesn't work

**Comment by nmancus1** [comment] 2020-03-16 16:21
@romani  Ok, I don't think this is ANTLR's fault.  The corresponding AST line:
`CHAR_LITERAL -> 'н' [4:11]`.  This bug has proved to be tougher to track down than I thought, since it only shows up when debugging the jar file, and not when ran in IDEA.  I'm still  working on this, but it's taking longer than expected.  By the way, this has failed for parsing most higher unicode chars (emoji, etc.) as CHAR_LITERAL .

**Comment by romani** [comment] 2020-03-17 15:39
we can not afford to make charset detection for each file (it will be too slow), we need to guide users to enforce charset in config to be UTF8 and make it work on our side.

**Comment by nmancus1** [comment] 2020-03-17 17:42
> we can not afford to make charset detection for each file (it will be too slow), we need to guide users to enforce charset in config to be UTF8 and make it work on our side

Yeah, I see that now.  I have been playing with ANTLR using matching surrogate codepoints, and I think I'm close to a solution. I actually had one rule that came pretty close, but failed one regression test, so I'm continuing to study ANTLR and trying to perfect it.

**Comment by romani** [comment] 2020-04-08 13:58
fix is merged.

**Closed by romani** 2020-04-08 13:58 UTC
Labels: approved, breaking compatibility
