### ISSUE TITLE
Support qualified annotation names

### ISSUE THREAD

**Issue by alexstaeding** [checkstyle/checkstyle#11736] opened 2022-06-13 20:08 UTC
https://checkstyle.sourceforge.io/config_javadoc.html#MissingJavadocType

I have come across the slight annoyance that I am unable to exclude some annotations from the `MissingJavadocType` check because they are nested within a class. [These](https://github.com/JetBrains/java-annotations/blob/master/common/src/main/java/org/jetbrains/annotations/ApiStatus.java) are the annotations in question. Currently, the only workaround is to import every nested annotation separately instead of just the enclosing class.

Specifically, I would like to exclude annotations such as `@ApiStatus.Internal` from `MissingJavadocType` as follows:

```xml
<module name="MissingJavadocType">
    <property name="scope" value="protected"/>
    <property name="tokens"
              value="INTERFACE_DEF, ENUM_DEF, ANNOTATION_DEF"/>
    <property name="excludeScope" value="nothing"/>
    <property name="skipAnnotations" value="ApiStatus.Internal"/> <!-- this does not work -->
</module>
```

From the [docs](https://checkstyle.sourceforge.io/config_javadoc.html#MissingJavadocType):
> Only short names are allowed, e.g. Generated.

Example affected [file(s)](https://github.com/SourceGrade/Jagr/blob/9843a0e01c019e87a6a2cd3de53782174317f519/grader-api/src/main/java/org/sourcegrade/jagr/api/rubric/Criterion.java)

Checkstyle config [here](https://github.com/SourceGrade/Style/blob/4d4b243b2c3a2c31eeb17d96aef6f43f336ae6a0/src/main/resources/config/checkstyle/checkstyle.xml), relevant part [here](https://github.com/SourceGrade/Style/blob/4d4b243b2c3a2c31eeb17d96aef6f43f336ae6a0/src/main/resources/config/checkstyle/checkstyle.xml#L334)

Example error:
```bash
> Task :jagr-grader-api:checkstyleMain FAILED
[ant:checkstyle] [WARN] /home/alex/IdeaProjects/Jagr/grader-api/src/main/java/org/sourcegrade/jagr/api/rubric/Criterion.java:239:5: Missing a Javadoc comment. [MissingJavadocType]

...

Execution failed for task ':jagr-grader-api:checkstyleMain'.
```

## Minimal example

https://github.com/alexstaeding/CheckStyle-Issue11736

```java
/**
 * Ignore.
 */
public interface Foo {

    @ApiStatus.Internal
    interface A {
    }

    @Internal
    interface B {
    }
}
```

It is currently not possible to provide a value for skipAnnotations so that this `Foo.A` interface does not require javadoc. This is specifically mentioned in the [docs](https://checkstyle.sourceforge.io/config_javadoc.html#MissingJavadocType).
```xml
<property name="skipAnnotations" value="ApiStatus.Internal"/> <!-- this does not work -->
```

## CLI (executed in [this](https://github.com/alexstaeding/CheckStyle-Issue11736) repository):

```bash
$ cat config/checkstyle/checkstyle.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="fileExtensions" value="java, properties, xml"/>
    <module name="TreeWalker">
        <module name="MissingJavadocType">
            <property name="scope" value="protected"/>
            <property name="tokens"
                      value="INTERFACE_DEF, ENUM_DEF, ANNOTATION_DEF"/>
            <property name="excludeScope" value="nothing"/>
            <property name="skipAnnotations" value="Internal"/> <!-- this does not work -->
        </module>
    </module>
</module>

$ cat src/main/java/Foo.java 
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.ApiStatus.Internal;

/**
 * Ignore.
 */
public interface Foo {

    @ApiStatus.Internal
    interface A {

    }

    @Internal
    interface B {

    }
}

java -jar checkstyle-10.3.1-all.jar -c config/checkstyle/checkstyle.xml src/main/java/Foo.java
Starting audit...
[ERROR] ***/IdeaProjects/CheckStyle-Issue11736/src/main/java/Foo.java:9:5: Missing a Javadoc comment. [MissingJavadocType]
Audit done.
Checkstyle ends with 1 errors.
```

**Comment by strkkk** [comment] 2022-06-18 09:36
@alexstaeding please report issue in proper format - https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F with minimal example to reproduce issue

**Comment by alexstaeding** [comment] 2022-06-18 10:04
I have uploaded a repository with a minimal example and updated the original issue text

**Comment by romani** [comment] 2022-06-18 20:43
CLI please, and nothing else

**Comment by romani** [comment] 2022-06-29 03:10
Can you update your CLI example  config like:
`<property name="skipAnnotations" value="Internal, ApiStatus.Internal"/>`

**Comment by alexstaeding** [comment] 2022-06-29 03:48
> Can you update your CLI example config like: `<property name="skipAnnotations" value="Internal, ApiStatus.Internal"/>`

```bash
$ cat config/checkstyle/checkstyle.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="fileExtensions" value="java, properties, xml"/>
    <module name="TreeWalker">
        <module name="MissingJavadocType">
            <property name="scope" value="protected"/>
            <property name="tokens"
                      value="INTERFACE_DEF, ENUM_DEF, ANNOTATION_DEF"/>
            <property name="excludeScope" value="nothing"/>
            <property name="skipAnnotations" value="Internal, ApiStatus.Internal"/>
        </module>
    </module>
</module>

$ cat src/main/java/Foo.java 
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.ApiStatus.Internal;

/**
 * Ignore.
 */
public interface Foo {

    @ApiStatus.Internal
    interface A {

    }

    @Internal
    interface B {

    }
}

java -jar checkstyle-10.3.1-all.jar -c config/checkstyle/checkstyle.xml src/main/java/Foo.java
Starting audit...
[ERROR] /Users/alexstaeding/IdeaProjects/CheckStyle-Issue11736/src/main/java/Foo.java:9:5: Missing a Javadoc comment. [MissingJavadocType]
Audit done.
Checkstyle ends with 1 errors.
```

**Comment by romani** [comment] 2022-07-02 22:22
@stoyanK7 , can you help us to fix this issue ?
I think it is good issue to start.

**Comment by stoyanK7** [comment] 2022-07-03 17:51
@romani On it! I found the cause. My question is:
Should 
```xml
<property name="skipAnnotations" value="Internal"/>
```
skip both `@Internal` and `@ApiStatus.Internal` or just `@Internal`?

**Comment by romani** [comment] 2022-07-03 17:52
ApiStatus.Internal

To match as is

**Comment by strkkk** [comment] 2022-07-09 12:47
fix is merged

**Closed by strkkk** 2022-07-09 12:47 UTC
Labels: approved, easy

**Comment by alexstaeding** [comment] 2022-07-12 00:26
Thanks, may I suggest also updating the [docs](https://checkstyle.sourceforge.io/config_javadoc.html#MissingJavadocType) as this is no longer accurate:

```
Only short names are allowed, e.g. Generated.
```

**Comment by romani** [comment] 2022-07-12 00:35
@stoyanK7, please send one more PR that reference the same issue.
