### ISSUE TITLE
6 tests in Checkstyle master branch fail at clean Ubuntu 14.04 Docker container (Java 8, Maven 3)

### ISSUE THREAD

**Issue by daniilyar** [checkstyle/checkstyle#3177] opened 2016-05-14 13:28 UTC
See more at https://groups.google.com/forum/#!topic/checkstyle-devel/MXmSM98XdfU

Here is the Dockerfile for Checkstyle master branch compilation inside Ubuntu 14.04 container (Java 8, Maven 3.3.9): https://gist.github.com/daniilyar/278fd9023f2a665134308eb07ac1f170

Maven build inside this container fails with (6 test failures):

```
Failed tests: 
  CheckerTest.testDestroyCacheFileWithInvalidPath:399 Exception did not happen
  MainTest.testExistingFilePlainOutputToFileWithoutReadAndRwPermissions System.exit has not been called.
  MainTest.testExistingTargetFilePlainOutputToFileWithoutRwPermissions System.exit has not been called.
  MainTest.testLoadPropertiesIoException:508 Exception was expected
  PropertyCacheFileTest.testNonAccessibleDirectory:189 AccessDeniedException is expected since directory is readonly.
  PropertyCacheFileTest.testNonAccessibleFile:73 FileNotFoundException is expected, since access to the file was denied!
Tests in error: 
  CommitValidationTest.setUp:106->getCommitsToCheck:142 ? IllegalArgument One of...

Tests run: 1798, Failures: 6, Errors: 1, Skipped: 1
```

**Comment by daniilyar** [comment] 2016-05-14 13:33
I was able to reproduce at clean OS, without any containers.

Checkstyle master branch (commit [54cdc72c](https://github.com/checkstyle/checkstyle/commit/54cdc72ced41390bb62f14d40e7d0a5518932c73)) fails the same tests on my PC (Java 1.8.0_31, Maven 3.2.2, Ubuntu 14.04 LTS). Full build log is here: http://pastebin.com/eEYTNN1F

**Comment by MEZk** [comment] 2016-05-14 17:32
@romani
The same tests failed when I tried to run Checkstyle on Wercker CI with the following DockerFile:
https://github.com/carlossg/docker-maven/blob/40cbcd2edc2719c64062af39baac6ae38d0becf9/jdk-8/Dockerfile

**Comment by romani** [comment] 2016-05-14 18:14
Good .just need to be resolved

**Comment by MEZk** [comment] 2016-05-26 17:08
@romani, @daniilyar 
I'm able to correct 2 of 6 UTs:
1) CheckerTest.testDestroyCacheFileWithInvalidPath
2) MainTest.testLoadPropertiesIoException

The following UTs remains broken at Dockers container ([profile](https://github.com/carlossg/docker-maven/blob/40cbcd2edc2719c64062af39baac6ae38d0becf9/jdk-8/Dockerfile)):

```
Failed tests: 
  MainTest.testExistingFilePlainOutputToFileWithoutReadAndRwPermissions System.exit has not been called.
  MainTest.testExistingTargetFilePlainOutputToFileWithoutRwPermissions System.exit has not been called.
  PropertyCacheFileTest.testNonAccessibleDirectory:189 AccessDeniedException is expected since directory is readonly.
  PropertyCacheFileTest.testNonAccessibleFile:73 FileNotFoundException is expected, since access to the file was denied!
```

The problem is caused by the fact that file/directory permissions do not set properly.
The following approaches which should set read only permission do not work at all:

1)
```java
final File file = temporaryFolder.newFile("file.output");
file.setReadable(true, false);
file.setWritable(false, false);
```

2)
```java
final File file = temporaryFolder.newFile("file.output");
file.setReadOnly();
```

3)
```java
final File file = temporaryFolder.newFile("file.output");
Runtime.getRuntime().exec("chmod 444 " + file.getPath());
```

4)
```java
final File file = temporaryFolder.newFile("file.output");
Set<PosixFilePermission> perms = new HashSet<>();
perms.add(PosixFilePermission.OWNER_READ);
Files.setPosixFilePermissions(file.toPath(), perms);
```

5)
```java
final File file = temporaryFolder.newFile("file.output");
chmod(file.getPath(), 444);
```

Own chmod implementation:
```java
private static int chmod(String filename, int mode) {
    try {
        Class<?> fspClass = Class.forName("java.util.prefs.FileSystemPreferences");
        Method chmodMethod = fspClass.getDeclaredMethod("chmod", String.class, Integer.TYPE);
        chmodMethod.setAccessible(true);
        return (Integer)chmodMethod.invoke(null, filename, mode);
    } catch (Throwable ex) {
        return -1;
    }
}
```

Nevertheless, they all work at my home PC with Ubuntu 14.04, at Travis CI, at Appveyor CI.
Any ideas?

**Comment by MEZk** [comment] 2016-05-28 11:37
**Further investigation.**

When I modified 'testNonAccessibleFile' like this:

```java
    @Test
    public void testNonAccessibleFile() throws IOException {
        final Configuration config = new DefaultConfiguration("myName");
        final File file = temporaryFolder.newFile("file.output");
        final boolean readOnly = file.setReadOnly();
        if (readOnly) {
            System.out.println("File is read only!");
        }
        try {
            new PropertyCacheFile(config, file.getAbsolutePath()).persist();
            fail("FileNotFoundException is expected, since access to the file was denied!");
        }
        catch (FileNotFoundException ex) {
            System.out.println("FileNotFoundException in testNonAccessibleFile");
            assertThat(ex.getMessage(), containsString("file.output"));
        }
    }
```

and ran the test at Wercker CI I had the following output:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.puppycrawl.tools.checkstyle.PropertyCacheFileTest
File is read only!
Tests run: 8, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.048 sec <<< FAILURE! - in com.puppycrawl.tools.checkstyle.PropertyCacheFileTest
testNonAccessibleDirectory(com.puppycrawl.tools.checkstyle.PropertyCacheFileTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.AssertionError: AccessDeniedException is expected since directory is readonly.
	at com.puppycrawl.tools.checkstyle.PropertyCacheFileTest.testNonAccessibleDirectory(PropertyCacheFileTest.
```

File is read only (as JVM thinks), but information can be written into it in PropertyCacheFile#persist.

**Comment by MEZk** [comment] 2016-06-03 13:43
@romani 
After merge of https://github.com/checkstyle/checkstyle/pull/3221 there are still 4 broken UTs left, all of them try to change file permissions. I'm working on the problem.

**Comment by MEZk** [comment] 2016-06-16 19:07
From canWrite() and canRead() documentation:

> On some platforms it may be possible to start the Java virtual machine with special privileges that allow it to modify files that are marked read-only. Consequently this method may return {@code true} even though the file is marked read-only.

https://docs.oracle.com/javase/8/docs/api/java/io/File.html#canRead--
https://docs.oracle.com/javase/8/docs/api/java/io/File.html#canWrite--

**Comment by romani** [comment] 2016-06-17 14:50
@MEZk mentioned that such code appear during #1181 , updated during #1510

We can remove validation from Main.java for RW access, it was done as over-protection that cost nothing for implementation during #1181 , original problem of #1181 was fixed in different way.
It is completely OK to let CLI fail with exception if smth wrong with access to file-system.

Resolution: we can remove validation of Write access from CLI (Main.java) and let validation fail with exception.

**Comment by romani** [comment] 2016-06-17 17:48
fix is merged

**Closed by romani** 2016-06-17 17:48 UTC
Labels: approved, miscellaneous
