### ISSUE TITLE
IndentationCheck: catch child indentation not checked

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#3803] opened 2017-02-07 06:36 UTC
$cat TestClass.java
```
public class TestClass {
    void method() {
        try {
            if (SomeVariableWithVeryLongName
            | OtherVariableWithVeryLongName) {
            }
        }
        catch (SomeExceptionWithVeryLongName
        | OtherExceptionWithVeryLongName e) {
        }
    }
}
```
$ cat TestConfig.xml
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
  "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
  "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <property name="charset" value="UTF-8"/>
  <module name="TreeWalker">
    <module name="Indentation"/>
  </module>
</module>
```

```
$ java -jar checkstyle-7.5.1-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:5: 'if' child have incorrect indentation level 12, expected level should be 16. [Indentation]
Audit done.
Checkstyle ends with 1 errors.
```
---------------

There must be two indentation errors: one for 'if', another for 'catch'.
It seems like the 'catch' handler lacks some code.

--------------

**Comment by rnveach** [comment] 2017-02-07 12:12
The catch is being checked, but its expected indentation is 8 instead of probably what user expects to be 12.
`[ERROR] TestClass.java:9: 'catch' child have incorrect indentation level 0, expected level should be 8. [Indentation]`

**Comment by romani** [comment] 2017-02-08 22:39
fix is merged

**Comment by romani** [comment] 2017-02-08 22:40
@rnveach , please add UTs for IF expression indentation as reported in issue.

**Comment by rnveach** [comment] 2017-02-13 13:09
@romani We have examples similar to this in valid cases, no invalid ones that I could find. You still want me to add it?
https://github.com/checkstyle/checkstyle/blob/edb810c10e121b34f4222a4bba9012add00f1e41/src/test/resources/com/puppycrawl/tools/checkstyle/checks/indentation/InputValidCommaIndent.java

**Comment by romani** [comment] 2017-02-13 14:39
Due to complexity of this check, it is better to have both valid and invalid cases. This will help us to catch regression on UT level.

**Comment by romani** [comment] 2017-02-16 04:11
final fix is merged.

**Closed by romani** 2017-02-16 04:11 UTC
Labels: approved, bug, indentaion
