### ISSUE TITLE
IllegalType rule misfires on classes that extend 'illegalClassNames'

### ISSUE THREAD

**Issue by lgoldstein** [checkstyle/checkstyle#6400] opened 2019-01-31 05:35 UTC
```
/var/tmp $ javac SetMultiKeyMap.java
#[[Nothing to report]]

/var/tmp $ cat config.xml
#[[
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<!--
    Checkstyle configuration for maintaining CB4 coding conventions.
    Checkstyle is very configurable. Be sure to read the documentation at
    http://checkstyle.sf.net (or in your downloaded distribution).
    To completely disable a check, just comment it out or delete it from the file.
 -->

<module name="Checker">
    <module name="SuppressWarningsFilter" />
    <module name="FileTabCharacter">
        <property name="eachLine" value="true" />
        <property name="fileExtensions" value="java,xml,properties,properties.in,reference" />
    </module>

    <!-- Checks that property files contain the same keys.         -->
    <!-- See http://checkstyle.sf.net/config_misc.html#Translation -->
    <module name="Translation" />

    <module name="FileLength">
        <property name="max" value="2650" />
    </module>

    <module name="TreeWalker">
        <!-- Make the @SuppressWarnings annotations available to Checkstyle -->
        <module name="SuppressWarningsHolder" />

        <module name="MissingOverride" />
        <module name="PackageDeclaration" />
        <module name="MissingCtor" />

            <!-- Checks for naming conventions - see http://checkstyle.sf.net/config_naming.html -->
        <module name="PackageName" />
        <module name="TypeName" />
        <module name="MethodName" />
        <module name="InterfaceTypeParameterName">
            <property name="format" value="^[A-Z]+$" />
        </module>
        <module name="MemberName" />

        <!-- See http://checkstyle.sf.net/config_imports.html -->
        <!--  default Eclipse formatter configuration (tested on Mars release): -->
        <!-- module name="CustomImportOrder">
            <property name="customImportOrderRules"
                value="STATIC###STANDARD_JAVA_PACKAGE###SPECIAL_IMPORTS###THIRD_PARTY_PACKAGE" />
            <property name="specialImportsRegExp" value="^org\." />
            <property name="thirdPartyPackageRegExp" value="^com\." />
            <property name="sortImportsInGroupAlphabetically" value="true" />
            <property name="separateLineBetweenGroups" value="true" />
        </module -->
        <module name="AvoidStarImport" />
        <module name="AvoidStaticImport" />
        <!-- defaults to sun.* packages -->
        <module name="IllegalImport">
            <!-- Why excluded:
                 com.sun,sun,sunw - internal JVM packages with classes having many similar names to core ones
                 com.ibm.icu.util - Avoid confusion with Java core classes with similar names and functionality - e.g., Calendar
                 javassist - contains some classes with names similar to java.lang.reflect
                 antlr,groovyjarjarantlr - contains some classes with names similar to commons-lang3
                 org.apache.commons.lang - we are using the type-safe commons-lang3
                 com.querydsl.core.util - contains some classes with names similar to commons-lang3
                 org.apache.commons.collections - we are using the type-safe commons-collection4
            -->
            <property name="illegalPkgs" value="com.sun,sun,sunw,com.ibm.icu.util,javassist,antlr,groovyjarjarantlr,org.apache.commons.lang,com.querydsl.core.util,org.apache.commons.collections,java.awt,javax.swing,java.applet" />

            <!--
                java.text.Annotation - Not to be confused with java.lang.Annotation

                com.google.common.base.Objects - Enforce usage of java.util.Objects
                com.google.common.base.Function - Enforce usage of java.util.function.Function
                com.google.common.base.Predicate - Enforce usage of java.util.function.Predicate

                org.springframework.util.StringUtils
                org.springframework.util.CollectionUtils
                org.springframework.cglib.core.CollectionUtils
                org.springframework.util.MapUtils - Enforce usage of Apache Commons

                org.apache.sshd.common.util.logging.AbstractLoggingBean - Enforce using our such named class
                org.apache.sshd.common.util.logging.LoggingUtils
            -->
            <property name="illegalClasses" value="java.text.Annotation,com.google.common.base.Objects,com.google.common.base.Predicate,org.springframework.util.StringUtils,org.springframework.util.CollectionUtils,org.springframework.cglib.core.CollectionUtils,org.springframework.util.MapUtils,org.apache.sshd.common.util.logging.AbstractLoggingBean,org.apache.sshd.common.util.logging.LoggingUtils" />
        </module>
        <module name="RedundantImport" />
        <module name="UnusedImports" />
        <module name="ImportOrder">
            <property name="groups" value="java,javax,org,net,io,cucumber,junit,antlr,com,*" />
            <property name="ordered" value="true" />
            <property name="separated" value="true" />
        </module>

        <module name="NeedBraces" />
        <module name="NoFinalizer" />
        <module name="CovariantEquals" />
        <module name="EqualsHashCode" />

        <module name="RedundantModifier" />
        <module name="ExplicitInitialization" />
        <module name="MultipleVariableDeclarations" />
        <module name="UnnecessaryParentheses" />
        <module name="OneStatementPerLine" />
        <module name="InnerAssignment" />
        <module name="Indentation">
            <property name="caseIndent" value="4" />
            <property name="lineWrappingIndentation" value="0" />
            <property name="braceAdjustment" value="0" />
        </module>
        <module name="BooleanExpressionComplexity">
            <property name="max" value="13" />
        </module>
        <module name="MissingSwitchDefault" />
        <module name="DefaultComesLast" />
        <module name="IllegalType">
            <property name="format" value="^xxx$" />
            <property name="illegalClassNames" value="java.util.GregorianCalendar, java.util.Hashtable, java.util.HashSet, java.util.HashMap, java.util.ArrayList, java.util.LinkedHashMap, java.util.LinkedHashSet, java.util.TreeSet, java.util.TreeMap, java.util.LinkedList" />
        </module>
        <module name="StringLiteralEquality" />
        <module name="RightCurly" />
        <module name="LeftCurly" />
        <module name="NoWhitespaceAfter">
            <property name="tokens" value="BNOT,DEC,DOT,INC,AT,LNOT,UNARY_MINUS,UNARY_PLUS,METHOD_REF" />
        </module>
        <module name="NoWhitespaceBefore">
            <property name="tokens" value="ELLIPSIS,COMMA,POST_INC,POST_DEC,METHOD_REF" />
        </module>
        <module name="EmptyStatement" />
        <module name="GenericWhitespace" />
        <module name="ParenPad" />
        <module name="TypecastParenPad" />
        <module name="WhitespaceAround">
            <property name="tokens" value="ASSIGN, BAND, BAND_ASSIGN, BOR, BOR_ASSIGN, BSR, BSR_ASSIGN, BXOR, BXOR_ASSIGN, COLON, DIV, DIV_ASSIGN, EQUAL, GE, GT, LAND, LCURLY, LE, LITERAL_ASSERT, LITERAL_CATCH, LITERAL_DO, LITERAL_ELSE, LITERAL_FINALLY, LITERAL_FOR, LITERAL_IF, LITERAL_RETURN, LITERAL_SYNCHRONIZED, LITERAL_TRY, LITERAL_WHILE, LOR, LT, MINUS, MINUS_ASSIGN, MOD, MOD_ASSIGN, NOT_EQUAL, PLUS, PLUS_ASSIGN, QUESTION, RCURLY, SL, SLIST, SL_ASSIGN, SR, SR_ASSIGN, STAR, STAR_ASSIGN,TYPE_EXTENSION_AND" />
        </module>

        <module name="NoLineWrap" />
        <module name="WhitespaceAfter" />
        <module name="MethodParamPad" />
        <module name="ConstantName" />
        <module name="ParameterName">
            <property name="format" value="^[a-z][a-zA-Z0-9_]*$" />
        </module>
        <module name="LocalVariableName">
            <property name="format" value="^[_a-z][a-zA-Z0-9_]*$" />
        </module>
        <module name="VariableDeclarationUsageDistance">
            <property name="allowedDistance" value="8" />
        </module>

        <module name="UpperEll" />
        <!--Assert statement may have side effects:-->
        <module name="DescendantToken">
            <property name="tokens" value="LITERAL_ASSERT" />
            <property name="limitedTokens" value="ASSIGN,DEC,INC,POST_DEC,POST_INC,PLUS_ASSIGN,MINUS_ASSIGN,STAR_ASSIGN,DIV_ASSIGN,MOD_ASSIGN,BSR_ASSIGN,SR_ASSIGN,SL_ASSIGN,BAND_ASSIGN,BXOR_ASSIGN,BOR_ASSIGN" />
            <property name="maximumNumber" value="0" />
        </module>
        <!-- Switch within switch -->
        <module name="DescendantToken">
            <property name="tokens" value="LITERAL_SWITCH" />
            <property name="limitedTokens" value="LITERAL_SWITCH" />
            <property name="maximumNumber" value="0" />
            <property name="minimumDepth" value="1" />
        </module>
        <!-- String literal equality check -->
        <module name="DescendantToken">
            <property name="tokens" value="EQUAL,NOT_EQUAL" />
            <property name="limitedTokens" value="STRING_LITERAL" />
            <property name="maximumNumber" value="0" />
            <property name="maximumDepth" value="1" />
        </module>
            <module name="LineLength">
            <property name="max" value="180" />
        </module>
        <module name="EmptyBlock">
            <property name="option" value="text" />
            <property name="tokens" value="LITERAL_TRY, LITERAL_CATCH, INSTANCE_INIT" />
        </module>
        <module name="EmptyBlock">
            <property name="tokens" value="LITERAL_WHILE, LITERAL_FINALLY, LITERAL_DO, LITERAL_IF, LITERAL_ELSE, LITERAL_FOR, INSTANCE_INIT, STATIC_INIT, LITERAL_SWITCH, LITERAL_SYNCHRONIZED, LITERAL_CASE, LITERAL_DEFAULT, ARRAY_INIT" />
        </module>
        <module name="EmptyLineSeparator">
            <property name="allowNoEmptyLineBetweenFields" value="true" />
            <property name="allowMultipleEmptyLines" value="false" />
            <property name="allowMultipleEmptyLinesInsideClassMembers" value="false" />
        </module>
        <module name="MissingDeprecated" />
            <!-- Enable FileContentsHolder to allow us to in turn turn on suppression comments -->
        <!-- <module name="FileContentsHolder" /> -->
            <!-- Checks for Javadoc comments.                     -->
            <!-- See http://checkstyle.sf.net/config_javadoc.html -->
            <!--
                <module name="PackageHtml" />
                <module name="JavadocMethod" />
                <module name="JavadocType" />
                <module name="JavadocVariable" />
                <module name="JavadocStyle" />
            -->

            <!-- Check annotations conventions -->
            <!-- See http://checkstyle.sourceforge.net/config_annotation.html -->
         <module name="AnnotationLocation">
            <property name="allowSamelineMultipleAnnotations" value="false" />
            <property name="allowSamelineSingleParameterlessAnnotation" value="false" />
            <property name="allowSamelineParameterizedAnnotation" value="false" />
        </module>
        <module name="EmptyCatchBlock">
            <property name="commentFormat" value="[a-z].*" />
            <property name="exceptionVariableName" value="^[a-z].*$" />
        </module>
    </module>
    <module name="RegexpSingleline">
        <property name="format" value="\s+$"/>
        <property name="message" value="Trailing whitespace"/>
        <!-- <property name="fileExtensions" value="......" /> -->
    </module>
    <module name="SuppressionFilter">
        <!-- using ${workspace.root.dir} 'Well Known' folder in order to use the same Suppression file configuration in both eclipse and maven -->
        <!-- '${samedir}' is an eclipse built in environment variable initialized with the value of the external checkstyle configuration file -->
        <!-- this works because checkstyle-cb4.xml defines SuppressionFilter file path as '${samedir}/suppressions-cb4.xml' -->
        <!-- Source: https://checkstyle.org/eclipse-cs/#!/properties -->
        <property name="file" value="${samedir}/suppressions-cb4.xml"/>
    </module>
</module>
]]

/var/tmp $ cat SetMultiKeyMap.java
#[[

package foo;

import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;

// NOTE: we extend LinkedHashMap since we want to be able to use it as cache
public class SetMultiKeyMap<K, V> extends LinkedHashMap<Set<K>, V> {
    private static final long serialVersionUID = -3398107541910390020L;

    public SetMultiKeyMap() {
        super();
    }

    public SetMultiKeyMap(int initialCapacity) {
        super(initialCapacity);
    }

    public SetMultiKeyMap(Map<? extends Set<K>, ? extends V> m) {
        super(m);
    }

    public SetMultiKeyMap(int initialCapacity, float loadFactor) {
        super(initialCapacity, loadFactor);
    }

    public boolean containsKey(K[] keys) {
        return containsKey(((keys == null) || (keys.length == 0)) ? Collections.emptyList() : Arrays.asList(keys));
    }

    public boolean containsKey(Collection<? extends K> keys) {
        return containsKey(new HashSet<>(keys));
    }

    public V get(K[] keys) {
        return get(((keys == null) || (keys.length == 0)) ? Collections.emptyList() : Arrays.asList(keys));
    }

    public V get(Collection<? extends K> keys) {
        return get(new HashSet<>(keys));
    }

    public V computeIfAbsent(K[] keys, Function<? super Set<K>, ? extends V> resolver) {
        return computeIfAbsent(((keys == null) || (keys.length == 0)) ? Collections.emptyList() : Arrays.asList(keys), resolver);
    }

    public V computeIfAbsent(Collection<? extends K> keys, Function<? super Set<K>, ? extends V> resolver) {
        return computeIfAbsent(new HashSet<>(keys), resolver);
    }

    public V put(K[] keys, V value) {
        return put(((keys == null) || (keys.length == 0)) ? Collections.emptyList() : Arrays.asList(keys), value);
    }

    public V put(Collection<? extends K> keys, V value) {
        return put(new HashSet<>(keys), value);
    }

    public V remove(K[] keys) {
        return remove(((keys == null) || (keys.length == 0)) ? Collections.emptyList() : Arrays.asList(keys));
    }

    public V remove(Collection<? extends K> keys) {
        return remove(new HashSet<>(keys));
    }
}
]]

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
#[[
Starting audit...
[ERROR] /tmp/SetMultiKeyMap.java:11:43: Usage of type 'LinkedHashMap' is not allowed. [IllegalType]
Audit done.
Checkstyle ends with 1 errors.
]]
```

---------------
I do not expect `IllegalType` rule to be violated since the class **extends** `LinkedHashMap` and does not use it as a

>> Classes that should not be used as types in variable declarations, return values or parameters
--------------

**Comment by lgoldstein** [comment] 2019-01-31 05:38
This behavior starts from 8.15 and onwards

**Comment by rnveach** [comment] 2019-01-31 12:00
Exact duplicate of https://github.com/checkstyle/checkstyle/issues/6267 . Similar to https://github.com/checkstyle/checkstyle/issues/6398 .
See https://github.com/checkstyle/checkstyle/issues/6267#issuecomment-458720654 on to suppress with xpath.

@romani This is the 3rd issue on this subject now.

**Comment by lgoldstein** [comment] 2019-01-31 12:07
Thanks - I don't think though that suppression is the answer (which is also what I did as a workaround). This is (IMO) clearly a bug - the original rule semantics are valid - i.e., we don't want to encourage using specific implementations as field types, return types or parameter types. However, I do think that extending a concrete implementation is a good practice and as such should not be disallowed.

**Comment by romani** [comment] 2019-01-31 20:43
we will never reconcile all demands from users.
Check should stay as is now, users need to use suppressions if they do not like new behavior.

**Closed by romani** 2019-01-31 20:43 UTC
