### ISSUE TITLE
Java interface constants treated as non-public by ConstantName check

### ISSUE THREAD

**Issue by amitchitale** [checkstyle/checkstyle#8569] opened 2020-07-28 07:39 UTC
Check documentation: https://checkstyle.sourceforge.io/config_naming.html#ConstantName

```
C:\Amit\Study\IntelliJ_Projects\Test_Checkstyle>type checkstyle.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="ConstantName">
            <property name="id" value="Non-Private-Field-Check"/>
            <property name="format" value="^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$"/>
            <property name="applyToPrivate" value="false"/>
        </module>
        <module name="ConstantName">
            <property name="id" value="Private-Field-Should-Start-With-Underscore"/>
            <property name="format" value="^_[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$"/>
            <property name="applyToPublic" value="false"/>
            <property name="applyToProtected" value="false"/>
            <property name="applyToPackage" value="false"/>
        </module>
    </module>
</module>

C:\Amit\Study\IntelliJ_Projects\Test_Checkstyle>type MyInterface.java
package com.test.checkstyle;

public interface MyInterface {
    int MAX_SIZE = 1024;

    //methods
}


C:\Amit\Study\IntelliJ_Projects\Test_Checkstyle>set RUN_LOCALE="-Duser.language=en -Duser.country=US"

C:\Amit\Study\IntelliJ_Projects\Test_Checkstyle>java %RUN_LOCALE% -jar checkstyle-8.35-all.jar -c checkstyle.xml MyInterface.java
Starting audit...
[ERROR] C:\Amit\Study\IntelliJ_Projects\Test_Checkstyle\MyInterface.java:4:9: Name 'MAX_SIZE' must match pattern '^_[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'. [Private-Field-Should-Start-With-Underscore]
Audit done.
Checkstyle ends with 1 errors.
```

---------------
Expected: There should not be any Error as Interface field should be treated as public.
MAX_SIZE should match with id - 'Non-Private-Field-Check' and succeed.
---------------

**Comment by strkkk** [comment] 2020-07-28 09:50
@amitchitale Please change issue description to template provided and change config to minimal one that reproduces problem

**Comment by amitchitale** [comment] 2020-07-28 14:55
@strkkk Updated as requested.

**Comment by strkkk** [comment] 2020-07-28 17:28
@amitchitale you have 2 same checks in config, it is not clear which one is reporting violation. You can either add id property for each one or leave only one.

**Comment by amitchitale** [comment] 2020-07-29 04:28
@strkkk Done. Added id property and updated the checkstyle check output and the Expected output

**Comment by Fernal73** [comment] 2020-07-29 06:54
https://dzone.com/articles/reasons-why-the-constant-interface-pattern-is-disc

Defining constants in interfaces is no longer encouraged.

**Comment by amitchitale** [comment] 2020-07-29 09:44
@Fernal73 In case you have interpreted this to be a constants only interface then that's not the case. Added //methods in the description.
If that's not the case, I would say it's something that is debated widely across the Java community.

**Comment by Fernal73** [comment] 2020-07-29 12:01
That was my feeling at the start as well since I was accustomed to declaring constants in interfaces. 

https://softwareengineering.stackexchange.com/questions/49572/is-it-a-bad-practice-to-have-an-interface-to-define-constants

It's upto the individual to decide. You have to weigh that against using too many static imports. 

I don't have very strong views on this. Just thought it's worth sharing.

**Comment by amitchitale** [comment] 2020-07-29 13:11
@Fernal73 Agree and disagree.
There is no restriction on having Constants in an Interface and some of the jdks' interfaces also have constants.
So it would rather be appropriate for checkstyle to have some configuration to handle this.

**Comment by Fernal73** [comment] 2020-07-29 14:35
I prefer the flexibility of using a class in which to define constants since I can make the modifiers public, private or package-private as per my requirements. The last allows me to break up classes if need be while still not exposing the constants to any external package making the constants 'internal'. Interface constants , by default, are public and thus are part of the interface exposed to other packages as well.

If I don't need the constants exposed, I'd go with package-private or private as part of the class itself or in a separate one.

**Comment by amitchitale** [comment] 2020-07-30 00:56
This is more heading into a discussion of "design choice" of using interface vs classes for constants. As I mentioned earlier, there are multiple views supporting both sides (https://stackoverflow.com/questions/2659593/what-is-the-use-of-interface-constants) and I don't want to go into that as it's not conclusive that only one particular approach is correct. What's out there are views and not established conclusions.
JDKs internal interfaces like ObjectStreamConstants or SocketOptions too have constants declared.

So I would still pitch for a enhancement in "ConstantNameCheck" to treat interface constants public by default.

**Comment by Fernal73** [comment] 2020-07-30 02:45
> So it would rather be appropriate for checkstyle to have some configuration to handle this.

If you feel strongly about this, you may write up a feature request.

**Comment by Fernal73** [comment] 2020-07-30 04:59
> This is more heading into a discussion of "design choice" of using interface vs classes for constants. As I mentioned earlier, there are multiple views supporting both sides (https://stackoverflow.com/questions/2659593/what-is-the-use-of-interface-constants) and I don't want to go into that as it's not conclusive that only one particular approach is correct. What's out there are simply views.
> JDKs internal interfaces like ObjectStreamConstants or SocketOptions too have constants declared.
> 
> So I would still pitch for a enhancement in "ConstantNameCheck" to treat interface constants public by default.

I think there's a case to have a new rule if you wish to enforce a standard across a project or programme. Whether that check has to reside in Checkstyle or not is debatable.

**Comment by Fernal73** [comment] 2020-07-30 17:40
> > This is more heading into a discussion of "design choice" of using interface vs classes for constants. As I mentioned earlier, there are multiple views supporting both sides (https://stackoverflow.com/questions/2659593/what-is-the-use-of-interface-constants) and I don't want to go into that as it's not conclusive that only one particular approach is correct. What's out there are simply views.
> > JDKs internal interfaces like ObjectStreamConstants or SocketOptions too have constants declared.
> > So I would still pitch for a enhancement in "ConstantNameCheck" to treat interface constants public by default.
> 
> I think there's a case to have a new rule if you wish to enforce a standard across a project/ programme/portfolio. Whether that check has to reside in Checkstyle or not is debatable.

There's actually a PMD rule for this:

https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#constantsininterface

For some reason, it seems to have slipped my mind.

**Comment by amitchitale** [comment] 2020-07-31 03:26
@Fernal73 Right. And the PMD rule has a property `ignoreIfHasMethods` which allows to have constants in interface with methods. So a strict violation is only for Constants Only Interface.

**Comment by Fernal73** [comment] 2020-07-31 06:51
Hmmm....
That's enabled by default. No wonder, I don't remember it.
I guess, I need to be doing a lot of coding for something like that to
stick in my head!!!

**Comment by willhains** [comment] 2020-08-03 00:51
This discussion seems to have gone off-track. The point is that fields declared in Java interfaces are *always* `public static final`, whether explicitly declared as such or not. Therefore the CheckStyle rules applying to constants in classes should also apply to constants in interfaces. Whether or not it's a good coding practice is beside the point.

**Comment by Fernal73** [comment] 2020-08-06 05:26
Agreed. The discussion was no longer about the Checkstyle rule. In that sense, it was off-Checkstyle. However, given that users don't use just one static analysis tool but more than one, this discussion was hardly irrelevant. It may, however, have been *nothing to write home about*  to the maintainers of this repo.

**Comment by amitchitale** [comment] 2020-08-20 07:21
Just wondering what's the status of this. I see the changes implemented by @strkkk but the issue is still not approved by Admins.

**Comment by pbludov** [comment] 2020-08-20 07:42
> Just wondering what's the status of this.

We are in the middle of GSoC. It is very important that students meet the deadline and perform their work efficiently and got their Google money and, more importantly, a good review in the cv. All other issues that are not critical bugs are the last to receive attention. We will definitely return to this issue later.

**Comment by strkkk** [comment] 2020-08-20 08:29
@amitchitale yes, I have fixed issue in ConstantName and MethodName checks, but there are other things to do.
I hope to finish it soon. But, as @pbludov said, there are heavy load for checkstyle team at least till end of August.

**Comment by strkkk** [comment] 2020-09-17 10:22
I will approve issue, it is clearly a bug.

**Comment by strkkk** [comment] 2020-09-25 19:13
Fix is merged

**Closed by strkkk** 2020-09-25 19:13 UTC
Labels: approved, bug
