### ISSUE TITLE
Generation and publishing regression diff report base on config in PR description

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7498] opened 2020-01-21 00:40 UTC
We need to remove from contributor responsibility generation of diff reports.

**Comment by romani** [comment] 2020-01-21 00:41
It is kind of continuation of https://github.com/checkstyle/regression-tool 
But in this case we make sure it works FIRST on simple config that we will define in a special way in PR description.So all we need is to put config in PR description and trigger CI to send message to some webservice (Richard server hosted or AWS or Heroku, …. , or php-based(it is available!!!) on sourceforge.io) to process request and publish website to some hosting by scp  or …. (AWS S3). 
We are sponsored for AWS instance, so we can keep it running, and have all credentials closed from public.
We should care about security to let service get all details from github PR it-self, and no do nothing if PR is not registered.
It should work from CLI even from local, to let us reuse it for github.io publication.
If we have time left we will continue  https://github.com/checkstyle/regression-tool  as suggestion tool for required configs to use.
So we will not ask contributes to figure out not simple tool and no reminders for regeneration will be NOT required.

PR can have in description following markers for Dif report generator:
Diff Regression projects: <URI to file like projects-to-test-on.properties>
Diff Regression config: <URI to file like my_checks.xml>

We should move all executions of wercker to some other CI (Shippable is good candidate)
We will use Wercker feature of execution on PRs and now access to logs from outside to execute PRs code with secure variables in place, so will be able to have secure token to deploy to report storage (S3(AWS)/sourceforge.io/…. ) .

Wercker should take PR description, parse it and get from it “Diff Regression config” and use https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-for-wercker.properties . Wercker build items will be predefined uncommenting of some project in property file and execution with “Diff Regression config”. Ones report is generated we should be able to deploy it to report storage. Ones deployment is done, wercker script should make a comment in PR about where to read for reports.
Summary of three separate steps:
Shell script of execution diff report generation
Shell script of deploy to report storage
Shell script of creation of comment in PR (the same script will be used by sonar build item to share link to PR violations dashboard)
Example:
run-diff-report.sh 5567 https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-for-wercker.properties
Deploy-diff-report-to-s3.sh /wercker/pipeline/checksyle/.ci-temp/confribution/reports/diff <s3 token>
Post-comment-to-pr.sh 5567 <github token> “any content”

Only ones wercker start generating all reports correctly we should start to think and do implementation of standalone web service. So absolute must is generation of diff reports by wercker, all other is for fun.

We can make service to be deployable to Heroku (if it has enough disk drive) or AWS.  Web service have post endpoint as request for diff report generation by PR, service do verification of PR and that all details provided in PR, if all ok return 200 to request and put request for diff report in internal queue. Web service always check his internal queue and do generation of reports same as werker is doing. One more end point is required to check status of queue and get status of particular PR. No security for first implementation, as service start working we should start to have more fun … .

More ideas on werker usage (probably should be just moved to issue tracker) :
As wercker is not that friendly for users to review logs …. And Shippable show logs to all , and take care of no-error regression in javadoc (that does not alarm that much) …. WE can swap build items of Wercker and Shippable. So we will not need to copy no-error violations in testing projects.

**Comment by gaurabdg** [comment] 2020-03-08 14:04
@romani @rnveach I have solved both `gsoc-first-issue` and `gsoc-second-issue`. Would you advice me to take up this issue?

**Comment by rnveach** [comment] 2020-03-08 14:06
@gaurabdg This issue is off limits since it is connected to GSoC project. https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2020-Project-Ideas#project-name-generation-and-publishing-regression-diff-report-based-on-configs-in-pull-request-description

**Comment by gaurabdg** [comment] 2020-03-08 14:40
Okay!

**Comment by strkkk** [comment] 2020-07-14 16:02
Initial version is merged, work will continue in next issues

**Closed by strkkk** 2020-07-14 16:02 UTC
Labels: approved, miscellaneous
