### ISSUE TITLE
Output file does not contain thrown exception

### ISSUE THREAD

**Issue by Fernal73** [checkstyle/checkstyle#7298] opened 2019-12-03 00:02 UTC
From 
https://github.com/checkstyle/checkstyle/issues/6885#issuecomment-560483861

```java
package cstests;

public interface TestMagicNumber {

  static byte[] getAsciiRotator() {
    byte[] rotation = new byte[95 * 2];
    for (byte i = ' '; i <= '~'; i++) {
      rotation[i - ' '] = i;
      rotation[i + 95 - ' '] = i;
    }
    return rotation;
  }
}
```

```
$ cat config.xml 
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module PUBLIC
  "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
  "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
      <module name="MagicNumber">
        <property name="ignoreFieldDeclaration" value="true" />
        <property name="ignoreAnnotation" value="true" />
        <property name="ignoreHashCodeMethod" value="true" />
    </module>
    <!--
    <module name="SuppressionXpathFilter">
      <property name="optional" value="true" />
      <property name="file" value="suppressions-xpath.xml" />
    </module>
    -->
  </module>
</module> 

$ java -jar checkstyle-8.27-all.jar -o suppressions-xpath.xml -g \
     -c config.xml TestMagicNumber.java
Checkstyle ends with 2 errors.

$ cat suppressions-xpath.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suppressions PUBLIC
    "-//Checkstyle//DTD SuppressionXpathFilter Experimental Configuration 1.2//EN"
    "https://checkstyle.org/dtds/suppressions_1_2_xpath_experimental.dtd">
<suppressions>
<suppress-xpath
       files="TestMagicNumber.java"
       checks="MagicNumberCheck"
       query="/INTERFACE_DEF[./IDENT[@text='TestMagicNumber']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='getAsciiRotator']]/SLIST/VARIABLE_DEF[./IDENT[@text='rotation']]/ASSIGN/EXPR/LITERAL_NEW/ARRAY_DECLARATOR/EXPR/STAR/NUM_INT[@text='95']"/>
<suppress-xpath
       files="TestMagicNumber.java"
       checks="MagicNumberCheck"
       query="/INTERFACE_DEF[./IDENT[@text='TestMagicNumber']]/OBJBLOCK/METHOD_DEF[./IDENT[@text='getAsciiRotator']]/SLIST/LITERAL_FOR/SLIST/EXPR/ASSIGN[./IDENT[@text='i']]/INDEX_OP[./IDENT[@text='rotation']]/EXPR/MINUS[./CHAR_LITERAL[@text='' '']]/PLUS[./IDENT[@text='i']]/NUM_INT[@text='95']"/>
</suppressions>

$ # activate filter
$ cat config.xml 
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module PUBLIC
  "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
  "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
      <module name="MagicNumber">
        <property name="ignoreFieldDeclaration" value="true" />
        <property name="ignoreAnnotation" value="true" />
        <property name="ignoreHashCodeMethod" value="true" />
    </module>

    <module name="SuppressionXpathFilter">
      <property name="optional" value="true" />
      <property name="file" value="suppressions-xpath.xml" />
    </module>

  </module>
</module>

$ java -jar checkstyle-8.27-all.jar -o cs.errors -c config.xml TestMagicNumber.java
Exception in thread "main" java.lang.IllegalArgumentException: Unexpected
 xpath query:
 /INTERFACE_DEF[./IDENT[@text='TestMagicNumber']]/OBJBLOCK/METHOD_DEF[.
/IDENT[@text='getAsciiRotator']]/SLIST/LITERAL_FOR/SLIST/EXPR/ASSIGN[./
IDENT[@text='i']]
/INDEX_OP[./IDENT[@text='rotation']]/EXPR/MINUS[./CHAR_LITERAL[@text='' '']]/
PLUS[./IDENT[@text='i']]/NUM_INT[@text='95']
	at com.puppycrawl.tools.checkstyle.filters.XpathFilterElement.<init>(XpathFilterElement.java:114)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.getXpathFilter(SuppressionsLoader.java:199)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.startElement(SuppressionsLoader.java:145)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(XMLDTDValidator.java:766)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.puppycrawl.tools.checkstyle.XmlLoader.parseInputSource(XmlLoader.java:84)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.getSuppressionLoader(SuppressionsLoader.java:275)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadXpathSuppressions(SuppressionsLoader.java:260)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadXpathSuppressions(SuppressionsLoader.java:247)
	at com.puppycrawl.tools.checkstyle.filters.SuppressionXpathFilter.finishLocalSetup(SuppressionXpathFilter.java:800)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:194)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:130)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:467)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:398)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:326)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:187)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:124)
Caused by: net.sf.saxon.trans.XPathException: expected "]", found "<string-literal>"
	at net.sf.saxon.expr.parser.XPathParser.grumble(XPathParser.java:315)
	at net.sf.saxon.expr.parser.XPathParser.grumble(XPathParser.java:272)
	at net.sf.saxon.expr.parser.XPathParser.grumble(XPathParser.java:259)
	at net.sf.saxon.expr.parser.XPathParser.expect(XPathParser.java:245)
	at net.sf.saxon.expr.parser.XPathParser.parsePredicate(XPathParser.java:2116)
	at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:2085)
	at net.sf.saxon.expr.parser.XPathParser.parseRelativePath(XPathParser.java:2000)
	at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1957)
	at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1971)
	at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1824)
	at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:753)
	at net.sf.saxon.expr.parser.XPathParser.parseExpression(XPathParser.java:660)
	at net.sf.saxon.expr.parser.XPathParser.parsePredicate(XPathParser.java:2159)
	at net.sf.saxon.expr.parser.XPathParser.parsePredicate(XPathParser.java:2115)
	at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:2085)
	at net.sf.saxon.expr.parser.XPathParser.parseRemainingPath(XPathParser.java:2035)
	at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1925)
	at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1971)
	at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1824)
	at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:753)
	at net.sf.saxon.expr.parser.XPathParser.parseExpression(XPathParser.java:660)
	at net.sf.saxon.expr.parser.XPathParser.parse(XPathParser.java:522)
	at net.sf.saxon.expr.parser.ExpressionTool.make(ExpressionTool.java:107)
	at net.sf.saxon.sxpath.XPathEvaluator.createExpression(XPathEvaluator.java:134)
	at com.puppycrawl.tools.checkstyle.filters.XpathFilterElement.<init>(XpathFilterElement.java:111)
	... 28 more
```

Expected:  I'd expect the file to be created and an error detailing the exception thrown at specific line number in the output file along with any other rule violations.

**Comment by Fernal73** [comment] 2019-12-03 03:29
None of the pitest mutations are going to catch errors like these. This is the case of faulty output generated which cannot be ingested by the program. A case of Checkstyle not being able to digest its own dog food.

**Comment by rnveach** [comment] 2019-12-03 03:50
Pitest isn't for catching bugs in your code. It is for gauging the quality of your tests.

**Comment by rnveach** [comment] 2019-12-03 03:53
Also this looks like a duplicate of https://github.com/checkstyle/checkstyle/issues/6893 .

> CHAR_LITERAL[@text='' '']]

Issue is from not escaping single quotes.

**Comment by Fernal73** [comment] 2019-12-03 04:05
@romani Since you've edited the bug to point to the Xpath suppression failing, doesn't the title need to be updated too? Or you wish to retain that to hit two birds with one stone?

**Comment by Fernal73** [comment] 2019-12-03 04:12
@rvneach Are any of the pitest mutations or test cases generating exceptions while Checkstyle runs? Then you can update this bug to point to the output file not generated when exceptions are thrown. If not, I'm leaving it that way.

**Comment by romani** [comment] 2019-12-03 17:51
I restored your expected, sorry.

-----

according to 
https://checkstyle.org/cmdline.html `-o file - specify the file to output to.`
it is destination for generated by checkstyle content - report, suppression file, ... It is not for CLI output
for CLI output you need to use command line redirections feature  like in linux `java -jar checkstyle-8.27-all.jar -o cs.violations -c config.xml TestMagicNumber.java > cs.errors`

**Comment by romani** [comment] 2019-12-03 17:52
please suggest better wording for documentation to make it more clear

**Closed by romani** 2019-12-03 17:51 UTC

**Comment by Fernal73** [comment] 2019-12-03 23:12
Not creating an output file with suppressions is a bug. In this case, since both the violations are suppressed, it ought to have created a file with at least the first line: 
'Starting audit'
Ideally, you'd have an exception line and then the line
'Audit done'.
If there were other violations (not suppressed), it creates the file. 
When I run Checkstyle without the Xpath suppressions, it creates the cs.errors output for the first and second suppressions.
The expected output should be all non-suppressed errors + an exception line for the failed xpath expression + the wrapping 'Starting audit' and 'Audit done' lines.

Add the following class to the command-line:

```java
package careers;

public class TestExtra {
}

```

None of its violations are generated either.

**Comment by Fernal73** [comment] 2019-12-03 23:19
Kindly reopen the bug.

**Comment by strkkk** [comment] 2019-12-04 06:43
> I expect @strkkk is working on the duplicate bug

Unfortunately, I am not

**Comment by Fernal73** [comment] 2019-12-04 10:14
> > I expect @strkkk is working on the duplicate bug
> 
> Unfortunately, I am not

Ok.

**Comment by romani** [comment] 2019-12-04 17:59
> it ought to have created a file with at least the first line

it is not expected, 

> Xpath suppressions fail, no output file will be generated at all?

yes, it might be that nothing is created at all, we can extend documentation but it is same for all functionality, not only for xpath.

**Comment by Fernal73** [comment] 2019-12-04 18:21
Is that the right behaviour?
PMD doesn't fall over if errors are encountered. It gracefully logs an
exception and continues processing all the files. Why should the inability
to process a suppression be a show-stopper?

**Comment by romani** [comment] 2019-12-04 18:27
we have https://checkstyle.org/config.html#Checker `haltOnException` try it might help you.

**Comment by Fernal73** [comment] 2019-12-04 18:47
I seem to have missed that in my configuration file and Checkstyle seem to
have missed a trick by still having it fall over with this value set.
I'm running my ant task and it fails to create the cs.errors file which I
specify.

**Comment by romani** [comment] 2019-12-04 19:00
you need to share details on how exactly you run in ant, by cli or by ant task ?

**Comment by rnveach** [comment] 2019-12-04 20:25
> we have https://checkstyle.org/config.html#Checker haltOnException try it might help you.

I don't think that will work. As exception in first post shows, we are failing in the `Checker.setupChild` method when we are initializing everything from the configuration. `haltOnException` only comes in after Checker is done setting up and has started executing on specific files.

Since we can't initialize from the configuration file, there is no way to continue as we stop initializing as soon as there is an error. Right now, to continue from an exception means not all the configuration is loaded and you would be working with a partial config and the module that threw the exception is incomplete and may throw more exceptions.

**Comment by Fernal73** [comment] 2019-12-04 23:39
What happens if you catch the exception and ignore that module? It's the
Xpath suppression filter that's causing the error while loading the
suppressions file.
It'll then ignore all suppressions in the Xpath file. Would that be
acceptable? It probably depends on how many suppressions there are. If
they're a lot, it's unacceptable and defeats the purpose. If it's just one
or two, it's almost business as usual.
The error is CRITICAL and should be treated as such.

@romani It always fails irrespective once you have created the erroneous
Xpath file , with or without the -g flag, from the command line or from
ant. It will fail from Gradle and Maven as well.

**Comment by Fernal73** [comment] 2019-12-05 03:05
Is it possible to read the Xpath expressions in scan only mode to check if
they're valid or not?
