### ISSUE TITLE
Resolve Pitest Issues - AvoidStarImportCheck (2)

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7800] opened 2020-03-08 18:41 UTC
Child issue of https://github.com/checkstyle/checkstyle/issues/7797 ,

This issue specifically focuses on the line https://github.com/checkstyle/checkstyle/blob/abf829f542023e089c741c55f73098cae52dcb12/.ci/pitest.sh#L75

**Comment by HuGanghui** [comment] 2020-03-11 03:35
I am on it

**Comment by HuGanghui** [comment] 2020-03-13 07:23
Pitest report

Link: https://huganghui.github.io/7800-AvoidStarImportCheck(2)/before-pit-reports/202003131405/
Surviving mutations:
on line 188: removed conditional - replaced equality check with false → SURVIVED I am focusing on it.
on line 224: removed conditional - replaced equality check with true → SURVIVED referenced by #7799, wilcoln is focusing on it.
Hardcoded mutation
mutation cs branch: https://github.com/HuGanghui/checkstyle/commit/1578ac0229711f39a4a7c77457f430491918cd57
comment:
Looking at the pitest report, we can see that the surviving mutation is the one for which removed conditional - replaced equality check with false → SURVIVED, this is equivalent as simply removing it. Which I did, leaving us with only the second condition inside the else statement.
Regression diff report

Link: coming soon

**Comment by wilcoln** [comment] 2020-03-13 11:04
Hi bro,
> comment:
> Looking at the pitest report, we can see that the surviving mutation is the one for which removed conditional - replaced equality check with false → SURVIVED, this is equivalent as simply removing it. Which I did, leaving us with only the second condition inside the else statement.

You might want to remove the following part of my comment because it doesn't apply to your case.
> .. , this is equivalent as simply removing it. Which I did, leaving us with only the second condition inside the else statement.

I believe what you want to say is 
> .. , this is equivalent as simply removing the entire condition and keeping only the else body. Which I did.

**Comment by HuGanghui** [comment] 2020-03-13 14:11
@wilcoln ok, Thanks~, your statement is more accurate.

**Comment by strkkk** [comment] 2020-03-15 11:55
Fix is merged.

**Closed by strkkk** 2020-03-15 11:55 UTC
Labels: approved, gsoc third issue
