### ISSUE TITLE
NPE at NoWhitespaceAfterCheck at INDEX_OP or METHOD_REF

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#4865] opened 2017-07-31 06:44 UTC
detected at CircleCI.
suppressed by - https://github.com/checkstyle/contribution/commit/284acd31b9f3d5274f72ba489d6aff335c286437
```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /home/ubuntu/checkstyle/contribution/checkstyle-tester/src/main/java/lucene-solr/solr/core/src/test/org/apache/solr/request/SimpleFacetsTest.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
    at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
    at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:473)
    ... 28 more
Caused by: java.lang.NullPointerException
    at com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceAfterCheck.getPositionAfter(NoWhitespaceAfterCheck.java:181)
    at com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceAfterCheck.visitToken(NoWhitespaceAfterCheck.java:139)
    at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:419)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:556)
    at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:359)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:205)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
```

**Comment by rnveach** [comment] 2017-07-31 14:03
@romani This is a duplicate of #4557 .

**Comment by rnveach** [comment] 2017-08-01 21:32
I am closing because it is a duplicate.

**Closed by rnveach** 2017-08-01 21:32 UTC
Labels: approved
