### ISSUE TITLE
TodoCommentCheck overflows the stack for files with many comments

### ISSUE THREAD

**Issue by denizarsan** [checkstyle/checkstyle#4563] opened 2017-06-30 19:36 UTC
$ { echo "class C {"; for i in {00000..30000}; do echo "// "$i; done; echo "}"; } > C.java

$ javac C.java

$ cat config.xml
```
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="TodoComment"/>
  </module>
</module>
```
$ java -jar checkstyle-7.8.2-all.jar -c config.xml C.java 2>log
```
Starting audit...
```
$ head log
```
Exception in thread "main" java.lang.Error: Error was thrown while processing C.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:299)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:425)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:359)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:174)
Caused by: java.lang.StackOverflowError
        at com.puppycrawl.tools.checkstyle.api.DetailAST.setParent(DetailAST.java:205)
        at com.puppycrawl.tools.checkstyle.api.DetailAST.setParent(DetailAST.java:205)
        at com.puppycrawl.tools.checkstyle.api.DetailAST.setParent(DetailAST.java:205)
# [...] there are 1021 more lines for the same recursive call
```
---------------

While the input file may look like an artificial example, it is actually simplified from the real file
https://github.com/robovm/robovm/blob/ef091902377c00dc0fb2db87e8d79c8afb5e9010/tests/robovm/src/test/java/org/robovm/rt/LineNumbersInStackTracesTestMethods.java

**Comment by rnveach** [comment] 2017-08-01 22:14
I can confirm issue still exists in 8.1 .
It is unrelated to module in configuration, but to our Java parser.

> $ { echo "class C {"; for i in {00000..30000}; do echo "// "$i; done; echo "}"; } > C.java

File's tree looks like:
````
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|--LITERAL_CLASS -> class [1:0]
|--IDENT -> C [1:6]
`--OBJBLOCK -> OBJBLOCK [1:8]
    |--LCURLY -> { [1:8]
    |--SINGLE_LINE_COMMENT -> // [2:0]
    |  `--COMMENT_CONTENT ->  00000\n [2:2]
    |--SINGLE_LINE_COMMENT -> // [3:0]
    |  `--COMMENT_CONTENT ->  00001\n [3:2]
    |--SINGLE_LINE_COMMENT -> // [4:0]
    |  `--COMMENT_CONTENT ->  00002\n [4:2]
````

StackOverflow occurs at https://github.com/checkstyle/checkstyle/blob/4c10bc55b4aea0f7e3b95b06d820eedb7c6a6fb2/src/main/java/com/puppycrawl/tools/checkstyle/api/DetailAST.java#L206 .

**Comment by romani** [comment] 2017-08-04 18:26
fix is merged.

**Closed by romani** 2017-08-04 18:26 UTC
Labels: approved, bug
