### ISSUE TITLE
Uppercase letters to be allowed in package names in javadoc

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#4408] opened 2017-06-02 02:44 UTC
Taken from https://github.com/checkstyle/checkstyle/blob/25a37e5049b7816b34c552899841a978efc37a63/src/test/resources/com/puppycrawl/tools/checkstyle/checks/javadoc/InputTestInvalidAtSeeReference.java#L4 .

````
$ cat TestClass.java
/**
 * @see javax.swing.tree.DefaultTreeCellRenderer.get
 */
public class TestClass {
    void method() {
    }
}

$ java -jar checkstyle-7.8-all.jar -J TestClass.java
Exception in thread "main" java.lang.IllegalArgumentException: [ERROR:1] Javadoc comment at column 0 has parse error. Unrecognized error from ANTLR parser: null
    at com.puppycrawl.tools.checkstyle.DetailNodeTreeStringPrinter.parseJavadocAsDetailNode(DetailNodeTreeStringPrinter.java:71)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.parseAndPrintJavadocTree(AstTreeStringPrinter.java:117)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:99)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:103)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:103)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:103)
    at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printJavaAndJavadocTree(AstTreeStringPrinter.java:82)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:333)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:174)
````

If you change `get` to `ge` than the tree prints fine with the following for the javadoc section:
````
|  |  |  `--JAVADOC -> \n * @see javax.swing.tree.DefaultTreeCellRenderer.ge\n <EOF> [1:3]
|  |  |      |--NEWLINE -> \n [1:3]
|  |  |      |--LEADING_ASTERISK ->  * [2:0]
|  |  |      |--WS ->  [2:2]
|  |  |      |--JAVADOC_TAG -> @see javax.swing.tree.DefaultTreeCellRenderer.ge\n  [2:3]
|  |  |      |  |--SEE_LITERAL -> @see [2:3]
|  |  |      |  |--WS ->  [2:7]
|  |  |      |  |--REFERENCE -> javax.swing.tree.DefaultTreeCellRenderer. [2:8]
|  |  |      |  |  |--PACKAGE -> javax.swing.tree [2:8]
|  |  |      |  |  |--DOT -> . [2:24]
|  |  |      |  |  |--CLASS -> DefaultTreeCellRenderer [2:25]
|  |  |      |  |  `--DOT -> . [2:48]
|  |  |      |  `--DESCRIPTION -> ge\n  [2:50]
|  |  |      |      |--TEXT -> ge [2:50]
|  |  |      |      |--NEWLINE -> \n [2:52]
|  |  |      |      `--TEXT ->  [3:0]
|  |  |      `--EOF -> <EOF> [3:1]
````
To me, this makes no sense why the parser is failing because of the word `get`.
One possibly explanation is [we may be too strict on casing for package and class](https://github.com/checkstyle/checkstyle/blob/ef112d1868e476219fbff6f4ed8a8e9dc54af3c3/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocLexer.g4#L122-L125), but then why doesn't `ge` fail the same.

Looking at tree output, to me `ge` shouldn't be part of description but in reference.

**Comment by MEZk** [comment] 2017-06-04 11:53
@rnveach 
> but then why doesn't ge fail the same.

```DefaultTreeCellRenderer``` recognized as CLASS. JavadocLexer thinks that after CLASS there should be HASH which is followed by a class member, but in your example there is DOT followed by ```get```. If ```get``` should be a part of the reference, then should it be a part of PACKAGE? If it should be a part of the PACKAGE than how can we distinguish CLASS from PACKAGE?

In order to allow ```get``` to be a part of PACKAGE we need to change the grammar. Something like this:

```
PACKAGE: [a-zA-Z_$] ([a-zA-Z0-9_$] | '.')+ [a-zA-Z0-9_$] {referenceCatched = true;};
```

The tree will be:

```
CLASS_DEF -> CLASS_DEF [4:0]
|--MODIFIERS -> MODIFIERS [4:0]
|   |--BLOCK_COMMENT_BEGIN -> /* [1:0]
|   |   |--COMMENT_CONTENT -> *\n * @see javax.swing.tree.DefaultTreeCellRenderer.get\n  [1:2]
|   |   |   `--JAVADOC -> \n * @see javax.swing.tree.DefaultTreeCellRenderer.get\n <EOF> [1:3]
|   |   |       |--NEWLINE -> \n [1:3]
|   |   |       |--LEADING_ASTERISK ->  * [2:0]
|   |   |       |--WS ->   [2:2]
|   |   |       |--JAVADOC_TAG -> @see javax.swing.tree.DefaultTreeCellRenderer.get\n  [2:3]
|   |   |       |   |--SEE_LITERAL -> @see [2:3]
|   |   |       |   |--WS ->   [2:7]
|   |   |       |   |--REFERENCE -> javax.swing.tree.DefaultTreeCellRenderer.get [2:8]
|   |   |       |   |   `--PACKAGE -> javax.swing.tree.DefaultTreeCellRenderer.get [2:8]
|   |   |       |   |--NEWLINE -> \n [2:52]
|   |   |       |   `--WS ->   [3:0]
|   |   |       `--EOF -> <EOF> [3:1]
|   |   `--BLOCK_COMMENT_END -> */ [3:1]
|   `--LITERAL_PUBLIC -> public [4:0]
|--LITERAL_CLASS -> class [4:7]
|--IDENT -> InputJavadocParserFailure [4:13]
`--OBJBLOCK -> OBJBLOCK [4:39]
    |--LCURLY -> { [4:39]
    |--METHOD_DEF -> METHOD_DEF [5:4]
    |   |--MODIFIERS -> MODIFIERS [5:4]
    |   |--TYPE -> TYPE [5:4]
    |   |   `--LITERAL_VOID -> void [5:4]
    |   |--IDENT -> method [5:9]
    |   |--LPAREN -> ( [5:15]
    |   |--PARAMETERS -> PARAMETERS [5:16]
    |   |--RPAREN -> ) [5:16]
    |   `--SLIST -> { [5:18]
    |       `--RCURLY -> } [6:4]
    `--RCURLY -> } [7:0]
```

As it can be seen, ```get``` became the part of PACKAGE.

**Comment by rnveach** [comment] 2017-06-04 16:13
> If get should be a part of the reference, then should it be a part of PACKAGE?

Originally I was thinking `get` should be class and the rest package. I don't think we can assume all users will write packages in lower case. I made this mistake before joining checkstyle.

> If it should be a part of the PACKAGE than how can we distinguish CLASS from PACKAGE?

We can't make this distinction in Java either.
> abc.def.ghi

`abc` can be a variable, and `def` be fields of the class.
`def` can be a class and `abc` could be the package it is in.
etc.

If we are too strict in grammar, users will get meaningless exceptions and not be sure what the problem is in their documentation without diving into our code.

**Comment by ps-sp** [comment] 2017-06-05 23:23
@rnveach @MEZk 

This tutorial on naming packages suggests that package names should be all lowercase: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

But the grammar page suggests that any identifier can be used: https://docs.oracle.com/javase/specs/jls/se8/html/jls-7.html#jls-PackageModifier

**Comment by MEZk** [comment] 2017-06-06 04:46
> This tutorial on naming packages suggests that package names should be all lowercase by convention: 

Convention is no a law. It it just suggestion. Language specification is what we must follow.

**Comment by romani** [comment] 2017-06-07 15:26
>Convention is not a law. It it just suggestion. Language specification is what we must follow.

Absolutely correct. Conventions are tending to change. Users have very different contexts so all that is compilable and match specification should be supported, in worse case ignored from validation, but not crashes for sure.

**Comment by romani** [comment] 2017-06-07 15:33
Expected see format is at http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#multiple@see

**Comment by ps-sp** [comment] 2017-06-19 11:16
@rnveach 
>but then why doesn't ge fail the same.

This is because `get` is taken in by ANTLR as a `package` token which by design has to be atleast 3 letters in length and the `reference` rule can only process one package . On the other hand `ge` is taken in as: `g: char` , `e: char` and hence can be attributed to the `description` rule which accepts text.

**Comment by ps-sp** [comment] 2017-06-22 13:27
[`PACKAGE`](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocLexer.g4#L122) token is used only in [`reference`](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L862) rule of the parser and all the tags using the `reference` rules (`@link`, `@see`, `@value`, `@linkplain` ) have the standard [package.class#member](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#package.class) notation for referencing members which is exactly identical to that of `@see` tag. So, should we delete the `PACKAGE` token  and replace it with `PACKAGE_CLASS` token as we can never separate a `package` from a `class` without context ?

**Comment by ps-sp** [comment] 2017-06-22 20:31
Consider this input:

    package com.puppycrawl.tools.checkstyle.checks.javadoc;

    /**
     * @see javax.swing.tree.DefaultTreeCellRenderer.getTreeCellRendererComponent()
     */
    class InputTestInvalidAtSeeReference {
    }

Currently, few of the UTs have this as input file and those UTs _assert_ an ANTLR error for parsing this file. With the modifications I have made to the grammar, I get the following parse tree for this input file:

    PACKAGE_DEF -> package [1:0]
    |--ANNOTATIONS -> ANNOTATIONS [1:46]
    |--DOT -> . [1:46]
    |   |--DOT -> . [1:39]
    |   |   |--DOT -> . [1:28]
    |   |   |   |--DOT -> . [1:22]
    |   |   |   |   |--DOT -> . [1:11]
    |   |   |   |   |   |--IDENT -> com [1:8]
    |   |   |   |   |   `--IDENT -> puppycrawl [1:12]
    |   |   |   |   `--IDENT -> tools [1:23]
    |   |   |   `--IDENT -> checkstyle [1:29]
    |   |   `--IDENT -> checks [1:40]
    |   `--IDENT -> javadoc [1:47]
    `--SEMI -> ; [1:54]
    CLASS_DEF -> CLASS_DEF [6:0]
    |--MODIFIERS -> MODIFIERS [6:0]
    |--BLOCK_COMMENT_BEGIN -> /* [3:0]
    |   |--COMMENT_CONTENT -> *\r\n * @see javax.swing.tree.DefaultTreeCellRenderer.getTreeCellRendererComponent()\r\n  [3:2]
    |   |   `--JAVADOC -> JAVADOC [3:3]
    |   |       |--NEWLINE -> \r\n [3:3]
    |   |       |--LEADING_ASTERISK ->  * [4:0]
    |   |       |--WS ->   [4:2]
    |   |       |--JAVADOC_TAG -> JAVADOC_TAG [4:3]
    |   |       |   |--SEE_LITERAL -> @see [4:3]
    |   |       |   |--WS ->   [4:7]
    |   |       |   |--REFERENCE -> REFERENCE [4:8]
    |   |       |   |   `--PACKAGE_CLASS -> javax.swing.tree.DefaultTreeCellRenderer.getTreeCellRendererComponent [4:8]
    |   |       |   `--DESCRIPTION -> DESCRIPTION [4:78]
    |   |       |       |--TEXT -> () [4:78]
    |   |       |       |--NEWLINE -> \r\n [4:80]
    |   |       |       `--TEXT ->   [5:0]
    |   |       `--EOF -> <EOF> [5:1]
    |   `--BLOCK_COMMENT_END -> */ [5:1]
    |--LITERAL_CLASS -> class [6:0]
    |--IDENT -> InputTestInvalidAtSeeReference [6:6]
    `--OBJBLOCK -> OBJBLOCK [6:37]
        |--LCURLY -> { [6:37]
        `--RCURLY -> } [7:0]

What sort of behavior or parse tree do we want for this ? Should we generate a parse tree for this or it should continue to result in ANTLR error. If this still is supposed to result in an ANTLR error then should presence of parenthesis after `reference` lead to an ANTLR error ? If not, what exactly should the ANTLR error stem from for such inputs.

**Comment by romani** [comment] 2017-06-23 21:14
@Vladlis and @sabaka , please address question from your student.

**Comment by Vladlis** [comment] 2017-06-27 22:16
@ps-sp , this case should definitely result in error as description has to be separeted from reference by a whitespace. Let's stay with an existing errors asserted in UTs.

**Comment by ps-sp** [comment] 2017-06-28 08:09
> As description has to be separated from reference by a whitespace. Let's stay with an existing errors asserted in UTs.

Please consider this input:

`* @serial includeDescription`

Following is the output javadoc tree generated for it which is the same for my checkstyle master and my patch:

    JAVADOC -> JAVADOC [0:0]
    |--LEADING_ASTERISK -> * [0:0]
    |--WS ->   [0:1]
    |--JAVADOC_TAG -> JAVADOC_TAG [0:2]
    |   |--SERIAL_LITERAL -> @serial [0:2]
    |   |--WS ->   [0:9]
    |   |--LITERAL_INCLUDE -> include [0:10]
    |   `--DESCRIPTION -> DESCRIPTION [0:17]
    |       `--TEXT -> Description [0:17]
    `--EOF -> <EOF> [0:28]

This is because `WS` is not ascertained before `DESCRIPTION` in the [JavadocParser here](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L883). There were few other places too where `WS` has not been ascertained.

In my patch I have ascertained `WS` [everywhere](https://github.com/ps-sp/checkstyle/blob/925df8ddc1577a3ce4715349b1b70ede7e137705/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L870-#L898) but for [SERIAL_LITERAL](https://github.com/ps-sp/checkstyle/blob/925df8ddc1577a3ce4715349b1b70ede7e137705/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L885) , since it was failing a UT if I remember correctly.

Please confirm the accepted behaviour for `SERIAL_LITERAL`.

**Comment by Vladlis** [comment] 2017-06-28 08:34
@ps-sp, yes, looks like `WS` is missed before `description` in some tags. Why do think `SERIAL_LITERAL` can be an exclusion?

**Comment by ps-sp** [comment] 2017-06-29 07:33
@Vladlis No. I don't think it should be, rather there should be a space before description everywhere ! I will update PR

**Comment by romani** [comment] 2017-09-17 13:52
fix is merged

**Closed by romani** 2017-09-17 13:52 UTC
Labels: antlr, approved, breaking compatibility, GSoC2017, javadoc
