### ISSUE TITLE
RedundantModifier incorrectly flags public constructor on nested class inside interface

### ISSUE THREAD

**Issue by nmx** [checkstyle/checkstyle#2199] opened 2015-09-17 21:03 UTC
public interface Iface {
        class Inner {
            public Inner(final int x) {
            }
        }
    }

I get:
src/x/Iface.java:3:9: Redundant 'public' modifier.

It's not redundant; inner classes of interfaces are inherently public, so leaving out the public modifier on the constructor makes the constructor package-private instead.

**Comment by romani** [comment] 2015-09-17 21:34
duplicate of #2167 , #2188.

please help to test a patch - https://github.com/checkstyle/checkstyle/issues/2188#issuecomment-140732833

**Closed by romani** 2015-09-17 21:34 UTC
