### ISSUE TITLE
Migrate to CircleCI 2.0

### ISSUE THREAD

**Issue by Vladlis** [checkstyle/checkstyle#5657] opened 2018-03-29 09:18 UTC
https://circleci.com/docs/1.0/

> We’re sunsetting CircleCI 1.0: August 31, 2018 is the final day for 1.0 builds. Refer to CircleCI 2.0 Hello World document for users and developers to get started with CircleCI 2.0.

**Comment by romani** [comment] 2018-03-29 12:06
Duplicate of #5528

**Closed by romani** 2018-03-29 12:06 UTC
Labels: CI
