### ISSUE TITLE
pitest: increase mutation coverage for pitest-imports profile to 100% 

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#6658] opened 2019-04-13 16:57 UTC
We should increase coverage for pitest-imports profile up to 100%.
This issue is a subtask of #3708

https://github.com/checkstyle/checkstyle/blob/d68d8c2d5d4037746cbe61e5d973a12e0ec886a4/.ci/pitest.sh#L106-L136

-------

<a href="https://www.bountysource.com/issues/72804073-pitest-increase-mutation-coverage-for-pitest-imports-profile-to-100">
<img src="https://api.bountysource.com/badge/issue?issue_id=72804073">
</a>

**Comment by developerhb** [comment] 2020-08-17 14:03
Hello @rnveach @romani .
I have started working on this issue.

As a starting I have executed pitest on updated master branch using command ` ./.ci/pitest.sh pitest-imports`. 
Here is the link to pitest report https://developerhb.github.io/202008171803/com.puppycrawl.tools.checkstyle.checks.imports/index.html

In the report however, I don't found some surviving mutations which are mentioned in **pitest.sh** in the issue description. Like mutations in class `AvoidStarImportCheck` and `CustomImportOrderCheck` are killed.

I have calculated that there are total 12 mutations surviving in 5 classes. 
Here is the summary

IllegalImportCheck - 1 surviving mutation
ImportControlLoader - 2 surviving mutation
ImportOrderCheck - 4 surviving mutation
PkgImportControl - 4 surviving mutation
PkgImportRule - 1 surviving mutation

**Comment by developerhb** [comment] 2020-08-17 14:04
@rnveach @romani If there are no faults in my report I would first suggest to remove the mutations from pitest.sh file that are not really surviving.

**Comment by developerhb** [comment] 2020-08-17 14:12
@romani I would also like to know if this project is implemeted :point_down:
https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2020-Project-Ideas#project-name-generation-and-publishing-regression-diff-report-based-on-configs-in-pull-request-description

It would be very helpful if this feature is available cause generating diff report for multiple projects and then uploading it consumes a lot of time.

**Comment by rnveach** [comment] 2020-08-17 23:27
@developerhb If there are lines that are not surviving in report, then I would first start looking into how they are appearing on the report as that would be an issue. Please make sure you are looking in latest master, and not an old commit. Print out in first post is tied to specific commit and is old now.

The following points to latest master.
https://github.com/checkstyle/checkstyle/blob/master/.ci/pitest.sh#L69-L83

> know if this project is implemeted 

I believe it is, but I don't know its current status or how to use it. @romani Please point to a guide.

**Comment by developerhb** [comment] 2020-08-18 04:50
You are right @rnveach I was looking at the print out in first post and not in the latest **pitest.sh**.

**Comment by developerhb** [comment] 2020-08-18 07:10
@rnveach @romani I am starting with this mutation 👇
`"IllegalImportCheck.java.html:<td class='covered'><pre><span  class='survived'>        if (!result) {</span></pre></td></tr>"`

Here is the link to hardcoded mutation
https://github.com/developerhb/checkstyle/commit/9a77f065bed68b934b7930cd55a4fec397904979

**Comment by romani** [comment] 2020-09-12 19:49
>Or we create two new functions - One for Illegal Package and another for Illegal Class.

Let's try this first. Thanks a lot for detailed report.

**Comment by developerhb** [comment] 2020-09-13 04:51
@romani 
> > Or we create two new functions - One for Illegal Package and another for Illegal Class.
> 
> Let's try this first. Thanks a lot for detailed report.

I just realized that even if we create two different functions, we would need to condition to stop execution of both functions every time. That condition would again survive mutation. So, what I suggest is we should remove condition.

**Comment by romani** [comment] 2020-09-13 05:20
Please remove condition

**Comment by developerhb** [comment] 2020-09-13 11:38
@romani 
> Please remove condition

Done. Created Pull Request.

**Comment by developerhb** [comment] 2020-09-14 05:50
@romani travis and cricle ci are failing in PR https://github.com/checkstyle/checkstyle/pull/8829. Please help.

**Comment by developerhb** [comment] 2020-09-20 03:28
@romani Now I am working on `ImportControlLoader`. How can I run Regression for that?

**Comment by romani** [comment] 2020-09-20 13:21
@developerhb , you need to configure ImportControl Check in some way.

**Comment by developerhb** [comment] 2020-09-21 13:59
@romani This is from pit report 👇 

I am dealing with `ImportControlLoader`. The surviving mutation is,

![image](https://user-images.githubusercontent.com/53093601/93775605-3d9c9580-fc40-11ea-9368-9abf2aa56a71.png)
![image](https://user-images.githubusercontent.com/53093601/93775644-5016cf00-fc40-11ea-8c1d-fceaa35e229c.png)

If I am interpreting it correctly, there are two mutations.
1) `ALLOW_ELEMENT_NAME.equals(qName)` replaced with `false`.
2) `"disallow".equals(qName)` replaced with `true`.

When I hardcode the first mutation the tests are failing. In that case that mutation should be killed. But its not.
I am surprised at this output.
Please help.

**Comment by romani** [comment] 2020-09-23 13:35
@developerhb , 
so it means that assumption is wrong :), because from pitest report it is not clear what part was changed.
please try all combinations (`-` mean keep unchanged)
```
- true
- false
true -
false -
```

**Comment by developerhb** [comment] 2020-09-23 13:41
@romani I tried both `- false` as well as `false - `, but in both cases tests fail. I am also surprised. What could be the reason?

**Comment by romani** [comment] 2020-09-23 13:41
try all 4 cases.

**Comment by developerhb** [comment] 2020-09-23 13:45
@romani okay will try all of them.

**Comment by romani** [comment] 2022-07-31 14:56
@Vyom-Yadav , did you fix this issue ? 
I see that https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L2973 ALL mutators are activated.

this issue was about to kill old set of mutators. it is better to   close this issue and let you get a bounty of it.

**Comment by nick-mancuso** [comment] 2022-07-31 17:54
Let's review what we left from previous mutations, but I think we have created issues/ killed/ permanently suppressed all old survivors.

**Comment by Vyom-Yadav** [comment] 2022-07-31 18:41
All old mutations in `pitest-imports` have been killed (https://github.com/checkstyle/checkstyle/blob/6db6d5f0c7caf7242dcba370c20929bad38bc3ae/.ci/pitest-suppressions/pitest-imports-suppressions.xml)

- https://github.com/checkstyle/checkstyle/pull/11921
- https://github.com/checkstyle/checkstyle/pull/11923
- https://github.com/checkstyle/checkstyle/pull/11922

**Comment by romani** [comment] 2022-07-31 19:34
@nick-mancuso , please double check and close issue

**Comment by nick-mancuso** [comment] 2022-08-01 00:37
Confirmed that all remaining surviving mutations are from newly added "ALL" group:

```
➜  checkstyle git:(master) git log -1
commit e4588bdee037f2d97f782ef706c219802bb12a73 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: Vyom-Yadav <jackhammervyom@gmail.com>
Date:   Thu Jul 28 23:32:27 2022 +0530

    Issue #11720: Kill surviving mutation in VariableDeclarationUsageDistanceCheck in searchVariableUsageExpressions

➜  checkstyle git:(master) git diff 24aedad~1:pom.xml 24aedad:pom.xml
diff --git a/pom.xml b/pom.xml
index d728131fe..21e35896b 100644
--- a/pom.xml
+++ b/pom.xml
@@ -2930,15 +2930,33 @@
               <mutators>
                 <mutator>CONDITIONALS_BOUNDARY</mutator>
                 <mutator>CONSTRUCTOR_CALLS</mutator>
-                <mutator>FALSE_RETURNS</mutator>
                 <mutator>INCREMENTS</mutator>
+                <!-- Read reason of disablement at https://github.com/checkstyle/checkstyle/issues/11895 -->
+                <!-- <mutator>INLINE_CONSTS</mutator> -->
                 <mutator>INVERT_NEGS</mutator>
                 <mutator>MATH</mutator>
                 <mutator>NEGATE_CONDITIONALS</mutator>
-                <mutator>REMOVE_CONDITIONALS</mutator>
+                <mutator>NON_VOID_METHOD_CALLS</mutator>
+                <mutator>REMOVE_CONDITIONALS_EQUAL_ELSE</mutator>
+                <mutator>REMOVE_CONDITIONALS_EQUAL_IF</mutator>
+                <mutator>REMOVE_CONDITIONALS_ORDER_ELSE</mutator>
+                <mutator>REMOVE_CONDITIONALS_ORDER_IF</mutator>
                 <mutator>RETURN_VALS</mutator>
-                <mutator>TRUE_RETURNS</mutator>
                 <mutator>VOID_METHOD_CALLS</mutator>
+                <mutator>EXPERIMENTAL_ARGUMENT_PROPAGATION</mutator>
+                <mutator>EXPERIMENTAL_BIG_DECIMAL</mutator>
+                <mutator>EXPERIMENTAL_BIG_INTEGER</mutator>
+                <mutator>EXPERIMENTAL_MEMBER_VARIABLE</mutator>
+                <mutator>EXPERIMENTAL_NAKED_RECEIVER</mutator>
+                <mutator>REMOVE_INCREMENTS</mutator>
+                <mutator>EXPERIMENTAL_RETURN_VALUES_MUTATOR</mutator>
+                <mutator>EXPERIMENTAL_SWITCH</mutator>
+                <mutator>REMOVE_SWITCH</mutator>
+                <mutator>FALSE_RETURNS</mutator>
+                <mutator>TRUE_RETURNS</mutator>
+                <mutator>EMPTY_RETURNS</mutator>
+                <mutator>NULL_RETURNS</mutator>
+                <mutator>PRIMITIVE_RETURNS</mutator>
               </mutators>
               <targetClasses>
                 <param>com.puppycrawl.tools.checkstyle.checks.imports.*</param>
@@ -2950,7 +2968,7 @@
                 <param>*.Input*</param>
               </excludedTestClasses>
               <coverageThreshold>100</coverageThreshold>
-              <mutationThreshold>97</mutationThreshold>
+              <mutationThreshold>98</mutationThreshold>
               <timeoutFactor>${pitest.plugin.timeout.factor}</timeoutFactor>
               <timeoutConstant>${pitest.plugin.timeout.constant}</timeoutConstant>
               <threads>${pitest.plugin.threads}</threads>

➜  checkstyle git:(master) cat .ci/pitest-suppressions/pitest-imports-suppressions.xml | grep mutator | sort -u
    <mutator>org.pitest.mutationtest.engine.gregor.mutators.experimental.ArgumentPropagationMutator</mutator>
    <mutator>org.pitest.mutationtest.engine.gregor.mutators.experimental.MemberVariableMutator</mutator>
    <mutator>org.pitest.mutationtest.engine.gregor.mutators.experimental.NakedReceiverMutator</mutator>
    <mutator>org.pitest.mutationtest.engine.gregor.mutators.NonVoidMethodCallMutator</mutator>


```

**Closed** 2022-08-01 00:37 UTC
Labels: approved, miscellaneous, has bounty

**Comment by romani** [comment] 2022-08-01 03:43
@Vyom-Yadav , please claim bounty

**Comment by Vyom-Yadav** [comment] 2022-08-01 03:50
> @Vyom-Yadav , please claim bounty 

Done
