### ISSUE TITLE
MismatchedTokenException on annotated varargs

### ISSUE THREAD

**Issue by maggu2810** [checkstyle/checkstyle#5629] opened 2018-03-21 22:03 UTC
`/var/tmp $ javac App.java`:

```
```

`/var/tmp $ cat App.java`:

```
import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

public class App {
    @Documented
    @Retention(value = RetentionPolicy.CLASS)
    @Target(value = {ElementType.TYPE_USE})
    @interface Nullable {
    }

    public void foo(String text, Object @Nullable ... arguments) {
        String.format(text, arguments);
    }
}
```

`/var/tmp $ cat config.xml`:

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
<module name = "Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="OuterTypeFilename"/>
    </module>
</module>
```

`/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.8-all.jar -c config.xml App.java`:

```
Starting audit...
/var/tmp/App.java:14:51: unexpected token: ...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing App.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:299)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:217)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:523)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:438)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:211)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: MismatchedTokenException occurred while parsing file /var/tmp/App.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:100)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:181)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:83)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:320)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:290)
        ... 4 more
Caused by: /var/tmp/App.java:16:5: expecting EOF, found '}'
        at antlr.Parser.match(Parser.java:211)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:211)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:94)
        ... 8 more
Checkstyle ends with 1 errors.
```

---------------

I do not expect any exception.
It seems the used module does not really care as long as `GeneratedJavaRecognizer.compilationUnit` (and so `antlr.Parser.match`) will be called.

-------

<a href="https://www.bountysource.com/issues/56305623-mismatchedtokenexception-on-annotated-varargs">
<img src="https://api.bountysource.com/badge/issue?issue_id=56305623">
</a>

**Comment by rnveach** [comment] 2018-03-21 22:48
most likely this is a duplicate of https://github.com/checkstyle/checkstyle/issues/3238

**Comment by romani** [comment] 2018-03-21 23:14
unfortunately still a non resolved problem, please try to use http://checkstyle.sourceforge.net/config_filefilters.html#BeforeExecutionExclusionFileFilter to skip this file completely from consideration by checkstyle.

**Comment by pbludov** [comment] 2018-03-22 05:03
Duplicates #3238

**Comment by maggu2810** [comment] 2018-03-22 10:16
@romani Thanks, will give it a try.

**Comment by nmancus1** [comment] 2020-03-20 03:28
@romani I think this issue can be closed as well, I can't reproduce this on latest master.

**Comment by romani** [comment] 2020-03-20 05:03
Please show prove by CLI output

**Comment by nmancus1** [comment] 2020-03-20 05:10
```➜  Issue-5629 javac App.java
➜  Issue-5629 cat App.java
import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

public class App {
    @Documented
    @Retention(value = RetentionPolicy.CLASS)
    @Target(value = {ElementType.TYPE_USE})
    @interface Nullable {
    }

    public void foo(String text, Object @Nullable ... arguments) {
        String.format(text, arguments);
    }
}
➜  Issue-5629 cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
<module name = "Checker">
    <property name="charset" value="UTF-8"/>
    <module name="TreeWalker">
        <module name="OuterTypeFilename"/>
    </module>
</module>
➜  Issue-5629 java -Duser.language=en -Duser.country=US -jar checkstyle-8.31-SNAPSHOT-all.jar -c config.xml App.java
Starting audit...
Audit done.
```

**Comment by romani** [comment] 2020-03-20 12:53
fix is released at 8.29, fixed by @esilkensen at  #3238 or related.

```
$ cat Test.java 
public class App {
    @Documented
    @Retention(value = RetentionPolicy.CLASS)
    @Target(value = {ElementType.TYPE_USE})
    @interface Nullable {
    }

    public void foo(String text, Object @Nullable ... arguments) {
        String.format(text, arguments);
    }
}rivanov@p5510:/var/tmp$ java -jar /var/tmp/checkstyle-8.29-all.jar -c config.xml Test.java 
Starting audit...
Audit done.

```

this issue has a bounty, @esilkensen , please claim a bounty.

**Comment by esilkensen** [comment] 2020-03-21 06:14
Thanks @romani! 

I "started a solution" on bountyhunter, it says
>You will be able to claim this bounty as soon as the original issue is marked as closed.

I wonder if that means this issue would need to be reopened and then closed again... I will try that quickly just to check.

**Comment by esilkensen** [comment] 2020-03-21 06:18
That doesn't seem to have changed anything -- maybe I would have needed to find the issue in bountyhunter and "start working on it" before the original PR was merged.

**Comment by romani** [comment] 2020-03-21 20:23
@esilkensen, reopened, please try again.

**Comment by esilkensen** [comment] 2020-03-21 21:12
Thanks @romani, no luck unfortunately, I tried emailing support@bountysource.com just now so maybe they will have an idea, but if not, no big deal 🙂

**Comment by romani** [comment] 2020-03-21 21:25
https://www.bountysource.com/issues/56305623-mismatchedtokenexception-on-annotated-varargs I see button "solve issue" what happening why you press it ?

**Comment by esilkensen** [comment] 2020-03-21 21:59
I see this screen after pressing it:
![image](https://user-images.githubusercontent.com/94125/77237328-ed5b5280-6b8c-11ea-908c-e7822c627f34.png)

**Comment by rnveach** [comment] 2020-03-21 22:03
Try now.

**Closed** 2020-03-21 22:03 UTC
Labels: antlr, approved, has bounty

**Comment by romani** [comment] 2020-03-21 22:29
@esilkensen , I got notification that you started to work on issue, please try to claim it.

**Comment by esilkensen** [comment] 2020-03-21 22:51
Looks like that worked, I was able to claim it now, thank you both!
