### ISSUE TITLE
check source file get NullPointerException

### ISSUE THREAD

**Issue by Wang-Jun-Chao** [checkstyle/checkstyle#4634] opened 2017-07-06 06:22 UTC
I use checkstyle to check my source file, I get an error.

```
<file name="E:\developtool\svncheck\TmpFile\src\E-CODE-workspace-cpqprototypemain-cpq-comm-src-main-java-unistar-cpq-comm\CommError.java">
<error line="0" severity="error" message="Got an exception - java.lang.NullPointerException" source="com.puppycrawl.tools.checkstyle.TreeWalker"/>
</file>
```
My source file is
```
package unistar.cpq.comm;

public enum CommError implements CPQError
{

    INVALID_INPUT( CPQError.COMMOM_ERROR_START + 1 ), // 1
    SERVER_ERROR( CPQError.COMMOM_ERROR_START + 2 ), // 2
    UNSUPPORT_DATA_TYPE( CPQError.COMMOM_ERROR_START + 3 );// 3
    private int errorCode;

    private CommError( int errorCode )
    {
        this.errorCode = errorCode;

    }

    @Override
    public int getErrorCode()
    {
        return errorCode;
    }

    @Override
    public void setErrorCode( int errorCode )
    {
        this.errorCode = errorCode;

    }
}
```
is this a bug. my checkstyle version is 4.4

**Comment by rnveach** [comment] 2017-07-06 06:38
> my checkstyle version is 4.4

@Wang-Jun-Chao Your checkstyle version is too old. We are now on version 8.
It is so old that we have probably fixed the issue by now.

Even if it wasn't fixed, I cannot reproduce the error on 4.4 or 8.0.
Please give us a configuration, and reproduce an issue on latest Checkstyle version using CLI (http://checkstyle.sourceforge.net/cmdline.html). 
CLI should give full stack trace.

**Comment by romani** [comment] 2017-07-14 16:34
If no feedback provided till end of month, we will close the issue

**Comment by rnveach** [comment] 2017-08-01 21:33
I am closing due to no feedback

**Closed by rnveach** 2017-08-01 21:33 UTC
