### ISSUE TITLE
StackOverflow in com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.findMatch

### ISSUE THREAD

**Issue by SergeyMakarenko** [checkstyle/checkstyle#48] opened 2013-11-05 23:16 UTC
MultilineDetector.findMatch is a recursive function which will return only if it was not able to find a match. Otherwise it will call itself again which will cause StackOverflow.
There is some check for exceeded number of matches but that check only logs such situation but does not stops the recursion. Probably that check should also break recursion in some way.
Below is Eclipse's stack trace which encountered this problem.
java.lang.StackOverflowError
	at java.util.AbstractCollection.toArray(AbstractCollection.java:175)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:236)
	at com.puppycrawl.tools.checkstyle.DefaultConfiguration.getMessages(DefaultConfiguration.java:144)
	at com.puppycrawl.tools.checkstyle.api.AbstractViolationReporter.getCustomMessages(AbstractViolationReporter.java:132)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.log(AbstractFileSetCheck.java:147)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.log(AbstractFileSetCheck.java:140)
	at com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.findMatch(MultilineDetector.java:83)
	at com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.findMatch(MultilineDetector.java:88)
	at com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.findMatch(MultilineDetector.java:88)
	at com.puppycrawl.tools.checkstyle.checks.regexp.MultilineDetector.findMatch(MultilineDetector.java:88)

**Comment by vorburger** [comment] 2015-06-18 13:54
I've also just hit this, clearly something wrong in that code: Using CS v6.1.1 which is still the default in maven-checkstyle-plugin:2.15, with a project that I can't easily share, but basically I was scanning A LOT (14746) of *.xml files with RegexpMultiline for "\r\n" for https://github.com/checkstyle/checkstyle/issues/893, which would have led to a lot of errors. But then using the regexp "(?s:\r\n.*)" instead to get only one error per file instead of for each line (thank you http://stackoverflow.com/questions/15003871/how-to-make-maven-checking-the-source-end-of-line) made this SO go away, reproducibly!

**Comment by romani** [comment] 2015-06-18 16:53
We restored backward compatibility in 6.2 ,http://checkstyle.sourceforge.net/releasenotes.html#Release_6.2 , please update your maven plugin configuration to use latest checkstyle 6.7 . 

Please let me know if that still failing.

You can share with us a part(even obfuscated) of file that cause a problem. You try to repproduce a problem by our cli - http://checkstyle.sourceforge.net/cmdline.html#Download_and_Run

**Comment by vorburger** [comment] 2015-06-18 20:24
@romani actually I've confused this StackOverflow (which I have also hit today, but cannot reproduce anymore now.. BTW is there a good reason why findMatch() is recursive?) with another StackOverflow problem, see https://github.com/checkstyle/checkstyle/issues/1221. However I'm proposing a fix for this one as well in https://github.com/checkstyle/checkstyle/pull/1225 because I'm on fire tonight - if it's that simple?

**Comment by romani** [comment] 2015-06-24 03:22
>  BTW is there a good reason why findMatch() is recursive?

no reason, just somebody contributed that code a while ago. I am open to better implementation.

**Comment by romani** [comment] 2015-07-01 03:43
merged.

**Closed** 2015-07-01 03:42 UTC
Labels: approved, high demand
