### ISSUE TITLE
Reduntant modifier on inner class constructor inside interface

### ISSUE THREAD

**Issue by krzyk** [checkstyle/checkstyle#2188] opened 2015-09-15 07:33 UTC
Here's code example:
```
public interface Keys {
    Key add(Add add);

    Optional<Key> find(Find find);

    List<Key> findKeys(Find find);

    class Find {
        private final String key;

        public Find(final String key) {
            this.key = key;
        }

        public String getKey() {
            return key;
        }
    }
}
```

I get ` Redundant 'public' modifier` on line with `public Find(final String key) {`, which is not correct because without public I can't construct the inner class.

**Comment by romani** [comment] 2015-09-15 14:41
Duplicate of https://github.com/checkstyle/checkstyle/pull/2134 .

@krzyk , please help to test that PR on your code, you can build all binaries by "mvn clean package -Passembly".

**Comment by krzyk** [comment] 2015-09-16 08:47
@romani I'll test it, but right now I have trouble building, probably because I'm behind proxy, and some of the tests (`SuppressionsLoaderTest.testLoadFromURL:75 » AssumptionViolated got: <false>, e...`) and xml-maven-plugin (`While parsing /tmp/checkstyle/src/site/resources/files/suppressions_none.xml: null: NullPointerException`) probably need direct internet connection.

I'll try to test it later today.

**Comment by romani** [comment] 2015-09-16 12:53
@krzyk ,

Links to snapshots:
checkstyle-6.11-SNAPSHOT-all.jar - https://drive.google.com/open?id=0B3LUiB4ZPKNjVFdmc2RJR0s5MTA
checkstyle-6.11-SNAPSHOT.jar - https://drive.google.com/open?id=0B3LUiB4ZPKNjNUlJeHh6dHVHVHc

that is really strange why you have UTs running, them should be skipped - https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L1120 , 

> xml-maven-plugin

yes, where is no skip option at this plugin.

**Comment by nmx** [comment] 2015-09-17 22:06
do we really need users to test this patch? this is something a unit test can easily capture...

**Comment by romani** [comment] 2015-09-17 22:26
@nmx , if that is ease for you, please confirm that such fix resolve all your false-positives.

We did one regression, I do not want to have one more.

if you have opensource project - please share a link to it.

**Comment by krzyk** [comment] 2015-09-18 10:44
@romani @nmx In either case, I can confirm that on my code base checkstyle from the URLs above is not complaining on inner classes in interfaces

**Closed** 2015-09-18 13:21 UTC
Labels: approved
