### ISSUE TITLE
Please tell me how to use MissingJavadocMethod, I have the following error.

### ISSUE THREAD

**Issue by sunchaser-lilu** [checkstyle/checkstyle#12236] opened 2022-09-29 09:07 UTC
just simple use

![image](https://user-images.githubusercontent.com/40930677/192988674-0045939f-89d5-4070-b700-dc43555ee17d.png)

```text
无法初始化类： 'MissingJavadocMethod' ，也无法初始化： .MissingJavadocMethod, MissingJavadocMethodCheck, .MissingJavadocMethodCheck。 请检查类名大小写，或阅读帮助手册中短名称配置部分： https://checkstyle.org/config.html#Packages.  同时，请检查Checker的ClassLoader是否配置正确。
```

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-checkstyle-plugin</artifactId>
    <version>3.1.0</version>
</plugin>
```

Can anyone tell me where is the problem? thanks.

I have read check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac YOUR_FILE.java
#[[MAKE SURE THERE IS SUCCESSFUL COMPILATION]]

/var/tmp $ cat config.xml
#[[PLACE YOUR OUTPUT HERE]]

/var/tmp $ cat YOUR_FILE.java
#[[PLACE YOU OUTPUT HERE]]

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
#[[PLACE YOUR OUTPUT HERE]]
```

For Windows users, please use `type` instead of `cat` and run

```cmd
set RUN_LOCALE="-Duser.language=en -Duser.country=US"
java %RUN_LOCALE% -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
```

in place of the last 2 commands above.

---

**Describe what you expect in detail.**

---

Still not clear ???
see example - https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

ATTENTION: FAILURE TO FOLLOW THE ABOVE TEMPLATE WILL RESULT IN THE ISSUE BEING CLOSED.

**Comment by rnveach** [comment] 2022-09-29 14:31
You did not provide any of the information requested in the template.

At just glance, I would confirm what version of checkstyle the maven plugin is using. The check was just introduced in 8.21 .

I am closing this as the issue is incompelte and may not be a problem with our library.

**Closed by rnveach** 2022-09-29 14:31 UTC
