### ISSUE TITLE
Resolve Pitest Issues - IllegalImportCheck (1)

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7854] opened 2020-03-15 16:12 UTC
Child issue of https://github.com/checkstyle/checkstyle/issues/7797 ,

https://github.com/checkstyle/checkstyle/blob/abf829f542023e089c741c55f73098cae52dcb12/.ci/pitest.sh#L82

**Comment by DXTkastb** [comment] 2020-03-15 20:06
I'm on it

**Comment by DXTkastb** [comment] 2020-03-20 17:45
@akki111singh yeah sure!

**Comment by akki111singh** [comment] 2020-03-21 05:59
# 1.Pitest  Report
* Link : https://akki111singh.github.io/pitest-reports/202003201414/com.puppycrawl.tools.checkstyle.checks.imports/IllegalImportCheck.java.html
* Surviving Mutations: 
	on line 398 : 3. removed conditional - replaced equality check with true → SURVIVED
	on line 422 : 3. removed conditional - replaced equality check with true → SURVIVED
	on line 440 : 3. removed conditional - replaced equality check with true → SURVIVED 
	I am focusing on the third one

# 2.Mutated Branch
* Hardcoded Mutated commit:   [981403f](https://github.com/akki111singh/checkstyle/commit/981403f91850155c6ada09054a5c3abd0d2e0869)
* Since the mutation was `removed conditional - replaced equality check with true → SURVIVED`so therefore the `if-else` statement was removed to set the execution of all the statements to always true.
# 3 Regression Report
* Regression Report: https://akki111singh.github.io/diff/index.html
* Modules used in the config file:

	   <module name="IllegalImport">
          <property name="regexp" value="true"/>
          <property name="illegalPkgs" value="java\.util"/>
        </module>
        
        <module name="IllegalImport">
          <property name="illegalPkgs" value="java.io, java.sql"/>
        </module>

**Comment by akki111singh** [comment] 2020-03-21 07:10
@rnveach please review

**Comment by rnveach** [comment] 2020-03-21 12:50
Everything looks good to me.

**Comment by strkkk** [comment] 2020-03-23 06:57
Fix is merged

**Closed by strkkk** 2020-03-23 06:57 UTC
Labels: approved, gsoc third issue
