### ISSUE TITLE
NPE in SuppressWarningsHolder

### ISSUE THREAD

**Issue by lkoe** [checkstyle/checkstyle#2284] opened 2015-10-08 18:11 UTC
I got a bug filed agains eclipse-cs (https://sourceforge.net/p/eclipse-cs/bugs/395/)

```
java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.isSuppressed(SuppressWarningsHolder.java:207)
        at com.puppycrawl.tools.checkstyle.filters.SuppressWarningsFilter.accept(SuppressWarningsFilter.java:38)
        at com.puppycrawl.tools.checkstyle.api.FilterSet.accept(FilterSet.java:88)
        at com.puppycrawl.tools.checkstyle.Checker.fireErrors(Checker.java:353)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:271)
        at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:159)
        at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:300)
        at net.sf.eclipsecs.core.jobs.RunCheckstyleOnFilesJob.runInWorkspace(RunCheckstyleOnFilesJob.java:116)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by romani** [comment] 2015-10-08 18:29
We use that module in default configuration and it works fine in our build system:
https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_checks.xml#L286

we need more details on how to reproduce this problem.
Please try to reproduce problem by CLI - http://checkstyle.sourceforge.net/cmdline.html#Download_and_Run

**Comment by MEZk** [comment] 2015-10-13 11:14
@romani 
Looks like we did some changes in SuppressWarningsHolder, because there is the "}" on line 207.
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java#L207

@lkoe 
Could you specify what checkstyle version do you use?

**Comment by lkoe** [comment] 2015-10-13 17:43
@MEZk Personally, I did not get the error - I just relayed a bug reported against eclipse-cs
The original poster probably was using Checkstyle 6.11.2 via the eclipse-cs plugin.

My intention was to use this bug as a vehicle for a more common issue, see #2285.

**Comment by lennartj** [comment] 2015-11-24 09:25
I tend to get these errors when running site in projects. Since it aborts the site generation, it also aborts any attempt to release the project with a Checkstyle report...

```
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.isSuppressed(SuppressWarningsHolder.java:155)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWarningsFilter.accept(SuppressWarningsFilter.java:37)
	at com.puppycrawl.tools.checkstyle.api.FilterSet.accept(FilterSet.java:88)
	at com.puppycrawl.tools.checkstyle.Checker.fireErrors(Checker.java:367)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:276)
	... 31 more
```

**Comment by romani** [comment] 2015-11-24 11:58
Please provide used version and config. Is it stable exception ? Do you know what source file cause it?

**Comment by romani** [comment] 2015-12-04 01:53
@lennartj , I will close this issue in 1 month if we will not find a way to reproduce it.

**Comment by vjkoskela** [comment] 2015-12-22 19:46
I am having a similar issue with Checkstyle failing in a Maven project with an NPE.

```
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.isSuppressed(SuppressWarningsHolder.java:155)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWarningsFilter.accept(SuppressWarningsFilter.java:37)
	at com.puppycrawl.tools.checkstyle.api.FilterSet.accept(FilterSet.java:88)
	at com.puppycrawl.tools.checkstyle.Checker.fireErrors(Checker.java:367)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:276)
```

This does not happen on __mvn clean verify__ but does happen on subsequent __mvn verify__. I have isolated it to a RegexpSingleline comment suppression I have in the file. Here is the relevant code:

```java
package com.arpnetworking.metrics.generator.client;

import com.arpnetworking.metrics.Event;
import com.arpnetworking.metrics.Quantity;
import com.arpnetworking.metrics.Sink;
// CHECKSTYLE.OFF: RegexpSingleline - These are included here for generation.
import com.arpnetworking.metrics.ch.qos.logback.classic.LoggerContext;
import com.arpnetworking.metrics.ch.qos.logback.classic.spi.ILoggingEvent;
import com.arpnetworking.metrics.ch.qos.logback.core.FileAppender;
import com.arpnetworking.metrics.com.arpnetworking.logback.StenoEncoder;
// CHECKSTYLE.ON: RegexpSingleline
import com.arpnetworking.metrics.impl.TsdLogSink;
import com.google.common.base.Throwables;
import com.google.common.collect.Maps;
import com.google.common.io.Files;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;

import java.lang.reflect.Field;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GeneratorSink implements Sink {
    // Class contents
}
```java

We have multiple RegexpSingleline rules defined to catch different problems. In the example above, two of these for importing shaded artifacts should match (and be suppressed). Here are the relevant portions of our checkstyle.xml:

```xml
    <!-- Turn checkstyle ON and OFF for a specified code block -->
    <module name="SuppressionCommentFilter">
        <property name="offCommentFormat" value="CHECKSTYLE\.OFF\: ([\w\|]+)"/>
        <property name="onCommentFormat" value="CHECKSTYLE\.ON\: ([\w\|]+)"/>
        <property name="checkFormat" value="$1"/>
    </module>
```

And

```xml
    <module name="RegexpSingleline">
        <property name="format" value="^import com\.arpnetworking\.metrics\.com\.fasterxml\.jackson\..*"/>
        <property name="message" value="Do not import shaded dependencies from ArpNetworking."/>
    </module>
    <module name="RegexpSingleline">
        <property name="format" value="^import com\.arpnetworking\.metrics\.ch\.qos\.logback\..*"/>
        <property name="message" value="Do not import shaded dependencies from ArpNetworking."/>
    </module>
    <module name="RegexpSingleline">
        <property name="format" value="^import junit\.framework\..*"/>
        <property name="message" value="Use JUnit v4 instead."/>
    </module>
```

We are using checkstyle 6.13 and checkstyle maven plugin 2.17. Here is our plugin configuration:

```xml
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-checkstyle-plugin</artifactId>
          <version>${maven.checkstyle.plugin.version}</version>
          <executions>
            <execution>
              <id>default-check</id>
              <phase>verify</phase>
              <goals>
                <goal>check</goal>
              </goals>
              <configuration>
                <skip>${skipCheckstyle}</skip>
              </configuration>
            </execution>
            <execution>
              <id>default-checkstyle-aggregate</id>
              <phase>verify</phase>
              <goals>
                <goal>checkstyle-aggregate</goal>
              </goals>
              <configuration>
                <skip>${skipCheckstyle}</skip>
              </configuration>
            </execution>
          </executions>
          <configuration>
          <configuration>
            <consoleOutput>true</consoleOutput>
            <logViolationsToConsole>true</logViolationsToConsole>
            <failOnViolation>true</failOnViolation>
            <maxAllowedViolations>0</maxAllowedViolations>
            <configLocation>checkstyle.xml</configLocation>
            <includeTestSourceDirectory>true</includeTestSourceDirectory>
            <suppressionsFileExpression>suppressions_file</suppressionsFileExpression>
            <suppressionsLocation>checkstyle-suppressions.xml</suppressionsLocation>
            <propertyExpansion>
              header_file=${project.build.directory}/al2
            </propertyExpansion>
            <linkXRef>false</linkXRef>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>com.puppycrawl.tools</groupId>
              <artifactId>checkstyle</artifactId>
              <version>${checkstyle.version}</version>
            </dependency>
            <dependency>
              <groupId>com.arpnetworking.build</groupId>
              <artifactId>build-resources</artifactId>
              <version>${build-resources.version}</version>
            </dependency>
          </dependencies>
        </plugin>
```

It looks like ENTRIES has not been initialized for this thread. 

https://github.com/checkstyle/checkstyle/blob/checkstyle-6.13/src/main/java/com/puppycrawl/tools/checkstyle/checks/SuppressWarningsHolder.java#L155

But you probably already knew that ;) -- any insight into what the problem is and how to work around it would be greatly appreciated.

**Comment by vjkoskela** [comment] 2015-12-22 20:06
This may be related to #2218

**Comment by MEZk** [comment] 2016-01-15 18:20
@vjkoskela 

```SuppressionCommentFilter``` does not invoke any of ```SuppressWarningsHolder's``` methods. The only place where method ```isSuppressed``` of ```SuppressWarningsHolder``` is invoked in our code is method ```accept``` in class SuppressWarningsFilter. Filter ```SuppressWarningsFilter``` uses annotations (@SuppressWarnings) to suppress audit events. So, the above example can not throw NPE. There is no @SuppressWarnings annotation. Sorry, but I could not reproduce the issue with UT.
It seams to me that @SuppressFBWarnings in [your code](https://github.com/ArpNetworking/metrics-generator/blob/ebcf791f62687a6a68764cd7e499ea4d48da22bf/src/main/java/com/arpnetworking/metrics/generator/client/GeneratorSink.java#L55) causes NPE in our code.

Would you be so kind to isolate the code with annotation and run ```mvn verify```.

**Comment by vjkoskela** [comment] 2016-01-15 19:14
@MEZk 

The code I am looking at for SuppressWarningsFilter is here:

https://github.com/checkstyle/checkstyle/blob/checkstyle-6.13/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressWarningsFilter.java

It makes a call on line 37 to SuppressWarningsHolder.isSuppressed. This code matches the stack trace that I provided for the NPE. The code looks a little different in master, although the call to isSuppressed is still there. 

Can you elaborate on why this call chain is not possible?

**Comment by MEZk** [comment] 2016-01-15 20:32
@vjkoskela

You do not use SuppressWarningsFilter in the configuration which was provided:

```xml
    <module name="SuppressionCommentFilter">
        <property name="offCommentFormat" value="CHECKSTYLE\.OFF\: ([\w\|]+)"/>
        <property name="onCommentFormat" value="CHECKSTYLE\.ON\: ([\w\|]+)"/>
        <property name="checkFormat" value="$1"/>
    </module>
```

You use only SuppressionCommentFilter which does not make a call to SuppressWarningsHolder.isSuppressed. That is why I don't think that your example causes NPE. 
You use SuppressWarningsFilter somewhere to suppress annotations and @SuppressFBWarnings in GeneratorSink.java may lead to NPE. Please, provide proper example and/or full filters configuration.

Now we have the following: GeneratorSink.java is the class from your source code which brings about NPE in SuppressWarningsHolder.isSuppressed. As I read from https://github.com/ArpNetworking/metrics-generator/issues/2 , exclusion of  GeneratorSink.java is a workaround. So, problematic input is located somewhere in GeneratorSink.java, but not in the part of code which has already been provided.

**Comment by romani** [comment] 2016-01-16 14:38
looks like collection is not initialized 
`private static final ThreadLocal<List<Entry>> ENTRIES = new ThreadLocal<>();`

but in code it has to be initialized each time we touch file
```
    public void beginTree(DetailAST rootAST) {
        ENTRIES.set(new LinkedList<Entry>());
    }
```

looks like we can not reproduce it by our CLI , and it might be related to multi-threading mode.
As note, maven plugin and Eclipse use cache by default  - https://maven.apache.org/plugins/maven-checkstyle-plugin/checkstyle-mojo.html#cacheFile

@lennartj , can you share exact command that you execute to generate report ? (I am interesting in MT mode and cache usage). Can you give us pom config and checkstyle config ?

**Comment by romani** [comment] 2016-01-16 14:51
@MEZk ,

@vjkoskela , already provided you steps to reproduce the problem. Follow his instructions:
```
git clone https://github.com/ArpNetworking/metrics-generator.git
cd metrics-generator/
"Change pom.xml file to remove exclude "
mvn verify
mvn verify

....
[INFO] --- maven-checkstyle-plugin:2.17:check (default-check) @ generator ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.680 s
[INFO] Finished at: 2016-01-16T06:46:43-08:00
[INFO] Final Memory: 40M/356M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default-check) on project generator: Failed during checkstyle configuration: Exception was thrown while processing /home/rivanov/Temp/metrics-generator/src/main/java/com/arpnetworking/metrics/generator/client/GeneratorSink.java: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

beware that this project requires Maven 3.3.3, so for me I did:
```
echo $M2_HOME 
sudo mv ~/Downloads/apache-maven-3.3.9/ /opt/
M2_HOME=/opt/apache-maven-3.3.9/
PATH=$M2_HOME/bin/:$PATH
mvn -version
```

**Comment by testn** [comment] 2016-01-25 16:33
I noticed the same thing... If the build is run without `clean` firstb, it will produce the above exception.

**Comment by vjkoskela** [comment] 2016-01-25 17:40
Regarding that project on ArpNetworking and Maven 3.3.3 you can alternatively invoke the included maven wrapper (./mvnw or ./mvnw.bat) to automatically download and run the required version of Maven (it's cached to ~/.m2/wrapper).

**Comment by romani** [comment] 2016-01-27 00:17
issue already assigned , @MEZk  will give us steps to reproduce by CLI and all other details as he start fixing it.

**Comment by hohwille** [comment] 2016-02-10 22:00
I am facing the same issue in eclipse:
Eclipse Checkstyle Plugin 6.14.0.201601142217

**Comment by hohwille** [comment] 2016-02-10 22:01
However, not exactly the same line number:

```
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.isSuppressed(SuppressWarningsHolder.java:155)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWarningsFilter.accept(SuppressWarningsFilter.java:37)
	at com.puppycrawl.tools.checkstyle.api.FilterSet.accept(FilterSet.java:88)
	at com.puppycrawl.tools.checkstyle.Checker.fireErrors(Checker.java:367)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:276)
	... 15 more
```

**Comment by vjkoskela** [comment] 2016-03-16 21:03
Is the change in #3038 expected to address this issue in addition to #2218?

**Comment by MEZk** [comment] 2016-03-19 20:37
I'm able to reproduce the issue with the following sequence of actions:

1) git clone https://github.com/ArpNetworking/metrics-generator.git
2) cd metrics-generator/
3) Remove excludes for checkstyle-maven-plugin from pom.xml.
4) mvn -e verify && mvn -e verify

Stack trace:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default-check) on project generator: Failed during checkstyle configuration: Exception was thrown while processing /media/andreiselkin/TOURO/IDEA_Projects/metrics-generator/src/main/java/com/arpnetworking/metrics/generator/client/GeneratorSink.java: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default-check) on project generator: Failed during checkstyle configuration
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed during checkstyle configuration
	at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:543)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /media/andreiselkin/TOURO/IDEA_Projects/metrics-generator/src/main/java/com/arpnetworking/metrics/generator/client/GeneratorSink.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
	at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:538)
	... 22 more
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.SuppressWarningsHolder.isSuppressed(SuppressWarningsHolder.java:155)
	at com.puppycrawl.tools.checkstyle.filters.SuppressWarningsFilter.accept(SuppressWarningsFilter.java:37)
	at com.puppycrawl.tools.checkstyle.api.FilterSet.accept(FilterSet.java:88)
	at com.puppycrawl.tools.checkstyle.Checker.fireErrors(Checker.java:367)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:276)
	... 24 more
```

Further investigation:

1) I installed Checkstyle's latest 6.17-SNAPSHOT version in my local m2 repo (```mvn clean install```);
2) I added the following changes to pom.xml of 'metrics-generator':
 2.1) Added the link to my local repository:
```xml
<repositories>
  <repository>
    <id>project.local</id>
    <name>project</name>
    <url>file:/home/andreiselkin/.m2/repository/com/puppycrawl/tools/checkstyle</url>
  </repository>
</repositories>
```
  2.2) Configure maven-checkstyle-plugin to use SNAPSHOT version of Checkstyle:
  ```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-checkstyle-plugin</artifactId>
  <dependencies>
    <dependency>
      <groupId>com.puppycrawl.tools</groupId>
      <artifactId>checkstyle</artifactId>
      <version>6.17-SNAPSHOT</version>
    </dependency>
  </dependencies>
</plugin>
  ```

3) I also added some debug output into 'isSuppressed' method:
```java
System.out.println("FileName: " + event.getFileName());
System.out.println("Line: " + event.getLine());
System.out.println("SourceName: " + event.getSourceName());
System.out.println("Column: " + event.getColumn());
```
4) Once again I ran maven-checkstyle-plugin with the following commmand: ```mvn -e verify && mvn -e verify```;

5) After the first run (```mvn -e verify```) there was the following output during analizing of GeneratorSink.java:

```
[INFO] --- maven-checkstyle-plugin:2.17:check (default-check) @ generator ---
FileName: /metrics-generator/src/main/java/com/arpnetworking/metrics/generator/client/GeneratorSink.java
Line: 22
SourceName: com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineCheck
Column: 0
FileName: /metrics-generator/src/main/java/com/arpnetworking/metrics/generator/client/GeneratorSink.java
Line: 23
SourceName: com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineCheck
Column: 0
FileName: /metrics-generator/src/main/java/com/arpnetworking/metrics/generator/client/GeneratorSink.java
Line: 24
SourceName: com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineCheck
Column: 0
```

6) After the second run there was no debug output, because the first ran had been successfully cached. 
7) There was no NPE after the second run.
8) It looks like #3038 also fixes NPE in this issue.

**Comment by romani** [comment] 2016-03-19 21:23
@MEZk ,
thank you very much for detailed report.
This project use checkstyle 6.13 - https://github.com/ArpNetworking/arpnetworking-parent-pom/blob/master/pom.xml#L79 , please test that project is still failing on 6.16.1 and works fine at 6.17-SNAPSHOT.

@vjkoskela , 
All snapshots are deployed to:
https://oss.sonatype.org/content/repositories/snapshots/com/puppycrawl/tools/checkstyle/
can you verify that you do not have problems on latest binaries ?

**Comment by MEZk** [comment] 2016-03-20 09:07
@romani 

| Checkstyle version        | Maven execution result           | Comment  |
| ------------- |:-------------:| -----:|
| 6.13     | NPE |  |
| 6.14      | NPE      |    |
| 6.14.1 | NPE      |     |
| 6.15 | NPE      |     |
| 6.16 | OK      |    fixed |
| 6.16.1 | OK     |     |
| 6.17-SNAPSHOT | OK     |     |

Commit that fixed the issue https://github.com/MEZk/checkstyle/commit/d46c2cf0e9df06bb5f424dbd7645574f082f7609 .

Related issue is #569 .

**Comment by romani** [comment] 2016-03-20 12:15
Issue is closed.

**Closed by romani** 2016-03-20 12:15 UTC
Labels: approved

**Comment by vjkoskela** [comment] 2016-03-21 17:25
Confirmed. Checkstyle version 6.16.1 addresses the problem with GeneratorSink. Thank you!
