### ISSUE TITLE
new CLI option: exclude directories

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3287] opened 2016-06-18 20:38 UTC
Split from https://github.com/checkstyle/checkstyle/issues/2866#issuecomment-226901806

Add a new option to the CLI to exclude one or more directories from being scanned for files by CheckStyle.
Many common directories in a project's base (bin, .git, .metadata, etc) can be picked up in a directory scan and almost never contain anything relevant to CheckStyle. Though we usually don't use any files from these scans, just scanning them and holding these files in memory can slow CheckStyle down.

Examples of new exclude option:
**Full Path Exclude**: `java -jar checkstyle-6.19-all.jar -c config.xml -e /excludeDirectory inputs...`
**Relative Path Exclude**: `/some/project$ java -jar checkstyle-6.19-all.jar -c config.xml -e path/excludeDirectory inputs...` (Exlcudes the absolute path `/some/project/path/excludeDirectory`)
**Regular Expression Exclude**: `java -jar checkstyle-6.19-all.jar -c config.xml -x "[\\/]excludeDirectory[\\/]" inputs...`

`-x` and `-e` can be used multiple times in 1 command.

more examples:
Without expression:
`java -jar checkstyle-6.19-all.jar -c config.xml D:\project -e D:\project\.metadata -e D:\project\.git -e D:\project\bin`
With expression:
`java -jar checkstyle-6.19-all.jar -c config.xml D:\project -x "[\\\/](.metadata|.git|bin)[\\\/]`"

**Comment by romani** [comment] 2016-06-18 21:33
why list of directories are stict values ?
Why not like excludes of maven plugin - https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties#L12 ?

> bin, .git, .metadata, etc

please show show command will looks like.

**Comment by rnveach** [comment] 2016-06-18 21:56
> why list of directories are strict values ?

I feel expressions are too inexact and can lead to false matches if not careful about directory structure the project is stored in. We are already giving a path for the list of files, so it seemed natural to me that excludes do the same.
I can change my current PR to an expression.

> please show show command will looks like

Without expression:
`java -jar checkstyle-6.19-all.jar -c config.xml D:\project -e D:\project\.metadata -e D:\project\.git -e D:\project\bin`
With expression:
`java -jar checkstyle-6.19-all.jar -c config.xml D:\project -e "[\\\/](.metadata|.git|bin)[\\\/]`"

**Comment by romani** [comment] 2016-06-19 16:46
ok , make sense, but this is not obvious (multiple argument usage) we need to describe this in documentation.

but what about relative paths ?

`java -jar checkstyle-6.19-all.jar -c config.xml . `
`java -jar checkstyle-6.19-all.jar -c config.xml my/some/subfolder `

**Comment by romani** [comment] 2016-06-21 21:40
@rnveach , is smth unclear in my question ? please let me know

**Comment by rnveach** [comment] 2016-06-21 22:43
No, you are clear. I will rework the pr to meet your concerns when I get the time.

Relative will be based on cwd, correct?

**Comment by romani** [comment] 2016-06-22 00:56
Please lets focus on issue description and expected behavior first, to avoid wasting your time on implementation that is not approved.

What is "cwd" ?

**Comment by rnveach** [comment] 2016-06-22 02:39
"Current Working Directory". The user can pass multiple directories for files to be picked up, so a relative directory exclude can't use that input as its base.
`D:\Project> java -jar checkstyle-6.19-all.jar -c config.xml -e my/some/subfolder filesPath`
So the full path for the exclude should be "D:\Project\my\some\subfolder".

**Comment by romani** [comment] 2016-06-22 04:47
yes, please update issue description and examples (absolute and relative paths) with all details and let me do final review .

**Comment by rnveach** [comment] 2016-06-22 11:58
@romani Done.

**Comment by romani** [comment] 2016-06-23 01:08
please provide names for full-names of arguments in issue description.

**Comment by romani** [comment] 2016-07-27 02:55
fix is merged

**Closed by romani** 2016-07-27 02:55 UTC
Labels: approved, new feature
