### ISSUE TITLE
Parse exception for RAW string template (Java 21+)

### ISSUE THREAD

**Issue by diversit** [checkstyle/checkstyle#14793] opened 2024-04-15 09:12 UTC
In Java 21/22, when using a String template with a raw String, checkstyle fails with a parsing error:

Maven checkstyle output:
```
An error has occurred in Checkstyle report generation.: Failed during checkstyle configuration: 
Exception was thrown while processing /path/to/a/java/Class.java: IllegalStateException occurred 
while parsing file /path/to/a/java/Class.java. 90:24: mismatched input '(' expecting ';': InputMismatchException
```

I have verified this issue by adding
```java
   String result11 = STR."""
                Hello World
                """;
```
to the Checkstyle's `com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java` test case.

See [updated test case InputStringTemplateBasic.java](https://github.com/diversit/checkstyle/blob/152acb199ee73ed164964a05c1e38e65d6ea0558/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java#L56)

The test fails with
`
Java21AstRegressionTest.testBasicStringTemplate:42->AbstractTreeTestSupport.verifyAst:77->AbstractTreeTestSupport.verifyAst:57 » Checkstyle IllegalStateException occurred while parsing file /Users/dhl/Project/others/checkstyle/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/grammar/java21/InputStringTemplateBasic.java
`

Using a raw string with a String Template is valid syntax. See [Java 21 String Templates: Multiline String Templates](https://docs.oracle.com/en/java/javase/21/language/string-templates.html#GUID-771D8AC4-EAE6-456D-A476-306717F75C0C) and [Java 22 String Templates: Multiline String Template](https://docs.oracle.com/en/java/javase/22/language/string-templates.html#GUID-771D8AC4-EAE6-456D-A476-306717F75C0C)

Also using `StringTemplate.RAW`, which is an alternative notation of `STR.""".."""` fails with a parse error.
[Java Api Docs StringTemplate](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/lang/StringTemplate.html)
```java
import static java.lang.StringTemplate.RAW;

    // raw string
    String result11 = RAW."""
            Hello \{name}
            """;
```

Tested with:

Java: 21 and 22
Checkstyle: 10.14 and 10.15

**Comment by mahfouz72** [comment] 2024-04-15 11:07
Checkstyle is currently unable to parse this syntax. there is an open issue for this https://github.com/checkstyle/checkstyle/issues/14195#issue-2057975642 
complete support for all java 21 new syntax (parsing and checkstyle checks) will be done by the summer.

**Comment by romani** [comment] 2024-04-17 04:03
>Also using StringTemplate.RAW, which is an alternative notation of STR.""".."""

Do we allow not STR ?

**Comment by nrmancuso** [comment] 2024-04-17 11:35
> > Also using StringTemplate.RAW, which is an alternative notation of STR.""".."""
> 
> @nrmancuso , Do we allow not STR ?

This example is not valid syntax. Text blocks must begin with three quotes and a newline character.

I am removing the approved label since this is a duplicate of https://github.com/checkstyle/checkstyle/issues/14195

It is unlikely that we will ever support this syntax, since Java themselves have dropped it: https://github.com/checkstyle/checkstyle/issues/14805

I suggest that we close this issue and continue any discussion at https://github.com/checkstyle/checkstyle/issues/14195

**Closed** 2024-04-17 23:44 UTC
Labels: antlr
