### ISSUE TITLE
Errors parsing new Java-14 switch statements/expressions

### ISSUE THREAD

**Issue by eant60** [checkstyle/checkstyle#7940] opened 2020-03-22 12:04 UTC
[NI.txt](https://github.com/checkstyle/checkstyle/files/4365163/NI.txt)
Name of affected check:

Not Applicable -- issue is with parsing Java-14.

------------------------
Example code builds under Java-14
------------------------

[redacted]$ cat __javac.sh
#!/bin/bash
###########

JAVAC="${DJAVA_HOME}/bin/javac -Xlint -Xmaxerrs 1000"

echo
echo ===========================
echo doing javac: $(${JAVAC} --version)
echo ===========================
find . -type f -name '*java' | xargs ${JAVAC} 

[redacted]$ ls -1
SwitchTest.java
__checkstyle.sh
__javac.sh

[redacted]$ ./__javac.sh

===========================
doing javac: javac 14
===========================

[redacted]$ ls -1
SwitchTest.class
SwitchTest.java
__checkstyle.sh
__javac.sh

------------------------
Here is code -- containing examples of new Java-14 switch statements
------------------------

[redacted]$ cat SwitchTest.java
public final class SwitchTest
{
   private SwitchTest()
   {
      // Not allowed
   }

   static private void howManyS(int k)
   {
      switch (k)
      {
         case 1  -> System.out.println("one");
         case 2  -> System.out.println("two");
         default -> System.out.println("many");
      }
   }

   static void howManyE(int k)
   {
      System.out.println(
         switch (k)
         {
            case  1 -> "one";
            case  2 -> "two";
            default -> "many";
         }
      );
   }

   static void howManyY(int k)
   {
      System.out.println(
         switch (k)
         {
            case  1 -> "one";
            case  2 -> "two";
            default -> 
               {
                  System.out.println("yield case");
                  yield "many";
               }
         }
      );
   }

   public static void main(String[] args)
   {
      howManyS(1);
      howManyS(2);
      howManyS(3);

      howManyE(1);
      howManyE(2);
      howManyE(3);

      howManyY(1);
      howManyY(2);
      howManyY(3);
   }
}

------------------------
Here is checkstyle 8.30 output, using the default google configuration file
------------------------

[redacted]$ cat __checkstyle.sh 
#!/bin/bash
###########

XCK="${DJAVACMD} -classpath ${CHECKSTYLE_JAR} com.puppycrawl.tools.checkstyle.Main -c /google_checks.xml"

echo
echo ===========================
echo doing checkstyle: $(${XCK} --version)
echo ===========================
find . -type f -name '*java' | xargs ${XCK} "$@"
echo

[redacted]$ ./__checkstyle.sh 

===========================
doing checkstyle: Checkstyle version: 8.30
===========================
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing ./SwitchTest.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:304)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:400)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:324)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:187)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:124)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException occurred while parsing file /home/[redacted]/./SwitchTest.java.
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:105)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:159)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)
	... 5 more
Caused by: java.lang.IllegalStateException: /home/[redacted]/./SwitchTest.java:12:15: unexpected token: 1
	at com.puppycrawl.tools.checkstyle.JavaParser$1.reportError(JavaParser.java:93)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:411)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:99)
	... 9 more
Caused by: /home/[redacted]/./SwitchTest.java:12:15: unexpected token: 1
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.expression(GeneratedJavaRecognizer.java:4923)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.aCase(GeneratedJavaRecognizer.java:6205)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.casesGroup(GeneratedJavaRecognizer.java:5760)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.traditionalStatement(GeneratedJavaRecognizer.java:5463)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.statement(GeneratedJavaRecognizer.java:4397)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compoundStatement(GeneratedJavaRecognizer.java:4063)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3453)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2643)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:634)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:556)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)
	... 11 more
Checkstyle ends with 1 errors.

**Comment by srividyavaishnavi** [comment] 2020-03-31 06:48
i am on it

**Comment by strkkk** [comment] 2020-03-31 07:30
Closed as duplicate of https://github.com/checkstyle/checkstyle/issues/6615

**Closed by strkkk** 2020-03-31 07:30 UTC
