### ISSUE TITLE
ImportOrder: example of Intellij Idea default import order is not working

### ISSUE THREAD

**Issue by jqno** [checkstyle/checkstyle#5510] opened 2018-02-05 08:35 UTC
`/var/tmp $ cat YOUR_FILE.java`:

```
import org.junit.runners.Parameterized.Parameters;

import java.util.Arrays;
```

`/var/tmp $ cat config.xml`:

```
<module name="ImportOrder">
    <property name="groups" value="*,javax,java"/>
    <property name="ordered" value="true"/>
    <property name="separated" value="false"/>
    <property name="option" value="bottom"/>
    <property name="sortStaticImportsAlphabetically" value="true"/>
</module>
```

`/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java`:

```
Starting audit...
[ERROR] /Users/jqno/w/equalsverifier/equalsverifier/src/test/java/nl/jqno/equalsverifier/coverage/CoverageWithInheritanceTest.java:25: Extra separation in import group before 'java.util.Arrays' [ImportOrder]
Audit done.
Checkstyle ends with 1 errors.
```

---------------

Describe what you expect in detail.

I'm attempting to upgrade from version 6.19 to version 8.8. The above used to work fine, but now I get a couple hundred errors like this. This behavior was introduced between 8.2 and 8.3.

If I set `separated` to false, I get less errors, but they still occur when `javax.` imports are followed by `java.` imports with no white line between them. I tried changing the `groups` to something like `*,javax?` (to make `javax.` and `java.` a single group) but that didn't help either.

Note that this configuration is identical to what's written on [this documentation page](http://checkstyle.sourceforge.net/config_imports.html#ImportOrder) where it says `Note: "separated" option is disabled because IDEA default has blank line between "java" and static imports, and no blank line between "javax" and "java"` which is exactly what I'm trying to achieve.

If you tell me what I need to change in my configuration, I'm willing to update the docs and submit a PR for that.

You can reproduce the issue on the EqualsVerifier repository, which you can find [here](https://github.com/jqno/equalsverifier). Check out the branch `upgrade-checkstyle` and run on Java 9 with `mvn checkstyle:checkstyle`.
If you change the Checkstyle dependency to 8.2 you'll see that it passes; if you leave it at 8.8 (or 8.3) you'll see that it fails. Checkstyle configuration file is in the `project/` folder.

**Comment by RohanNagar** [comment] 2018-02-05 18:29
+1 on this. It is breaking behavior, and I would at least like to know how to keep the same behavior as prior to v8.3. I don't care about separation rules on my imports, I just want to enforce alphabetical.

**Comment by RohanNagar** [comment] 2018-02-12 18:58
Anyone?

**Comment by akhaku** [comment] 2018-03-10 00:29
Happening for me too, also traced it to being introduced in 8.3. Test case for me:
```
import static com.mypackage.MyClass.SOME_STATIC_THING;

import com.mypackage.SomeClass;
```

```
<module name="Checker">
  <module name="TreeWalker">
    <!-- Import rules -->
    <module name="ImportOrder">
      <property name="separated" value="false"/> <!-- or true, doesn't seem to make a difference -->
      <property name="groups" value="*"/>
      <property name="option" value="above"/>
      <property name="sortStaticImportsAlphabetically" value="true"/>
    </module>
  </module>
</module>
```

**Comment by RohanNagar** [comment] 2018-03-10 00:40
Just FYI, I also mentioned this on another issue here:

For those of you wanting to get back to similar behavior prior to v8.3, you can use `CustomImportOrder`.

Replace

```xml
<module name="ImportOrder">
  ...
</module>
```

with

```xml
<module name="CustomImportOrder">
  <property name="sortImportsInGroupAlphabetically" value="true"/>
  <property name="separateLineBetweenGroups" value="true"/>
  <property name="customImportOrderRules" value="THIRD_PARTY_PACKAGE###STATIC"/>
</module>
```

and see additional options for configuration [here](http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.html).

**Comment by jqno** [comment] 2018-03-10 16:37
It's nice to know there's a workaround, unfortunately it doesn't work in my case. I find the documentation for CustomImportOrder to be quite confusing, too, so I haven't been able to tweak it the way I want. Maybe I'll try again later.

I just want Checkstyle to check that the imports are in the order that IntelliJ puts them in by default. (In other words, to enforce that I didn't forget to Order Imports.) This seems like a thing many people would want?

**Comment by jqno** [comment] 2018-09-08 12:47
Is there any news about this?

I'm still unable to configure Checkstyle to accept the default ordering from IntelliJ IDEA. The configuration in the [Checkstyle documentation](http://checkstyle.sourceforge.net/config_imports.html#ImportOrder) doesn't work. Therefore I'm still unable to upgrade past Checkstyle 8.2. (I just tried 8.12 but no dice.)

**Comment by romani** [comment] 2018-09-08 23:18
@jqno , please report issue as REQUIRED without any cut of corners , incomplete configuration ... .
ones you follow rules (help us) , it is much easier to help.

**Comment by romani** [comment] 2018-09-08 23:44
looks like IDEAs default is
![image](https://user-images.githubusercontent.com/812984/45259544-80a2ad80-b384-11e8-8e72-565185316a32.png)

where java and javax groups are not separated between each other by empty line.

in checkstyle's ImportOrder, there is no way to define that some groups are separated and some are not.
This is limitation of this Check, previously there was bug in ImportOrder Check that made it possible.
You might need to use http://checkstyle.sourceforge.net/config_imports.html#CustomImportOrder .

you should also be aware of https://github.com/checkstyle/checkstyle/issues/5724 , so it make special processing of static groups, but default value match IDEA's format(all in one).

```
$ cat Test.java 
import org.junit.runners.Parameterized.Parameters;

import java.util.Arrays;

$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <module name="TreeWalker">
        <property name="tabWidth" value="4"/>
        <module name="ImportOrder">
            <property name="groups" value="*,javax,java"/>
            <property name="ordered" value="true"/>
            <property name="separated" value="true"/> <!!ATTENTION here>
            <property name="option" value="bottom"/>
            <property name="sortStaticImportsAlphabetically" value="true"/>
        </module>
    </module>
</module>

$ java -Duser.language=en -Duser.country=US -jar checkstyle-8.12-all.jar -c config.xml Test.java
Starting audit...
Audit done.
```

**Comment by romani** [comment] 2018-09-09 00:30
but this will not match IDEA format:
```
$ cat Test.java 
import org.junit.runners.Parameterized.Parameters;

import javax.util.Arrays;
import java.util.Arrays;

$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <module name="TreeWalker">
        <property name="tabWidth" value="4"/>
        <module name="ImportOrder">
            <property name="groups" value="*,javax,java"/>
            <property name="ordered" value="true"/>
            <property name="separated" value="true"/>
            <property name="option" value="bottom"/>
            <property name="sortStaticImportsAlphabetically" value="true"/>
        </module>
    </module>
</module>

$ java -Duser.language=en -Duser.country=US -jar checkstyle-8.12-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /var/tmp/Test.java:4: 'java.util.Arrays' should be separated from previous imports. [ImportOrder]
Audit done.
Checkstyle ends with 1 errors.

```

so you might make it work but you will need  to use suppressions by message http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter with `message="'java.* should be separated from previous imports"`

**Comment by romani** [comment] 2018-09-09 00:40
this config should in some sort support IDEA's default:
```
$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <module name="TreeWalker">
        <property name="tabWidth" value="4"/>
        <module name="ImportOrder">
            <property name="groups" value="*,javax,java"/>
            <property name="ordered" value="true"/>
            <property name="separated" value="true"/>
            <property name="option" value="bottom"/>
            <property name="sortStaticImportsAlphabetically" value="true"/>
        </module>
    </module>
    <module name="SuppressionFilter">
      <property name="file" value="suppressions.xml"/>
      <property name="optional" value="false"/>
    </module>
</module>

$ cat Test.java 
import org.junit.runners.Parameterized.Parameters;

import javax.util.Arrays;
import java.util.Arrays;

$ java -Duser.language=en -Duser.country=US -jar checkstyle-8.12-all.jar -c config.xml Test.java
Starting audit...
Audit done.

```

**Comment by romani** [comment] 2018-09-09 00:42
@jqno , please confirm that this ugly workaround works for your code, so we need to update config in our documentation to not mislead users.

**Comment by jqno** [comment] 2018-09-09 07:45
@romani Thanks for looking into this for me.
I can confirm that your workaround works for my project.
I noticed that with this configuration, checkstyle doesn't care if there's a separation between `java.*` and `javax.*` groups or not, but that's not a big deal for me. Otherwise, it works very well.
Thank you!

**Comment by jqno** [comment] 2018-10-09 07:47
One of the users of my project pointed out that the suppression only works on English locales (his locale is French). He suggests to change the suppression as follows:

```
<suppressions>
    <suppress checks="ImportOrder" message="'java.*"/>
</suppressions>
```

instead of

```
<suppressions>
    <suppress checks="ImportOrder" message="'java.* should be separated from previous imports"/>
</suppressions>
```

(In French, the message would be `'java.io.Closeable' devrait être séparé des imports précédents.`)

**Comment by romani** [comment] 2018-10-17 01:48
@jqno ,

Here are links to messages templates and their translations.

https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fimports+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+"import.ordering"
https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fimports+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+"import.separation"
https://github.com/search?q=path%3Asrc%2Fmain%2Fresources%2Fcom%2Fpuppycrawl%2Ftools%2Fcheckstyle%2Fchecks%2Fimports+filename%3Amessages*.properties+repo%3Acheckstyle%2Fcheckstyle+"import.groups.separated.internally"

Message regexp should be `^'java\.\*'.*`. As required message type is the only who have group at the beginning.

Please recheck this on your project, if it works please be welcome to send PR with documentation update.
We appreciate your help.

Fyi: if you project is opensource and you enforce checkstyle by build command, and you use bunch of Checks, please let me know , we can use your project in our CI, to run on your code each commit. You will never have regression in future :).

**Comment by jqno** [comment] 2018-10-23 07:50
@romani , thanks for the update.

The regex you provided doesn't work, but `^'java\..*'.*` does, so I'm now using that. I've tested it on my project with English, French an Chinese locales.

I've updated the documentation and provided a pull request: #6163 .

My project is indeed an open source project, I would very much like it if you use it in your CI. You can find it at https://github.com/jqno/equalsverifier , which is also used in Checkstyle's unit tests :) . It's a standard maven project, so you can run the checks simply with `mvn checkstyle:checkstyle`.

**Comment by rnveach** [comment] 2018-10-26 00:38
fix was merged

**Closed by rnveach** 2018-10-26 00:38 UTC
Labels: approved, miscellaneous
