### ISSUE TITLE
NPE on type parameter annotations for this

### ISSUE THREAD

**Issue by maggu2810** [checkstyle/checkstyle#3732] opened 2017-01-16 16:53 UTC
* `/var/tmp $ javac Demo.java`

```text
```
(compiled without error)

* `/var/tmp $ cat Demo.java`

```java
package tmp.demo.checkstyle;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;

public class Demo {

    @Retention(RetentionPolicy.RUNTIME)
    @Target({ ElementType.TYPE_USE, ElementType.TYPE_PARAMETER })
    public @interface UnknownInitialization {
        Class<?> value() default Object.class;
    }

    /**
     * Function to demonstrate a Checkstyle bug.
     *
     * @param buffer dummy argument
     */
    public void foo(@UnknownInitialization(Demo.class) Demo this,final ByteBuffer buffer) {
        buffer.putInt(1);
    }

}
```

* `/var/tmp $ cat config.xml`

```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <!-- Checks for Javadoc comments.                     -->
        <!-- See http://checkstyle.sf.net/config_javadoc.html -->
        <module name="JavadocMethod"/>
        <module name="JavadocType"/>
        <module name="JavadocVariable"/>
        <module name="JavadocStyle"/>
    </module>
</module>
```

* `/var/tmp $ java -jar ~/Downloads/checkstyle-7.4-all.jar -c config.xml Demo.java`

```text
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Demo.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:293)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:211)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:425)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:359)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:174)
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck.removeMatchingParam(JavadocMethodCheck.java:824)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck.checkParamTags(JavadocMethodCheck.java:756)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck.checkComment(JavadocMethodCheck.java:499)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck.processAST(JavadocMethodCheck.java:357)
	at com.puppycrawl.tools.checkstyle.checks.AbstractTypeAwareCheck.visitToken(AbstractTypeAwareCheck.java:154)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:361)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:498)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:303)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:182)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:314)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:284)
	... 4 more
Checkstyle ends with 1 errors.
```

---------------

I would expect that a type parameter annotation for `this` works does not raise a NPE in the checker framework.
Such annotations are used e.g. if you try to use the Checker Framework stuff (https://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#initialization-checker).

**Comment by maggu2810** [comment] 2017-01-16 16:55
Without an understanding about your source code, this is at least a workaround for the NPE: https://github.com/maggu2810/checkstyle/commit/e91e37a6ccebae031abdd7cea43cc85565c496de

**Comment by rnveach** [comment] 2017-01-16 17:34
The issue and the fix look valid to me.
The issue is with Java 8s 'receiver parameters'. They don't have a variable name, but the `this` literal. JavadocMethodCheck is trying to find only variable name parameters.

**Comment by maggu2810** [comment] 2017-01-16 19:44
Thanks @rnveach 
Will create the PR after the approval label has been added.

**Comment by maggu2810** [comment] 2017-01-17 08:41
I found https://github.com/checkstyle/checkstyle/issues/3239 and it seems to be solved. Is this a regression or what is different here?

**Comment by rnveach** [comment] 2017-01-17 12:58
@maggu2810 That was just adding the tokens to our antlr so we could identify and understand the java code syntax.

**Comment by romani** [comment] 2017-01-17 20:09
Issue is approved.
All old javadoc Checks do not pass our regression testing, so quality is less than for other Checks.
Old javadoc checks unfortunately are error prone and fragile.
Please be welcome with PR.

**Comment by romani** [comment] 2017-01-27 14:06
Fix is merged

**Closed by romani** 2017-01-27 14:06 UTC
Labels: approved, bug
