### ISSUE TITLE
when enum name equals to class name import enum will cause unsed import bug

### ISSUE THREAD

**Issue by dnlixiaoxin** [checkstyle/checkstyle#12529] opened 2022-12-14 13:52 UTC
I have read check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash

/var/tmp $ cat config.xml
#[
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="UnusedImports"/>
  </module>
</module>

]

/var/tmp $ cat YOUR_FILE.java

enum MsgType

[
@AllArgsConstructor
public enum MsgType {
    TXT(1, "text"),
    MsgType(999, "MsgType"),
    ;

    @Getter
    private final int type;
    @Getter
    private final String desc;

    private static final Map<Integer, MsgType> TYPE_MAP = Maps.newHashMap();

    static {
        Arrays.stream(MsgType.values()).forEach(msgType -> TYPE_MAP.put(msgType.getType(), msgType));
    }

    public static MsgType getByType(int type) {
        return TYPE_MAP.get(type);
    }
}
]

class MsgType
[
import static com.monarch66.message.constant.MsgType.MsgType;

public class MsgType {

    public void inline() {
        int type = MsgType.getType();
    }

}

]

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
#[

src/main/java/com.monarch66.message/service/MsgType.java:[3,15] (imports) UnusedImports:  - com.monarch66.message.constant.MsgType.MsgType

]
```
when enum name equals class name will cause unused import but this. is correct

---

Still not clear ???
see example - https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

ATTENTION: FAILURE TO FOLLOW THE ABOVE TEMPLATE WILL RESULT IN THE ISSUE BEING CLOSED.

**Comment by nrmancuso** [comment] 2022-12-14 14:01
@dnlixiaoxin please strictly follow issue template so that we can help you.

**Comment by dnlixiaoxin** [comment] 2022-12-14 14:54
> @dnlixiaoxin please strictly follow issue template so that we can help you.

**Comment by dnlixiaoxin** [comment] 2022-12-14 14:54
@nrmancuso  I have followed the template

**Comment by pbludov** [comment] 2022-12-18 06:42
@dnlixiaoxin Could you please fix the code you provided? It fails to compile:
```bash
$ javac YOUR_FILE.java
YOUR_FILE.java:1: error: '{' expected
enum MsgType
            ^
YOUR_FILE.java:4: error: enum constant expected here
public enum MsgType {
^
YOUR_FILE.java:25: error: '{' expected
class MsgType
             ^
YOUR_FILE.java:27: error: <identifier> expected
import static com.monarch66.message.constant.MsgType.MsgType;
                                                            ^
YOUR_FILE.java:35: error: reached end of file while parsing
}
 ^
5 errors
```

See https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F for the details. Please pay attention to 
> Code has to be compilable, in other case behaviour could be strange.

**Comment by pbludov** [comment] 2022-12-18 07:20
According to the [specs](https://docs.oracle.com/javase/specs/jls/se17/html/jls-7.html#jls-7.5.3) such code should be non-compilable:

> If a single-static-import declaration imports a class or interface whose simple name is x, and the compilation unit also declares a top level class or interface ([§7.6](https://docs.oracle.com/javase/specs/jls/se17/html/jls-7.html#jls-7.6)) whose simple name is x, a compile-time error occurs.

**Comment by romani** [comment] 2022-12-18 16:01
We will close this ticket if no proper details by our issue format is provided until end of December

**Comment by dnlixiaoxin** [comment] 2022-12-19 08:57
@romani @pbludov Hello，
To fully show the problem, I created a temporary project that can run and reproduce the problem. You can use mvn checkstyle: check to run the project
project link: https://github.com/dnlixiaoxin/checkstyle-demo.git

**Comment by romani** [comment] 2022-12-19 22:53
we will be hard for us to support this
https://checkstyle.org/writingchecks.html#Limitations

we have knowledge only for one file during validation, we are not aware of types.

we probably can deduce this by assumptions:
if we reference to itself, and no method like this in file and we know that file is compile-able so we can presume it is name overlap  - skip.

But I think it will be too much change for logic to cover this small edge case, and it is not good pattern any way to name stuff in same way.

I would recommend you to disable violation on this by our filters 
one of them - https://checkstyle.org/config_filters.html#SuppressionSingleFilter
```
<module name="SuppressionSingleFilter">
  <property name="message" value="UnusedImports:  - com.monarch66.message.constant.MsgType.MsgType"/>
</module>
```

of no disagreements from other maintainers we can close issue as wont fix. We might change our mind if more cases like this popup and users will show us why this is good pattern in some cases.

**Comment by nrmancuso** [comment] 2022-12-21 14:35
>But I think it will be too much change for logic to cover this small edge case, and it is not good pattern any way to name stuff in same way.

Agreed, it is probably better to use suppression in this case.

**Comment by pbludov** [comment] 2022-12-25 08:07
> project link: https://github.com/dnlixiaoxin/checkstyle-demo.git

@dnlixiaoxin It looks like you found a bug in the Java compiler or the Java language specification.

Basically,
```java
public enum MsgTypeEnum {

    TXT(1, "text"),
    MsgType(999, "MsgType"),
    ;

    private final int type;
    private final String desc;

   MsgTypeEnum(int type, String desc) {
        this.type = type;
        this.desc = desc;
    }

    public int getType() {
        return type;
    }

    public String getDesc() {
        return desc;
    }
}
```

is same as
```java
public class MsgTypeClass {

    private final int type;
    private final String desc;

    MsgTypeClass(int type, String desc) {
        this.type = type;
        this.desc = desc;
    }

    public int getType() {
        return type;
    }

    public String getDesc() {
        return desc;
    }

    public static class TXT extends MsgTypeClass {
        public TXT() {
            super(1, "text");
        }
    }

    public static class MsgType extends MsgTypeClass {
        public MsgType() {
            super(999, "MsgType");
        }
    }
}
```

The first version (enum) compiles fine with your demo, but the second (class) fails to compile.

I agree with @romani that this is a very rare edge case. Enum constants usually named in UPPER case in Java, so such collision is uncommon.

**Comment by romani** [comment] 2022-12-26 15:51
> Enum constants usually named in UPPER case in Java, so such collision is uncommon.

unfortunately people use all possible.
Main point is better to NOT overlap by names, but if this happens and can not be changed, checkstyle is error prone due to limitations by design.

**Closed by romani** 2022-12-26 15:51 UTC
