### ISSUE TITLE
Improve Maven output

### ISSUE THREAD

**Issue by nkavian** [checkstyle/checkstyle#10775] opened 2021-09-03 20:37 UTC
**How it works Now:**

```bash
[INFO] --- maven-checkstyle-plugin:3.1.2:checkstyle (default-cli) @ project ---
[INFO] Starting audit...
... other checkstyle output ...
Audit done.
[INFO] 
```

**Desired output**
```bash
[INFO] --- maven-checkstyle-plugin:3.1.2:checkstyle (default-cli) @ project ---
[INFO] Starting audit...
... other non-indented checkstyle output is okay ...
[INFO] Audit done.
[INFO] 
```

**So that the output is aligned when there are no violations**
```bash
[INFO] --- maven-checkstyle-plugin:3.1.2:checkstyle (default-cli) @ project ---
[INFO] Starting audit...
[INFO] Audit done.
[INFO] 
```

**Similar to SpotBugs and PMD output**
```bash
[INFO] --- spotbugs-maven-plugin:4.3.0:spotbugs (spotbugs) @ project ---
[INFO] Fork Value is true
[INFO] Done SpotBugs Analysis....
[INFO] 
[INFO] --- maven-pmd-plugin:3.14.0:check (default-cli) @ project ---
[INFO] PMD version: 6.37.0
[INFO] 
```

**Comment by rnveach** [comment] 2021-09-03 20:41
> maven-checkstyle-plugin

This is most likely an issue for the maven plugin. We are not the maven plugin. We are only the main checkstyle library.

**Comment by nkavian** [comment] 2021-09-03 23:09
The `DefaultLogger` and the output strings are here in this repo but the output stream I suppose is to the plugin. I'll try to open the issue there, thanks.

**Comment by rnveach** [comment] 2021-09-04 01:09
The issue is our logger was made for our purposes, which is the output from our CLI program. If other people can use it as is, that's great for them, but I am not seeing any change in this situation that would benefit the maven plugin. We can't control how other people use our library, and in this instance if using out logger doesn't work, they would need to implement their own.
They are the ones using it.
https://github.com/apache/maven-checkstyle-plugin/blob/2f45933ff9ce22413dcededc5be9a8f48b9942df/src/main/java/org/apache/maven/plugins/checkstyle/AbstractCheckstyleReport.java#L642

I am closing this for now until.

**Closed by rnveach** 2021-09-04 01:09 UTC

**Comment by nkavian** [comment] 2021-09-04 01:11
https://issues.apache.org/jira/browse/MCHECKSTYLE-408
