### ISSUE TITLE
create validation of git status on Windows environments

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#11816] opened 2022-07-02 19:14 UTC
we did update for all/most Linux buillds at https://github.com/checkstyle/checkstyle/pull/11815

we need same for windows hosts: Appveyor and Cirrus 
so we need cmd implementation of such validation.

**Comment by rnveach** [comment] 2022-07-02 19:23
Since this is not being done on windows, this will most likely mean the following issue , https://github.com/checkstyle/checkstyle/issues/8884 , will have to be fixed for this issue to be completed as long as CI reproduces the issue.

**Comment by romani** [comment] 2022-07-02 21:47
I ok to disable such git status validation in some CIs until #8884. But we need cmd script.

**Comment by kalpadiptyaroy** [comment] 2023-09-03 16:18
I am on it.

**Comment by romani** [comment] 2023-09-03 18:08
Add execution of `validations.cmd git-diff` after https://github.com/checkstyle/checkstyle/blob/08814f209de43368cf9078a56e9175bf1f91f7a9/appveyor.yml#L75 and create a PR. We will suggest in PR how to trigger a gift. 
Most easy way to cause a diff is to change template  wording https://github.com/checkstyle/checkstyle/blob/08814f209de43368cf9078a56e9175bf1f91f7a9/src/xdocs/checks/annotation/annotationlocation.xml.template#L14  of some Check a bit, remove some word from it, it will update xdoc file automatically and it will be a diff as in your commit you will have only change in template.

**Comment by kalpadiptyaroy** [comment] 2023-09-03 18:51
> echo Top 300 lines of diff:\n
>       call git status
>       call git diff ^| head -n 300
>       goto :ERROR

Ok. Trying to implement this way. Will raise a PR soon.

**Comment by kalpadiptyaroy** [comment] 2023-09-03 18:52
> Add execution of `validations.cmd git-diff` after
> 
> https://github.com/checkstyle/checkstyle/blob/08814f209de43368cf9078a56e9175bf1f91f7a9/appveyor.yml#L75
> 
> and create a PR. We will suggest in PR how to trigger a gift.
> Most easy way to cause a diff is to change template wording
> https://github.com/checkstyle/checkstyle/blob/08814f209de43368cf9078a56e9175bf1f91f7a9/src/xdocs/checks/annotation/annotationlocation.xml.template#L14
> 
> of some Check a bit, remove some word from it, it will update xdoc file automatically and it will be a diff as in your commit you will have only change in template.

Ok. Trying to implement this way. Will raise a PR soon.

**Comment by nrmancuso** [comment] 2023-10-28 18:57
Closed via #13696

**Closed by nrmancuso** 2023-10-28 18:57 UTC
Labels: approved, CI

**Comment by romani** [comment] 2023-10-28 22:09
@kalpadiptyaroy, thanks a lot for your hard work on this not easy issue. All windows contributors should know that you are hero who makes their lives easier.

I look forward for continue working with you.

**Comment by kalpadiptyaroy** [comment] 2023-10-30 06:42
> @kalpadiptyaroy, thanks a lot for your hard work on this not easy issue. All windows contributors should know that you are hero who makes their lives easier.
> 
> I look forward for continue working with you.

Thanks @romani. It's amazing to know that! Feeling glad.
