### ISSUE TITLE
Behavior change with JavadocMethodCheck

### ISSUE THREAD

**Issue by vendmr23** [checkstyle/checkstyle#10338] opened 2021-07-14 22:30 UTC
I have recently upgraded Checkstyle from 8.20 to 8.39 and have noticed a behavior change that I did not see documented.  Maybe this was a bug that was fixed or is a new bug.

Here is my old definition (8.20):
```
        <module name="JavadocMethod">
            <property name="scope" value="public"/>
            <property name="ignoreMethodNamesRegex" value="^test.*$"/>
            <property name="allowUndeclaredRTE" value="true"/>
            <property name="allowMissingPropertyJavadoc" value="true"/>
            <property name="suppressLoadErrors" value="true"/>
            <property name="allowThrowsTagsForSubclasses" value="true"/>
        </module>
```

Here is my new definition (8.39):
```
        <module name="JavadocMethod">
            <property name="scope" value="public"/>
        </module>
        <module name="MissingJavadocMethod">
            <property name="scope" value="public"/>
        </module>
```

The change is related to missing parameters:

My Javadoc looks as follows:
```
    /**
     * Create a component using this model.
     *
     * @param inModel
     */

public Component(Model inModel) {
        _model = inModel;
    }
```

In 8.20 this would fail with
Expected @param tag for 'inModel' [JavadocMethod]

In 8.39 is does not fail

If I add anything after the @param inModel in 8.20 then it passes.  This forced me to add (meaningful?) docs as in:
     * @param inModel The model that will be used to save the world.
     
I thought this was a useful feature.  The thing is the check was satisfied even if I just add a single space after the parameter name.

So I don't know if this was a feature that went away or a bug that was fixed.  I preferred the old behavior.

Thanks,
Michael

**Comment by strkkk** [comment] 2021-07-15 07:07
@vendmr23 you can use other check for such cases - https://checkstyle.org/config_javadoc.html#NonEmptyAtclauseDescription

I do not say this is not a bug.

**Comment by vendmr23** [comment] 2021-07-15 15:52
Thanks, that works for me.

**Comment by vendmr23** [comment] 2021-07-16 15:55
One issue I still have is that NonEmptyAtclauseDescription is not scoped, whereas the JavadocMethod was applied to public methods only.

**Comment by rnveach** [comment] 2021-09-04 19:04
> Here is my old definition (8.20):

Same behavior up to 8.24. Minor changes to config and this behavior continues up to 8.26 .

> In 8.20 this would fail with
> Expected @param tag for 'inModel' [JavadocMethod]
> In 8.39 is does not fail

Behavior changed in 8.27 which the only thing that looks related is https://github.com/checkstyle/checkstyle/issues/6743 but I am not seeing how it is connected.

Its not clear from check description if old behavior is valid or new behavior is.
> Violates parameters and type parameters for which no param tags are present can be suppressed by defining property allowMissingParamTags. 

Regardless, I agree change was not expected.

**Comment by rnveach** [comment] 2021-09-04 19:04
@romani ping. Can you help identify if this an issue or not?

**Comment by rnveach** [comment] 2021-09-04 19:14
Regression identified at https://github.com/checkstyle/checkstyle/pull/7212#discussion_r337500962 .

Ability to restore violation on missing description is moved to https://github.com/checkstyle/checkstyle/issues/6746 .

I am closing this issue because of this.

**Closed by rnveach** 2021-09-04 19:14 UTC
