### ISSUE TITLE
CheckStyle does not accept @NonNull...

### ISSUE THREAD

**Issue by duesentrieb17** [checkstyle/checkstyle#5371] opened 2017-12-20 16:49 UTC
`/var/tmp $ javac Test.java`:

```
```

`/var/tmp $ cat Test.java`:

```
import static java.lang.annotation.ElementType.TYPE_USE;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

public class Test {

	@Retention(RetentionPolicy.CLASS)
	@Target({TYPE_USE})
	public @interface NonNull {
	}

	public void test(final Object @NonNull... args) {
	}
}
```

`/var/tmp $ cat config.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="UpperEll"/>
  </module>
</module>
```

`/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.5-all.jar -c config.xml Test.java`:

```
Starting audit...
/var/tmp/Test.java:14:40: unexpected token: ...
Audit done.
```

---------------

The "@NonNull..." is valid but CheckStyle stumbles over it.

--------------

**Comment by rnveach** [comment] 2017-12-20 17:54
Closing as a duplicate of https://github.com/checkstyle/checkstyle/issues/3238

**Closed by rnveach** 2017-12-20 17:54 UTC
