### ISSUE TITLE
RequireThisCheck: Use and declare a local variable with same name as class variable cause a NPE

### ISSUE THREAD

**Issue by elehuitouze** [checkstyle/checkstyle#4777] opened 2017-07-20 10:15 UTC
````
/var/tmp $ javac LocalVariableSwitch.java 

/var/tmp $ cat LocalVariableSwitch.java

public class LocalVariableSwitch {
    private String aVariable;

    public String aMethod(int val) {
        switch (val) {
            case 0:
                String aVariable = "";
                
                if (this.aVariable != null) {
                    aVariable = this.aVariable;
                }
                
                return aVariable;
            default:
                return null;
        }
    }
}

/var/tmp $ cat config.xml

<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="RequireThisCheck" />
    </module>
</module>

/var/tmp $ java -jar checkstyle-8.0-all.jar -c config.xml LocalVariableSwitch.java

Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing LocalVariableSwitch.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:430)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:362)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:177)
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.isUserDefinedArrangementOfThis(RequireThisCheck.java:511)
	at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.getClassFrameWhereViolationIsFound(RequireThisCheck.java:485)
	at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.getFieldWithoutThis(RequireThisCheck.java:318)
	at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.processIdent(RequireThisCheck.java:270)
	at com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck.visitToken(RequireThisCheck.java:231)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:368)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:505)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:310)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:182)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
	... 4 more
Checkstyle ends with 1 errors.
````

---------------

Declare and use a local variable with the same name as a class variable in a switch cause a NPE.
It's ok (no NPE), if the local variable is declared outside the switch.

**Comment by rnveach** [comment] 2017-07-20 11:22
I can confirm exception. It started at version 6.17 .

**Comment by rnveach** [comment] 2017-07-29 13:04
[The problem is `getBlockEndToken` is returning `null`.](https://github.com/checkstyle/checkstyle/blob/bb05231428d62fa6e253fa3f55a47335c958f4b4/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.java#L530)
`blockNameIdent` and `blockStartToken` are both set to `SLIST[7x16]` which is the start of the case statement. However `getAllTokensOfType` is looking for a right curly that ends the `SLIST` and it is not a right curly that does it, it is the next case group at line 11.

**Comment by romani** [comment] 2017-07-31 06:35
fix is merged

**Closed by romani** 2017-07-31 06:35 UTC
Labels: approved, bug
