### ISSUE TITLE
Confusing violation of Indentation rule

### ISSUE THREAD

**Issue by Serranya** [checkstyle/checkstyle#7675] opened 2020-02-26 13:25 UTC
Im having a problem with the https://checkstyle.sourceforge.io/config_misc.html#Indentation check.

```/home/serra/dev/cs-repro $ javac Test.java```
[no output here]
```/home/serra/dev/cs-repro $ cat my-checks.xml```
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
	<property name="charset" value="UTF-8" />
	<property name="tabWidth" value="3" />
	<module name="TreeWalker">
		<module name="Indentation">
			<property name="basicOffset" value="3" />
			<property name="caseIndent" value="0" />
			<property name="lineWrappingIndentation" value="6" />
		</module>
	</module>
</module>
```

```/home/serra/dev/cs-repro $ cat Test.java```
```java
import java.util.Arrays;
import java.util.stream.Stream;

public class Test {
	public void test(Stream<Inner<?>> stream) {
		stream
				.filter(ps -> ps instanceof Inner)
				.map(ps -> ((Inner<?>) ps).getPropertyNames())
				.forEach(System.out::println);
	}

	private static class Inner<T> {
		String[] getPropertyNames() {
			return new String[] {"a", "b"};
		}
	}
}
```
```/home/serra/dev/cs-repro $ java -Duser.language=en -Duser.country=us -jar checkstyle-8.29-all.jar -c my-checks.xml Test.java
Starting audit...
[ERROR] /home/serra/dev/cs-repro/Test.java:8: 'lambda' has incorrect indentation level 12, expected level should be 18. [Indentation]
Audit done.
```

---------------

I expected the code to be conforming to my rules.
As far as I can recognize I adhere to all the rules in the xml.

I am not sure if this is a bug or if I am just misunderstandung how the rule is working.

**Comment by rnveach** [comment] 2020-02-26 13:33
This looks like a bug to me from the information I am seeing, but indentation is always tricky.

Lambda does not start the line and should not have been the one reporting the problem if the indentation was wrong. I would expect the `.` or referenced the message call to be where the failure message to be.

**Comment by liach** [comment] 2020-03-19 04:54
Duplicate of #5969.

**Comment by romani** [comment] 2020-03-21 20:04
@Serranya, please share all output  as requested in template. We need version of checkstyle you used, ply make sure it is latest

**Closed** 2020-03-27 06:40 UTC
Labels: approved, indentation

**Comment by strkkk** [comment] 2020-03-27 06:41
Fix is merged
