### ISSUE TITLE
NeedBraces: NPE crash

### ISSUE THREAD

**Issue by dhendriks** [checkstyle/checkstyle#2135] opened 2015-09-07 08:14 UTC
For a Java file 'Test.java':

```java
public class StateInfo {
    public boolean isInitial() {
        for (int loc: srcLocs) if (loc != 0) return false;
        return true;
    }
}
```

with Checkstyle configuration 'checkstyle.xml':

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <property name="severity" value="warning"/>
  <module name="TreeWalker">
    <module name="NeedBraces">
      <property name="allowSingleLineStatement" value="true"/>
    </module>
  </module>
</module>
```

Checkstyle 6.10.1 crashes with a NullPointerException:

```
$ java -jar ../checkstyle-6.10.1/checkstyle-6.10.1-all.jar -c checkstyle.xml Test.java
Exception in thread "main" java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck.isSingleLineFor(NeedBracesCheck.java:286)
        at com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck.isSingleLineStatement(NeedBracesCheck.java:203)
        at com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck.isSkipStatement(NeedBracesCheck.java:177)
        at com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck.visitToken(NeedBracesCheck.java:164)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:392)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:503)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:334)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:209)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:265)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:271)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:121)
```

**Comment by mkordas** [comment] 2015-09-07 20:25
Thanks, issue confirmed. Looks like this check with this option does not support enhanced for loops at all.
Minimal code to reproduce NPE:
```java
    void enhancedForLoop(int[] array) {
        for (int value: array) return;
    }
```

**Comment by romani** [comment] 2015-09-08 23:34
merged

**Closed by romani** 2015-09-08 23:34 UTC
Labels: approved
