### ISSUE TITLE
Parsing problems on openjdk9 sources

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#955] opened 2015-04-21 21:38 UTC
https://github.com/checkstyle/contribution/tree/master/checkstyle-tester

change at 
checkstyle-tester/projects-to-test-on.properties
-#openjdk|hg|http://hg.openjdk.java.net/jdk7/jdk7/jdk/
+openjdk|hg|http://hg.openjdk.java.net/jdk9/jdk9/jdk/|jdk9-b59

launch testing "./launch":

Results:
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/GetAnnotatedReceiverType.java:35:25: unexpected token: GetAnnotatedReceiverType
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/GetAnnotatedReceiverType.java:36:19: unexpected token: void
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/GetAnnotatedReceiverType.java:43:72: unexpected token: .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/GetAnnotatedReceiverType.java:89:20: unexpected token: int
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/GetAnnotatedReceiverType.java:90:20: unexpected token: int
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/GetAnnotatedReceiverType.java:92:19: unexpected token: void
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/GetAnnotatedReceiverType.java:93:52: expecting IDENT, found '.'
[ERROR] MismatchedTokenException occurred during the analysis of file /home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/GetAnnotatedReceiverType.java .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/ConstructorReceiverTest.java:131:92: unexpected token: .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/ConstructorReceiverTest.java:134:56: unexpected token: .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/ConstructorReceiverTest.java:137:72: unexpected token: .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/ConstructorReceiverTest.java:142:54: unexpected token: .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/ConstructorReceiverTest.java:150:70: unexpected token: .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/ConstructorReceiverTest.java:153:87: unexpected token: .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/ConstructorReceiverTest.java:161:90: unexpected token: .
[ERROR] MismatchedTokenException occurred during the analysis of file /home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/ConstructorReceiverTest.java .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/TestExecutableGetAnnotatedType.java:200:52: expecting IDENT, found '@'
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/TestExecutableGetAnnotatedType.java:200:60: unexpected token: RuntimeException
[ERROR] MismatchedTokenException occurred during the analysis of file /home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/typeAnnotations/TestExecutableGetAnnotatedType.java .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeAnnotationReflection.java:522:86: unexpected token: .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeAnnotationReflection.java:523:31: unexpected token: ParameterizedInner
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeAnnotationReflection.java:523:82: unexpected token: Integer
[ERROR] MismatchedTokenException occurred during the analysis of file /home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeAnnotationReflection.java .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:97:37: expecting IDENT, found '@'
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:97:77: unexpected token: AnnotatedElement
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:97:131: unexpected token: Type
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:101:47: expecting IDENT, found '@'
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:101:87: unexpected token: Set
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:101:115: unexpected token: Callable
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:111:32: expecting IDENT, found '@'
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:111:61: unexpected token: Runnable
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:112:16: unexpected token: <
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:112:21: unexpected token: C6MT1
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:113:34: unexpected token: AnnotatedElement
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:114:34: unexpected token: AnnotatedElement
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:114:58: unexpected token: Type
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java:115:35: unexpected token: C6CT2
[ERROR] MismatchedTokenException occurred during the analysis of file /home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeVariableBounds.java .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeParamAnnotation.java:102:18: expecting IDENT, found '@'
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeParamAnnotation.java:102:49: unexpected token: T
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeParamAnnotation.java:104:49: unexpected token: V
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeParamAnnotation.java:105:12: unexpected token: <
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeParamAnnotation.java:105:44: unexpected token: X
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/lang/annotation/TypeParamAnnotation.java:107:44: unexpected token: Z
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/util/concurrent/ConcurrentHashMap/ToArray.java:91:26: unexpected token: <
[ERROR] MismatchedTokenException occurred during the analysis of file /home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/java/util/concurrent/ConcurrentHashMap/ToArray.java .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TargetTypes.java:93:25: expecting ELLIPSIS, found 'this'
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TargetTypes.java:108:5: unexpected token: <
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TargetTypes.java:108:9: unexpected token: T
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TargetTypes.java:108:15: unexpected token: U
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TargetTypes.java:112:13: expecting IDENT, found '@'
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TargetTypes.java:112:22: unexpected token: U
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TargetTypes.java:143:44: expecting SEMI, found '@'
[ERROR] MismatchedTokenException occurred during the analysis of file /home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TargetTypes.java .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TypeUseTarget.java:37:6: unexpected token: String
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TypeUseTarget.java:37:16: unexpected token: [
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TypeUseTarget.java:39:6: unexpected token: String
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TypeUseTarget.java:39:21: unexpected token: TypeUseTarget
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TypeUseTarget.java:39:47: unexpected token: String
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TypeUseTarget.java:39:64: unexpected token: String
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TypeUseTarget.java:39:74: unexpected token: ...
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TypeUseTarget.java:40:8: unexpected token: Object
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TypeUseTarget.java:40:26: unexpected token: String
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TypeUseTarget.java:40:36: unexpected token: [
[ERROR] MismatchedTokenException occurred during the analysis of file /home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/test/tools/pack200/typeannos/TypeUseTarget.java .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/src/java.base/unix/classes/java/io/FileDescriptor.java:217:26: expecting IDENT, found ')'
[ERROR] MismatchedTokenException occurred during the analysis of file /home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/src/java.base/unix/classes/java/io/FileDescriptor.java .
/home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/src/java.base/windows/classes/java/io/FileDescriptor.java:215:26: expecting IDENT, found ')'
[ERROR] MismatchedTokenException occurred during the analysis of file /home/rivanov/checkstyle-test/contribution/checkstyle-tester/src/main/java/openjdk/src/java.base/windows/classes/java/io/FileDescriptor.java .

Expected: no parsing problems if sources are compilable, if smth is not compilable we need toput exclude path to property file of checkstyle-tester.

**Comment by rnveach** [comment] 2016-06-02 14:10
duplicate of #3033

**Closed** 2016-06-02 15:50 UTC
Labels: antlr, approved
