### ISSUE TITLE
Parse error of Java 8 code using generic type with double-colon operator

### ISSUE THREAD

**Issue by smarr** [checkstyle/checkstyle#2861] opened 2016-02-01 12:09 UTC
Hi:

I got a parse error for the code below. 
The parsers complains with: `Test.java:8:22: expecting RPAREN, found '<'`

So, the problematic code is the line with `toArray()`. Removing `<?>` works as a work around.

```Java
import java.util.Arrays;

public class Test {
  private static Class<?>[] getJavaTypes(final Object[] args) {
    return Arrays.stream(args).
        map(e -> e.getClass()).
        toArray(Class<?>[]::new);
  }
}
```

This is tested with Checkstyle 6.15.

**Comment by romani** [comment] 2016-02-05 14:12
duplicate of #2729

**Closed by romani** 2016-02-05 14:12 UTC
