### ISSUE TITLE
update documentation for windows users

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#2622] opened 2015-11-18 15:43 UTC
Most of our documentation centers around commands that only work for linux users.
We should expand it to also include support for Windows users so anyone can use CS.

Examples:
https://github.com/checkstyle/checkstyle/blob/71950237c1728ec9a20c9b3d6801beb1f334857d/src/xdocs/report_issue.xml#L60
https://github.com/checkstyle/checkstyle/blob/master/.github/ISSUE_TEMPLATE.md

Window users must use `type` instead of `cat`.
So we need one more example block for windows users below example for Linux/Unix. Should be "Example of report that we expect from Windows users .............."

**Comment by romani** [comment] 2017-10-18 11:51
@Raman1121 , can you help us to resolve this issue ?

**Comment by Raman1121** [comment] 2017-10-19 14:31
@romani So basically, here I have to reproduce the same block in which the word 'cat' is replaced with the word 'type'?

**Comment by romani** [comment] 2017-10-20 22:24
yes, and test it on windows to make sure it works on any windows

**Comment by pbludov** [comment] 2017-11-29 09:12
@Raman1121 Please add this two lines to the report_issue.xml:

For reporting javadoc errors, it is recommended to add the output of the javadoc tool:
`$ javadoc -Xdoclint:all TestClass.java`

@romani, should it be a new issue or it is OK to add this to windows related changes?

**Comment by romani** [comment] 2017-11-29 13:36
It is better to do in separate issue.
One problem that I see with extending issue template is that too much people ignore it because it is long to read. And now he will need to share version of javadoc tool too. 

But it still good to have one link to share with user to force him to give all details

**Comment by wltan** [comment] 2020-04-11 11:46
I am on it

**Comment by romani** [comment] 2020-04-26 12:27
fix is merged.

**Closed** 2020-04-26 12:26 UTC
Labels: approved, easy
