### ISSUE TITLE
Checkstyle failing to parse new escape symbol that was added in jdk15 

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#9132] opened 2020-12-26 03:05 UTC
https://openjdk.java.net/jeps/368

> Second, the new \s escape sequence simply translates to a single space (\u0020).
Escape sequences aren't translated until after incident space stripping, so \s can act as fence to prevent the stripping of trailing white space. Using \s at the end of each line in this example guarantees that each line is exactly six characters long:
String colors = """
    red  \s
    green\s
    blue \s
    """;
The \s escape sequence can be used in both text blocks and traditional string literals.

```
$ java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

$ cat Test.java 
public class Test {
  String value = "\s";
}

$ javac Test.java 
$ java -jar checkstyle-8.38-all.jar -t Test.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: TokenStreamRecognitionException occurred while parsing file /var/tmp/Test.java.
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:120)
	at com.puppycrawl.tools.checkstyle.JavaParser.parseFileText(JavaParser.java:137)
	at com.puppycrawl.tools.checkstyle.JavaParser.parseFile(JavaParser.java:157)
	at com.puppycrawl.tools.checkstyle.AstTreeStringPrinter.printFileAst(AstTreeStringPrinter.java:65)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:284)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:190)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
Caused by: line 2:20: unexpected char: 's'
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:412)
	at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
	at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:134)
	at antlr.TokenStreamSelector.nextToken(TokenStreamSelector.java:65)
	at antlr.TokenBuffer.fill(TokenBuffer.java:69)
	at antlr.TokenBuffer.LA(TokenBuffer.java:80)
	at antlr.LLkParser.LA(LLkParser.java:52)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classOrInterfaceType(GeneratedJavaRecognizer.java:1117)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classTypeSpec(GeneratedJavaRecognizer.java:887)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeSpec(GeneratedJavaRecognizer.java:849)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3119)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:3415)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:646)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:561)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:402)
	at com.puppycrawl.tools.checkstyle.grammar.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:212)
	at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:114)
	... 6 more
Checkstyle ends with 1 errors.

```

**Comment by romani** [comment] 2020-12-26 03:07
@nmancus1 , please help to fix if you are around.
it is found at https://github.com/checkstyle/checkstyle/pull/9129#discussion_r548902300

**Comment by nmancus1** [comment] 2020-12-26 03:26
@romani this is a duplicate of https://github.com/checkstyle/checkstyle/issues/8651 I think. I will work on this.

**Closed** 2020-12-26 03:49 UTC
Labels: antlr, approved
