### ISSUE TITLE
Invoking Checkstyle directly from Java

### ISSUE THREAD

**Issue by mockitoguy** [checkstyle/checkstyle#6234] opened 2018-11-30 21:55 UTC
Hello Checkstyle team! Thank you for the tool - we have been using if for years!

### Problem

I'm trying to cleanly integrate Checkstyle with Gradle and for this I need to programmatically invoke Checkstyle from Java (https://github.com/gradle/gradle/issues/7867). com.puppycrawl.tools.checkstyle.Main#main() does not work because it calls System.exit().

### Suggested solution

Options:

a) provide Java API
b) avoid System.exit() in main()
c) offer a CLI flag / system property to prevent System.exit() in main()
d) as a user I can use security manager to catch "exitVM" attempts

a) From what I gathered there isn't a Java API today. Adding it is an extra work, test, future maintenance. As a user I actually prefer to call main() because it is more stable (minimum API footprint) for the long game. It reuses CLI code so I feel safer as user that it won't break.
b) An incompatible change.
c) Good, pragmatic option.
d) I am experimenting with this workaround now. I'm not entirely happy with it because in the past I did not find SecurityManager as a reliable solution to this use case (preventing 3rd party code from exiting vm).

I suggest we go for c). I can put together a PR but first I would like know if you would accept it.

**Comment by rnveach** [comment] 2018-11-30 23:11
I don't know gradle very well but would it be better if it had its own custom main? For maven and ant, they have their own custom entry points and don't use Checkstyle's main. I'm not sure if we should be hosting this or someone else. We host any (not sure why) but we don't host maven.

**Comment by romani** [comment] 2018-12-01 06:05
CLI is not our API, we have special package for API - https://github.com/checkstyle/checkstyle/tree/master/src/main/java/com/puppycrawl/tools/checkstyle/api

Main class that is our CLI is created to ease usage of of some functionality, and define a way to reproduce issues. Do not use it, but review code of it and copy parts it to your plugin.

Non of suggested points make any sense to me. 

Please review our numerous plugins codes, to get to know how to use core library properly. https://checkstyle.org/#Related_Tools


I am closing issue, but discussion can be continued.

**Closed by romani** 2018-12-01 06:05 UTC

**Comment by romani** [comment] 2018-12-01 17:14
>then (in semver sense)? 

Unfortunately not now, but eventually yes - https://checkstyle.org/#Development_Cycle

>How often it changes / how do you manage compatibility?

Not that often, but we try to do changes when we have time. Follow our release notes, we accurately classifying issues as breaking compatibility https://checkstyle.org/releasenotes.html

>What integration is considered "gold standard"? 

Good question, ... I do not know, we do not have people enough to make smth as gold standard, probably your Gradle plugin will become it, we could help with advices to let you succeed.
Unfortunately internal ANT integration is far from good example only because not that much people are using it, so some problems might exists in it, but it makes sense to review it. 
As gradle plugin developer, you do not need to know Checkstyle API that much, all you need to know is how to deliver configuration to Checker and just run it, and get output.
The best way to communicate is to let you share your design of plugin and we will guide you what you need to use.

>uses classes from "com/puppycrawl/tools/checkstyle/api/" (public API?) 

Yes.

from "com/puppycrawl/tools/checkstyle/" (internal API?).

Not an API, just some general stuff. All you need to know is Checker and TreeWalker. It is highly recommend to read https://checkstyle.org/extending.html to understand how it works.

**Comment by rnveach** [comment] 2018-12-01 17:36
> Not an API, just some general stuff.

I would consider some things there more than general.

CheckstyleAnt and maven's plugin, both have to use non-API classes to just be able to invoke Checkstyle.

Take `ConfigurationLoader`. This is how your configuration file is loaded to use by Checkstyle. You can't load a configuration to use in Checkstyle without it unless you want to build it yourself by hand. Why isn't this considered an API of some kind?

XMLLogger and DefaultLogger is the same. By default Checkstyle has no automatic console/file printer. You would either have to create your own, or use our non-API  versions.

It seems to me if we say we don't support non-API use, then we should have some API form to do these common tasks.

**Comment by romani** [comment] 2018-12-01 18:04
Interfaces are an API. All our implementations out of API package are not API, but could be reused.
We do not have well designed API strategy, sorry.

**Comment by mockitoguy** [comment] 2018-12-02 03:13
Do you know how is Checkstyle used most commonly? Via Maven plugin? Perhaps this will guide us what's the best reference integration / most stable API. Have you had integration problems such as: a change in Checkstyle that breaks Maven integration?

How do you test the releases? Do you check if maven plugin still works (or test any other 3rd party integration)? I assume that the highest chance of compatibility is the ant task and the CLI because they are part of the Checkstyle project.

Current Gradle Checkstyle integration uses ant task internally and it has been stable for many years. I'm looking for a way to a) stop using ant b) remain same level of stability. I can use classes from "com/puppycrawl/tools/checkstyle/[api]/*" but I'm worried about stability.

Thank you for very useful insights!

**Comment by rnveach** [comment] 2018-12-02 03:41
> Do you know how is Checkstyle used most commonly?

I'm not sure we have any statistic, but I would say maven since that is what people seem to be migrating to as part of their CIs.

> Have you had integration problems such as: a change in Checkstyle that breaks Maven integration?

Yes.
It doesn't happen often, but we have broken compile-ability in the past with the maven plugin and eclipse-cs. Right now we are still slightly broken with the maven plugin only in a specifc use-case but the reason for this is no one seems to want to update the plugin anymore. See https://issues.apache.org/jira/browse/MCHECKSTYLE-344 .
Sevntu is almost like our sister project, so when we break something here we almost always update it right away.

> How do you test the releases?

See our CI in our YML files. Mostly this is just running `mvn verify test`, which does use the maven plugin. We also run the new changes against projects that use checkstyle looking for exceptions or new violations. We do use the maven plugin in this case too, but, IMO, we should only be using the CLI since that is what we maintain. Too much reliance on an external plugin that is having problems getting updates causes us issues. I personally want to break away from using it completely.

> Do you check if maven plugin still works (or test any other 3rd party integration)?

We have maven plugin defined in our POM, so yes, we check it all the time that way. It won't catch everything, but it atleast maintains the connection still works. We also test a connection with sevntu this way.
We don't test the connection with eclipse-cs, but we have gotten slightly more involved with its process.

**Comment by mockitoguy** [comment] 2018-12-07 23:57
Thank you for the feedback! I'm curious why you recommend us to use the Checkstyle Java API instead of running the CLI?

If we use the Java API in the Gradle plugin (like maven plugin does today) we get higher risk of incompatibilities in the future. Gradle has very strict compatibility commitment. If any of the Checkstyle Java APIs change we will have to add "compatibility layer" in Gradle to keep the code working with multiple versions. This is extremely inconvenient.

Thoughts?

**Comment by romani** [comment] 2018-12-08 06:36
>use the Checkstyle Java API instead of running the CLI?

API exists for many many years. CLI is relatively recent product, main idea of it was to standardize issue reporting :) , fun ? We never thought a lot about it, and change it as we wanted. With API we are very accurate, as we understand how much it could damage in the world.

You can use CLI, we unlikely to change it for most main  arguments. Just beware that we will not provide deprecation period for some functionality. Xpath and multi thread features are unstable in CLI.

> If any of the Checkstyle Java APIs change 

API will change for sure, we kept it unchanged for about 7 years or more. We have to start to change API, step by step.

>we will have to add "compatibility layer" in Gradle to keep the code working with multiple versions. This is extremely inconvenient.

Hard to suggest something without all details. If you use API you will have ability to wrap configuration to non-xml , and generate output in any required format or view. If you do not plan to provide it in plugin, you can use CLI. But how it will make you different from shell execution step in gradle?  I hope you know what you are doing.

CLI will unlikely to change, as it very limited in functionality and just do basic stuff. I am afraid to give you a promise to support it the same way as API. CLI unlikely to change with incompabilities, we have no problems with naming, in last release we did extra cleanup at CLI, we now use picocli library :).
