### ISSUE TITLE
Split BaseCheckTestSupport into AbstractPathTestSupport, AbstractModuleTestSupport, and AbstractTreeTestSupport

### ISSUE THREAD

**Issue by ps-sp** [checkstyle/checkstyle#4592] opened 2017-07-03 04:41 UTC
Other test classes which aren't check tests also extend [`BaseCheckTestSupport`](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/BaseCheckTestSupport.java) . For example look at the following classes which extend `BaseCheckTestSupport`

[`AstTreeStringPrinterTest`](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/AstTreeStringPrinterTest.java#L37)
[`JavadocParseTreeTest`](https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParseTreeTest.java#L29)

In the future, there might be need for other non-check tests' classes to extend it too. It overall seems better to call it `BaseTestSupport`

**Comment by subkrish** [comment] 2017-07-05 08:58
@romani I'll work on this.

**Comment by romani** [comment] 2017-07-08 03:19
@subkrish , @rnveach 

I think here is big conceptual mis understanding .
BaseCheckTestSupport was designed for Checks and have a lot of methods that are for Checks only
![image](https://user-images.githubusercontent.com/812984/27982166-6d6423f0-6350-11e7-912d-fb0d65b06292.png)

Fact that other Test are using it it is their problem, they should not extend this class at all.
Example: CheckstyleAntTaskTest can have its own implementation of getPath and that is all that he use from BaseCheckTestSupport, extending is not appropriate.

AstTreeStringPrinterTest, JavadocParseTreeTest use only verifyAstXXXXX methods , so they could have that methods in their common parent, that is not BaseCheckTestSupport.

**Comment by rnveach** [comment] 2017-07-08 12:47
> CheckstyleAntTaskTest can have its own implementation of getPath 

Almost all tests should override `getPath` to support their own specific path. You can see this in checks where we take the original `getPath` and build upon it. We want everyone to put their inputs in their own directory. I dislike the idea of rewriting the full path in every test file. I like it when we extend and just append to the end.

> rename BaseCheckTestSupport to BaseModuleTestSupport

I am fine with this.

> CheckstyleAntTask, AstTreeStringPrinter, JavadocParseTree are not modules

I assumed the purpose of this class was to make a place for all common testing methods, hence why we we added `verifyAst` to it. I don't really see a big problem keeping it as it is. If we split this class into 2, than it will cause issues if we ever have a test that requires methods from both. I assume we will wait until this happens, unless someone can point to a place where it has already.

How about we make 3 classes?
1) BaseTestSupport - contains bare common things like `getPath`. Extends nothing.
2) BaseModuleTestSupport - contains everything module run related. Extends BaseTestSupport.
3) BaseTreeTestSupport - contains everything tree related. Extends BaseTestSupport.

I still think the classes should be abstract (and named so) to signal they are not to be used without extending. It doesn't bother me there are no abstract methods.

**Comment by romani** [comment] 2017-07-08 13:31
I agree on this.

@subkrish , fyi - #4661 . And please think how to make that changes steps by step without huge PR.
we need to cut Ant first from hierarchy
then cut from hierarchy AstTreeStringPrinter, JavadocParseTree
third PR will be about renaming or changing BaseCheckTestSupport

**Comment by rnveach** [comment] 2017-07-08 13:42
After talking with @romani we added `AbstractPathTestSupport` for classes that don't fall under the other 2.
Ant and any other weird ones should use it.

**Comment by subkrish** [comment] 2017-07-08 22:22
@romani @rnveach 

Regarding first PR, `CheckstyleAntTaskTest` only uses `getPath()`. I think it can directly just extend `AbstractPathTestSupport` as you have suggested that it is not a module.

**Comment by ps-sp** [comment] 2017-07-09 02:06
@romani @rnveach 
Why can't we have an abstract class `BaseTestSupport` with constants like `static final File TEST_DIR = new File(...)` and abstract methods like `getPath()` and can also have all the other _general_ methods in it. It can be extended by `BaseCheckTestSupport` _(and other `...TestSupport` classes if necessary)_. This also helps overcome the issue of some test requiring methods from multiple test support classes, since if a test actually has such requirement then that means 
**either** 
the method is more general than the particular `...TestSupport` class it resides in and hence can be moved upward in the parent class.
**or**
the test requires a new `...TestSupport` class which would extend the abstract `BaseTestSupport` class.

**Comment by rnveach** [comment] 2017-07-09 03:17
> 'module related' 

Anything that is a check, fileset, etc should be extending the module one.

> I think AbstractPathTestSupport must also contain getNonCompilablePath() or will this be in AbstractModuleTestSupport?

It should be in module unless you can point to use a specific non-module that must use a non-compilable file.

**Comment by rnveach** [comment] 2017-07-09 03:27
> Why can't we have an abstract class BaseTestSupport with constants like static final File TEST_DIR = new File(...) and abstract methods like getPath() and can also have all the other general methods in it.

This is basically what `AbstractPathTestSupport` is but slightly different. There are no other general methods that don't fall into one of the 2 categories we have defined.

**Comment by rnveach** [comment] 2017-07-14 02:40
@subkrish Please continue on with creating AbstractModuleTestSupport or AbstractTreeTestSupport.
Just do a small PR with new class and one existing test class changed so we can agree on contents of class like `AbstractPathTestSupport`.

Once these 2 are done in separate PRs, we change the rest of the tests in mass.

**Comment by romani** [comment] 2017-07-18 03:14
@subkrish , are we done with this issue ?

**Comment by subkrish** [comment] 2017-07-18 03:21
@romani No I still need to create `AbstractModuleTestSupport` and extend all other tests from it.

Also do I need to make changes to `ITs` as well? I wasn't sure about those changes. If they need to be done as well then I will work on them in this issue itself after `AbstractModuleTestSupport` is created.

**Comment by romani** [comment] 2017-07-18 04:54
> Also do I need to make changes to ITs as well?

yes, please, as it was created originally as some from copy UT code.

**Comment by subkrish** [comment] 2017-07-19 16:03
What should we do about `BaseFileSetCheckTestSupport`?
Because the tests in the `header` package use it.
-> https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/BaseFileSetCheckTestSupport.java
-> https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java#L51
How should I go about making changes for that?

**Comment by subkrish** [comment] 2017-07-21 11:33
`AllBlockComments` and `AllSinglelineComments` need both methods from `AbstractTreeTestSupport` and `AbstractModuleTestSupport`.
If I extend it from tree I would have to add `verify`, `checkConfig` and I think two more methods to tree.
I don't want to extend it from module because then I would need to add the `verifyAst` method,etc.
What should I do?

**Comment by romani** [comment] 2017-07-22 16:00
> AllBlockComments and AllSinglelineComments need both methods from AbstractTreeTestSupport and AbstractModuleTestSupport

if both methods are required, it means it is problems with location of test. All test for Checks (that use `verify` methods) should be Test classes that extended from AbstractModuleTestSupport. 
All test methods that verify ast structure should be grouped in Test classes that extends AbstractTreeTestSupport.

**Comment by subkrish** [comment] 2017-07-23 03:48
@romani 
> All test for Checks (that use verify methods) should be Test classes that extended from AbstractModuleTestSupport.
All test methods that verify ast structure should be grouped in Test classes that extends AbstractTreeTestSupport.

Exactly. But the problem is that, for example `AllBlockComments` uses both `verify` and `verifyAst` so it requires both the abstract classes based on the current design.

Also what about https://github.com/checkstyle/checkstyle/issues/4592#issuecomment-316435109 ? @rnveach suggested we make `AbstractFileSetTestSupport` for it and copy the method from `BaseFileCheckTestSupport` and have it extend `AbstractPathTestSupport` or `AbstractModuleTestSupport` based on the methods the UTs require.

**Comment by romani** [comment] 2017-07-23 14:31
> But the problem is that, for example AllBlockComments uses both verify and verifyAst

As mentioned before, method https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/grammars/comments/AllBlockCommentsTest.java#L58 need to be moved out of this class as it is misplaced. Please move to `AstTreeStringPrinterTest.java`.

> BaseFileCheckTestSupport and have it extend AbstractPathTestSupport or AbstractModuleTestSupport

`Module` is more abstract term than `Check`. I would like to avoid extra hierarchy level as much as possible. But if we come to this then `BaseFileCheckTestSupport`  should extends `AbstractModuleTestSupport`. But I do not see why we need this now, please point me to a problem.

**Comment by subkrish** [comment] 2017-07-23 16:53
@romani 

> But I do not see why we need this now, please point me to a problem.

I don't know whether it is a problem or not but, the tests in `header` package and a few other tests use it. `BaseFileCheckTestSupport` contains one method that these test files use. As you have  suggested extending it from `AbstractModuleTestSupport` should do the trick. 

https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java#L51 will now extend `AbstractModuleTestSupport` instead of `BaseFileTestSupport` and no other changes would be made to `BaseFileCheckTestSupport`.

**Comment by rnveach** [comment] 2017-08-02 16:35
I am closing this as all changes should be complete.
Removal of old test support class will be done in https://github.com/checkstyle/checkstyle/issues/4867 .

**Closed by rnveach** 2017-08-02 16:35 UTC
Labels: approved, easy, miscellaneous
