### ISSUE TITLE
Exception during processing file ArrayClass.java:8:49: expecting IDENT, found 'int'

### ISSUE THREAD

**Issue by zielint0** [checkstyle/checkstyle#6064] opened 2018-08-09 17:57 UTC
```
D:\projects\untitled2\src>javac ArrayClass.java
D:\projects\untitled2\src>

/var/tmp $ cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.2//EN" "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<!-- https://github.com/INRIA/spoon/blob/master/checkstyle.xml -->
<module name="Checker">
  <module name="TreeWalker">
    <module name="LeftCurly" />
  </module>
</module>

/var/tmp $ cat ArrayClass.java
import java.lang.annotation.ElementType;
import java.lang.annotation.Target;

public class ArrayClass {

	int[][][] i = new @TypeAnnotation(integer = 1) int[0][][];

	@Target({ ElementType.TYPE_USE })
	@interface TypeAnnotation {
		int integer() default 0;
	}
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml ArrayClass.java

D:\projects\spoon\src\test\java\spoon\test\arrays\testclasses\ArrayClass.java:8:49: expecting IDENT, found 'int'
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing src\test\java\spoon\test\arrays\testclasses\ArrayClass.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:581)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:472)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:226)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: MismatchedTokenException occurred while parsing file D:\projects\spoon\src\test\java\spoon\test\arrays\testclasses\ArrayClass.java.
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:98)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:180)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:81)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
        ... 4 more
Caused by: D:\projects\spoon\src\test\java\spoon\test\arrays\testclasses\ArrayClass.java:10:2: expecting EOF, found 'int'
        at antlr.Parser.match(Parser.java:211)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:211)
        at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:92)
        ... 8 more
Checkstyle ends with 1 errors.
PS D:\projects\spoon>

```

---------------
java -jar .\checkstyle-8.11-all.jar -c .\checkstyle.xml 
ArrayClass.java

Checkstyle ended with exception.
It should provide list of code style violations
D:\projects\spoon\src\test\java\spoon\test\arrays\testclasses\ArrayClass.java:8:49: expecting IDENT, found 'int'

-------

<a href="https://www.bountysource.com/issues/61947262-exception-during-processing-file-arrayclass-java-8-49-expecting-ident-found-int">
<img src="https://api.bountysource.com/badge/issue?issue_id=61947262">
</a>

**Comment by romani** [comment] 2018-08-10 00:11
@zielint0 , thanks for reporting issue, but please make extra effort to completely follow our issue template. Provide compilable single file, ..., Without any "Project builds successfully using IntelliJ IDEA/Maven."

**Comment by zielint0** [comment] 2018-08-12 22:54
@romani 
I updated template. Javac compiles code successfully (no errors).

**Comment by nmancus1** [comment] 2020-03-20 03:23
@romani, I wanted to take a look at this, but I can't reproduce it with newest master. I think we can mark this resolved.

**Comment by romani** [comment] 2020-03-20 05:06
To close issue we need CLI prove that it works.
@zielint0 , please recheck your side.

**Comment by nmancus1** [comment] 2020-03-20 05:14
```
➜  Issue_6064 javac ArrayClass.java
➜  Issue_6064 cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.2//EN" "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<!-- https://github.com/INRIA/spoon/blob/master/checkstyle.xml -->
<module name="Checker">
  <module name="TreeWalker">
    <module name="LeftCurly" />
  </module>
</module>
➜  Issue_6064 cat ArrayClass.java
import java.lang.annotation.ElementType;
import java.lang.annotation.Target;

public class ArrayClass {

	int[][][] i = new @TypeAnnotation(integer = 1) int[0][][];

	@Target({ ElementType.TYPE_USE })
	@interface TypeAnnotation {
		int integer() default 0;
	}
}
➜  Issue_6064 RUN_LOCALE="-Duser.language=en -Duser.country=US"
➜  Issue_6064 java $RUN_LOCALE -jar checkstyle-8.31-SNAPSHOT-all.jar -c config.xml ArrayClass.java 
Starting audit...
Audit done.

```

**Comment by romani** [comment] 2020-03-20 12:49
confirmed, resolved in 8.29

```
$ cat Test.java 
import java.lang.annotation.ElementType;
import java.lang.annotation.Target;

public class ArrayClass {

  int[][][] i = new @TypeAnnotation(integer = 1) int[0][][];

  @Target({ ElementType.TYPE_USE })
  @interface TypeAnnotation {
    int integer() default 0;
  }
}

$ java -jar /var/tmp/checkstyle-8.29-all.jar -c config.xml Test.java 
Starting audit...
Audit done.

```

**Comment by romani** [comment] 2020-03-20 12:55
fixed by @esilkensen at #3238 or related.

but I think it will be honest to let @nmancus1 to claim a bounty in this issue as he found this issue and helped to close it.
@nmancus1 , when bountysource.com come back online please claim a bounty.

**Comment by nmancus1** [comment] 2020-03-20 13:04
@romani that's very generous, thank you. Can you recommend another ANTLR issue that would be good for me?

**Comment by zielint0** [comment] 2020-03-20 13:20
Thank you for fixing this. Me and Spoon project are grateful :-)

**Comment by romani** [comment] 2020-03-20 13:24
@nmancus1 , I mentioned you in few issue , but can choose yourself at https://github.com/checkstyle/checkstyle/issues?q=is%3Aopen+is%3Aissue+label%3Aantlr

**Comment by romani** [comment] 2020-03-20 13:37
@zielint0 , to be honest I always wanted to try spoon , I never had a time to do this , but we try to apply all possible code analysis tool to your code, we have a lot of them already, but not a http://spoon.gforge.inria.fr/

I created https://github.com/checkstyle/checkstyle/issues/7913, I would appreciate if you help us start using it or explain in what validations checkstyle will benefit.

I will add spoon code to our testing projects, I hope we will not make exceptions on spoon code in future.

**Comment by zielint0** [comment] 2020-03-20 21:11
@romani 
AFAIK Spoon is a Java library to *low-level* processing Java source code. You can for example use its API to [detect empty catch blocks](http://spoon.gforge.inria.fr/first_analysis_processor.html).
```
// file processors/CatchProcessor.java
package processors;

import org.apache.log4j.Level;
import spoon.processing.AbstractProcessor;
import spoon.reflect.code.CtCatch;

/**
 * Reports warnings when empty catch blocks are found.
 */
public class CatchProcessor extends AbstractProcessor<CtCatch> {
    public void process(CtCatch element) {
        // we get all statements and if there isn't statement, it means the block catch is empty!
        if (element.getBody().getStatements().size() == 0) {
            getFactory().getEnvironment().report(this, Level.WARN, element, "empty catch clause");
        }
    }
}
```
Spoon has no *high-level* checkers (like FinalClass, HideUtilityClassConstructor, InnerTypeLast in Checkstyle).

[PVS-Studio](https://www.viva64.com/en/pvs-studio/) is a static analysis tool that uses Spoon as a Java library for analyzing Java source code. Perhaps Checkstyle could use Spoon as an *engine* to overcome current [limitations](https://checkstyle.sourceforge.io/writingchecks.html#Limitations).

I think that you can also use Spoon to write some *deep* Spoon rules to analyze specific problems in Checkstyle Java source code (another words: write a mini static code analyzer for detecting problems in Checkstyle Java source code). However I don't know what would be useful. I use Checkstyle as an ordinary user, I don't develop Checkstyle per se.

**Comment by nmancus1** [comment] 2020-03-21 15:28
@romani Bountysource appears to be back up, but I don't see this issue on there.

**Comment by romani** [comment] 2020-03-21 22:38
@nmancus1 , issue reopened, there should be button "solve issue" , please try again.

**Comment by nmancus1** [comment] 2020-03-22 02:26
Ok! Done.

**Comment by romani** [comment] 2020-03-22 02:33
Please claim bounty

**Closed** 2020-03-22 02:33 UTC
Labels: antlr, approved, has bounty

**Comment by nmancus1** [comment] 2020-03-23 00:02
Claimed! Thanks again.
