### ISSUE TITLE
Two unit tests for SuppressionCommentFilterTest do not fail if CheckstyleException is not thrown

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#5210] opened 2017-10-21 08:25 UTC
https://github.com/checkstyle/checkstyle/blob/d371c3431d076dcb7a5d2565b4ca061c798732f4/src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java#L262-L295

Both testInvalidCheckFormat and testInvalidMessageFormat tests will not fail if exception is not thrown.

fail() method should be invoked after verifySuppressed.

**Comment by rnveach** [comment] 2017-10-23 02:43
I agree with this as I have seen this before.
We might want to think of an automated way to catch these like with a new check.

**Comment by MEZk** [comment] 2017-10-23 15:56
@rnveach 
We can control that each test contains verify, fail, or assert statement.

**Comment by rnveach** [comment] 2017-10-23 17:49
@MEZk Look at the snippet you gave. It does contain an assert statement in the catch. Technically it does contain a verify in the try. The problem is a try/catch needs a fail in the try. For tests there is no need to catch exceptions if they are not examined and should be passed up the chain so the main junit runner gets it.

**Comment by rnveach** [comment] 2017-10-26 20:14
These are the violations produced by the custom check at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/619 : 
````
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java:[140,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java:[155,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java:[170,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java:[186,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/DetailNodeTreeStringPrinterTest.java:[201,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/ThreadModeSettingsTest.java:[68,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java:[200,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java:[271,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java:[293,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/TreeWalkerTest.java:[329,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java:[46,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/api/AutomaticBeanTest.java:[62,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java:[156,17] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/checks/NewlineAtEndOfFileCheckTest.java:[251,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java:[74,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheckTest.java:[89,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheckTest.java:[371,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractTypeAwareCheckTest.java:[79,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AbstractTypeAwareCheckTest.java:[160,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/ClassResolverTest.java:[123,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/checks/javadoc/ClassResolverTest.java:[175,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java:[246,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressWithNearbyCommentFilterTest.java:[282,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java:[264,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionCommentFilterTest.java:[281,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java:[142,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java:[159,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java:[176,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java:[262,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/filters/SuppressionsLoaderTest.java:[283,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/filters/XpathFilterTest.java:[240,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtilityTest.java:[38,9] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.
````

**Comment by rnveach** [comment] 2017-10-26 21:57
> [ERROR] src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java:[156,17] (extension) RequireFailForTryCatchInJunit: try/catch requires a fail at the end of the try clause for junit tests.

https://github.com/checkstyle/checkstyle/blob/b16aef991830dd1fce1ce2640af7e7db8b329d86/src/test/java/com/puppycrawl/tools/checkstyle/api/DetailASTTest.java#L156-L162
This is a false positive because it is inside a lambda and the method throws a checked exception.
If you don't have the catch, it won't compile with the error `Unhandled exception type Exception` because lambdas don't declare any exceptions thrown. You must catch and throw it as an uncaught exception in this case.

**Comment by romani** [comment] 2017-10-27 03:32
fix is merged.

**Closed by romani** 2017-10-27 03:32 UTC
Labels: approved, miscellaneous
