### ISSUE TITLE
Checkstyle 9.0: Expiring Daemon because JVM heap space is exhausted (8.45 works)

### ISSUE THREAD

**Issue by Siedlerchr** [checkstyle/checkstyle#10792] opened 2021-09-09 19:55 UTC
We upgraded to Checkstyle 9.0 and now the Github Ci (linux) runs out of memory:

https://github.com/JabRef/jabref/runs/3560086739

I also tested with increasing the heap space config. But this did not help. Locally on my mac computer it worked
 ```
GRADLE_OPTS: -Xmx4g
JAVA_OPTS: -Xmx4g
```

Workaround: A downgrade to 8.45-1 fixed the problem

**Comment by nmancus1** [comment] 2021-09-10 21:50
@strkk @pbludov what do you think about adding jabref to our no-error testing CI?

**Comment by romani** [comment] 2021-09-11 04:25
Can you share their config?
If they use a lot of checks, then yes, it makes sense.

**Comment by pbludov** [comment] 2021-09-11 06:39
JabRef config is here: https://github.com/JabRef/jabref/tree/main/config/checkstyle

**Comment by nmancus1** [comment] 2021-09-11 12:14
> I have memory issues for checkstyle build on my local machine as well (win10)

@strkkk please share details

**Comment by nmancus1** [comment] 2021-09-11 14:03
Update: jabref checkstyle gradle build only needed about 200M more memory than before to complete successfully (merged PR at https://github.com/JabRef/jabref/pull/8074 increased heap size by 3.5M, but this much was not required). 

If @romani is good with adding jabref to no-error testing, let's make a new issue for that.

**Comment by romani** [comment] 2021-09-11 16:56
I see about 40 modules in their config.

**Comment by strkkk** [comment] 2021-09-12 09:35
> @strkkk please share details

I couldn't reproduce it, it happens from time to time. I think it can be ignored for now, I will add some information next time it happens.

**Comment by romani** [comment] 2021-09-12 16:42
@Siedlerchr , please confirm that you can extend JVM execution on +200mb.

We replaced parsing of java to new implementation. We will not come back. More efficient memory usage might good point to look, but it is less in priority.

@nmancus1 , if you already tested it, can you send PR to such project.

**Comment by nmancus1** [comment] 2021-09-12 16:51
> if you already tested it, can you send PR to such project.

Sent and merged :) But, we ended up increasing heap size more than that per @Siedlerchr

**Comment by romani** [comment] 2021-09-12 20:50
Ok now I see it https://github.com/JabRef/jabref/pull/8074/files

Not that much bigger.
I think issue is resolved.

Yes , we demand more memory from 9.0 .

**Closed by romani** 2021-09-12 20:50 UTC
