### ISSUE TITLE
JavadocStyle isn't supporting {@code} construct

### ISSUE THREAD

**Issue by vmassol** [checkstyle/checkstyle#5482] opened 2018-01-22 15:19 UTC
Example input:

```
/**
 * Maven2 plugin to install one or several extensions into a running XWiki instance. This is useful for example
 * when provisioning an XWiki instance for executing functional tests.
 *
 * Example usage:
 * <p>
 *
 * <pre>{@code
 * <plugin>
 *   <groupId>org.xwiki.platform</groupId>
 *   <artifactId>xwiki-platform-tool-provision-plugin</artifactId>
 *   <version>...version...</version>
 *   <configuration>
 *     <username>Admin</username>
 *     <password>admin</password>
 *     <extensionIds>
 *       <extensionId>
 *         <id>org.xwiki.contrib.markdown:syntax-markdown-markdown12</id>
 *         <version>8.5.1</version>
 *       </extensionId>
 *     </extensionIds>
 *   </configuration>
 *   <executions>
 *     <execution>
 *       <id>install</id>
 *       <goals>
 *         <goal>install</goal>
 *       </goals>
 *     </execution>
 *   </executions>
 * </plugin>
 * }</pre>
 *
 * @version $Id: 659c3caef65105689d888af7b34d17d7e52175fd $
 * @since 10.0RC1
 */
```

Yield:

```
[INFO] --- maven-checkstyle-plugin:3.0.0:check (default) @ xwiki-platform-tool-provision-plugin ---
[INFO] Starting audit...
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:60:33: Extra HTML tag found: </groupId> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:61:54: Extra HTML tag found: </artifactId> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:62:28: Extra HTML tag found: </version> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:64:23: Extra HTML tag found: </username> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:65:23: Extra HTML tag found: </password> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:68:69: Extra HTML tag found: </id> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:69:26: Extra HTML tag found: </version> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:70:10: Extra HTML tag found: </extensionId> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:71:8: Extra HTML tag found: </extensionIds> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:72:6: Extra HTML tag found: </configuration> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:75:21: Extra HTML tag found: </id> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:77:25: Extra HTML tag found: </goal> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:78:10: Extra HTML tag found: </goals> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:79:8: Extra HTML tag found: </execution> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:80:6: Extra HTML tag found: </executions> [JavadocStyle]
[ERROR] /Users/vmassol/dev/xwiki/xwiki-platform/xwiki-platform-tools/xwiki-platform-tool-provision-plugin/src/main/java/org/xwiki/tool/provision/InstallMojo.java:81:4: Extra HTML tag found: </plugin> [JavadocStyle]
Audit done.
[INFO] There are 16 errors reported by Checkstyle 8.7 with checkstyle.xml ruleset.
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[60,33] (javadoc) JavadocStyle: Extra HTML tag found: </groupId>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[61,54] (javadoc) JavadocStyle: Extra HTML tag found: </artifactId>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[62,28] (javadoc) JavadocStyle: Extra HTML tag found: </version>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[64,23] (javadoc) JavadocStyle: Extra HTML tag found: </username>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[65,23] (javadoc) JavadocStyle: Extra HTML tag found: </password>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[68,69] (javadoc) JavadocStyle: Extra HTML tag found: </id>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[69,26] (javadoc) JavadocStyle: Extra HTML tag found: </version>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[70,10] (javadoc) JavadocStyle: Extra HTML tag found: </extensionId>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[71,8] (javadoc) JavadocStyle: Extra HTML tag found: </extensionIds>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[72,6] (javadoc) JavadocStyle: Extra HTML tag found: </configuration>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[75,21] (javadoc) JavadocStyle: Extra HTML tag found: </id>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[77,25] (javadoc) JavadocStyle: Extra HTML tag found: </goal>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[78,10] (javadoc) JavadocStyle: Extra HTML tag found: </goals>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[79,8] (javadoc) JavadocStyle: Extra HTML tag found: </execution>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[80,6] (javadoc) JavadocStyle: Extra HTML tag found: </executions>
[ERROR] src/main/java/org/xwiki/tool/provision/InstallMojo.java:[81,4] (javadoc) JavadocStyle: Extra HTML tag found: </plugin>
```

Something as simple as the following makes checkstyle choke:

```
 * {@code <plugin></plugin>}
```

Thanks!

**Comment by wltan** [comment] 2020-03-08 06:48
Looks like a duplicate of #3351, although this one is easier to find due to having `JavadocStyle` in the title

**Comment by romani** [comment] 2020-03-11 03:55
@wltan , thanks a lot.
Title of other issue is updated.
This issue is closed, as it has no required details.

**Closed by romani** 2020-03-11 03:55 UTC
