### ISSUE TITLE
Redundant checking of file in ant task

### ISSUE THREAD

**Issue by shashwatj07** [checkstyle/checkstyle#8104] opened 2020-04-15 08:38 UTC
```mvn compile antrun:run@ant-phase-verify```
```
main:

execute:
     [echo] Checkstyle started (checkstyle_checks.xml): 15/04/2020 02:04:21 PM
[checkstyle] Running Checkstyle  on 1145 files
[checkstyle] [ERROR] C:\Users\Shashwat\checkstyle\src\it\java\org\checkstyle
\suppressionxpathfilter\XpathRegressionInterfaceMemberImpliedModifierTest.java:1: 
File does not end with a newline. [NewlineAtEndOfFile]
     [echo] Checkstyle finished (checkstyle_checks.xml) : 15/04/2020 02:04:23 PM
     [echo] Checkstyle started (checkstyle_non_main_files_checks.xml): 15/04/2020 
02:04:21 PM
[checkstyle] Running Checkstyle  on 2070 files
[checkstyle] [ERROR] C:\Users\Shashwat\checkstyle\src\it\java\org\checkstyle\
suppressionxpathfilter\XpathRegressionInterfaceMemberImpliedModifierTest.java:1: 
File does not end with a newline. [NewlineAtEndOfFile]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

The same file, namely ```XpathRegressionInterfaceMemberImpliedModifierTest.java``` is being checked for the same violation twice. This is inefficient and redundant.

**Comment by rnveach** [comment] 2020-04-15 22:03
It shouldn't be checking the same file in both configs, but I am not seeing how it is happening.
https://github.com/checkstyle/checkstyle/blob/master/config/ant-phase-verify.xml#L66
https://github.com/checkstyle/checkstyle/blob/master/config/ant-phase-verify.xml#L141

**Comment by rnveach** [comment] 2020-04-15 22:12
non_main run is pulling in full list of files but excluding ones it doesn't want to duplicate.
https://github.com/checkstyle/checkstyle/blob/master/config/ant-phase-verify.xml#L66
We specifically exclude test java but don't do the same for IT java.
https://github.com/checkstyle/checkstyle/blob/master/config/ant-phase-verify.xml#L69

We should update the exclude to do the same and confirm if there are any more duplicates we need to look into.

**Comment by rnveach** [comment] 2020-04-15 23:01
During my own search it seems both are looking at the xdocs too.

`checkstyle_non_main_files_checks` and `checkstyle_resources` seem to be checking the same files and different files, which may be ok, but now I am not fully sure what is the difference between them.   `checkstyle_resources` is not checking `it\resources-noncompilable` or `site\resources`.

**Comment by shashwat70** [comment] 2020-04-16 09:30
- The configs ```checkstyle_non_main_files_checks``` and ```checkstyle_resources_checks``` are absolutely disjoint. So, I guess there is no problem if they check same files.

- ```src\it\java``` needs to be excluded from ```checkstyle_non_main_files_checks```

- Unfortunately, ```checkstyle_resources_checks``` in not checking the following and they need to be added:

    1. ```it\resources-noncompilable```
    2. ```site\resources```
    3. ```main\resources```

I guess that's it.
@rnveach ping :)

**Comment by shashwat70** [comment] 2020-04-16 11:54
I've fixed some stuff to the best of my understanding. I'd be glad if you could please take a look at my PR. @rnveach

**Comment by nmancus1** [comment] 2020-11-14 14:32
>non_main run is pulling in full list of files but excluding ones it doesn't want to duplicate.
https://github.com/checkstyle/checkstyle/blob/master/config/ant-phase-verify.xml#L66
We specifically exclude test java but don't do the same for IT java.
https://github.com/checkstyle/checkstyle/blob/master/config/ant-phase-verify.xml#L69

>checkstyle_checks was for all executable java code (it/main/test java) and main resources.
checkstyle_non_main_files_checks was for resources used as inputs and such.

>We should update the exclude to do the same and confirm if there are any more duplicates we need to look into.

While there is overlap in the files included in different steps of `ant-phase-verify.xml` ,  they are not always being checked for the same violations.  Example:

```
[INFO] Executing tasks
[INFO]      [echo] Checkstyle started (checkstyle_checks.xml): 14/11/2020 07:30:11 AM
[INFO] [checkstyle] Running Checkstyle  on 1384 files
[ERROR] [checkstyle] [ERROR] /home/nick/IdeaProjects/checkstyle/src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAnonInnerLengthTest.java:66: Unnecessary consecutive lines [noConsecutiveLines]
[INFO]      [echo] Checkstyle finished (checkstyle_checks.xml) : 14/11/2020 07:31:33 AM
[INFO]      [echo] Checkstyle started (checkstyle_non_main_files_checks.xml): 14/11/2020 07:30:11 AM
[INFO] [checkstyle] Running Checkstyle  on 2388 files
[ERROR] [checkstyle] [ERROR] /home/nick/IdeaProjects/checkstyle/src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionAnonInnerLengthTest.java:1: Two or more test cases are required for unit testing in Xpath  [numberOfTestCasesInXpath]
```

Much of this overlap then does make sense, since we are checking the entire project for (example) unnecessary consecutive lines, but then only checking UT's for the appropriate amount of test cases.

If we are to move ahead with this issue and/or the existing PR, we need to take a deeper look at the overlapping  coverage, and determine how we will move forward. Also, as discovered by @pbludov at https://github.com/checkstyle/checkstyle/pull/8109#discussion_r422933144 , in the existing PR there is a regression in coverage of at least some files. Due to removing the "overlapping" coverage.

I am not sure how we can prove that we are able to maintain/ improve the coverage of files after "fixing" this issue.  I can continue with the current PR, but it would be good to have some measure of the impact that it will have.

Another consideration:

from master:
```
[INFO] --- maven-antrun-plugin:3.0.0:run (ant-phase-verify) @ checkstyle ---
[INFO] Executing tasks
[INFO]      [echo] Checkstyle started (checkstyle_checks.xml): 14/11/2020 08:38:24 AM
[INFO] [checkstyle] Running Checkstyle  on 1384 files
[INFO]      [echo] Checkstyle finished (checkstyle_checks.xml) : 14/11/2020 08:39:51 AM
[INFO]      [echo] Checkstyle started (checkstyle_non_main_files_checks.xml): 14/11/2020 08:38:24 AM
[INFO] [checkstyle] Running Checkstyle  on 2388 files
[INFO]      [echo] Checkstyle finished (checkstyle_non_main_files_checks.xml): 14/11/2020 08:39:51 AM
[INFO]      [echo]     
[INFO]      [echo] Checkstyle started (checkstyle_resources_checks.xml): 14/11/2020 08:38:24 AM
[INFO] [checkstyle] Running Checkstyle  on 2056 files
[INFO]      [echo] Checkstyle finished (checkstyle_resources_checks.xml): 14/11/2020 08:39:51 AM
[INFO]      [echo] Checkstyle started (checkstyle_input_checks.xml): 14/11/2020 08:38:24 AM
[INFO] [checkstyle] Running Checkstyle  on 1150 files
[INFO]      [echo] Checkstyle finished (checkstyle_input_checks.xml): 14/11/2020 08:39:51 AM
[INFO] Executed tasks
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:50 min
[INFO] Finished at: 2020-11-14T08:40:02-05:00
[INFO] ------------------------------------------------------------------------
```

from current PR, after fixing violations and rebasing:
```
[INFO] --- maven-antrun-plugin:3.0.0:run (ant-phase-verify) @ checkstyle ---
[INFO] Executing tasks
[INFO]      [echo] Checkstyle started (checkstyle_checks.xml): 14/11/2020 09:03:02 AM
[INFO] [checkstyle] Running Checkstyle  on 1384 files
[INFO]      [echo] Checkstyle finished (checkstyle_checks.xml) : 14/11/2020 09:04:24 AM
[INFO]      [echo] Checkstyle started (checkstyle_non_main_files_checks.xml): 14/11/2020 09:03:02 AM
[INFO] [checkstyle] Running Checkstyle  on 91 files
[INFO]      [echo] Checkstyle finished (checkstyle_non_main_files_checks.xml): 14/11/2020 09:04:24 AM
[INFO]      [echo]     
[INFO]      [echo] Checkstyle started (checkstyle_resources_checks.xml): 14/11/2020 09:03:02 AM
[INFO] [checkstyle] Running Checkstyle  on 2071 files
[INFO]      [echo] Checkstyle finished (checkstyle_resources_checks.xml): 14/11/2020 09:04:24 AM
[INFO]      [echo] Checkstyle started (checkstyle_input_checks.xml): 14/11/2020 09:03:02 AM
[INFO] [checkstyle] Running Checkstyle  on 1150 files
[INFO]      [echo] Checkstyle finished (checkstyle_input_checks.xml): 14/11/2020 09:04:24 AM
[INFO] Executed tasks
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:43 min
[INFO] Finished at: 2020-11-14T09:04:34-05:00
[INFO] ------------------------------------------------------------------------

```
The run time is essentially the same.  The `checkstyle_non_main_files_checks.xml` config file is pretty light.  Is this worth pursuing?

**Comment by romani** [comment] 2020-11-14 16:38
@nmancus1 , I do not think it worse it.
resolving missed violation will take significantly more time then what we try to optimize.

We have big overlap in validation by all static tools, BUT we keep all of them as it is ok to get numerous same violation as prove it is required to be fixed.

**Closed** 2020-11-14 16:39 UTC
