### ISSUE TITLE
Resolve Pitest Issues - JavadocMethodCheck (8)

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7980] opened 2020-03-28 16:03 UTC
Child issue of https://github.com/checkstyle/checkstyle/issues/7797 ,

https://github.com/checkstyle/checkstyle/blob/f9131f9536c71d963c83aab1550b7a0371aa9ff5/.ci/pitest.sh#L189

**Comment by gaurabdg** [comment] 2020-03-29 08:57
I am on it

**Comment by gaurabdg** [comment] 2020-03-31 22:23
I am on it

**Comment by gaurabdg** [comment] 2020-04-01 00:32
@rnveach My addition of an UT after analyzing the code logic has solved 3 other issues as well #7923 #7924 #7925 .
How do you want me to go about submitting a PR? Shall I just mention the other 3 in description and this issue in the commit/pr message?

**Comment by rnveach** [comment] 2020-04-01 01:35
@gaurabdg Please post the requested reports when you submit your PR. Reference this PR as the issue number and report to the other issues that your PR solves them. The first to PR gets to finish the issues.

**Comment by gaurabdg** [comment] 2020-04-01 11:42
## 1. Pitest Report:
https://gaurabdg.github.io/checkstyle-tester-reports/pitest/JavadocMethodCheck/com.puppycrawl.tools.checkstyle.checks.javadoc/JavadocMethodCheck.java.html#grouporg.pitest.mutationtest.report.html.SourceFile@45cb5b80_1078
Surviving Mutation:  `negated conditional → SURVIVED`

## 2. Mutated Branch: 

Hardcoded Mutation Commit: https://github.com/gaurabdg/checkstyle/commit/cd24f3b9695a99b55b4cb9eb7a659ea80ebc1d6a

## 3. Regression Report:

https://gaurabdg.github.io/checkstyle-tester-reports/regression/JavadocMethod/diff/index.html

Diff found: 0

## 4. Regression and Code Logic Analysis

will be update asap

**Comment by rnveach** [comment] 2020-04-01 13:05
> This check has been achieved using reflection on createClassInfo in the UT and checking equality of its toString result.

This is a slight concern that we had to use reflection.

Maybe I missed it, but can you explain why we need reflection and can't hit this code naturally? If this can't be hit naturally, then can you also explain why we need the code and shouldn't remove it?

**Comment by gaurabdg** [comment] 2020-04-01 14:35
@rnveach It is being hit naturally when `processTypeParams` is being executed, but I wanted to capture the return value of `createClassInfo` to determine the instance whether it is a `RegularClass` or `ClassAlias`.

**Comment by rnveach** [comment] 2020-04-01 15:15
> I wanted to capture the return value of createClassInfo to determine the instance whether it is a RegularClass or ClassAlias.

Why doesn't a real case help you determine this and it can only be done during reflection? Is this determination needed to kill the mutation or just an extra check? If it is needed to kill the mutation, then this goes back to why do we need this to kill the mutation and we can't create a natural case.

We prefer natural cases instead of having to use reflection and make the test more complicated then it has to be. If reflection must stay, then test has to be documented why reflection is needed.

**Comment by gaurabdg** [comment] 2020-04-01 15:21
@rnveach We cannot check the instance through simple `log`ging. It gets consumed by `ExceptionInfo` and other subsequent method calls and doesn't help to kill the mutation. So, we need to do the checking to kill the mutation at the return value of `createClassInfo`.

I can document why the reflection is needed. On a side note I got the idea of using reflection since it was used to test the `toString` methods of the inner classes in the tests.

**Comment by rnveach** [comment] 2020-04-01 16:53
Ok, I am getting a bit lost.

https://gaurabdg.github.io/checkstyle-tester-reports/pitest/JavadocMethodCheck/com.puppycrawl.tools.checkstyle.checks.javadoc/JavadocMethodCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@45cb5b80_1078
> while (iterator.hasNext()) {

This is the mutation this issue is trying to kill. This has nothing to do with class types, but is checking how many items are in the list. According to the mutation, it sounds like it doesn't care about whats in the list, it will always return `null`. Example, if the list is always populated, negating the condition makes it believe the list is empty. Correct me if my understanding is wrong.

How does this reference back to the type of instance we are creating? I am missing the gap from this search routine to the instance being created.

Why aren't we checking why the list is never empty or we have a type param being searched on that can't be found? Is it the case that these situations can NEVER happen?

> It gets consumed by ExceptionInfo and other subsequent method calls and doesn't help to kill the mutation.

If a normal case, without reflection, can't prove this code is needed as to prevent an exception or some other faulty logic, then what is the benefit in keeping it?

**Comment by gaurabdg** [comment] 2020-04-01 17:51
>How does this reference back to the type of instance we are creating? I am missing the gap from this search routine to the instance being created.
1. At first, with all the default inputs, ` classInfo = paramMap.get(name)` never got a non null result.
2. But when I introduced the chain of type parameter extension in a new input : X extends Comparable , Z extends X, 
it got a non null result from the hashmap
3. `if (classInfo != null)` passed and `break` was executed.
4. So, here we got a non null `classInfo` return.
5. But if we would have negated the `while` condition, we would have got a null classInfo return.
6. So basically we need to **write an UT to check this condition and fail**, so that the **mutation doesn't survive**.
7. Since the return result of `createClassInfo` depends on the return result of `findClassAlias`, we could easily check whether:
a. `RegularClass` is returned if return result of `findClassAlias` was null.
b. `ClassAlias` is returned if return result of `findClassAlias` was non null.
8. Hence, this is being checked in the UT, which kills the mutation.

@ rnveach Hope its clear the link between the while condition, null return and determining the class types.

**Comment by rnveach** [comment] 2020-05-13 20:06
I am sorry for long delay.

> with all the default inputs, classInfo = paramMap.get(name) never got a non null result.

For me, `testGenerics1` is returning some non-null results from `paramMap.get(name)`.

I was able to follow your flow through 7 but it didn't go much after that and dive into why null versus non-null matters after and that is where the reasoning for why we need the code would lie.

As 7a and 7b say, null and non-null seem the difference between `RegularClass` and `ClassAlias`, where `RegularClass` gets the extra this instance. Neither class has any other methods and both extend `ClassInfo` and are essentially final. Once we return `RegularClass` of `ClassAlias` from the method, it is then just passed to `ExceptionInfo` and is only used in it for wrapping a call to `getName`.

Looking at what makes `RegularClass` a bit more special, the instance of the check is not used in any fashion. It is basically worthless. We should remove this code.

After that the difference between `RegularClass` of `ClassAlias` relies on the difference between `surroundingClass` versus `classInfo`. But again, when these values are passed to their respective classes, they are never used and are again pointless and should be removed.

The only thing that matters for `RegularClass` of `ClassAlias` is the variable `name` and returning it from `createClassInfo`. Both of these classes extend the class `ClassInfo`, which can also be a final class and can be passed `name`.

It looks like we can completely remove `createClassInfo` and replace it with `new ClassInfo(name)`. We can also completely remove `findClassAlias`, `RegularClass`, and `ClassAlias` as they will not be used anywhere and just create noise for the code.

**Comment by rnveach** [comment] 2020-05-13 20:11
> It looks like we can completely remove createClassInfo and replace it with new ClassInfo(name). We can also completely remove findClassAlias, RegularClass, and ClassAlias as they will not be used anywhere and just create noise for the code. What makes them unique is discarded and just redundant.

@romani It can be logically proven a big chunck of this code doesn't serve a purpose and can be removed. Are you ok and agree to this? It is possible removing big chunks like this will show other chunks that need to be removed as well and could cascade.

**Comment by romani** [comment] 2020-05-14 04:17
>Are you ok and agree to removing these chunks

I am ok to remove.
I ok to remove any code that we can not cover (we do not know test inputs). Live will show us it in worse case, it is better to make bug to users than hesitate over some code.

**Comment by romani** [comment] 2020-05-19 13:27
fix is merged.

**Closed** 2020-05-19 13:26 UTC
Labels: approved, gsoc third issue
