### ISSUE TITLE
AvoidDoubleBraceInitialization Documentation Link Incorrect

### ISSUE THREAD

**Issue by mttjj** [checkstyle/checkstyle#8215] opened 2020-04-30 20:14 UTC
The [main checks page](https://checkstyle.org/checks.html) links to AvoidDoubleBraceInitialization in the config_misc.html but it actually exists in the config_coding.html. 

Bad link (existing): https://checkstyle.org/config_misc.html#AvoidDoubleBraceInitialization
Good link (correct): https://checkstyle.org/config_coding.html#AvoidDoubleBraceInitialization

I would have opened this issue on the [checkstyle.github.io](https://github.com/checkstyle/checkstyle.github.io/) repo but it doesn't appear that Issues are enabled there. Hopefully it's fine to put this here.

**Comment by Gaurav-Punjabi** [comment] 2020-04-30 20:21
Yes, the links is broken. I'm on it once it's approved.

**Comment by strkkk** [comment] 2020-05-01 06:53
Closed as duplicate of #7889
@mttjj FYI - pr for fix is in review, hopefully link will be fixed in next release

**Closed by strkkk** 2020-05-01 06:53 UTC
