### ISSUE TITLE
Java Linting Fails for switch statements with lamba

### ISSUE THREAD

**Issue by shemachandran** [checkstyle/checkstyle#10580] opened 2021-08-09 02:21 UTC
Linting seems tto be failing for code blocks like shown below. Tried with version 8.45.1 as well
```
private String getStringForString(String abc) {
    return switch (abc) {
            case A, B ->  "c";
            case D -> "d";
        };
```

**Comment by romani** [comment] 2021-08-30 05:02
@shemachandran , please strictly follow issue temple. It will provide all details we need. Your description is not clear.
 In other case issue will be closed.

**Comment by nmancus1** [comment] 2021-11-29 18:37
I am closing this issue, since no further details have been provided. It is likely that this was a duplicate of https://github.com/checkstyle/checkstyle/issues/10866.

**Closed by nmancus1** 2021-11-29 18:37 UTC
