### ISSUE TITLE
Add default config example for ConstantName

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#7564] opened 2020-02-21 23:12 UTC
split from #5832

update AbstractClassName to make examples for all configs shown in documentation
https://checkstyle.org/config_naming.html#ConstantName
this check need default config and example of code that is violates and expect as correct.

See original issues for examples on how to make update.

------------

PLEASE READ https://github.com/checkstyle/checkstyle/wiki/Good-practice-on-how-to-update-examples

**Comment by romani** [comment] 2020-02-21 23:13
@RhnSaxena , please help to resolve.

**Comment by RhnSaxena** [comment] 2020-02-22 03:22
I am on it.

**Comment by romani** [comment] 2020-02-28 14:08
@RhnSaxena  , I placed in description link on how PR should looks like , please do.

**Comment by Vyom-Yadav** [comment] 2020-11-22 07:22
@romani I am on it, would ask if I have any doubt in the process.

**Comment by Vyom-Yadav** [comment] 2020-11-24 08:56
@romani pls review I have made this for default config.
        ```
        <p>
	The following is the default configuration.
	</p>
	<source>
&lt;module name="ConstantName"/&gt;
	</source>
	<p>Code Example:</p>
	<source>
class MyCLass {
  public final static int FIRST_CONSTANT1 = 10; // OK
  protected final static int SECOND_CONSTANT2 = 100; // OK
  final static int third_Constant3 = 1000; // violation, name 'thirdConstant' must
					   // match pattern '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'
  private final static int fourth_Constant4 = 50; // violation, name 'fourthConstant' must match
						  // pattern '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'
	}
	</source>
```

**Comment by Vyom-Yadav** [comment] 2020-11-24 08:59
@romani Pls review once, I have made the changes.
![PR](https://user-images.githubusercontent.com/73882557/100071717-60764080-2e61-11eb-8be3-2a726be6d0c9.PNG)

**Comment by Vyom-Yadav** [comment] 2020-11-24 09:00
@romani I have to just change the XML file and make a commit right?

**Comment by strkkk** [comment] 2020-11-24 09:14
@Vyom-Yadav you need to modify both javadoc and xml. Take a look at merged PRs with similar issues

**Comment by Vyom-Yadav** [comment] 2020-11-24 09:39
@strkkk @romani Made the changes in javadoc also, now is it fine?
![PR!](https://user-images.githubusercontent.com/73882557/100076216-f52f6d00-2e66-11eb-9aca-5cdd305ae42d.PNG)

**Comment by Vyom-Yadav** [comment] 2020-11-24 09:43
@strkkk @romani I made a mistake but will correct it, `// violation, name 'thirdConstant'` but will correct them, is the rest fine?

**Comment by strkkk** [comment] 2020-11-24 09:58
@Vyom-Yadav not quite. Please make sure that build is passing on your local machine `mvn clean verify` and please send PR, it will be easier to provide comments there.

**Comment by Vyom-Yadav** [comment] 2020-11-26 12:52
@strkkk @romani How to make default config in AbstractClassNameCheck? and after that do I have to do some changes in AbstractClassNameCheckTest and AbstarctClassNameCheck XML file? Also the images I uploaded earlier, some changes have to be done there or not? Please I'm very confused. What I mean to say is what all do I have to change?

**Comment by strkkk** [comment] 2020-11-26 13:46
No need to make changes in the code, only javadoc and xml. Default config contains only name of the check, like 
`<module name="SomeCheck"/>`
See https://github.com/checkstyle/checkstyle/pull/8988 for example, there are code examples for default configuration added for other check

**Comment by Vyom-Yadav** [comment] 2020-11-26 16:05
@strkkk @romani I ran the command mvn clean verify
It showed 1 error 
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project checkstyle: There are test failures.

Please refer to E:\checkstyle\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
How do I fix it?

**Comment by Vyom-Yadav** [comment] 2020-11-26 16:14
java.lang.Error: Error was thrown while processing src\main\java\com\puppycrawl\tools\checkstyle\checks\naming\ConstantNameCheck.java
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.examineCheckSection(XdocsJavaDocsTest.java:209)
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.testAllCheckSectionJavaDocs(XdocsJavaDocsTest.java:182)
Caused by: org.opentest4j.AssertionFailedError: 
ConstantName's class-level JavaDoc ==> expected: <

**Comment by Vyom-Yadav** [comment] 2020-11-26 16:26
@strkkk @romani I ran the command mvn clean verify.
It showed one error. How to fix it?
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project checkstyle: There are test failures.

Please refer to E:\checkstyle\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.

[ERROR] testAllCheckSectionJavaDocs  Time elapsed: 2.84 s  <<< ERROR!
java.lang.Error: Error was thrown while processing src\main\java\com\puppycrawl\tools\checkstyle\checks\naming\ConstantNameCheck.java
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.examineCheckSection(XdocsJavaDocsTest.java:209)
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.testAllCheckSectionJavaDocs(XdocsJavaDocsTest.java:182)
Caused by: org.opentest4j.AssertionFailedError: 
ConstantName's class-level JavaDoc ==> expected: <

**Comment by Vyom-Yadav** [comment] 2020-11-27 04:32
I ran the command mvn clean verify, It showed one error, I went through all similar PR's but couldn't find where I am going wrong.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.259 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest
[ERROR] testAllCheckSectionJavaDocs  Time elapsed: 2.259 s  <<< ERROR!
java.lang.Error: Error was thrown while processing src\main\java\com\puppycrawl\tools\checkstyle\checks\naming\ConstantNameCheck.java
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.examineCheckSection(XdocsJavaDocsTest.java:209)
	at com.puppycrawl.tools.checkstyle.internal.XdocsJavaDocsTest.testAllCheckSectionJavaDocs(XdocsJavaDocsTest.java:182)
Caused by: org.opentest4j.AssertionFailedError: 
ConstantName's class-level JavaDoc ==> expected: <

What shall I do to fix this error?

**Comment by Vyom-Yadav** [comment] 2020-11-27 04:33
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project checkstyle: There are test failures.

Please refer to E:\checkstyle\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.

**Comment by Vyom-Yadav** [comment] 2020-11-27 04:43
@strkkk @romani ping

**Comment by Vyom-Yadav** [comment] 2020-11-27 06:53
Also tried the command mvn clean verify -X but I couldn't find where I am going wrong

**Comment by strkkk** [comment] 2020-11-27 08:19
@Vyom-Yadav run your test without maven (as usual junit test), you will see what is expected and actual results are.

Test is failing because contents of javadoc and xml xdoc are different

**Comment by Vyom-Yadav** [comment] 2020-11-27 09:09
@strkkk Yes, I made them the same it showed build success. I Don't have knowledge of Junit but will learn it.

**Comment by romani** [comment] 2020-11-30 07:08
Please run test in your IDE, it will show violation in better form

**Comment by romani** [comment] 2020-12-03 04:45
Fix is merged

**Closed** 2020-12-03 04:44 UTC
Labels: approved, gsoc first issue
