### ISSUE TITLE
TranslationCheck reports duplicate lines in xml report

### ISSUE THREAD

**Issue by Nimfadora** [checkstyle/checkstyle#5103] opened 2017-09-10 21:31 UTC
taken from #5043 

When checking several files with TranslationCheck and generating xml output, check reports duplicate lines with default translation file. Moreover, on different operation systems this line appears in different places.

steps to reproduce:
1) generate properties files with some error, for e.z.:
```
$ cat props/InputTranslationCheckFireErrors.properties 
someKey=Some key
anotherKey=one more
```
and
```
$ cat props/InputTranslationCheckFireErrors_de.properties 
someKey=einige Schlüssel
```
2) generate checkstyle profile, so that there was some absent translation:
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name = "Checker">
    <module name="Translation">
        <property name="requiredTranslations" value="de, ja"/>
        <property name="baseName" value="^InputTranslation.*$"/>
    </module>
</module>
```
3) generate all-jar and run:
`$ java -jar checkstyle-8.3-SNAPSHOT-all.jar -f xml -c /home/valeria/IdeaProjects/contribution/checkstyle-tester/my_check.xml /home/valeria/IdeaProjects/contribution/checkstyle-tester/props/`

4) In report you will see duplicate line:
```
    <file name="/home/valeria/IdeaProjects/contribution/checkstyle-tester/props/InputTranslationCheckFireErrors.properties">
    </file>
```
On windows and linux you will receive such report:
```
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="8.3-SNAPSHOT">
    <file name="/home/valeria/IdeaProjects/contribution/checkstyle-tester/props/InputTranslationCheckFireErrors.properties">
    </file>
    <file name="/home/valeria/IdeaProjects/contribution/checkstyle-tester/props/InputTranslationCheckFireErrors_de.properties">
    </file>
    <file name="/home/valeria/IdeaProjects/contribution/checkstyle-tester/props">
        <error line="0" severity="warning" message="Properties file &apos;InputTranslationCheckFireErrors_ja.properties&apos; is missing." source="com.puppycrawl.tools.checkstyle.checks.TranslationCheck"/>
    </file>
    <file name="/home/valeria/IdeaProjects/contribution/checkstyle-tester/props/InputTranslationCheckFireErrors_de.properties">
        <error line="0" severity="warning" message="Key &apos;anotherKey&apos; missing." source="com.puppycrawl.tools.checkstyle.checks.TranslationCheck"/>
    </file>
    <file name="/home/valeria/IdeaProjects/contribution/checkstyle-tester/props/InputTranslationCheckFireErrors.properties">
    </file>
</checkstyle>
```
on Mac OS line will be in different place:
```
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="8.3-SNAPSHOT">
    <file name="/home/valeria/IdeaProjects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/translation/InputTranslationCheckFireErrors.properties">
    </file>
    <file name="/home/valeria/IdeaProjects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/translation/InputTranslationCheckFireErrors_de.properties">
    </file>
    <file name="/home/valeria/IdeaProjects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/translation">
        <error line="0" severity="error" message="Properties file &apos;InputTranslationCheckFireErrors_ja.properties&apos; is missing." source="com.puppycrawl.tools.checkstyle.checks.TranslationCheck"/>
    </file>
    <file name="/home/valeria/IdeaProjects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/translation/InputTranslationCheckFireErrors.properties">
    </file>
    <file name="/home/valeria/IdeaProjects/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/misc/translation/InputTranslationCheckFireErrors_de.properties">
        <error line="0" severity="error" message="Key &apos;anotherKey&apos; missing." source="com.puppycrawl.tools.checkstyle.checks.TranslationCheck"/>
    </file>
</checkstyle>
```

**Comment by romani** [comment] 2017-09-12 12:40
@Nimfadora , it is not good to open issue with usage on SANPSHOT version, it is unclear how to reproduce.

Here is my steps to reproduce and it looks like problem exists even before your changes in 8.2 release.
```
rivanov@p5510:/var/tmp$ tree props/
props/
├── InputTranslationCheckFireErrors_de.properties
└── InputTranslationCheckFireErrors.properties

0 directories, 2 files

$ java -jar checkstyle-8.2-all.jar -c config.xml -f xml props/ 
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="8.2">
<file name="/var/tmp/props/InputTranslationCheckFireErrors.properties">
</file>
<file name="/var/tmp/props/InputTranslationCheckFireErrors_de.properties">
</file>
<file name="/var/tmp/props">
<error line="0" severity="error" message="Properties file &apos;InputTranslationCheckFireErrors_ja.properties&apos; is missing." source="com.puppycrawl.tools.checkstyle.checks.TranslationCheck"/>
</file>
<file name="props/InputTranslationCheckFireErrors_de.properties">
<error line="0" severity="error" message="Key &apos;anotherKey&apos; missing." source="com.puppycrawl.tools.checkstyle.checks.TranslationCheck"/>
</file>
<file name="props/InputTranslationCheckFireErrors.properties">
</file>
</checkstyle>
Checkstyle ends with 2 errors.
```

if that is true, please update description to use 8.2 release binaries and short name of path.
Attention to my report, looks like duplicates are from different paths (absolute vs relative).

**Comment by rnveach** [comment] 2019-02-27 14:23
Duplicate lines are due to multi-file validation.
See https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/TranslationCheck.java#L459-L467
File must be triggered as started before printing violations for each as we are in the `finishProcessing` phase of the check and files are not normally processed here.

@romani We can check if violations are present before we send the file started event.
If you agree please approve issue.

**Comment by rnveach** [comment] 2019-04-06 13:19
We cannot limit excess file reporting in multi-file mode. Multi-file check can produce violation on any file it has already processed once during `finishProcessing`. We can limit reporting multi-files with no violations, but we can't merge it with the first reporting if there are violations.

> different paths (absolute vs relative).

This is because we call `getPath` on the file instead of `getAbsolutePath`. Translation is creating the file name itself.

**Comment by rnveach** [comment] 2019-04-06 13:21
> Moreover, on different operation systems this line appears in different places.

This is because we deal fully with `Set`s without any hash implementation. `filesAssociatedWithKeys` is a hash map so there is no guarantee of order in this situation and we prefer it that way.
Tests were already fixed to accommodate this.

**Comment by rnveach** [comment] 2019-04-17 11:42
Fix was merged

**Closed by rnveach** 2019-04-17 11:42 UTC
Labels: approved, bug
