### ISSUE TITLE
OneTopLevelClass: Improve data structure efficiency

### ISSUE THREAD

**Issue by wltan** [checkstyle/checkstyle#7812] opened 2020-03-09 15:18 UTC
From https://github.com/checkstyle/checkstyle/pull/7790#discussion_r389439081

In PR #7790 we changed `OneTopLevelClass` to log violations using the DetailAST node itself, rather than just the line number. However that is a very minimal change to the check functionality and was more focused on the changes to unit/integration/regression testing, where we now log the column number as well.

There is a bit of inefficiency in the way this check works. In particular, the problem is that we are using a `TreeMap` to store our (potential) violations. Some observations:
1. Although a `TreeMap` can help us to maintain that the nodes are in the correct order, there is no need to do this as the AST traversal in `beginTree` should already visit all of the nodes in the correct order. As long as we store the nodes in a way that preserves this "traversal order", that is sufficient for our purposes.
2. There is no longer a need to store the type name together with the node, as we can simply derive the type name from the node itself.

Hence, I am suggesting to replace the usage of `SortedMap` and `TreeMap` with a more appropriate data structure such as `Queue<DetailAST>`. This will reduce the runtime of `beginTree` from O(m + n log n) to just O(m) for m nodes and n violations, and also removes the redundant string storage for type name.

Open to more ideas on even better ways to implement this, maybe just use the node given in `finishTree` and traverse it again?

**Comment by strkkk** [comment] 2020-03-10 07:24
It looks like whole check can be rewritten to get rid of internal data structure at all.
For example, it checks every class/interface/enum definition and has internal flag if there already was top level element in this file.
If definition is first - flag is set, all following token checks will report violation.

In my opinion, it will be clearer.

**Comment by wltan** [comment] 2020-03-10 07:39
> It looks like whole check can be rewritten to get rid of internal data structure at all.
> For example, it checks every class/interface/enum definition and has internal flag if there already was top level element in this file.
> If definition is first - flag is set, all following token checks will report violation.
> 
> In my opinion, it will be clearer.

Agreed. It should be possible to just traverse the AST again without needing to store which nodes need to be visited again. The only case I can think of where this would be a bad trade-off is when there are a lot of sibling nodes that are (somehow) not class/interface/enum definitions, which I think is highly unlikely.

Another thing that I'd like to point out is that the current behavior currently ignores *every* public type definition, regardless of how many other public types there are. To illustrate, suppose these are in the same file:
```java
public class Foo1 {} // no violation
public class Foo2 {} // no violation either
```
This isn't really a big problem as the above example isn't even valid (compilable) to begin with, but it seems rather counterintuitive to think that multiple public types causes no violation.

**Comment by rnveach** [comment] 2020-03-10 14:55
This issue should only be about improving check efficiency and should avoid any extra change in behavior of check if possible.

> it seems rather counterintuitive to think that multiple public types causes no violation.
> Checks that each top-level class, interface or enum resides in a source file of its own.

This makes sense to me. I would make it a separate issue.

@wltan If you know how to improve check and want to, feel free to. Regression will need to be provided to show that check behaves the same as before. If you feel this would take to long for GSoC, then I would work on the other issues labeled for GSoC.

**Comment by wltan** [comment] 2020-03-11 04:02
> @wltan If you know how to improve check and want to, feel free to. Regression will need to be provided to show that check behaves the same as before. If you feel this would take to long for GSoC, then I would work on the other issues labeled for GSoC.

Alright, I'll give this a lower priority in favor of the latest pitest issue(s) for now.

**Comment by romani** [comment] 2020-04-03 13:22
fix is merged.

**Closed** 2020-04-03 13:21 UTC
Labels: approved
