### ISSUE TITLE
java 14 pattern Matching for instanceof not supported

### ISSUE THREAD

**Issue by jflefebvre06** [checkstyle/checkstyle#7999] opened 2020-03-30 07:48 UTC
```java
if (x instanceof Integer i) {
    
}
```
Error: `antlr.MismatchedTokenException: expecting RPAREN, found 'i'`

**Comment by strkkk** [comment] 2020-03-30 08:28
Closed as duplicate of https://github.com/checkstyle/checkstyle/issues/7290

**Closed by strkkk** 2020-03-30 08:28 UTC
