### ISSUE TITLE
enforce class package to be the same as folder

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#5930] opened 2018-06-15 07:19 UTC
base on problems at #5916 

for some reason eclipse compiler(eclipse-compiler-javac.sh) with our option do not catch cases when file have package different from folder.
if there is no easy way to make it happen by eclipse compiler, we should do this by Checkstyle Check http://checkstyle.sourceforge.net/config_coding.html#PackageDeclaration
and special execution on all Input files.

**Comment by rnveach** [comment] 2018-06-15 15:59
Exact duplicate of https://github.com/checkstyle/checkstyle/issues/4100 .

Reason for preventing us doing this is at https://github.com/checkstyle/checkstyle/issues/4100#issuecomment-289233550 . Point 2 is the main reason.

**Closed** 2018-06-15 19:07 UTC
Labels: approved
