### ISSUE TITLE
New Check: UnusedVariable

### ISSUE THREAD

**Issue by furstenheim** [checkstyle/checkstyle#7504] opened 2020-01-22 14:44 UTC
I'd like to request an unused variable module. The following should fail:

    public void foo() {
        Integer bar = 1;
        // This should fail since bar is not used
    }
    
Where as:

    public Integer foo() {
        Integer bar = 1;
        return bar
    }
    
Should not since it is used.

Thanks

**Comment by aydinugur** [comment] 2020-02-20 14:03
Agree, this would be useful.

**Comment by eriklansner-blip** [comment] 2020-02-21 16:31
Hello, I would like to work on this issue.

**Comment by rnveach** [comment] 2020-02-21 20:41
@eriklansner-blip If you are new to checkstyle then I would not recommend this issue as a first time. To be able to see if a variable is used or not would require some degree of tracking the variable in the code. There could be name conflicts like a field with the same name, or an anonymous class. It may require some degree of difficulty like the `RequireThisCheck`.

**Comment by romani** [comment] 2020-02-22 02:39
We are welcoming you to make a fix, we will guide you on how to make it and we will assist you.

We just try to warn you in advance that it might be not that easy when it comes to edge cases.

**Comment by eriklansner-blip** [comment] 2020-02-23 15:04
Thank you for the responses. I am part of a student group that has been tasked with resolving an issue on an open-source project. We chose this particular issue and we understand that it will not be that easy. We will give it some amount of hours and we will get back to you with the results.

**Comment by gaurabdg** [comment] 2020-03-08 13:58
If @eriklansner-blip is not working on it, I'd be interested to work on it

**Comment by eriklansner-blip** [comment] 2020-03-08 14:40
sadly we did not solve the issue of shadowing and stopped working on it.

**Comment by gaurabdg** [comment] 2020-03-08 15:44
@rnveach @romani Would you advise me to work on this provided I've completed both the gsoc issue categories?

**Comment by rnveach** [comment] 2020-03-08 18:50
@gaurabdg There is now a 3rd gsoc category if you want to check them out. You are also free to work on multiple issues from any of the categories.

**Comment by gaurabdg** [comment] 2020-03-09 05:03
@rnveach Sure, will check that out.

**Comment by wilcoln** [comment] 2020-03-18 12:42
I'm on it

**Comment by srividyavaishnavi** [comment] 2020-03-31 06:36
I am on it

**Comment by wilcoln** [comment] 2020-03-31 06:38
@srividyavaishnavi  you can't. I claimed it first.

**Comment by SGanguly1999** [comment] 2021-04-18 16:49
I am on it.

**Comment by Vyom-Yadav** [comment] 2021-11-01 05:33
I am on it, will make a check called UnusedLocalVarible

**Comment by nmancus1** [comment] 2021-11-07 17:21
I think that this check should verify usage of pattern variables, since they are just a special case of local variable. Example:

```bash
public class Test {
    void method1(Object o) {
        if (o instanceof String s) { // ok
            System.out.println(s);
        }
        else if(o instanceof Integer i) {  // violation
            System.out.println("not using 'i'!");
        }
        else {
            System.out.println("something else!");
        }
    }
}

```

Read more about pattern variables at https://openjdk.java.net/jeps/394

**Comment by Vyom-Yadav** [comment] 2021-11-21 08:38
@nmancus1 While adding support for pattern variables ( adding support for if-then-else right now, will discuss later adding support for ternary, etc.)  I would need to negate the expression apply de morgans law to an expression to check whether it will exist in else statement.
Examples will explain better-
```
String p,s,n; // instance variables

// inside some method
Object o = 45;
if (!(o instanceof String p && p.equals("sd")) || !p.equals("wq")) {
    p = ""; // local var p not in scope here
}
else if (!(o instanceof Integer s && o instanceof String n)) {
    p = "a"; // local var p in scope here
    s = ""; // local var s not in scope here
    n = ""; // local var n not in scope here
}
else {
    p = "a"; // local var p in scope here
    s = 41; // local var s in scope here
    n = ""; // local var n in scope here
}
```
So to evaluate the scopes of variables I would have to negate the expression apply de morgans law on an expression and obtain that expression in form of an AST.
For something like-
```
!(o instanceof String p && p.equals("sd")) || !p.equals("wq")

--EXPR -> EXPR [82:63]
   `--LOR -> || [82:63]
       |--LNOT -> ! [82:20]
       |   |--LPAREN -> ( [82:21]
       |   |--LAND -> && [82:44]
       |   |   |--LITERAL_INSTANCEOF -> instanceof [82:24]
       |   |   |   |--IDENT -> o [82:22]
       |   |   |   `--PATTERN_VARIABLE_DEF -> PATTERN_VARIABLE_DEF [82:35]
       |   |   |       |--MODIFIERS -> MODIFIERS [82:35]
       |   |   |       |--TYPE -> TYPE [82:35]
       |   |   |       |   `--IDENT -> String [82:35]
       |   |   |       `--IDENT -> p [82:42]
       |   |   `--METHOD_CALL -> ( [82:55]
       |   |       |--DOT -> . [82:48]
       |   |       |   |--IDENT -> p [82:47]
       |   |       |   `--IDENT -> equals [82:49]
       |   |       |--ELIST -> ELIST [82:56]
       |   |       |   `--EXPR -> EXPR [82:56]
       |   |       |       `--STRING_LITERAL -> "sd" [82:56]
       |   |       `--RPAREN -> ) [82:60]
       |   `--RPAREN -> ) [82:61]
       `--LNOT -> ! [82:66]
           `--METHOD_CALL -> ( [82:75]
               |--DOT -> . [82:68]
               |   |--IDENT -> p [82:67]
               |   `--IDENT -> equals [82:69]
               |--ELIST -> ELIST [82:76]
               |   `--EXPR -> EXPR [82:76]
               |       `--STRING_LITERAL -> "wq" [82:76]
               `--RPAREN -> ) [82:80]
```
I would like something like-
```
(o instanceof String p && p.equals("sd")) && p.equals("wq")

--EXPR -> EXPR [82:62]
   `--LAND -> && [82:62]
       |--LPAREN -> ( [82:20]
       |--LAND -> && [82:43]
       |   |--LITERAL_INSTANCEOF -> instanceof [82:23]
       |   |   |--IDENT -> o [82:21]
       |   |   `--PATTERN_VARIABLE_DEF -> PATTERN_VARIABLE_DEF [82:34]
       |   |       |--MODIFIERS -> MODIFIERS [82:34]
       |   |       |--TYPE -> TYPE [82:34]
       |   |       |   `--IDENT -> String [82:34]
       |   |       `--IDENT -> p [82:41]
       |   `--METHOD_CALL -> ( [82:54]
       |       |--DOT -> . [82:47]
       |       |   |--IDENT -> p [82:46]
       |       |   `--IDENT -> equals [82:48]
       |       |--ELIST -> ELIST [82:55]
       |       |   `--EXPR -> EXPR [82:55]
       |       |       `--STRING_LITERAL -> "sd" [82:55]
       |       `--RPAREN -> ) [82:59]
       |--RPAREN -> ) [82:60]
       `--METHOD_CALL -> ( [82:73]
           |--DOT -> . [82:66]
           |   |--IDENT -> p [82:65]
           |   `--IDENT -> equals [82:67]
           |--ELIST -> ELIST [82:74]
           |   `--EXPR -> EXPR [82:74]
           |       `--STRING_LITERAL -> "wq" [82:74]
           `--RPAREN -> ) [82:78]
```
The only option I can see is to take the `EXPR` node and create new nodes according to the logic and add the respective descendants.
Any ideas will be appreciated.

**Comment by nmancus1** [comment] 2021-11-21 13:43
@Vyom-Yadav thanks for your investigation and explanation of nuances of implementing pattern variable support. I think in light of complicated implementation, and recent extension of pattern variables proposed by https://openjdk.java.net/jeps/405 and https://openjdk.java.net/jeps/406, perhaps pattern variables are a special enough case to require their own check.

We should clearly mention this limitation in the documentation (that it does not check pattern variables) for `UnusedLocalVariableCheck`.

@pbludov @strkkk what do you think?

**Comment by rnveach** [comment] 2021-11-21 16:17
> While adding support for pattern variables ( adding support for if-then-else right now, will discuss later adding support for ternary, etc.) I would need to negate the expression apply de morgans law to an expression to check whether it will exist in else statement.

You basically need to track the frames like `RequireThisCheck` to understand if `p` is the first local variable or if it is the pattern variable instead. Also the pattern variable is basically another local variable, so I can see someone wanting it to check those too sometime. You may want to check how `RequireThisCheck` does this.

I think it is better to build the check in small steps and create new issues for the missing functionality. I can see people wanting pattern support.

This also makes me ask if `RequireThisCheck` has the necessary support for for patterns.

**Comment by nmancus1** [comment] 2021-11-21 16:21
> You basically need to track the frames like RequireThisCheck to understand if p is the first local variable or if it is the pattern variable instead.

Support for pattern variables is more complicated than this; the expressions in the conditionals must be evaluated to determine the scope of the variable.

**Comment by rnveach** [comment] 2021-11-21 16:22
> the expressions in the conditionals must be evaluated to determine the scope of the variable.

Which is what `RequireThisCheck` attempts to do with it's "frames". It sees {} as a separate frame and see the distinction between the different scopes.

**Comment by rnveach** [comment] 2021-11-21 16:30
>     p = "a"; // local var p in scope here

Shouldn't this be the instance variable here? The scope of local p expired after the `if`. The same with some of the others.

**Comment by nmancus1** [comment] 2021-11-21 16:33
`if (!(o instanceof String p && p.equals("sd"))....` means that pattern variable `p` is in scope of the else block, since the condition is basically `!(o instanceof String p && p.equals("sd"`).

**Closed** 2022-01-17 19:34 UTC
Labels: approved, new module

**Comment by Vyom-Yadav** [comment] 2022-01-18 05:56
@romani The issue is still valid, there are many more types of variables that can be checked https://docs.oracle.com/javase/specs/jls/se17/html/jls-4.html#jls-4.12.3. Method parameters, constructor parameters, etc.

**Comment by strkkk** [comment] 2022-01-18 09:26
> there are many more types of variables that can be checked

@Vyom-Yadav enhancements can be implemented in separate tickets, no need to make this one big

**Comment by romani** [comment] 2022-01-18 15:12
Parameters are not local variables, should be separate Check or special customization in existing.

**Comment by Vyom-Yadav** [comment] 2022-01-18 15:14
We can extract the core components of the current check and make small checks for parameters, array components, etc.

**Comment by rnveach** [comment] 2022-01-18 16:32
@Vyom-Yadav If you wish to fix up your check, you can also look at https://github.com/checkstyle/checkstyle/pull/11157#issuecomment-1015406885
