### ISSUE TITLE
Resolve Pitest Issues - ImportOrderCheck (6)

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7877] opened 2020-03-16 23:03 UTC
Child issue of https://github.com/checkstyle/checkstyle/issues/7797 ,

https://github.com/checkstyle/checkstyle/blob/abf829f542023e089c741c55f73098cae52dcb12/.ci/pitest.sh#L91

**Comment by yajna-pandith** [comment] 2020-03-17 11:48
I am on it

**Comment by aryaniiit002** [comment] 2021-02-10 09:09
i am on it.

**Comment by bossever** [comment] 2021-02-10 09:43
I am on it.

**Comment by bossever** [comment] 2021-02-12 07:31
I ran 
```
groovy diff.groovy --localGitRepo /home/ayushman/Documents/Development/checkstyle --baseBranch pitestIssue6 --patchBranch mutated --config /home/ayushman/Desktop/Checkstyle\ Experiments/ImportOrder/configs.xml --listOfProjects projects-to-test-on.properties
```
to generate diff report, but I'm getting this error - 
```
Error: file Checkstyle does not exist!
Caught: java.lang.IllegalArgumentException: Error: invalid command line arguments!
java.lang.IllegalArgumentException: Error: invalid command line arguments!
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at launch.run(launch.groovy:13)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caught: groovy.lang.GroovyRuntimeException: Error: !
groovy.lang.GroovyRuntimeException: Error: !
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at diff.executeCmd(diff.groovy:471)
	at diff.executeCmd(diff.groovy:465)
	at diff$executeCmd$10.callCurrent(Unknown Source)
	at diff.generateCheckstyleReport(diff.groovy:217)
	at diff$generateCheckstyleReport$6.callCurrent(Unknown Source)
	at diff.run(diff.groovy:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

I checked my command again and it seems to be correct, any help would be appreciated.

**Comment by strkkk** [comment] 2021-02-12 08:03
@bossever you can create diff report by using github action as described here https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#report-generation
Create a draft PR, add necessary lines in PR description and trigger execution.

P.S. it is better to discuss such issues in gitter or in PR.

**Comment by strkkk** [comment] 2021-02-12 08:12
@bossever you can try to debug diff.groovy file to check what is wrong with arguments.
Also, it is better to discuss such things in gitter or in PR.

**Comment by nmancus1** [comment] 2021-02-12 08:16
@bossever remove the space from your config file's path. It is a good practice not to have spaces in filenames and file paths.

**Comment by bossever** [comment] 2021-02-12 08:27
> @bossever remove the space from your config file's path. It is a good practice not to have spaces in filenames and file paths.

Thanks, that made it work.

**Comment by bossever** [comment] 2021-02-12 17:33
### Pitest Report ###
https://bossever.github.io/issue7877/pit-reports/202102122217/index.html

Surviving mutation on line 878 - `removed conditional - replaced equality check with true → SURVIVED`

**Comment by bossever** [comment] 2021-02-12 18:14
### Pitest Report: 
https://bossever.github.io/issue7877/pit-reports/202102122217/com.puppycrawl.tools.checkstyle.checks.imports/ImportOrderCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@476dda8b_878

### Surviving mutation on line 878:
    removed conditional - replaced equality check with true → SURVIVED
Hardcoded mutation is [here.](https://github.com/bossever/checkstyle/commit/e116864f815bb60275b80ba46faba555d7db065f)

### Diff Report: https://bossever.github.io/issue7877/diff-report/index.html


Config used for diff report: https://gist.github.com/bossever/9af6e0f85a4fdabaedebf3863349fc9f
Let me know if I should add more permutations to the config.

**Comment by bossever** [comment] 2021-02-12 18:19
I have mostly understood how pitest works and what it is meant for, but I am having some trouble understanding how diff regression works. From what I can gather, it runs checkstyle on various projects from two branches (the baseBranch and the patchBranch) and tries to find differences between the output of the two. 
Please correct me if I'm wrong.
Thanks!

**Comment by romani** [comment] 2021-02-12 18:51
You are correct

**Comment by bossever** [comment] 2021-02-15 12:23
I am somehwat confused about the usage of variable `beforeFirstImport` in this method. 
https://github.com/checkstyle/checkstyle/blob/9c53648515ba2208ca50c7078fc059328424ee3e/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L877-L879

The Javadoc description for it is - 
https://github.com/checkstyle/checkstyle/blob/9c53648515ba2208ca50c7078fc059328424ee3e/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L601-L602
This would imply that it is true whenever there were any imports at all. 
However, the variable name seems to mean something else - `before` `First` `Import`
I tried to understand the variable by looking at its usage, but I couldn't get it, any help would be appreciated.
After understanding it, I think I could come up with a test case where the mutation can be killed.

**Comment by rnveach** [comment] 2021-02-16 08:21
Like the variable says, it defines whether we are at or before the first import. The variable is true when we begin any new AST tree and only becomes false after we complete our first visit and examine an import statement.

**Comment by bossever** [comment] 2021-02-16 09:31
Thanks, that made it clear!

**Comment by bossever** [comment] 2021-02-18 13:00
After a lot of thought, I believe that this particular mutation cannot be killed. I have explained why below.
The method at which mutation occurred returns whether there is a seperator before current import. It calculates this using current line number and the line number of the last import. It is only called once, inside `isSeperatorInGroup` to check whether there is an unnecessary seperator in an import group.

https://github.com/checkstyle/checkstyle/blob/9c53648515ba2208ca50c7078fc059328424ee3e/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L877-L879

When `!beforeFirstImport` is changed to `true` by pitest, the return statement is efectively reduced to 
```java
    return line - lastImportLine > 1; 
```

I could create a UT in two ways -

## Case 1: 

`$ cat Test.java`
```java
import java.util.HashMap;
// Unnecessary seperator
import java.util.LinkedList;

public class Test {}
```

Expected violation: `Extra separation in import group before 'java.io.IOException'`
Actual violation: `null`

For this, I would need the method `isSeparatorBeforeImport` to return `false`, which is only possible when `line - lastImportLine > 1` is false, which is clearly not the case. So case 1 will not work.

## Case 2:

`$ cat Test.java`
```java
import java.util.HashMap;
import java.util.LinkedList;

public class Test {}
```

Expected violation: `null`
Actual violation: `Extra separation in import group before 'java.io.IOException'`

This would require `line - lastImportLine > 1` to be true, which is again, not possible for this test file. So case 2 will also not work.

I think `!beforeFirstImport` cannot be removed either because that would break the logic of the method. I have not tested this with non-default configuration of check, because in all possible configurations, extra seperator in import group will always produce violation.
I request admins to have a look and let me know if I have missed anything.
@romani @strkkk @nmancus1

**Comment by nmancus1** [comment] 2021-02-18 13:15
@bossever consider:

```bash
➜  checkstyle git:(master) ✗ grep -iR "beforeFirstImport" **/ImportOrderCheckTest.java
➜  checkstyle git:(master) ✗ 
```

There appear to be no UT's that use this property (setting it to true), which is probably why this mutation is surviving.

**Comment by nmancus1** [comment] 2021-02-18 13:23
> `Extra separation in import group before 'java.io.IOException'`

I do not see this import in your example.

**Comment by bossever** [comment] 2021-02-18 13:25
> I do not see this import in your example.

Ah, looks like I forgot to change the violation message appropriately, will change now.

**Comment by nmancus1** [comment] 2021-02-18 14:11
@bossever it looks like a lot of refactoring around this method happened at 9e24cf14dd2bab5c2e29cfd010ba28cfb496a197 ,  and checking `!beforeFirstImport` in this  method might be unnecessary now.  Please submit a PR to remove this condition.  Make sure to link to all of your research in the PR description.

**Comment by bossever** [comment] 2021-02-18 15:29
@nmancus1 If I remove `!beforeFirstImport`, the method's return value will be entirely dependent on `line - lastImportLine > 1`. But, this method is called before `lastImportLine` is actually assigned a line number. (It is initialized with `Integer.MIN_VALUE`). Wouldn't that result in unexpected behaviour?

**Comment by nmancus1** [comment] 2021-02-18 15:35
> Wouldn't that result in unexpected behaviour?

No, this is what pitest is telling you; no existing test inputs are hitting this code such that mutating `!beforeFirstImport` to `true` is failing. We must either find a test case where this mutation fails (then the mutation is "killed"), or remove this condition, since it isn't doing us any good right now.

**Comment by bossever** [comment] 2021-02-18 15:51
`mvn clean verify` is indeed passing, but I can't understand the behind the scenes. This in particular - 
> But, this method is called before `lastImportLine` is actually assigned a line number. (It is initialized with `Integer.MIN_VALUE`).

**Comment by nmancus1** [comment] 2021-02-18 16:26
> Is it so that removal of the condition is the only other option?

You have two options, as stated above:

1. Find a test case that depends on this condition.
2. Remove the condition.

In order to find test cases, we usually look to the regression report (which is clean in this case, so no help there) or think of some way to hit the code otherwise (with real input, not reflection, etc. in this case).  It is good to think about it logically; is there ever a case where the result of this method does not solely depend on `line - lastImportLine > 1` when `beforeFirstImport` is true?

**Comment by bossever** [comment] 2021-02-18 17:17
Hmm okay, I don't think I can come up with a test case that can kill the mutation, so I will remove this condition now.

**Comment by strkkk** [comment] 2021-02-21 08:05
fix is merged

**Closed** 2021-02-21 08:04 UTC
Labels: approved, gsoc third issue
