### ISSUE TITLE
Tests fail with German locale on Windows with default encoding

### ISSUE THREAD

**Issue by Vampire** [checkstyle/checkstyle#6560] opened 2019-03-11 10:23 UTC
Followup of #6511

CS tests fail with German locale on Windows with default encoding due to encoding problems.
CI with German locale is most probably passing because it is run on Linux where default encoding is `UTF-8`.

When I run `mvn clean test -DargLine='-Duser.language=de -Duser.country=DE -Dfile.encoding=Cp1252' -Dtest=com.puppycrawl.tools.checkstyle.DefaultLoggerTest#testAddError` on the latest master, I get errors like:
![grafik](https://user-images.githubusercontent.com/325196/54116819-dc132e00-43ef-11e9-9789-7e16a8293691.png)

Using the checkstyle all jar, it always outputs in `UTF-8` which might be fine in a generated file, but is bad on the commandline.
![grafik](https://user-images.githubusercontent.com/325196/54125573-aed17a80-4405-11e9-9f78-aa4b25c3e995.png)
(the prompt is Cygwin, but looks the same in `cmd.exe`, I just tried)

Default encoding for Windows in most western european locales is Cp1252, so is it here.

I propose to run the tests by default with `en_US.UTF-8` locale, for better build reproducability and test stability.

**Comment by rnveach** [comment] 2019-03-11 11:42
@Vampire http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug.3F
Do you get same problem with released all JAR? https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-8.18
If so, then this is a problem loading our messages files and could be affected by non-developers too.

**Comment by Vampire** [comment] 2019-03-11 12:50
Are you aware that I'm still talking about the Checkstyle tests, not using Checkstyle on a different project?
Default encoding for Windows in most western european locales is `Cp1252`, so is it here.
If you check out CS sources on latest `master` and do `mvn test -Duser.language=de -Duser.country=DE -Dfile.encoding=Cp1252 -Dtest=com.puppycrawl.tools.checkstyle.DefaultLoggerTest#testAddError`, you will get the same test failure as in the screenshot.

**Comment by Vampire** [comment] 2019-03-11 12:58
Hm, well, actually it also works sub-optimal when using checkstyle, it always outputs in `UTF-8` which might be fine in a generated file, but is bad on the commandline.
![grafik](https://user-images.githubusercontent.com/325196/54125573-aed17a80-4405-11e9-9f78-aa4b25c3e995.png)
(Don't wonder about the prompt, it is Cygwin, but looks the same in `cmd.exe`, I just tried)

**Comment by rnveach** [comment] 2019-03-11 13:30
> Are you aware that I'm still talking about the Checkstyle tests, not using Checkstyle on a different project?

Yes I am aware. I am trying to ascertain if it is a problem with only developers or if users would be impacted too. The change in your PR is only a fix for developers as it in the pom and the all jar won't be able to use that fix. It is a band-aid that is not fixing the underlying problem. We shouldn't be loading our own file as `Cp1252` or anything else if we store it as `UTF-8`.

> System.getProperty("file.encoding")

My windows default file encoding is `UTF-8`.

> If you check out CS sources on latest master and do mvn test -Duser.language=de -Duser.country=DE -Dfile.encoding=Cp1252 -Dtest=com.puppycrawl.tools.checkstyle.DefaultLoggerTest#testAddError, you will get the same test failure as in the screenshot.

The command is slightly wrong.
When I run `mvn clean test -DargLine='-Duser.language=de -Duser.country=DE -Dfile.encoding=Cp1252' -Dtest=com.puppycrawl.tools.checkstyle.DefaultLoggerTest#testAddError` I got the expected error on a linux machine too. (I haven't gotten `argLine` to work on windows yet)
````
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ checkstyle ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.puppycrawl.tools.checkstyle.DefaultLoggerTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.132 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.DefaultLoggerTest
[ERROR] testAddError(com.puppycrawl.tools.checkstyle.DefaultLoggerTest)  Time elapsed: 0.027 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected output expected:<Beginne Pr[?fung...
Pr?]fung beendet.
> but was:<Beginne Pr[??fung...
Pr??]fung beendet.
>
	at com.puppycrawl.tools.checkstyle.DefaultLoggerTest.testAddError(DefaultLoggerTest.java:129)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DefaultLoggerTest.testAddError:129 expected output expected:<Beginne Pr[?fung...
Pr?]fung beendet.
> but was:<Beginne Pr[??fung...
Pr??]fung beendet.
>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
````

I agree this is an issue that should be fixed.

**Comment by Vampire** [comment] 2019-03-11 13:44
> Yes I am aware. I am trying to ascertain if it is a problem with only developers or if users would be impacted too. The change in your PR is only a fix for developers as it in the pom and the all jar won't be able to use that fix. It is a band-aid that is not fixing the underlying problem. We shouldn't be loading our own file as `Cp1252` or anything else if we store it as `UTF-8`.

The file is not loaded in the wrong encoding I think, it is just unconditionally output as `UTF-8`.
The test then reads in the file with the platform default encoding and compares it to the internal `UTF-8` version.
So the question is whether it should be output in the system default encoding and under which conditions.
If you e. g. output `plain` to an `-o` file, it is probably ok to output `UTF-8`.
If you output `xml` it is probably ok to output `UTF-8` as long as the XML header specifies `UTF-8` or nothing (it does specify `UTF-8`, but `UTF-8` is also the specified default for `XML` if nothing is specified in the file).
So the question is more when to output what encoding.
My change assumes that the output encoding is like intended and fixes the test accordingly.
Maybe this could be fixed with my PR and a separate issue should be opened that specifies when to output what encoding if it is not like intended?

> The command is slightly wrong. I am told I have to use `argLine`.
> When I run `mvn clean test -DargLine='-Duser.language=de -Duser.country=DE -Dfile.encoding=Cp1252' -Dtest=com.puppycrawl.tools.checkstyle.DefaultLoggerTest#testAddError` I got the expected error on a linux machine. (I haven't gotten `argLine` to work on windows yet)

Ah, right, sorry. Yes, with `mvn test -DargLine="-Duser.language=de -Duser.country=DE -Dfile.encoding=UTF-8" -Dtest=com.puppycrawl.tools.checkstyle.DefaultLoggerTest#testAddError` on latest `master` it works for me, not with the separate `-D` options.

**Comment by rnveach** [comment] 2019-03-11 14:26
> The file is not loaded in the wrong encoding I think

I agree.
I got the failure working in Eclipse on windows. The assertion fails because of the same reason.
In `DefaultLoggerTest.testAddError`, `infoStream.toString()` prints the bad characters while `auditStartMessage.getMessage()` (which is the loaded message) prints fine.

I haven't determined the final issue but I believe it might be related to `DefaultLogger` and `PrintWriter`.
I can write the message directly to `ByteArrayOutputStream` and it comes out correctly, so whatever we are giving through `PrintWriter` is being mangled.
If it is `DefaultLogger` then it can be affecting the users somehow.

> Maybe this could be fixed with my PR and a separate issue should be opened that specifies when to output what encoding if it is not like intended?

I am just commenting on the issue, @romani decides what should be done.
I feel we should fix the issue and not apply the band-aid if can ascertain the exact issue.

**Comment by rnveach** [comment] 2019-03-11 20:46
This is the bare minimum code needed to reproduce the issue in `DefaultLoggerTest`:
````
    @Test
    public void test() throws IOException {
        final OutputStream infoStream = new ByteArrayOutputStream2();
        final OutputStreamWriter osw = new OutputStreamWriter(infoStream, StandardCharsets.UTF_8);
        osw.write(auditStartMessage.getMessage());
        osw.flush();
        osw.close();

        assertEquals(auditStartMessage.getMessage(), infoStream.toString());
    }
````

Converting it to `PrintWriter` solves the issue except for the test `testCtor` which fails on the call `errorStream.toString(StandardCharsets.UTF_8.name())`.

**Comment by Vampire** [comment] 2019-03-12 00:50
The "bare minimum" you show is just the typical problem with encodings.
You write to a collection of bytes (stream, channel, array, file, whatever) in one encoding (in your example `UTF-8`) and read from it in a different encoding (in your example the platform default encoding as `ByteArrayOutputStream#toString()` uses `new String(byte[], int, int)` without specifying the encoding explicitly; it will work properly on a system that has `UTF-8` as `file.encoding` and potentially fail on others, depending on the characters used.

And yes, `PrintWriter` is not using `UTF-8` if you don't tell it to. Basically all classes that convert characters to bytes or vice-versa like `OutputStreamWriter`, `InputStreamReader` and all others, among them `PrintWriter` if you give it an `OutputStream` as it then creates an `OutputStreamWriter` around it use the system default encoding if you don't specify an encoding explicitly.

One of the few exceptions is `Properties#load(InputStream)` and `Properties#store(OutputStream)` which use ISO-8859-1 encoding with unicode escapes.

**Comment by romani** [comment] 2019-03-16 14:20
Unfortunately I am not a windows person for many years. I agree that we should address ease of checkstyle build by Europe localized Win OS. But this should not happen in expense of cases when encoding is set correctly (looks like in linux). 
Please do not forget to update our Windows CI to verify that German people continue to have no problems.

If no good solution can be made ... probably we can print message from unit tests that execution is detected to happen from non UTF-8 and tests might fail, please use extra arguments for execution or ....

I am not placing "approved" label, only to make sure we endup with some plan on how to fix this issue.

**Comment by rnveach** [comment] 2019-03-16 17:56
@romani I squashed most of the comments.

My suggestion for a fix is at https://github.com/checkstyle/checkstyle/issues/6560#issuecomment-471506358 , converting `OutputStreamWriter` to `PrintWriter` in `DefaultLogger`. This ensures we print our messages exactly how we loaded them and we are saving and loading them as UTF-8.

**Comment by Vampire** [comment] 2019-03-18 20:47
I don't know how this should change a thing.
Both `OutputStreamWriter` and `PrintWriter` are writers.
So both need an encoding specified.
And for both if you don't specify one explicitly, you get the system default encoding.
Also this is not the problem at all.

In the two tests you see in the screenshot above for example you use the `DefaultLogger` to write into two `ByteArrayOutputStream` and it does so with `UTF-8` encoding. But to verify it you use `ByteArrayOutputStream.toString()` which uses `new String(buf, 0, count)` which again uses the system default encoding to transform the pile-o-bytes into a pile-o-characters. If the test instead would use `ByteArrayOutputStream.toString(String)` specifying `UTF-8`, the test would be green, no matter what the system default encoding is.

My intention to set the locale to `en_US.UTF-8`, besides that it also fixes the test, was to improve test reliability and reproducability.
If you e. g. have a failing test on CI and then try to run the same test locally and get totally different results because the locale is different, this can be very confusing and time-consuming to find out.
Because of that I like it very much if tests run the same, no matter where you run them and if different locales should be tested, they should be tested explicitly and the same, no matter where the tests are run.

If you don't like this, fine, we can also instead fix those tests to use the proper `toString(String)` method if the output should be in `UTF-8`, or fix the output so that it is in the system default encoding. Whatever you like better.

The main thing to decide is still what I asked about above.
When should which encoding be output.
- text to the console
- text to an output file
- text to a pipe
- xml to the console
- xml to an output file
- xml to a pipe
- ...

**Comment by Vampire** [comment] 2019-03-18 20:53
Actually we could also fix the tests in this or a separate issue and you could use this or a separate issue to discuss when to output which encoding and how to do it properly.

**Comment by Vampire** [comment] 2019-03-18 22:29
Assuming the current behavior is intended, https://github.com/Vampire/checkstyle/commit/99bfd992acf5a7c40e1aba01e9b4bf1c5ab02f07 would fix the tests that expect the output in the wrong encoding.

**Comment by romani** [comment] 2019-04-29 02:13
@Vampire , we have encoding problem even with your name https://checkstyle.org/releasenotes.html#Release_8.20 , can you help us resolve it ?
We use release notes generation , result is at https://travis-ci.org/checkstyle/checkstyle/jobs/525368324 sources are at 
https://github.com/checkstyle/contribution/tree/master/releasenotes-builder

**Comment by rnveach** [comment] 2019-04-29 12:19
@romani Do you have a preference on this issue, what has been said, and how it should be handled to get it either approved or closed?

**Comment by Vampire** [comment] 2019-05-02 02:02
And besides that, did you now resolve the release notes issue? Because on the website it is still wrong.

**Comment by Vampire** [comment] 2019-05-02 02:03
For the 8.20 release that is. For the previous releases it is fine.

**Comment by romani** [comment] 2019-05-11 18:57
>  did you now resolve the release notes issue?

I will try to be more accurate next release.

> Because on the website it is still wrong.

please send PR to fix at 
https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/releasenotes.xml#L47

**Comment by Vampire** [comment] 2019-05-12 01:24
Sure, here you have it: #6748

**Comment by tobiasbaum** [comment] 2020-08-01 09:16
I also noticed this problem (i.e., some unit tests fail when -Dfile.encoding is not set to UTF-8). It would be great if the build would run out of the box.

Some further observations of mine for the records: Several test classes are failing, of which I had a deeper look at MainTest.java. As stated in the earlier comments, the problem here is that DefaultLogger always writes its results in UTF-8, but the test assumes the default encoding. I see three ways to fix this:
1. Let DefaultLogger use the default encoding by removing "StandardCharsets.UTF_8" when constructing infoWriter and errorWriter in the constructor of DefaultLogger
2. Correct the encoding used by the test cases. In this case, this seems to be not that easy, because the tests use "@SysOut Capturable" from org.itsallcode.junit.sysextensions, which currently neither allows to specify the encoding nor to get the raw written bytes. (Another, hacky, way would be to change the expected string to have a broken encoding, too)
3. Leave the code as it is and change the Maven build to explicitly set the UTF-8 encoding for the unit tests.

Although I would consider 1 the "correct" fix at least in this case, I consider 3 to be preferable because it is less risky. I'll create a for it PR shortly if I don't hear to the contrary.

**Comment by tobiasbaum** [comment] 2020-08-01 14:04
The PR is https://github.com/checkstyle/checkstyle/pull/8585 

Somehow I overlooked that this issue hasn't been approved yet, could you please approve it? This seems to be the reason why the Travis build is failing.

**Comment by strkkk** [comment] 2020-08-02 16:01
fix is merged

**Closed by strkkk** 2020-08-02 16:01 UTC
Labels: approved
