### ISSUE TITLE
New Check: UnnecessarySemicolon

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#6752] opened 2019-05-13 08:01 UTC
Semicolon is not necessary in some places (code block end, last resource declaration, some enums)
I thought checkstyle already had some check for it, but looks like it is not (or I missed something). There is an EmptyStatementCheck but cases below are not empty statements and therefore ignored by this check.
```
$ cat Test.java
import java.io.*;

public class TestClass {
   {/*init block*/}; // violation
   static {}; // violation
   TestClass(){}; // violation
   class A{}; // violation
   void method(){}; // violation
   void method2() throws IOException {
       try(
           OutputStream s = new PipedOutputStream(); // violation
       ){}
   }
   interface aa{}; //violation
    enum aa1{
        A,B; //violation, if no more statements in enum body, semicolon is unnecessary
    };
}; // violation

$ cat conf.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
       <module name="UnnecessarySemicolon" />
    </module>
</module>

$ java -jar checkstyle-8.20-all.jar -c conf.xml Test.java
Starting audit...
Audit done.

```

I would like to try to implement this check if this issue will be approved.

UPDATE: There is no ability to Change existing EmptyStatementCheck, name of Check is critical API point. Additionally it is better to keep Checks to address single target.

**Comment by romani** [comment] 2019-05-19 17:21
@strkkk , I updated description and title.

@rnveach , I am ok to have such Check(s), for now I do not see what properties it might need.
Ateention to `OutputStream s = new PipedOutputStream(); // violation` as it is well known questionable point .... is it statement or expression ? 
All other cases looks like `;` after block `{}`. It kind of already give us a hint that items are too different and it is better to have separate Checks for this as configuration (`tokens`) will be more clear for users.

@rnveach  and @pbludov , please share your opinion  on design (one Check or two). I am in favor of two (UnnecessarySemicolonAfterBlock, UnnecessarySemicolonInTryWithResources).

UnnecessarySemicolonInTryWithResources - might end up with more properties to support modes or singleline and multiline. In multiline mode it is better to keep trailling semicolon, as it become the same trailing comma in arrays.

**Comment by strkkk** [comment] 2019-05-19 18:14
@romani thank you.

Maybe try-with-resources case can be ignored with a property for this check

**Comment by pbludov** [comment] 2019-05-19 20:22
> please share your opinion on design (one Check or two)

... or even more. IDEA inspection `unnecessary semicolon` has an exception for enum constants:
```
enum Nothing {
  A,B
}
enum Comma {
  A,B,
}
enum Semicolon {
  A,B;
}
```
All three cases are valid. Let's also exclude enum constants from the check.

**Comment by romani** [comment] 2019-05-19 20:56
Problem is that try-with-resources are completely different different from `{. };` in our experience decide to make over smart Checks result in problems to maintain and define non conflicting configuration.

I do understand that two separate Checks are a bit more work at the beginning, but long run it will be more beneficial. Life show us that user come with interesting usecase. And I already predict issue with extra semicolon in try-with-resources. I will not be very surprised is somebody come up to as with proposal to ignore some cases of extra ';' after `{}`.

**Comment by strkkk** [comment] 2019-05-20 09:34
@romani ok, sounds very reasonable.
So examples for this check:
```
public class InputUnnecessarySemicolon {

    {/*init block*/}; // violation

    static {}; // violation

    InputUnnecessarySemicolon(){}; // violation

    class A{}; // violation

    void method(){}; // violation

    interface aa{}; //violation

    enum aa1{}; // violation

    @interface anno {}; // violation

}; // violation
```

And following things ignored:
```
public abstract class InputUnnecessarySemicolonEmptyStatements {

    void ignoreMethodEmptyStatements(boolean cond){
      // all below is ignored, these are empty statements
        while(cond){};
        if(cond){};
        if(cond){};
        if(cond); else {};
        for(;cond;){};
        {};
        ;
    }

    void ignoreTryWithResources() {
        try(Reader r1 = new PipedReader();
            Reader r2 = new PipedReader();  // ignored
        ){}
        catch (IOException e) {}
    }

    enum ignoreEnumConstants{
        A,B; // ignored
    }
}
```

**Comment by rnveach** [comment] 2019-05-20 11:30
> please share your opinion on design (one Check or two).

I am fine with multiple checks. Looks like we are up to 3.

> UnnecessarySemicolonAfterBlock, UnnecessarySemicolonInTryWithResources

What about naming this all "UnnecessarySemicolonIn" so they follow a pattern?
UnnecessarySemicolonInObjectDefinition, UnnecessarySemicolonInTryWithResource, UnnecessarySemicolonInEnumeration, etc...

**Comment by strkkk** [comment] 2019-05-22 12:55
@romani are you ok with 3 checks:
- UnnecessarySemicolonInObjectBlock
- UnnecessarySemicolonInTryWithResources
- UnnecessarySemicolonInEnumeration

**Comment by romani** [comment] 2019-05-22 15:51
Yes, agree on split.
Let's close this issue and create 3 new issues with good summary of expected behavior, config design, examples for final approval.

>And following things ignored .. ignoreMethodEmptyStatements

I think it should be controlled by 'target' property of this Check, but this Check should detect such unnecessary semicolon.

**Comment by strkkk** [comment] 2019-05-22 17:16
@romani 
> I think it should be controlled by 'target' property of this Check, but this Check should detect such unnecessary semicolon.

If this check will detect these semicolons, it will duplicate functionality of EmptyStatementCheck. Are you sure it is necessary?

I listed this cases only to demonstrate difference between empty statements and useless semicolons after code blocks.

**Comment by romani** [comment] 2019-05-22 19:15
> If this check will detect these semicolons, it will fully duplicate functionality of EmptyStatementCheck. Are you sure it is necessary?

good reason, but lets mention this in documentation of new Check, as they are similar, it is not very obvious.

**Comment by strkkk** [comment] 2019-05-23 07:01
@romani there is another thing - if name of the check is `UnnecessarySemicolonInObjectBlock` and it will detect semicolons that are empty statements, valid cases like
```
void method(){
; // empty statement
}
```
can be confusing because there is no object block to put semi after

**Comment by strkkk** [comment] 2019-05-23 07:29
@romani  I created issues for each type of check, please take a look and approve if OK.

**Comment by romani** [comment] 2019-05-25 19:44
discussion was moved to outbound issues.

**Closed by romani** 2019-05-25 19:44 UTC
