### ISSUE TITLE
Checkstyle crashes when for loop without braces has if with braces

### ISSUE THREAD

**Issue by mareksabo** [checkstyle/checkstyle#5296] opened 2017-11-25 09:49 UTC
Hello,

I would like to inform you that the following code causes checkstyle to crash:

```java
class Demo {
    public static void main(String[] args) {
        for (int i = 0; i < 5; i++)
            if (1 < 2) {
                System.out.println("Multiple line if block");
            }
    }
}
```
It happens when an `for` loop without braces contains nested `if` with curly braces inside.

The error output is obviously not suprising:

```
[[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project seminar-project: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed. NullPointerException -> [Help 1]
```

Although I can agree that the code above is not nice at all, it is definitely a bug.
I can agree that the best way to avoid it is to to not write code like this at all, but our students sometimes write code like this and then they have surely no idea why the build is failing.

I hope it is an easy fix and could be resolved!

Thank you,

Marek

**Comment by rnveach** [comment] 2017-11-25 14:00
@mareksabo Please see http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug .
We need your configuration to be able to reproduce the issue.

**Comment by mareksabo** [comment] 2017-11-26 15:43
@rnveach Thank you for your quick response.
I totally forgot that, my bad (I read the notes quite quickly).

checkstyle version: 2.17

I extracted only the important part from the config file (I checked that it is still failing).
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">

    <module name="TreeWalker">

        <module name="NeedBraces">
            <property name="allowSingleLineStatement" value="true"/>
        </module>
    </module>
</module>
```

**Comment by romani** [comment] 2017-11-26 15:51
@mareksabo ,

I closing issue as invalid.

Format HAS to be like we demand - https://github.com/checkstyle/checkstyle/blob/master/.github/ISSUE_TEMPLATE.md , it helps to avoid multiple unnecessary conversations and ....

**Closed by romani** 2017-11-26 15:51 UTC

**Comment by mareksabo** [comment] 2017-11-26 18:30
`/var/tmp $ javac Demo.java`:

```
(nothing)
```

`/var/tmp $ cat Demo.java`:

```
public class Demo {
    public static void main(String[] args) {
        for (int i = 0; i < 5; i++)
            if (1 < 2) {
                System.out.println("Multiple line if block");
            }
    }
}
```

`/var/tmp $ cat config.xml`:

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">

    <module name="TreeWalker">

        <module name="NeedBraces">
            <property name="allowSingleLineStatement" value="true"/>
        </module>
    </module>
</module>
```

`/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-X.X-all.jar -c config.xml Demo.java`:

Well, I am not using jar, I am using **maven**.
I already reported that to maven-checkstyle-plugin, and they forwarded me here.
[https://issues.apache.org/jira/browse/MCHECKSTYLE-345](https://issues.apache.org/jira/browse/MCHECKSTYLE-345)

---------------
So, back to the problem.
When I try to build it using maven with the following `pom.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>temp</groupId>
    <artifactId>temp</artifactId>
    <version>1.0-SNAPSHOT</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>2.17</version>

                <executions>
                    <execution>
                        <id>validate</id>
                        <phase>validate</phase>
                        <configuration>
                            <configLocation>config.xml</configLocation>
                        </configuration>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

`/var/tmp $ mvn clean install -e`

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building temp 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ temp ---
[INFO] Deleting /home/mrek/temp/temp/target
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (validate) @ temp ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.973 s
[INFO] Finished at: 2017-11-26T19:17:50+01:00
[INFO] Final Memory: 13M/255M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project temp: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project temp: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck.isSingleLineFor(NeedBracesCheck.java:286)
        at com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck.isSingleLineStatement(NeedBracesCheck.java:203)
        at com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck.isSkipStatement(NeedBracesCheck.java:177)
        at com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck.visitToken(NeedBracesCheck.java:164)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:388)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:499)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:330)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:203)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:265)
        at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
        at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:538)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

When I add the curly braces around `for` cycle, it works.

I am also attatching a simple project containing only Demo, pom.xml and config.xml.
[issue-NPE-project.zip](https://github.com/checkstyle/checkstyle/files/1504120/issue-NPE-project.zip)

So, you demanded your output, here it is.

**I would like to ask you to reopen the request.**

**Comment by rnveach** [comment] 2017-11-26 19:26
@mareksabo I cannot reproduce your issue on the latest checkstyle.
Since you are using maven-checkstyle and only that, you must be using an outdated version of Checkstyle.
Please use the latest version of Checkstyle in maven.

**Comment by mareksabo** [comment] 2017-11-26 19:47
Thank you. :+1: 

Issue was resolved by overriding checkstyle.
I am adding a link to solution if somebody will have the same problem:
https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html
