### ISSUE TITLE
adjacent static import groups ones became impossible in 8.3

### ISSUE THREAD

**Issue by ssp** [checkstyle/checkstyle#5176] opened 2017-10-08 10:27 UTC
In Version 8.3 checkstyle start to enforce no blank lines within what it considers an import group. [ImportOrder](http://checkstyle.sourceforge.net/config_imports.html#ImportOrder)

In a project, we have a setup where static imports from a group are considered a group of its own, separated by a blank line. In terms of a an Eclipse-Importorder file it looks like this:

    2=javax
    1=\#java
    0=java

As far as I understand the documentation and code in checkstyle, this means I cannot make checkstyle accept this kind of import order anymore. Previously 8.3 will only let me have static imports without a blank line separating them from their non-static counterparts or all of them together in a group at the very top or bottom.

Example import order that used to be OK but is not anymore:

```
➜  cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="ImportOrderCheck">
            <property name="groups" value="java, javax" />
            <property name="separated" value="true" />
            <property name="ordered" value="true" />
            <property name="option" value="bottom" />
         </module>
    </module>
</module>


➜  cat InputImportOrderGapBetweenStaticGroups.java
import static java.lang.Math.abs;
import static java.lang.Math.cos; // Attention: gap below

import static javax.xml.transform.TransformerFactory.newInstance;

public class InputImportOrderGapBetweenStaticGroups { }

# Error about extra separation between import groups
➜  java -jar checkstyle-8.3-all.jar -c config.xml InputImportOrderGapBetweenStaticGroups.java
Starting audit...
[ERROR] /var/tmp/InputImportOrderGapBetweenStaticGroups.java:4: Extra separation in import group before 'javax.xml.transform.TransformerFactory.newInstance' [ImportOrder]
Audit done.
Checkstyle ends with 1 errors.

# compare with Checkstyle 8.2: No error with separation
➜  java -jar checkstyle-8.2-all.jar -c config.xml InputImportOrderGapBetweenStaticGroups.java
Starting audit...
Audit done.
```

After removing separation: ERROR about missing separation.
```
➜  cat InputImportOrderNoGapBetweenStaticGroups.java
import static java.lang.Math.abs;
import static java.lang.Math.cos; // no gap below
import static javax.xml.transform.TransformerFactory.newInstance;

public class InputImportOrderNoGapBetweenStaticGroups { }

➜  java -jar checkstyle-8.3-all.jar -c config.xml InputImportOrderNoGapBetweenStaticGroups.java
Starting audit...
[ERROR] /var/tmp/InputImportOrderNoGapBetweenStaticGroups.java:3: 'javax.xml.transform.TransformerFactory.newInstance' should be separated from previous imports. [ImportOrder]
Audit done.
Checkstyle ends with 1 errors.

➜  java -jar checkstyle-8.2-all.jar -c config.xml InputImportOrderNoGapBetweenStaticGroups.java
Starting audit...
[ERROR] /var/tmp/InputImportOrderNoGapBetweenStaticGroups.java:3: 'javax.xml.transform.TransformerFactory.newInstance' should be separated from previous imports. [ImportOrder]
Audit done.
Checkstyle ends with 1 errors.
```

I am not able to have two static import groups following each other without non-static imports between them in 8.3.

This used to work up to 8.2 using the same configuration.

This behaviour seems to have been introduced by a736d191a9d240a3a8b3a90b5651eb98b3af7d18, the fix for #5065. The suggested test above runs OK without it: https://github.com/ssp/checkstyle/commits/static-imports-between

My impression is that checkstyle unintentionally allowed this kind of import grouping because the of issue fixed by that patch and now cannot be configured anymore to allow it. Ideally we’d have both the fix of that patch and the interspersed static import groups.

**Comment by rnveach** [comment] 2017-10-08 12:59
@ssp Based on your example and config, what is wrong with using `bottom` for option?

````
$ cat TestClass.java
package com.puppycrawl.tools.checkstyle.checks.imports.importorder;

import java.lang.Long;

import static java.lang.Math.abs;
import static java.lang.Math.cos;

import javax.annotation.Nonnull;

public class InputImportOrderStaticGroupsBetween {
    void method() {
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="ImportOrderCheck">
<property name="groups" value="java, org" />
<property name="separated" value="true" />
<property name="ordered" value="true" />
<property name="option" value="bottom" />
</module>
    </module>
</module>

$ java -jar checkstyle-8.3-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````

**Comment by ssp** [comment] 2017-10-08 20:22
Thanks for your help @rnveach .

It seems like I didn’t reduce my example file correctly and mis-analysed the problem because of it. With some more analysis, my new impression is that the issue is triggered by having two static import groups being adjacent to one another without non-static imports in between.

E.g. – using the option=bottom setup:

```java
checkConfig.addAttribute("groups", "java, javax");
checkConfig.addAttribute("separated", "true");
checkConfig.addAttribute("ordered", "true");
checkConfig.addAttribute("option", "bottom");
```
checkstyle will mark this as incorrect because of an extra gap before the static »javax.xml.transform.TransformerFactory.newInstance« import group.

Not OK:
```java
import java.lang.Long;

import static java.lang.Math.abs;
import static java.lang.Math.cos;

import static javax.xml.transform.TransformerFactory.newInstance;
```

Interestingly, removing the blank line doesn’t pass the check either, with checkstyle noting that the new import group should be separated by a blank line.

Not OK:
```java
import java.lang.Long;

import static java.lang.Math.abs;
import static java.lang.Math.cos;
import static javax.xml.transform.TransformerFactory.newInstance;
```

Adding another non-static import group between the two static import groups will work, though.

OK:
```java
import java.lang.Long;

import static java.lang.Math.abs;
import static java.lang.Math.cos;

import javax.annotation.Nonnull;

import static javax.xml.transform.TransformerFactory.newInstance;
```

https://github.com/ssp/checkstyle/commits/static-imports-adjacent

**Comment by romani** [comment] 2017-10-11 23:39
@ssp , please change description of issue with steps to reproduce by CLI as we request during issue creation.
Link to UT is good help but it is not what we demand to approve issue.
Issue should be clear for any user/contributor.
As it is done, I will remove all discussion history to make issue  clear and not scary with long discussion.

**Comment by ssp** [comment] 2017-10-12 04:54
@romani 

Checkstyle config:

```
➜  cat InputImportOrderStaticGroupsBetween.java
package com.puppycrawl.tools.checkstyle.checks.imports.importorder;

import static java.lang.Math.abs;
import static java.lang.Math.cos;

import static javax.xml.transform.TransformerFactory.newInstance;

/*
 * ^^^^^^
 * Gap between two directly adjacent static import groups.
 */
public class InputImportOrderStaticGroupsBetween {
    void method() {
    }
}


➜  cat InputImportOrderStaticGroupsBetween2.java
package com.puppycrawl.tools.checkstyle.checks.imports.importorder;

import static java.lang.Math.abs;
import static java.lang.Math.cos;
import static javax.xml.transform.TransformerFactory.newInstance;

/*
 * ^^^^^^
 * No gap between two directly adjacent static import groups.
 */
public class InputImportOrderStaticGroupsBetween {
    void method() {
    }
}


➜  java -Duser.language=en -Duser.country=US -jar checkstyle-8.3-all.jar -c config.xml InputImportOrderStaticGroupsBetween.java
Starting audit...
[ERROR] /Users/ssp/Downloads/checkstyle-static/InputImportOrderStaticGroupsBetween.java:6: Extra separation in import group before 'javax.xml.transform.TransformerFactory.newInstance' [ImportOrder]
Audit done.
Checkstyle ends with 1 errors.


➜  java -Duser.language=en -Duser.country=US -jar checkstyle-8.3-all.jar -c config.xml InputImportOrderStaticGroupsBetween2.java
Starting audit...
[ERROR] /Users/ssp/Downloads/checkstyle-static/InputImportOrderStaticGroupsBetween2.java:5: 'javax.xml.transform.TransformerFactory.newInstance' should be separated from previous imports. [ImportOrder]
Audit done.
Checkstyle ends with 1 errors.


# compare with Checkstyle 8.2
➜  checkstyle-static java -Duser.language=en -Duser.country=US -jar checkstyle-8.2-all.jar -c config.xml InputImportOrderStaticGroupsBetween.java
Starting audit...
Audit done.


➜  checkstyle-static java -Duser.language=en -Duser.country=US -jar checkstyle-8.2-all.jar -c config.xml InputImportOrderStaticGroupsBetween2.java
Starting audit...
[ERROR] /Users/ssp/Downloads/checkstyle-static/InputImportOrderStaticGroupsBetween2.java:5: 'javax.xml.transform.TransformerFactory.newInstance' should be separated from previous imports. [ImportOrder]
Audit done.
Checkstyle ends with 1 errors.
```


I am not able to have two static import groups following each other without non-static imports between them in 8.3.

This used to work up to 8.2 using the same configuration.

**Comment by romani** [comment] 2017-10-12 23:53
[option "bottom"](http://checkstyle.sourceforge.net/property_types.html#importOrder) means - "All static imports are at the bottom."

So from first looks this is invalid issue, as Checkstyle do exactly what is required.
We need to recheck that Eclipse actually can support sorting like @ssp is provided. 

If that is possible - we probably need to make new options top_separated, bottom_separated to work like "All static imports are at the top/bottom but separated by local groups."

**Comment by djydewang** [comment] 2017-10-13 08:29
@romani 
It's casued by https://github.com/checkstyle/checkstyle/blob/2a5690c28a5ce3af7341428f6b71b6897733cf74/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L442
It can be resolved by adding `<property name="sortStaticImportsAlphabetically" value="true"/>` to config file temporarily.
I will fix it.

**Comment by djydewang** [comment] 2017-10-27 16:00
@romani 
It's a bug since with config file:

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="ImportOrderCheck">
            <property name="groups" value="java, javax" />
            <property name="separated" value="true" />
            <property name="ordered" value="true" />
            <property name="option" value="bottom" />
         </module>
    </module>
</module>
```
```
 cat InputImportOrderNoGapBetweenStaticGroups.java
import static java.lang.Math.abs;
import static java.lang.Math.cos; // no gap below
import static javax.xml.transform.TransformerFactory.newInstance;

public class InputImportOrderNoGapBetweenStaticGroups { }

➜  java -jar checkstyle-8.3-all.jar -c config.xml InputImportOrderNoGapBetweenStaticGroups.java
Starting audit...
[ERROR] /var/tmp/InputImportOrderNoGapBetweenStaticGroups.java:3: 'javax.xml.transform.TransformerFactory.newInstance' should be separated from previous imports. [ImportOrder]
Audit done.
Checkstyle ends with 1 errors.
```
The error is not except.
Please add "approved" label.

**Comment by djydewang** [comment] 2017-10-29 13:47
@romani 
Please reply my last comment.
Thanks!:)

**Comment by cesar1000** [comment] 2017-10-31 00:35
We have a similar problem: 8.2 would allow us to declare groups of static imports, so that our imports would look like this:

```
import static com.twitter.test.mockito.TwitterArgumentMatchers.anyNullable;

import static org.mockito.Matchers.anyInt;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
```

Checkstyle 8.3/8.4 now flags this as an error (which is not right), and this is blocking the upgrade. It would be awesome if the rule was updated to allow these groups.

**Comment by yasserg** [comment] 2017-11-02 05:48
We have the same issue. With separated=true checkstyle 8.4 shows error if we separate groups in static imports or not separate them.

**Comment by ssp** [comment] 2017-11-03 20:03
still seeing the issue in 8.4 as well here

**Comment by romani** [comment] 2017-11-11 14:36
@ssp , @djydewang , bug is approved, sorry for delay.

**Comment by rnveach** [comment] 2017-11-24 03:48
Fix was merged

**Closed by rnveach** 2017-11-24 03:48 UTC
Labels: approved

**Comment by ssp** [comment] 2017-11-25 17:57
@djydewang thanks a lot for your effort!

I just built a current repo version (8441fca) which contains your commits. For my test case it does indeed not fail for both test files, but only for one of them. However, the behaviour now seems to differ from that seen in Checkstyle 8.2.

I’m pasting my output below so you can judge whether that’s intended or not.

```
➜  checkstyle-5176 cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="ImportOrderCheck">
            <property name="groups" value="java, javax" />
            <property name="separated" value="true" />
            <property name="ordered" value="true" />
            <property name="option" value="bottom" />
         </module>
    </module>
</module>

➜  checkstyle-5176 cat InputImportOrderStaticGroupsBetween.java
package com.puppycrawl.tools.checkstyle.checks.imports.importorder;

import static java.lang.Math.abs;
import static java.lang.Math.cos;

import static javax.xml.transform.TransformerFactory.newInstance;

/*
 * ^^^^^^
 * Gap between two directly adjacent static import groups.
 */
public class InputImportOrderStaticGroupsBetween {
    void method() {
    }
}

➜  checkstyle-5176 cat InputImportOrderStaticGroupsBetween2.java
package com.puppycrawl.tools.checkstyle.checks.imports.importorder;

import static java.lang.Math.abs;
import static java.lang.Math.cos;
import static javax.xml.transform.TransformerFactory.newInstance;

/*
 * ^^^^^^
 * No gap between two directly adjacent static import groups.
 */
public class InputImportOrderStaticGroupsBetween2 {
    void method() {
    }
}

➜  checkstyle-5176 java \
-Duser.language=en \
-Duser.country=US \
-jar /Users/ssp/Downloads/checkstyle-5176/checkstyle-8.2-all.jar \
-c config.xml \
InputImportOrderStaticGroupsBetween.java
Starting audit...
Audit done.

➜  checkstyle-5176 java \
-Duser.language=en \
-Duser.country=US \
-jar /Users/ssp/Downloads/checkstyle-5176/checkstyle-8.5-SNAPSHOT-all.jar \
-c config.xml \
InputImportOrderStaticGroupsBetween.java
Starting audit...
[ERROR] /Users/ssp/Downloads/checkstyle-5176/InputImportOrderStaticGroupsBetween.java:6: Extra separation in import group before 'javax.xml.transform.TransformerFactory.newInstance' [ImportOrder]
Audit done.
Checkstyle ends with 1 errors.

➜  checkstyle-5176 java \
-Duser.language=en \
-Duser.country=US \
-jar /Users/ssp/Downloads/checkstyle-5176/checkstyle-8.2-all.jar \
-c config.xml \
InputImportOrderStaticGroupsBetween2.java
Starting audit...
[ERROR] /Users/ssp/Downloads/checkstyle-5176/InputImportOrderStaticGroupsBetween2.java:5: 'javax.xml.transform.TransformerFactory.newInstance' should be separated from previous imports. [ImportOrder]
Audit done.
Checkstyle ends with 1 errors.

➜  checkstyle-5176 java \
-Duser.language=en \
-Duser.country=US \
-jar /Users/ssp/Downloads/checkstyle-5176/checkstyle-8.5-SNAPSHOT-all.jar \
-c config.xml \
InputImportOrderStaticGroupsBetween2.java
Starting audit...
Audit done.
```

**Comment by romani** [comment] 2017-11-25 23:18
>
```
-jar /Users/ssp/Downloads/checkstyle-5176/checkstyle-8.5-SNAPSHOT-all.jar \
-c config.xml \
InputImportOrderStaticGroupsBetween.java
Starting audit...
[ERROR] .....:6: Extra separation in import group before 'javax.xml.transform.TransformerFactory.newInstance' [ImportOrder]
```

we updated xdoc to make it clear that grouping does not work in static, when `sortStaticImportsAlphabetically` is on - https://github.com/checkstyle/checkstyle/commit/acfe3c0ad96616bee811de28528aaeac74a62319#diff-86e367c71f2d80def0ab6755375bf88a.
But in this case we use only `separated` that can follow grouping even with `bottom` mode.

@djydewang , please confirm and if so , lets create new issue on this.

**Comment by djydewang** [comment] 2017-11-26 07:52
@ssp It's intended now. Thanks! 

@romani
> If that is possible - we probably need to make new options top_separated, bottom_separated to work like "All static imports are at the top/bottom but separated by local groups."

I have created the Issue #5279 about it. Because top/bottom means "All static imports are at the top/bottom as one group" now.

> But in this case we use only separated that can follow grouping even with bottom mode.

If we agree with this behaviour, then behaviour of `sortStaticImportsAlphabetically` is complicated since it has two funtion:
1. Applyed for all static imports as one group.
2. Sorting them alphabetically.

Please confirm our requirement.
Thanks!

**Comment by ssp** [comment] 2017-12-01 18:12
@djydewang 

unfortunately it’s not really clear to me know what I need to do to upgrade to Checkstyle with this behaviour. The updated documentation mentioned by @romani  does not seem to relate to the situation I am stuck with (alternating non-static and static import groups which should be separated), so it’s not clear to me how I need to configure Checkstyle > 8.2 to work with the existing code. Any hints?

**Comment by romani** [comment] 2017-12-02 00:53
@ssp  , looks like @djydewang know how to reconcile all requests , you should be able to upgrade as soon #5279 is fixed.

**Comment by eric-milles** [comment] 2018-01-03 16:56
I'm not sure I can follow the current status of this issue.  Using Eclipse's import ordering feature, both normal and static imports may be separated into groups.  For example, all java imports then all javax imports then all java static imports then all javax static imports.

This used to be achievable in Checkstyle until the definition of "top" and "bottom" was changed without notice.

Checkstyle 8.1 and previous has been used successfully using this config:
```xml
        <module name="ImportOrder">
            <message key="import.groups.separated.internally"
              value="Blank line before import ''{0}'' should be removed" />
            <message key="import.ordering" value="Import ''{0}'' is out of order" />
            <message key="import.separation" value="Import ''{0}'' should be separated from previous import group by a blank line" />
            <property name="groups" default="java,javax,groovy,groovyx"
              value="java,javax,groovy,groovyx,/^(?!com\.(xxxxxxxxx|xxxx?|tr(gr)?))\w+/,/^com\.(xxxxxxxxx|xxxx?|tr(gr(?!\.cobalt\.(\w+\.)?${cobalt.package}))?)\./,/^com\.trgr\.cobalt\.(\w+\.)?${cobalt.package}/"
            /><!--   ^language/runtime,        ^third-party,                            ^first-party (but not this module),                                        ^module                                      -->
            <property name="option" value="top" /><!-- Place static imports above regular imports. -->
            <property name="ordered" value="false" /><!-- Eclipse's organize imports will fix order. -->
            <property name="separated" default="true" value="${cobalt.imports.separated}" />
            <property name="id" value="importOrder" />
        </module>
```

This is the corresponding Eclipse config:
![import-order](https://user-images.githubusercontent.com/18193802/34530227-15c362c6-f074-11e7-9123-15b40dbec217.png)

**Comment by ssp** [comment] 2018-01-05 10:23
@djydewang, @romani , @timurt 👍 

Thanks for all your efforts, the latest checkstyle version works for our existing import orders again.
