### ISSUE TITLE
Github rebase action does not work

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#12404] opened 2022-11-13 20:45 UTC
Example of failed job
https://github.com/checkstyle/checkstyle/actions/runs/3456817016/jobs/5769827096
it may be introduced by new github feature - workspaces
```
Collecting information about PR #12316 of checkstyle/checkstyle...
Base branch for PR #12316 is master
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

**Comment by rnveach** [comment] 2022-11-13 21:34
Duplicate of https://github.com/checkstyle/checkstyle/issues/11134 , I suggest to close this one

**Closed** 2022-11-13 21:58 UTC
Labels: approved, CI
