### ISSUE TITLE
CommentsIndentation executed while severity property is "ignore"

### ISSUE THREAD

**Issue by pe4enko** [checkstyle/checkstyle#5258] opened 2017-11-12 20:26 UTC
Hi.
I'am try to configure checkstyle on my project. 
I'am using checkstyle-maven-plugin with dependency on checkstyle 8.0 version

```
<dependency>
	<groupId>com.puppycrawl.tools</groupId>
	<artifactId>checkstyle</artifactId>
	<version>8.0</version>
</dependency>
```
but my build is hanging on 

```
"pool-1-thread-6" #43 prio=5 os_prio=0 tid=0x00007f31d4316000 nid=0x3c5f runnable [0x00007f31a6785000]
   java.lang.Thread.State: RUNNABLE
	at com.puppycrawl.tools.checkstyle.utils.CommonUtils.isBlank(CommonUtils.java:515)
	at com.puppycrawl.tools.checkstyle.checks.indentation.CommentsIndentationCheck.countEmptyLines(CommentsIndentationCheck.java:754)
	at com.puppycrawl.tools.checkstyle.checks.indentation.CommentsIndentationCheck.isOnPreviousLineIgnoringComments(CommentsIndentationCheck.java:709)
	at com.puppycrawl.tools.checkstyle.checks.indentation.CommentsIndentationCheck.findPreviousStatement(CommentsIndentationCheck.java:647)
	at com.puppycrawl.tools.checkstyle.checks.indentation.CommentsIndentationCheck.getOneLinePreviousStatement(CommentsIndentationCheck.java:575)
	at com.puppycrawl.tools.checkstyle.checks.indentation.CommentsIndentationCheck.getPreviousStatement(CommentsIndentationCheck.java:183)
	at com.puppycrawl.tools.checkstyle.checks.indentation.CommentsIndentationCheck.visitComment(CommentsIndentationCheck.java:135)
	at com.puppycrawl.tools.checkstyle.checks.indentation.CommentsIndentationCheck.visitToken(CommentsIndentationCheck.java:113)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:368)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:505)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:310)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:187)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
	at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:473)
	at org.apache.maven.plugin.checkstyle.CheckstyleReport.executeReport(CheckstyleReport.java:154)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
	at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:143)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:167)
	at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:163)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

i'am don't understand why this check invokes because in my checkstyle config it has severity "ignore"

```
<module name="CommentsIndentation">
  <property name="severity" value="ignore"/>
  <metadata name="net.sf.eclipsecs.core.lastEnabledSeverity" value="inherit"/>
</module>
```

and i'am **not** using **executeIgnoredModules** option

All checkstyle config 
```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<!--
    This configuration file was written by the eclipse-cs plugin configuration editor
-->
<!--
    Checkstyle-Configuration: Checks
    Description:
Checkstyle configuration that checks the Google coding conventions from Google Java Style that can be found at https://google.github.io/styleguide/javaguide.html. С изменениями для студии.
-->
<module name="Checker">
  <property name="severity" value="warning"/>
  <property name="charset" value="UTF-8"/>
  <property name="fileExtensions" value="java, properties, xml"/>
  <module name="TreeWalker">
    <property name="tabWidth" value="4"/>
    <module name="FileContentsHolder"/>
    <module name="OuterTypeFilename"/>
    <module name="IllegalTokenText">
      <property name="tokens" value="STRING_LITERAL, CHAR_LITERAL"/>
      <property name="format" value="\\u00(08|09|0(a|A)|0(c|C)|0(d|D)|22|27|5(C|c))|\\(0(10|11|12|14|15|42|47)|134)"/>
      <property name="message" value="Avoid using corresponding octal or Unicode escape."/>
    </module>
    <module name="AvoidEscapedUnicodeCharacters">
      <property name="allowEscapesForControlCharacters" value="true"/>
      <property name="allowByTailComment" value="true"/>
      <property name="allowNonPrintableEscapes" value="true"/>
    </module>
    <module name="LineLength">
      <property name="ignorePattern" value="^package.*|^import.*|a href|href|http://|https://|ftp://"/>
      <property name="max" value="160"/>
    </module>
    <module name="AvoidStarImport"/>
    <module name="OneTopLevelClass"/>
    <module name="NoLineWrap"/>
    <module name="EmptyBlock">
      <property name="option" value="TEXT"/>
      <property name="tokens" value="LITERAL_TRY, LITERAL_FINALLY, LITERAL_IF, LITERAL_ELSE, LITERAL_SWITCH"/>
    </module>
    <module name="NeedBraces"/>
    <module name="LeftCurly">
      <property name="maxLineLength" value="100"/>
    </module>
    <module name="RightCurly"/>
    <module name="RightCurly">
      <property name="option" value="alone"/>
      <property name="tokens" value="CLASS_DEF,METHOD_DEF,CTOR_DEF,LITERAL_FOR,LITERAL_WHILE,STATIC_INIT,INSTANCE_INIT"/>
    </module>
    <module name="WhitespaceAround">
      <property name="allowEmptyConstructors" value="true"/>
      <property name="allowEmptyMethods" value="true"/>
      <property name="allowEmptyTypes" value="true"/>
      <property name="allowEmptyLoops" value="true"/>
      <message key="ws.notPreceded" value="WhitespaceAround: ''{0}'' is not preceded with whitespace."/>
      <message key="ws.notFollowed" value="WhitespaceAround: ''{0}'' is not followed by whitespace. Empty blocks may only be represented as '{}' when not part of a multi-block statement (4.1.3)"/>
    </module>
    <module name="OneStatementPerLine"/>
    <module name="MultipleVariableDeclarations"/>
    <module name="ArrayTypeStyle"/>
    <module name="MissingSwitchDefault"/>
    <module name="FallThrough"/>
    <module name="UpperEll"/>
    <module name="ModifierOrder"/>
    <module name="EmptyLineSeparator">
      <property name="tokens" value="IMPORT,CLASS_DEF,ENUM_DEF,INTERFACE_DEF,CTOR_DEF,METHOD_DEF,STATIC_INIT,INSTANCE_INIT,VARIABLE_DEF"/>
      <property name="allowNoEmptyLineBetweenFields" value="true"/>
    </module>
    <module name="SeparatorWrap">
      <property name="option" value="nl"/>
      <property name="tokens" value="DOT"/>
    </module>
    <module name="SeparatorWrap">
      <property name="option" value="EOL"/>
      <property name="tokens" value="COMMA"/>
    </module>
    <module name="PackageName">
      <property name="format" value="^[a-z]+(\.[a-z][a-z0-9]*)*$"/>
      <message key="name.invalidPattern" value="Package name ''{0}'' must match pattern ''{1}''."/>
    </module>
    <module name="TypeName">
      <message key="name.invalidPattern" value="Type name ''{0}'' must match pattern ''{1}''."/>
    </module>
    <module name="MemberName">
      <property name="format" value="^[a-z][a-z0-9][a-zA-Z0-9]*$"/>
      <message key="name.invalidPattern" value="Member name ''{0}'' must match pattern ''{1}''."/>
    </module>
    <module name="ParameterName">
      <property name="format" value="^[a-z]([a-zA-Z0-9]*)?$"/>
      <property name="accessModifiers" value="public"/>
      <message key="name.invalidPattern" value="Parameter name ''{0}'' must match pattern ''{1}''."/>
    </module>
    <module name="CatchParameterName">
      <property name="format" value="^[a-z][a-zA-Z0-9]*$"/>
      <message key="name.invalidPattern" value="Catch parameter name ''{0}'' must match pattern ''{1}''."/>
    </module>
    <module name="LocalVariableName">
      <property name="allowOneCharVarInForLoop" value="true"/>
      <property name="tokens" value="VARIABLE_DEF"/>
      <message key="name.invalidPattern" value="Local variable name ''{0}'' must match pattern ''{1}''."/>
    </module>
    <module name="ClassTypeParameterName">
      <property name="format" value="(^[A-Z][0-9]?)$|([A-Z][a-zA-Z0-9]*[T]$)"/>
      <message key="name.invalidPattern" value="Class type name ''{0}'' must match pattern ''{1}''."/>
    </module>
    <module name="MethodTypeParameterName">
      <property name="format" value="(^[A-Z][0-9]?)$|([A-Z][a-zA-Z0-9]*[T]$)"/>
      <message key="name.invalidPattern" value="Method type name ''{0}'' must match pattern ''{1}''."/>
    </module>
    <module name="InterfaceTypeParameterName">
      <property name="format" value="(^[A-Z][0-9]?)$|([A-Z][a-zA-Z0-9]*[T]$)"/>
      <message key="name.invalidPattern" value="Interface type name ''{0}'' must match pattern ''{1}''."/>
    </module>
    <module name="NoFinalizer"/>
    <module name="GenericWhitespace">
      <message key="ws.notPreceded" value="GenericWhitespace ''{0}'' is not preceded with whitespace."/>
      <message key="ws.followed" value="GenericWhitespace ''{0}'' is followed by whitespace."/>
      <message key="ws.preceded" value="GenericWhitespace ''{0}'' is preceded with whitespace."/>
      <message key="ws.illegalFollow" value="GenericWhitespace ''{0}'' should followed by whitespace."/>
    </module>
    <module name="Indentation">
      <property name="throwsIndent" value="8"/>
      <property name="lineWrappingIndentation" value="8"/>
    </module>
    <module name="AbbreviationAsWordInName">
      <property name="allowedAbbreviationLength" value="1"/>
      <property name="allowedAbbreviations" value="ID,URI,URL,AM,HTTP,XMI,XML,UI,CDO"/>
      <property name="ignoreFinal" value="false"/>
    </module>
    <module name="OverloadMethodsDeclarationOrder"/>
    <module name="VariableDeclarationUsageDistance"/>
    <module name="CustomImportOrder">
      <property name="customImportOrderRules" value="STATIC###THIRD_PARTY_PACKAGE"/>
      <property name="sortImportsInGroupAlphabetically" value="true"/>
    </module>
    <module name="MethodParamPad"/>
    <module name="OperatorWrap">
      <property name="option" value="NL"/>
      <property name="tokens" value="BAND, BOR, BSR, BXOR, DIV, EQUAL, GE, GT, LAND, LE, LITERAL_INSTANCEOF, LOR, LT, MINUS, MOD, NOT_EQUAL, PLUS, QUESTION, SL, SR, STAR, METHOD_REF "/>
    </module>
    <module name="AnnotationLocation">
      <property name="tokens" value="CLASS_DEF, INTERFACE_DEF, ENUM_DEF, METHOD_DEF, CTOR_DEF"/>
    </module>
    <module name="AnnotationLocation">
      <property name="tokens" value="VARIABLE_DEF"/>
      <property name="allowSamelineMultipleAnnotations" value="true"/>
    </module>
    <module name="NonEmptyAtclauseDescription"/>
    <module name="JavadocTagContinuationIndentation"/>
    <module name="SummaryJavadoc">
      <property name="severity" value="ignore"/>
      <property name="forbiddenSummaryFragments" value="^@return the *|^This method returns |^A [{]@code [a-zA-Z0-9]+[}]( is a )"/>
      <metadata name="net.sf.eclipsecs.core.lastEnabledSeverity" value="inherit"/>
    </module>
    <module name="JavadocParagraph"/>
    <module name="AtclauseOrder">
      <property name="target" value="CLASS_DEF, INTERFACE_DEF, ENUM_DEF, METHOD_DEF, CTOR_DEF, VARIABLE_DEF"/>
      <property name="tagOrder" value="@param, @return, @throws, @deprecated"/>
    </module>
    <module name="JavadocMethod">
      <property name="minLineCount" value="2"/>
      <property name="allowedAnnotations" value="Override, Test"/>
      <property name="scope" value="public"/>
      <property name="allowThrowsTagsForSubclasses" value="true"/>
      <property name="allowMissingParamTags" value="true"/>
      <property name="allowMissingThrowsTags" value="true"/>
      <property name="allowMissingReturnTag" value="true"/>
      <property name="allowMissingJavadoc" value="true"/>
    </module>
    <module name="MethodName">
      <property name="format" value="^[a-z][a-z0-9][a-zA-Z0-9_]*$"/>
      <message key="name.invalidPattern" value="Method name ''{0}'' must match pattern ''{1}''."/>
    </module>
    <module name="SingleLineJavadoc">
      <property name="ignoreInlineTags" value="false"/>
    </module>
    <module name="EmptyCatchBlock">
      <property name="exceptionVariableName" value="expected"/>
    </module>
    <module name="CommentsIndentation">
      <property name="severity" value="ignore"/>
      <metadata name="net.sf.eclipsecs.core.lastEnabledSeverity" value="inherit"/>
    </module>
    <module name="RegexpSinglelineJava">
      <property name="format" value="^\t* +\t*\S"/>
      <property name="message" value="Line has leading space characters; indentation should be performed with tabs only."/>
      <property name="ignoreComments" value="true"/>
    </module>
  </module>
  <module name="FileTabCharacter">
    <property name="severity" value="ignore"/>
    <property name="eachLine" value="true"/>
    <metadata name="net.sf.eclipsecs.core.lastEnabledSeverity" value="inherit"/>
  </module>
  <module name="SuppressionCommentFilter">
    <property name="offCommentFormat" value="@generated$"/>
    <property name="onCommentFormat" value="@generated NOT$"/>
  </module>
</module>
```

**Comment by rnveach** [comment] 2017-11-13 03:33
@pe4enko To me this might sound like a maven issue.
Can you reproduce this behavior with our CLI outside maven? We aren't the maven plugin.

> but my build is hanging on

How did you determine this is what is hanging and not just what was being executed at the time of the examination? It could just be taking a long time to complete.

> i'am don't understand why this check invokes because in my checkstyle config it has severity "ignore"
> and i'am not using executeIgnoredModules option

Maven hasn't released this to my knowledge. I still can't set it in the POM.
By default, maven will still execute ignored modules, just not print any violations found since they use the default load for the configuration.
https://github.com/checkstyle/checkstyle/blob/8174ea2a778fbd3e75c790f89f83f979ad8e3c9a/src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java#L198-L200

**Comment by pe4enko** [comment] 2017-11-13 07:59
> It could just be taking a long time to complete.
Yes, it finished after several hours.

I found a bug for maven-checkstyle-plugin 
Add support for 'omitIgnoredModules'
https://issues.apache.org/jira/browse/MCHECKSTYLE-338

**Comment by rnveach** [comment] 2017-11-13 13:57
Then I will close this issue since it does complete with no issue.

Unless we know the project and it's source you are running checkstyle on or you debug the issue further, we cannot help with why it is taking so long to complete. If you are scanning a lot of files, big files, or have a slow disk access, this could be the problem but usually the Java and Javadoc parser is the common lag point.
You can start a google group post at https://groups.google.com/forum/#!forum/checkstyle-devel if you need us to help you more to discern why it's taking so long.

> I found a bug for maven-checkstyle-plugin

Yes, this is the one I opened, and they have made the code changes, but have not released a new version in quite a while. Their last release was `Oct, 2015` (source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-checkstyle-plugin) so I wouldn't hope a release gets done soon.

**Closed by rnveach** 2017-11-13 13:57 UTC
