### ISSUE TITLE
ConfigurationLoaderTest::testIncorrectTag is flaky

### ISSUE THREAD

**Issue by flakycov** [checkstyle/checkstyle#4664] opened 2017-07-08 14:33 UTC
from TestingResearchIllinois/NonDex#112

`ConfigurationLoaderTest.testIncorrectTag` failed for us on commit 82bc23f but did not fail on [the corresponding Travis run](https://travis-ci.org/checkstyle/checkstyle/jobs/229572526).

Our tool confirms this test is flaky. The full stacktrace is below. We set up our build environment to be as close as possible to your Travis build environment, using Xcode 7.3.1, OS X 10.11, Java 1.8.0_92 and Maven 3.3.9.

It seems Nondex should also have caught this flaky test. @alexgyori, @romani ?

```
Tests run: 25, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.299 sec <<< FAILURE!
testIncorrectTag(com.puppycrawl.tools.checkstyle.ConfigurationLoaderTest)  Time elapsed: 0.015 sec  <<< ERROR!
java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoaderTest.testIncorrectTag(ConfigurationLoaderTest.java:384)
  ```

This is the line in question: https://github.com/checkstyle/checkstyle/blob/82bc23f45d7d57dfa26d1a1d4ec0f7dfcd88abb2/src/test/java/com/puppycrawl/tools/checkstyle/ConfigurationLoaderTest.java#L384

**Comment by rnveach** [comment] 2017-07-08 14:53
@flakycov Do you have this problem in the current master commit? Do you need this specific commit for some reason?

> argument type mismatch

Can you clarify what the argument was that was sent versus what it is expecting?
`InternalLoader` only has 1 constructor, so how can it be choosing the wrong one?

> It seems Nondex should also have caught this flaky test.

Do you mean because of the result of `getDeclaredConstructors`? If you can confirm an issue, you should report it to them.

**Comment by rnveach** [comment] 2017-07-08 14:58
> InternalLoader only has 1 constructor, so how can it be choosing the wrong one?

I actually debugged this and there is 2.
One is: `public com.puppycrawl.tools.checkstyle.ConfigurationLoader$InternalLoader(org.powermock.core.IndicateReloadClass)`
The second is: `public com.puppycrawl.tools.checkstyle.ConfigurationLoader$InternalLoader(com.puppycrawl.tools.checkstyle.ConfigurationLoader) throws org.xml.sax.SAXException,javax.xml.parsers.ParserConfigurationException`

It looks like powermock is interfering with the reflection.
I can confirm without powermock there is only 1 constructor.

@romani This looks like a valid issue to me even if we aren't seeing any negative results.

**Comment by rnveach** [comment] 2017-07-08 15:08
> It seems Nondex should also have caught this flaky test.

@flakycov It did. We suppressed it during https://github.com/TestingResearchIllinois/NonDex/issues/112 .
This is why nondex didn't catch it.

**Comment by rnveach** [comment] 2017-07-08 16:08
@flakycov can you confirm if this is just a personal issue or was this based on problem we filled with nondex? Why are you using this specific commit?

**Comment by alexgyori** [comment] 2017-07-08 16:15
@rnveach you are correct; you mentioned this issue in https://github.com/TestingResearchIllinois/NonDex/issues/112

@flakycov ran into it through some other means, and then I noticed that you already pointed to this after reasoning that NonDex should catch this.

After debugging more, it seems that indeed, as you mention, powermock adds one extra constructor at runtime, and depending on whether it is the last one or the first added the test may break (and that's what @flakycov observed). NonDex would just proactively explore different orders and flag the code; that's what you observed in the issue you filed.

I think the test code should be changed and instead of those loops just get the correct constructor. Do you want me to make a PR for that?

**Comment by rnveach** [comment] 2017-07-08 16:46
> I think the test code should be changed and instead of those loops just get the correct constructor. Do you want me to make a PR for that?

The PR has already been started at #4666 , we are just awaiting the results now.

**Comment by romani** [comment] 2017-07-08 17:39
fix is merged.
@flakycov , thanks a lot !

**Closed by romani** 2017-07-08 17:39 UTC
Labels: approved, miscellaneous

**Comment by alexgyori** [comment] 2017-07-08 20:07
Do you want to remove --fail-never or replace it with --fail-at-end?

**Comment by romani** [comment] 2017-07-11 00:00
I use fail-never to print some details to CI log before failing the build process to give contributor some details to output.
Ones you fix https://github.com/TestingResearchIllinois/NonDex/issues/97 , we can remove that option from maven and simplify CI command line.
