### ISSUE TITLE
How do I enforce no @author tag in Javadoc?

### ISSUE THREAD

**Issue by danielb987** [checkstyle/checkstyle#5339] opened 2017-12-10 09:28 UTC
[My checkstyle configuration](https://github.com/danielb987/EmojicodeEditor/blob/master/checkstyle/emojicode_checks.xml). See lines 198 - 207.

[The output from checkstyle](https://danielb987.github.io/EmojicodeEditor/checkstyle/checkstyle_errors.xml)

[An example Java file with the error](https://github.com/danielb987/EmojicodeEditor/blob/master/src/emojicode/code/MainBlock.java). See line 37.

---------------

How do I enforce no \@author tag in Javadoc?

By reading [this page](http://markmail.org/message/6373xhvurzydnm4x) and [this page](http://checkstyle.sourceforge.net/config_javadoc.html), I have the following configuration:

```
<module name="Checker">
    . . .
    <module name="TreeWalker">
        . . .
        <module name="WriteTag">
            <!-- The tag to check -->
            <property name="tag" value="@author"/>
            <!-- The format of the tag -->
            <property name="tagFormat" value="\S"/>
            <!-- What to do if the tag does not exists? -->
            <property name="severity" value="ignore"/>
            <!-- What to do if the tag exists? -->
            <property name="tagSeverity" value="error"/>
        </module>
    </module>
</module>
```

This configuration will do nothing. It doesn't react on the \@author tags at all.

If I remove the line  property name="severity" value="ignore" ,  checkstyle will emit error if an \@author tag is found, but it will also emit an error if no \@author tag is found.

---------------

A second question:

How do I enforce no copyright line in the source code? Line 4 in the Java file above has the copyright line "Copyright 2017 Daniel Bergqvist" and I want to enforce not having that line in the source code, independent of what name is on that line.

**Comment by rnveach** [comment] 2017-12-10 16:21
@danielb987 Please ask questions in google groups: https://groups.google.com/forum/?hl=en#!forum/checkstyle-devel
Issues are for 'possible' bugs and problems.

> This configuration will do nothing. 
> `<property name="severity" value="ignore"/>`

This line is most likely why. Checkstyle by default will not run checks with a severity of ignore, even though this check will print with severities of `tagSeverity` too. You must enable ignored modules by passing `-executeIgnoredModules` to the command line. http://checkstyle.sourceforge.net/cmdline.html
This check is sort of deprecated to us too, even though it isn't marked as such.
If you are using maven, they do not support this feature yet as we are waiting on a release from them.
See https://issues.apache.org/jira/browse/MCHECKSTYLE-346

Another possibility is to use regular expression:
````
	<module name="RegexpSingleline">
		<property name="format" value="^\s*\*\s*@author" />
		<property name="minimum" value="0" />
		<property name="maximum" value="0" />
		<property name="message" value="Javadoc has illegal ''author'' tag." />
	</module>
````

**Closed by rnveach** 2017-12-10 16:21 UTC

**Comment by romani** [comment] 2017-12-10 20:17
WriteTag is broken Check by design, we have issue on this somewhere in issue tracker. As far as I remember it is not possible and want the same policy to be enforced over our code too.

**Comment by danielb987** [comment] 2017-12-11 01:35
Thanks. RegexpSingleline works fine.

@romani 
Here is how I did it.

[My checkstyle configuration](https://github.com/danielb987/EmojicodeEditor/blob/master/checkstyle/emojicode_checks.xml). The check of author tag is at lines 93 - 99.

I also wanted to enforce the copyright statement to have my name and my name only, to get the copyright statement consistent thru the code. I do this at lines 102 - 121. The first check do check if the copyright statement is written in the correct way with my name. The second check do check that there is exactly one copyright notice in the file, not zero or many.
