### ISSUE TITLE
Add to CI import order validation on certain projects

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#6018] opened 2018-07-09 14:11 UTC
https://github.com/checkstyle/contribution/tree/master/checkstyle-tester/checks-import-order

No diff is expected on such configs. No errors validations could be used.

**Comment by rnveach** [comment] 2018-07-11 12:54
I am fine with such regression since it has been a hot topic.
I just question if we should be grabbing the repository's config for the import checks then duplicating them and hoping the user's don't change them.

**Comment by romani** [comment] 2018-07-12 01:11
Such projects do not have config, @pbludov just figured out what match them, so we can run with such configuration on them and expect no violations.
If any appear - clear signal that fix is not ok.

Ideally is to find projects which use ImportOrder, but I failed to find.

**Comment by rnveach** [comment] 2018-07-13 01:56
fix was merged

**Closed by rnveach** 2018-07-13 01:56 UTC
Labels: approved
