### ISSUE TITLE
JavadocStyleCheck: If a class contains   /**/   then "String index out of range: -1 is thrown"

### ISSUE THREAD

**Issue by GoofyHTS** [checkstyle/checkstyle#2387] opened 2015-10-19 19:05 UTC
If a class contains javadoc like the following:   /**/   the following error is thrown:

"Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1"

Example  class below:
```
/var/tmp $ cat 3.java 
package test;
public class Test {
/**/
public void someMethod() {}
}

/var/tmp $ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <module name="TreeWalker">
    <module name="JavadocStyleCheck"/>
  </module>
</module>

/var/tmp $ java -jar checkstyle-6.11.2-all.jar -c config.xml   3.java
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:210)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.trimTail(JavadocStyleCheck.java:316)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.getCommentText(JavadocStyleCheck.java:269)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.checkFirstSentenceEnding(JavadocStyleCheck.java:230)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.checkComment(JavadocStyleCheck.java:207)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocStyleCheck.visitToken(JavadocStyleCheck.java:148)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:388)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:499)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:330)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:203)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:265)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:277)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:118)
```

**Comment by romani** [comment] 2015-10-19 20:15
Can you provide config , we need to know what Check cause exception

**Comment by GoofyHTS** [comment] 2015-10-19 20:23
It's the original config from the checkstyle-6.11.2-bin.zip, "\config\checkstyle_checks.xml". 
Inside checkstyle_checks.xml the originals in the zip was used as well:

SuppressionFilter.file=\config\suppressions.xml
Header.headerFile=\config\java.header
RegexpHeader.headerFile=\config\java.header
ImportControl=\config\import-control.xml

Hope this helps.

**Comment by romani** [comment] 2015-10-19 20:23
I can presume that this is caused by core class, comment indentuficator is missed, this is a problem for parser. Should be fixed

**Comment by mkordas** [comment] 2015-10-31 15:15
I'm on it. The thing here is that `/**/` should not be recognized as Javadoc - it's just a normal comment.

**Comment by romani** [comment] 2015-10-31 22:12
merged.

**Closed by romani** 2015-10-31 22:12 UTC
Labels: approved

**Comment by GoofyHTS** [comment] 2015-10-31 22:18
Thank you
