### ISSUE TITLE
Pitest/Checker: Drop New/Unnecessary Displays And Switch to Git Diff

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#12243] opened 2022-10-02 03:19 UTC
From trying to work out making CI pass at https://github.com/checkstyle/checkstyle/pull/11617#event-7452762112 I have reached a new level of dislike towards Checker. Since I can't run this on my local, I have to rely on the faulty new/unnecessary display and figure out how to modify the file myself with not good results.

My suggestion is to drop the New/Unnecessary and rely on our git difference to report back any differences, if any, and use this as a way to allow the user to apply the difference patch to their local to pass CI in one go.

This works way more easier for things like arch unit's cycles, which also does not work the same as CI on my local, but I am able to resolve it in one go with the git difference reported by the CI.

I dunno how, but I assume we will still have to continue supporting unstables and recreating the fill on the git difference means keeping that value if it is set. It makes sense for pitest, but I don't remember us having any unstables for checker. This issue will probably have to be taken slowly to ensure it meets our needs.

**Comment by Vyom-Yadav** [comment] 2022-10-02 04:49
I think the primary problem is the instability with the checker framework, pitest model works smoothly, not sure if git diff is better. 

We can change to `-g` flag in all scripts to get the suppressions in XML, the only drawback is that it won't show line number then because we do not add line number in suppressions, you  would have to search by text in the file.

**Comment by rnveach** [comment] 2022-10-02 12:04
I am open to anything to make this a better experience.

**Comment by nrmancuso** [comment] 2022-10-02 12:08
@rnveach to be clear, the goal of this issue is to have each groovy script generate/remove suppressions of violations in their respective files, and rely on git diff to fail build in CI?

**Comment by rnveach** [comment] 2022-10-02 12:46
Yes. This also provides the benefit that user can copy git diff and apply it to their local (mainly for checker) if all suppressions will stay.

I am open to other options like removing pitest from this, but I have really had enough trying to get checker to pass.

**Comment by romani** [comment] 2022-10-03 04:42
Git diff can be done in addition to embedded ability to provide "patch".

**Comment by romani** [comment] 2022-10-14 20:00
Issue is not finished, we have one more PR for it. Based on agreement in private chat we need to keep unstable feature just in case.
And improve new items that we found

**Comment by nrmancuso** [comment] 2022-10-24 04:13
> Issue is not finished, we have one more PR for it. Based on agreement in private chat we need to keep unstable feature just in case. And improve new items that we found [#12244 (comment)](https://github.com/checkstyle/checkstyle/pull/12244#issuecomment-1272559147)

I am on it

**Comment by nrmancuso** [comment] 2022-10-28 04:53
@romani please confirm if what remains to do here (see https://github.com/checkstyle/checkstyle/issues/12243#issuecomment-1279405407)  is a duplicate of https://github.com/checkstyle/checkstyle/issues/12221. If so, please close this and we will continue there.

**Comment by romani** [comment] 2022-10-28 06:10
Yes, I lost a reason of discussion there we did this in some updates over the script.

**Closed by romani** 2022-10-28 06:10 UTC
Labels: approved, high demand, miscellaneous
