### ISSUE TITLE
RegexMultiline contains Example7 that is actually part of Example6

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/checkstyle#15172] opened 2024-06-29 18:17 UTC
https://github.com/checkstyle/checkstyle/blob/b0961ea6a54e1d3b920857e708cfc1cac8c3734d/src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline/Example7.txt

```
/
*xml
<module name="Checker">
  /var/tmp/Test.java // violation, a file must not be empty.
</module>
*/
```

I am working on test-configs and this creates parsing issue for the application. 

```
Error processing directory: ../.ci-temp/checkstyle/src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/regexp/regexpmultiline
com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream - The content of element type "module" must match "(module|property|metadata|message)*".:2:93
at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:317)
at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:282)
at com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser.parseWithXmlHeader(InlineConfigParser.java:245)
at com.example.extractor.ConfigSerializer.extractModuleName(ConfigSerializer.java:220)
at com.example.extractor.Main.processDirectory(Main.java:84)
```

**Comment by rnveach** [comment] 2024-06-29 18:28
Basically a duplicate of #13345.

https://github.com/checkstyle/checkstyle/blob/b0961ea6a54e1d3b920857e708cfc1cac8c3734d/src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckExamplesTest.java#L27-L28
Examples is disable and is not guaranteed to be correct. Issue will be resolved under #13345 .

**Comment by relentless-pursuit** [comment] 2024-06-29 18:38
> Basically a duplicate of #13345.
> 
> https://github.com/checkstyle/checkstyle/blob/b0961ea6a54e1d3b920857e708cfc1cac8c3734d/src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckExamplesTest.java#L27-L28
> 
> 
> https://github.com/checkstyle/checkstyle/blob/b0961ea6a54e1d3b920857e708cfc1cac8c3734d/src/xdocs-examples/java/com/puppycrawl/tools/checkstyle/checks/regexp/RegexpMultilineCheckExamplesTest.java#L94
> 
> Examples is disable and is not guaranteed to be correct. Issue will be resolved under #13345 .

But, this will be a blocker for my PRs in test-config? What alternative do we have? Because, my application parses both Examples.java and Examples.txt file.

**Comment by rnveach** [comment] 2024-06-29 18:43
This is not blocking you from fixing this if you desire. It is just a duplicate of the other issue since the test is disabled and has no guarantees to be correct. Either you can enable the test and fix the parsing issue or skip this file in your process.

**Comment by relentless-pursuit** [comment] 2024-06-29 18:46
> This is not blocking you from fixing this if you desire. It is just a duplicate of the other issue since the test is disabled and has no guarantees to be correct. Either you can enable the test and fix the parsing issue or skip this file in your process.

Okay, currently we are trying  to have the CI to run and generate all the configs. And, maybe I can create a exclusion for this at the moment. Thank you for the suggestion.

**Comment by rnveach** [comment] 2024-06-29 18:52
Just so you are aware, the data you are gathering and processing will be in doubt until https://github.com/checkstyle/checkstyle/issues/13345 is resolved.

**Comment by romani** [comment] 2024-06-30 13:30
@rnveach  is right, but to help test-configs repo to handle it easier to can fix it sooner wihout activation of Example.

https://checkstyle.org/checks/regexp/regexpmultiline.html#Example6-config
this example contains 3 bllocks of code: config, test file content AND print of violation (that is not expected at all).

We can simply remove:
```
Result:

/var/tmp/Test.java // violation, a file must not be empty.
        
```
as it is not a Example7

**Comment by romani** [comment] 2024-06-30 13:32
@relentless-pursuit , please send PR to remove Example7.txt and related references in template file.

**Closed** 2024-09-14 05:51 UTC
Labels: approved, miscellaneous
