### ISSUE TITLE
NullPointerException from TreeWalker.destroy

### ISSUE THREAD

**Issue by jshiell** [checkstyle/checkstyle#921] opened 2015-04-11 08:36 UTC
One of the users of the IDEA plugin [reported a problem](https://github.com/jshiell/checkstyle-idea/issues/150) with a NPE being generated during TreeWalker.destroy. This is reproducible with the 6.5 JAR distribution.

```
$  java -jar ../checkstyle-6.5-all.jar -c rules.xml TestCase.java
Exception in thread "main" java.lang.NullPointerException
	at com.google.common.io.Flushables.flush(Flushables.java:56)
	at com.puppycrawl.tools.checkstyle.PropertyCacheFile.flushAndCloseOutStream(PropertyCacheFile.java:135)
	at com.puppycrawl.tools.checkstyle.PropertyCacheFile.destroy(PropertyCacheFile.java:123)
	at com.puppycrawl.tools.checkstyle.TreeWalker.destroy(TreeWalker.java:499)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:299)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:125)
```

The rules file is:
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <property name="cacheFile" value="target/checkstyle_cache"/>
    </module>
</module>
```

The test Java file is pretty trivial:
```
public class TestCase {

}
```

Thank you :smile:

**Comment by mkordas** [comment] 2015-04-11 13:23
This is bug introduced by me in 06865630aa3da0b36064b9e00e0e95ff681f234e. I knew that `Closeables.close()` has null check, and I assumed the same for `Flushables.flush()` which is not true. This should be detected by unit tests though... I'm working on fix, @romani please assign me.

**Comment by mkordas** [comment] 2015-04-11 13:36
Looks like this bug was also detected by FindBugs and it has been already fixed with @romani's 547fb51b1db4533e6e1a03aa528a2fed5de828e9 which will be released in 6.6.

**Comment by romani** [comment] 2015-04-11 14:15
UT has to be created, as it easily reproducible.

**Comment by jshiell** [comment] 2015-04-11 15:15
Smashing - thanks very much!

**Comment by mkordas** [comment] 2015-04-12 21:40
This is interesting - in UT I get this NPE only when path to cache file is invalid or write to this file was not successful. And from code perspective, this is also the only possibility (see https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java#L110).

UT with `<property name="cacheFile" value="target/checkstyle_cache"/>` passes, while UT `<property name="cacheFile" value="/invalidPath!"/>` fails with the same stacktrace as presented. 

Am I right or I miss something?

**Comment by romani** [comment] 2015-04-13 05:27
This is exactly a case, as after commenting out  ```
```
all work file, and in current folder there is no folder "target", I missed that during issue description update.

**Comment by mkordas** [comment] 2015-04-13 05:57
OK - so besides this NPE which is already fixed (and I can write UT for this) shouldn't we validate that path for cacheFile is correct and fail fast with meaningful exception if it is not?

**Comment by romani** [comment] 2015-04-13 14:10
Yes, please fail with human friendly exception

**Comment by mkordas** [comment] 2015-04-15 16:58
OK, now I see that we do not fail on purpose - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PropertyCacheFile.java#L98. @romani, what do you think? Should we leave this behaviour or change it? If we want to change then new issue is needed anyway.

**Comment by romani** [comment] 2015-04-15 18:03
merged.

**Closed by romani** 2015-04-15 18:03 UTC
Labels: approved

**Comment by romani** [comment] 2015-04-15 18:04
>  what do you think? Should we leave this behaviour or change it?

Lets keep that for now, we need to redo a bit Cache implementation , we already have issue in our pool for that, during that that issue we will refresh all nuances of that functionality.
