### ISSUE TITLE
IllegalTokenTextCheck and IllegalTokenCheck does not work with COMMENT_CONTENT token

### ISSUE THREAD

**Issue by Qix-** [checkstyle/checkstyle#3153] opened 2016-05-03 07:32 UTC
The error message says it all.
```
$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="IllegalTokenText">
            <property name="tokens" value="COMMENT_CONTENT" />
        </module>
    </module>
</module>
```
```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Check 'com.puppycrawl.tools.checkstyle.check
s.coding.IllegalTokenTextCheck' waits for comment type token ('COMMENT_CONTENT') and should override 'isCommentNodesRequired()' method to r
eturn 'true'
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:181)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:138)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:326)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:159)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Check 'com.puppycrawl.tools.checkstyle.checks.coding.IllegalTokenTextCh
eck' waits for comment type token ('COMMENT_CONTENT') and should override 'isCommentNodesRequired()' method to return 'true'
        at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:266)
        at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:221)
        at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:162)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:138)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:176)
        ... 3 more
Checkstyle ends with 1 errors.
```

Definitely a bug :) Currently can't check comment contents for potentially insecure content at my company!

**Comment by Qix-** [comment] 2016-05-03 07:52
Another bug that may/may not be related"

```
		<module name="IllegalTokenText">
			<property name="format" value="^[cbdefghijklnrtuv]{16,44}" />
			<property name="ignoreCase" value="false" />
			<property name="message" value="A potential Yubikey was found in a string, comment, or identifier." />
			<property name="tokens" value="STRING_LITERAL, IDENT" />
		</module>
```

Identifiers are checked:

```java
private String hknhfjbrjnlnldnhcujvddbikngjrtgh;
```

but not string literals:

```java
private String foobar = "hknhfjbrjnlnldnhcujvddbikngjrtgh";
```

**Comment by rnveach** [comment] 2016-05-03 11:45
I can reproduce the exception in 6.18, and the config is:
````
$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="IllegalTokenText">
            <property name="tokens" value="COMMENT_CONTENT" />
        </module>
    </module>
</module>
````

**Comment by rnveach** [comment] 2016-05-03 11:47
@Qix- 
> but not string literals:
> > private String foobar = "hknhfjbrjnlnldnhcujvddbikngjrtgh";

You forgot that string literals start and end with the quotes.
Try something like:
`<property name="format" value="^&quot;?[cbdefghijklnrtuv]{16,44}&quot;?" />`

**Comment by Qix-** [comment] 2016-05-03 11:57
@rnveach straight from the docs:

```xml
<module name="IllegalTokenText">
    <property name="tokens" value="STRING_LITERAL"/>
    <property name="format" value="a href"/>
</module>
```

No quotes there :/ Wouldn't make sense to be honest.

**Comment by rnveach** [comment] 2016-05-03 12:30
@Qix- 
The reason there is no quotes for that example, is it is looking for `a href` anywhere in that string. It can be at the start, 1 character from the start, middle, or end. Anywhere.
Since your example is using `^`, you are forcing the search to only the start of the string literal. If you use the `-t` option from CheckStyle's CLI, you will see quotes are part of the string literal and thats why you have to account for them.
````
$ cat TestClass.java
public class TestClass {
    private String foobar = "hknhfjbrjnlnldnhcujvddbikngjrtgh";
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="IllegalTokenText">
            <property name="format" value="^&quot;[cbdefghijklnrtuv]{16,44}" />
            <property name="ignoreCase" value="false" />
            <property name="message" value="A potential Yubikey was found in a string, comment, or identifier." />
            <property name="tokens" value="STRING_LITERAL, IDENT" />
        </module>
    </module>
</module>

$ java -jar checkstyle-6.18-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:2:29: A potential Yubikey was found in a string, comment, or identifier. [IllegalTokenText]
Audit done.
Checkstyle ends with 1 errors.
````

**Comment by romani** [comment] 2016-05-03 12:54
we need to update the Check to override this method.

Unrelated discussion is moved to https://groups.google.com/forum/#!topic/checkstyle/D9fcAs40ILM

**Comment by rnveach** [comment] 2016-05-03 13:37
The issue is with any checks that have `TokenUtils.getAllTokenIds` as acceptable tokens. The issue can be seen with `IllegalTokenCheck`.
````
$ cat TestClass.java
public class TestClass {
    void method() {
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="IllegalTokenCheck">
<property name="tokens" value="COMMENT_CONTENT" />
</module>
    </module>
</module>

$ java -jar checkstyle-6.18-all.jar -c TestConfig.xml TestClass.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Check 'com.puppycrawl.tools.checkstyle.checks.coding.IllegalTokenCheck' waits for comment type token ('COMMENT_CONTENT') and should override 'isCommentNodesRequired()' method to return 'true'
    at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:376)
    at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:138)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:337)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:170)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Check 'com.puppycrawl.tools.checkstyle.checks.coding.IllegalTokenCheck' waits for comment type token ('COMMENT_CONTENT') and should override 'isCommentNodesRequired()' method to return 'true'
    at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:266)
    at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:221)
    at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:162)
    at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:138)
    at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:371)
    ... 3 more
Checkstyle ends with 1 errors.
````

**Comment by romani** [comment] 2016-05-08 12:36
fix is merged.

**Closed by romani** 2016-05-08 12:36 UTC
Labels: approved, bug
