### ISSUE TITLE
Support for Default IntelliJ IDEA Formatting in CustomImportOrder or ImportOrder

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#525] opened 2014-12-20 01:31 UTC
Default formatting in IntelliJ looks like as follows:

```
all other imports
<blank line>
javax.* in alphabetical order
java.* in alphabetical order
<blank line>
static imports in alphabetical order
```

Right now, it is not possible to sort `java` and `javax` separately without blank line in-between.
##

**Comment by ivanov-alex** [comment] 2015-07-27 10:47
@mkordas I propose addressing this problem by disabling "blank line" check in CustomImportOrder (separateLineBetweenGroups=false).
Please see below proposed configuration:
```xml
<module name="CustomImportOrder">
    <property name="customImportOrderRules"
        value="THIRD_PARTY_PACKAGE###SPECIAL_IMPORTS###STANDARD_JAVA_PACKAGE###STATIC"/>
    <property name="specialImportsRegExp" value="^javax\."/>
    <property name="standardPackageRegExp" value="^java\."/>
    <property name="sortImportsInGroupAlphabetically" value="true"/>
    <property name="separateLineBetweenGroups" value="false"/>
</module>
```

**Comment by romani** [comment] 2015-07-29 06:47
@mkordas, are you ok with such solution ?

**Comment by mkordas** [comment] 2015-07-30 20:12
Not really - what I want would be rather something like that:
```xml
<property name="customImportOrderRules"
        value="THIRD_PARTY_PACKAGE###SPECIAL_IMPORTS#STANDARD_JAVA_PACKAGE###STATIC"/>```
where `###` means blank line and single `#` no blank line.

It's because I definitely want blank line between STANDARD_JAVA_PACKAGE and STATIC. The only place I don't want blank line is between java and javax.

**Comment by romani** [comment] 2015-09-09 13:14
IntelijIdea format is multi-line:
```
all other imports
<blank line>
javax.* in alphabetical order
java.* in alphabetical order
<blank line>
static imports in alphabetical order
```

if we force them to be single line , it will looks like:
```all other imports###<blank line>###javax.* in alphabetical order###java.* in alphabetical order###<blank line>###static imports in alphabetical order```

So format will looks like (in out notation):
ALL_IMPORTS###BLANK_LINE###STANDARD###BLANK_LINE##STATIC

So we need to introduce new macros - BLANK_LINE , that is ok.
It will conflict with separateLineBetweenGroups option, and we need to update that option logic to be ignored completely if user use at least one BLANK_LINE macros.

**Comment by mkordas** [comment] 2015-09-14 21:05
> So format will looks like (in out notation):
ALL_IMPORTS###BLANK_LINE###STANDARD###BLANK_LINE##STATIC

What about `java` and `javax` groups?

**Comment by ivanov-alex** [comment] 2015-09-15 13:17
With current functionality we can use SPECIAL for one of the java groups:
```xml
<module name="CustomImportOrder">
    <property name="customImportOrderRules"
        value="THIRD_PARTY_PACKAGE###BLANK_LINE###SPECIAL_IMPORTS###BLANK_LINE###STANDARD_JAVA_PACKAGE###BLANK_LINE###STATIC"/>
    <property name="specialImportsRegExp" value="^javax\."/>
    <property name="standardPackageRegExp" value="^java\."/>
    <property name="sortImportsInGroupAlphabetically" value="true"/>
    <property name="separateLineBetweenGroups" value="false"/>
</module>
```

**Comment by romani** [comment] 2017-03-18 17:31
pre-assigned to @GabrielBercaru

**Comment by GabrielBercaru** [comment] 2017-03-18 20:35
I am on it.

**Comment by GabrielBercaru** [comment] 2017-04-16 19:37
I have read the documentation of `ImportOrderCheck.java` and applied the configurations described there for formatting IntelliJ IDEA imports. I have tried to change the `CustomImportOrder` module inside `checkstyle_checks.xml` to match the default IntelliJ imports formatting.

I have added a new test case inside `CustomImportOrderCheckTest.java` (`public void testIntelliJ() throws Exception { /*...*/ }`), and its corresponding input, a new input file called `InputCustomImportOrderIntelliJ.java`. Is this good so far?

**Comment by romani** [comment] 2017-04-17 17:15
@GabrielBercaru , result of you work should be:
1) new UTs for both Checks (with inputs that matching default IntelijIdea of certain version). Beware that IntelijIdea could change default behavior also, so you need to define on what IntelijIdea version you did configs.
2) update for xdoc examples to let users know how to make it as such configuration example is in demand by users.

**Comment by romani** [comment] 2017-07-03 18:37
connection with @GabrielBercaru   is lost, PR is closed as incomplete.
If smb want to continue from scratch or from where @GabrielBercaru  is finished, please be welcome .

**Comment by Abhishek-kumar09** [comment] 2020-04-01 11:51
Hello @romani 
Should I start working on this logic https://github.com/checkstyle/checkstyle/issues/525#issuecomment-138905442.

Secondly, we need to add this configuration particularly for IntelliJ IDEA, as configuration below is true for eclipse https://github.com/checkstyle/checkstyle/blob/230e3650c2e718e2fb9eee11d56b8814f7fa06bd/config/checkstyle_checks.xml#L474

Should we  make a new configuration file that works specially for IntelliJ like `IntelliJ_Checks.xml`.
Please guide.

**Comment by Abhishek-kumar09** [comment] 2020-04-04 09:28
@romani @rnveach @strkkk ping!
This is regarding adding rules for restricting blank-lines between two or more groups in `ImportOrder`. 
I think we can attain this goal in two ways.
1. using a `#` between groups that need not to be sepearted by blank line(like customImportOrder), the configuration may look like:
For setting up the configuration to allow blankLines between groups except between `javax` and `java`.
```
<module name="ImportOrder">
  <property name="groups" value="*,javax,#,java"/>
  <property name="ordered" value="true"/>\
  <property name="option" value="bottom"/>
  <property name="separated" value="true"/>
  <property name="sortStaticImportsAlphabetically" value="true"/>
</module>
```
2. using a new property (something like combineGroups) that doesn't allow blankLine separation,
```
<module name="ImportOrder">
  <property name="groups" value="*,javax,java"/>
  <property name="combineGroups" value="javax,java" />
  <property name="ordered" value="true"/>\
  <property name="option" value="bottom"/>
  <property name="separated" value="true"/>
  <property name="sortStaticImportsAlphabetically" value="true"/>
</module>
```

Please guide over any better idea you have or command me to choose an idea between the two to start with.

**Comment by romani** [comment] 2020-04-19 14:56
This issue is already addressed , it was fixed in scope of #5510

https://checkstyle.org/config_imports.html#ImportOrder_Examples , search for "To configure the check so that it matches default IntelliJ IDEA formatter". 
It is not very elegant support as extra module/filter should be used to suppress violations.

the only good solution is to implement new Check that counts design of famous IDEs for import order (sequence of empty lines and regexp for import). 
if somebody need such Check - please create new issue on it to discuss design.

**Closed by romani** 2020-04-19 14:56 UTC
Labels: approved

**Comment by romani** [comment] 2020-04-19 15:10
@Abhishek-kumar09 ,  [CustomImportOrder](https://checkstyle.org/config_imports.html#CustomImportOrder) is very special Check.
There is a problem in design of CustomImportOrder Check ... it is was created for Google style coverage specifically, so matching it default IDEAs format is wrong from the beginning. Users should use ImportOrder Check.

you proposal to have new rule `BLANK LINE`(`#`) will conflict with `separateLineBetweenGroups` property, it will be hard for user understand what is expected behavior when `separateLineBetweenGroups=true` and `customImportOrderRules` has blank lines in it. As `customImportOrderRules` is sequence of groups.

To avoid making CustomImportOrder even more complicated to configure .... it is better to do new Check, so user will choose himself what Check to use.

**Comment by Abhishek-kumar09** [comment] 2020-04-19 17:46
I think for the Project [Reconcile formatters](https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2020-Project-Ideas#project-name-reconcile-formatters-of-eclipse--netbeans-and-intellij-idea-ides-by-checkstyle-config), it is an important step and a new check is definitely needed that can easily checks import order based on default editor's formatters without much complexity.
