### ISSUE TITLE
Google Style Checks

### ISSUE THREAD

**Issue by icirellik** [checkstyle/checkstyle#3742] opened 2017-01-19 14:51 UTC
The following line excludes using `e` as an exception name. Though the google style guide, I cannot find any reference to this claim.

https://github.com/checkstyle/checkstyle/blob/258c440a011f1845a2095e5b6361ae9639849f1f/src/main/resources/google_checks.xml#L125

Should this line be updated to match the current google style guide?

**Comment by jochenvdv** [comment] 2017-01-19 15:21
Yes. This is a duplicate of issue #3702.

**Comment by rnveach** [comment] 2017-01-19 15:42
Closing as a duplicate

**Closed by rnveach** 2017-01-19 15:42 UTC
