### ISSUE TITLE
AnnotationLocation: Remove unused tokens

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6416] opened 2019-02-10 09:55 UTC
From #6379 

https://checkstyle.org/config_annotation.html#AnnotationLocation

Acceptable tokens for `AnnotationLocationCheck` [are
](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/AnnotationLocationCheck.java#L238)
```
    public int[] getAcceptableTokens() {
        return new int[] {
            TokenTypes.CLASS_DEF,
            TokenTypes.INTERFACE_DEF,
            TokenTypes.PACKAGE_DEF,
            TokenTypes.ENUM_CONSTANT_DEF,
            TokenTypes.ENUM_DEF,
            TokenTypes.METHOD_DEF,
            TokenTypes.CTOR_DEF,
            TokenTypes.VARIABLE_DEF,
            TokenTypes.PARAMETER_DEF,
            TokenTypes.ANNOTATION_DEF,
            TokenTypes.TYPECAST,
            TokenTypes.LITERAL_THROWS,
            TokenTypes.IMPLEMENTS_CLAUSE,
            TokenTypes.TYPE_ARGUMENT,
            TokenTypes.LITERAL_NEW,
            TokenTypes.DOT,
            TokenTypes.ANNOTATION_FIELD_DEF,
        };
    }
```
Tokens `LITERAL_THROWS`, `DOT`, `IMPLEMENTS_CLAUSE` shouldn't be here.
They have no annotation tokens among children.
Tokens `TYPECAST` and `LITERAL_NEW` may have annotations, but they aren't fit to the check:
```
Object var = @Ann
                    new Type();
return (@Ann
          ) var;
```
This code will compile, but no one will use this style.
For now, `AnnotationLocationCheck` ignores these tokens, although they are acceptable.

**Comment by rnveach** [comment] 2019-02-10 14:57
@pbludov 
> LITERAL_THROWS
> They have no annotation tokens among children.

The java grammar says annotations can appear right after the throws token.
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammar/java.g#L947

Are you still saying there is no way for the check to validate them? Is this just a bug that we need fix suppport for them?

Example:
````
void method() throws @Annotation Exception {
````
````
    |  |--LITERAL_THROWS -> throws [2:18]
    |  |  |--ANNOTATIONS -> ANNOTATIONS [2:25]
    |  |  |  `--ANNOTATION -> ANNOTATION [2:25]
    |  |  |      |--AT -> @ [2:25]
    |  |  |      `--IDENT -> Annotation [2:26]
    |  |  `--IDENT -> Exception [2:37]
````

> This code will compile, but no one will use this style.

If the code can compile and the check can create violations on them, then I think they should stay. It is not up to use to say who's style will be used or not. Check creator went through our process to create the check which isn't always easy.

**Comment by pbludov** [comment] 2019-02-10 15:18
@rnveach can you please spot a repository with code like that:
```
void method foo() throws
  @Ann("foo")
Exception {
}
```
?

**Comment by romani** [comment] 2019-02-11 03:16
Annotations are in use over code more and more, especially to do hints to some tools or even use codegeneration. But it is up to us to decide what Check should cover it. It is clear that it not always reasonable to have a check that can do all token support, some cases we can skip also.

**Comment by rnveach** [comment] 2019-02-11 16:30
> can you please spot a repository with code like that

No because there are too many repositories and too many private projects and such. It still doesn't mean someone would not use it. There are also other options in check to allow some singleline annotations in that scenario.
Even doing a search of the normal regression repositories show that annotations in exceptions is rarely used. http://rveach.no-ip.org/checkstyle/regression/reports/227/ . Only 2 other projects use it and even then only in their tests.

The history of these tokens goes back to https://github.com/checkstyle/checkstyle/pull/604#issuecomment-73180885 point number 3. They were added without any tests, so that may be why they may or may not work correctly.
Since @romani asked for them to be added, I am fine with them being removed if he wants to go that way.

**Comment by pbludov** [comment] 2019-02-15 19:06
> please define strict list of tokens you think should be removed, to make it clear why we remove each token.
```
           TokenTypes.TYPECAST,
            TokenTypes.LITERAL_THROWS,
            TokenTypes.IMPLEMENTS_CLAUSE,
            TokenTypes.TYPE_ARGUMENT,
            TokenTypes.LITERAL_NEW,
            TokenTypes.DOT,
```
* TYPECAST
```
( @ann
Foo &
  @Ann
Bar) smth;`
```

 * LITERAL_THROWS
```
void method foo() throws
  @Ann("foo")
Exception {
}
```
* IMPLEMENTS_CLAUSE
```
class Foo implements
  @Ann
Bar
```
* TYPE_ARGUMENT
```
class Foo<
  @Ann
Bar>
```
* LITERAL_NEW
```
return
       @Ann
  smth;
```
* TokenTypes.DOT ???
I have no idea what it should be. `varargs` perhaps?

**Comment by romani** [comment] 2019-02-18 01:38
I am ok to remove such Tokens, I extended comment at https://github.com/checkstyle/checkstyle/issues/6416#issuecomment-462210043 with details on a reason.

All that tokens are not related to original idea of Check `Check enforce to locate annotations immediately after documentation block and before target element, annotation should be located on separate line from target element.` ... attention to `documentation block`. 
Line wrapping that is possible with annotation usage should be covered by some other Check, I am not ready even tell about possible design for new Check .... live/users will show us what might be valuable in such validations.

I am ok to remove proposed list of tokens and cause breaking compatibility.

@rnveach , please review this issue one more time and approve it.

**Comment by rnveach** [comment] 2019-02-18 02:00
Fix was merged

**Closed by rnveach** 2019-02-18 02:00 UTC
Labels: approved, breaking compatibility

**Comment by Vampire** [comment] 2019-02-22 14:46
@romani with that reasoning applied, shouldn't `PARAMETER_DEF` also be removed and `VARIABLE_DEF` only support fields and not local variable definitions? Because both do not have documentation comments in front.

**Comment by romani** [comment] 2019-02-23 05:44
@Vampire ,
Please move this to separate issue, and lets discuss on examples why we need to remove certain token , each token separately.
