### ISSUE TITLE
Add support for regular expression in RegexpHeader spanning mutliple lines

### ISSUE THREAD

**Issue by krichter722** [checkstyle/checkstyle#5298] opened 2017-11-25 20:30 UTC
`/var/tmp $ javac YOUR_FILE.java`:

```
[no output]
```

`/var/tmp $ cat YOUR_FILE.java`:

```
/*
 * a
 * b
 */
package richtercloud.maven.checkstyle.plugin.multiline;

/**
 *
 * @author richter
 */
public class NewMain {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
    }
    
}
```

`/var/tmp $ cat config.xml`:

```
<?xml version="1.0"?>
 <!DOCTYPE module PUBLIC
   "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
   "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<module name="Checker">
    <module name="RegexpHeader">
        <property
            name="header"
            value="(^/\*\n \* a\n \* b\n \*/$)|(^/\*\n \* a\n \* c\n \*/$)"/>
        <property name="fileExtensions" value="java"/>
    </module>
</module>
```

`/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.4-all.jar -c config.xml YOUR_FILE.java`:

```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module RegexpHeader - Cannot set property 'header' to '(^/\*\n \* a\n \* b\n \*/$)|(^/\*\n \* a\n \* c\n \*/$)' in module RegexpHeader
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:463)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:186)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:519)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:437)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:210)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Cannot set property 'header' to '(^/\*\n \* a\n \* b\n \*/$)|(^/\*\n \* a\n \* c\n \*/$)' in module RegexpHeader
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:227)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:179)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:458)
	... 4 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2127)
	at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2108)
	at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean.java:437)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:217)
	... 6 more
Caused by: java.lang.IllegalArgumentException: line 1 in header specification is not a regular expression
	at com.puppycrawl.tools.checkstyle.checks.header.RegexpHeaderCheck.postProcessHeaderLines(RegexpHeaderCheck.java:158)
	at com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck.loadHeader(AbstractHeaderCheck.java:183)
	at com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck.setHeader(AbstractHeaderCheck.java:154)
	at com.puppycrawl.tools.checkstyle.checks.header.RegexpHeaderCheck.setHeader(RegexpHeaderCheck.java:177)
	... 14 more
Caused by: java.util.regex.PatternSyntaxException: Unclosed group near index 5
(^/\*
     ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.accept(Pattern.java:1813)
	at java.util.regex.Pattern.group0(Pattern.java:2908)
	at java.util.regex.Pattern.sequence(Pattern.java:2051)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at com.puppycrawl.tools.checkstyle.checks.header.RegexpHeaderCheck.postProcessHeaderLines(RegexpHeaderCheck.java:154)
	... 17 more
Checkstyle ends with 1 errors.
```

---------------

`checkstyle` currently doesn't support regular expression which span multiple lines in `RegexpHeader`. In order to validate that files start with a header with has either one or another set of copyright holders which span multiple rows, it's necessary to have this feature.

It'd be great to support those regular expression in general because they offer great flexibility and to profit from the complete concept of regular expressions.

The current feedback that a valid regular expression fails due to `Unclosed group near index ...` isn't very intuitive.

**Comment by romani** [comment] 2017-11-25 23:50
this is very tiny nuance ..... it was tricky even for me .... 

http://checkstyle.sourceforge.net/config_header.html#RegexpHeader
`header` - `... Individual header lines must be separated by the string "\n" ...`

So we internally split one line of regexp that use provide by multiple regexps by "\n"
that is why you have  
`Caused by: java.util.regex.PatternSyntaxException: Unclosed group near index 5 (^/\*`
as your `(^/\*\n \* a\n \* b\n \*/$)|(^/\*\n \* a\n \* c\n \*/$)` transformed to several regexps:
`(^/\*`
` \* a`
` \* b`
` \*/$)|(^/\*`
....

so standard java regexp compile is right -  `(^/\*` - is not valid regexp.

You artificial header should be validated as: `value="^/\*\n \* a\n \* (b|c)\n \*/$"` but I do understand that it real case it is not ok if header is completely different.

So this issue is invalid, but it shows how bad is our documentation (sorry about this).
But if you know how to make it better, please suggest how to make it more clear https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/config_header.xml#L186

I am closing this issue, but for documentation update feel free to open new issue (your are welcome with PR/fix too).
If you want to support your use case, we need to think about new feature or even new Check - please open new issue to discuss but please share more real life examples.

**Closed by romani** 2017-11-25 23:50 UTC
