### ISSUE TITLE
Indentation properties not applied properly to lambdas

### ISSUE THREAD

**Issue by zenglian** [checkstyle/checkstyle#6682] opened 2019-04-20 15:53 UTC
@rnveach In below example, it passed the first lamda, but failed at the second. Using google_checks, version=8.16

```
import java.time.Instant;
import java.util.UUID;
import java.util.function.Supplier;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class LazyLog {
  public static void main(String[] args) {
    info("arg1 = {}, arg2 = {}", () -> {
      System.out.println(Instant.now().toString() + " constructing arg 1");
      return UUID.randomUUID();
    }, () -> {
      System.out.println(Instant.now().toString() + " constructing arg 2");
      return UUID.randomUUID();
    });
  }

  @SafeVarargs
  private static void info(final String message, final Supplier<Object>... suppliers) {
    if (log.isInfoEnabled()) {
      Object[] args = new Object[suppliers.length];
      for (int i = 0; i < suppliers.length; i++) {
        args[i] = suppliers[i].get();
      }
      log.info(message, args);
    }
  }
}
```

**Comment by rnveach** [comment] 2019-04-20 16:07
@zenglian Is this a duplicate of https://github.com/checkstyle/checkstyle/issues/3182 ? It looks awfully similar.

**Closed** 2019-04-21 05:23 UTC
Labels: indentaion
