### ISSUE TITLE
JavadocMethod: Unable to get class information for @throws tag

### ISSUE THREAD

**Issue by osiegmar** [checkstyle/checkstyle#5088] opened 2017-09-07 20:11 UTC
Starting with [checkstyle 6.17](http://checkstyle.sourceforge.net/releasenotes.html#Release_6.17) (and also including 8.2), I often get this type of error:

`Unable to get class information for @throws tag 'XXXException'. [JavadocMethod]`

For example, using the `LANG_3_6` tag of commons-lang (git://git.apache.org/commons-lang.git)(https://github.com/apache/commons-lang):
checkstyle.xml  is [here](https://github.com/apache/commons-lang/blob/master/checkstyle.xml).
ConcurrentUtils.java is [here](https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/concurrent/ConcurrentUtils.java).
With checkstyle 6.16.1:
```
java -jar ~/checkstyle-6.16.1-all.jar -c checkstyle.xml \
    src/main/java/org/apache/commons/lang3/concurrent/ConcurrentUtils.java
Starting audit...
Audit done.
```

With checkstyle 8.2:
```
java -jar ~/checkstyle-8.2-all.jar -c checkstyle.xml \
    src/main/java/org/apache/commons/lang3/concurrent/ConcurrentUtils.java
Starting audit...
[ERROR] /tmp/commons-lang/src/main/java/org/apache/commons/lang3/concurrent/ConcurrentUtils.java:123:8: Unable to get class information for @throws tag 'ConcurrentRuntimeException'. [JavadocMethod]
[ERROR] /tmp/commons-lang/src/main/java/org/apache/commons/lang3/concurrent/ConcurrentUtils.java:197:8: Unable to get class information for @throws tag 'ConcurrentRuntimeException'. [JavadocMethod]
[ERROR] /tmp/commons-lang/src/main/java/org/apache/commons/lang3/concurrent/ConcurrentUtils.java:297:8: Unable to get class information for @throws tag 'ConcurrentRuntimeException'. [JavadocMethod]
Audit done.
Checkstyle ends with 3 errors.
```

I checked the release notes of 6.17 but couldn't find something that is obvious to me.

**Comment by romani** [comment] 2017-09-08 12:32
yes, strange, I do not see obvious reason too for this issue to appear.

BUT, this functionality(searching types in classpath) is deprecated in Checkstyle as it does not work.

For this Check we need to update it to skip reporting such violations.

**Comment by dmitry-timofeev** [comment] 2017-10-18 09:55
Have the same issue. In my project, Checkstyle checks are bound to 'validate' phase of a Maven build lifecycle, therefore, Checkstyle performs its checks _before_ compilation. So when I run
```
$ mvn clean compile
[WARN] … Unable to get class information for @throws tag 'FooBarException'. [JavadocMethod]
…
```
I get warnings that Checkstyle can't find the classes. But after that the warnings are gone, unless you clean the compiled classes again:
```
$ mvn validate
```

**Comment by romani** [comment] 2017-11-15 16:08
@dmitry-timofeev

>Checkstyle performs its checks before compilation. 

This project is only to track issues in checkstyle library, not plugins. That is we demand to use our CLI to reproduce problems.
Your post if off topic.
I recommend you to review your pom file, as if checkstyle is running on compile phase, it is instructed to do in pom. If any problems please report issue to maven-checkstyle-plugin project.

**Comment by dmitry-timofeev** [comment] 2017-11-15 17:26
@romani , 

> That is we demand to use our CLI to reproduce problems.

The problem **is** reproducible if you run Checkstyle as a standalone app from the command line, you get the same report as if you run it via the plugin:
```
$ java -jar ~/Downloads/checkstyle-8.4-all.jar -c checkstyle-rules.xml Foo.java
…
[WARN] … Unable to get class information for @throws tag 'FooBarException'. [JavadocMethod]
…
```

If Checkstyle is supposed to work on _source_ files, rather than on compiled classes, then it doesn't make sense if the phase to which the checks are bound makes any difference, does it?

**Comment by romani** [comment] 2017-11-15 19:40
> The problem is reproducible if you run 

yes, exactly as original report stated, nothing new.

> sense if the phase to which the checks are bound makes any difference, does it?

yes, it does, but there are a lot of nuances of classpath on particular phase.
No mater what, one day all classpath related functionality will be removed completely from all Checks. Current implementation search in classpath is too unreliable.

**Comment by krichter722** [comment] 2018-05-23 01:53
@rnveach the current state of the example didn't demonstrate the issue right away. I amended the only commit, so that the issue occurs within the build command.

**Comment by krichter722** [comment] 2018-06-01 01:58
@rnveach Could you reproduce the issue with the SSCCE?

**Comment by krichter722** [comment] 2018-08-15 11:04
@rnveach Another ping, sorry for it in case you're aware and too busy. I pushed another commit to the SSCCE reproducing the issue with 8.12.

**Comment by krichter722** [comment] 2018-09-26 18:16
@rnveach I reproduced the issue on GitLab CI based on the Docker image `maven:latest` so that you should be able to reproduce it locally at least inside Docker, example output is available at https://gitlab.com/krichter/maven-checkstyle-plugin-clazz-information/-/jobs/101934977.

The issue can be triggered by adding a `@throws IllegalArgumentException` to a method which doesn't throw `IllegalArgumentException` in the signature.

**Comment by romani** [comment] 2018-10-23 05:00
@krichter722, sorry for delay in reply.
Classpath resolving is deprecated in Checkstyle. Check works for in mode as-is.
This Check will be completely reimplemented one day in future and in new version it will completely loose this ability to work with types. Checkstyle is not type aware tool.

If you see how to fix current implementation of Check, we can merge a fix.

**Comment by ctubbsii** [comment] 2019-06-19 19:38
> The issue can be triggered by adding a `@throws IllegalArgumentException` to a method which doesn't throw `IllegalArgumentException` in the signature.

Similarly, it can also be triggered when you document a `@throws SubClassException` when the method declares `throws SuperClassException`. Example: documenting `@throws ClassNotFoundException` and `@throws InstantiationException` separately when the method merely declares their common super-type: `throws ReflectiveOperationException`.

What's weird when I encountered this is that the error message (using checkstyle 8.21) actually indicated the error was with the exception which followed these... a completely unrelated checked exception which was declared and also documented in the javadoc in the same way it was declared thrown.

**Comment by romani** [comment] 2019-06-23 05:06
@ctubbsii, can you reproduce issue on single file and report issue on this, we might be able to resolve it

**Comment by ctubbsii** [comment] 2019-06-24 22:30
> @ctubbsii, can you reproduce issue on single file and report issue on this, we might be able to resolve it

I can't seem to be able to reproduce it. :frowning_face:
I'll provide a test case if it occurs again.

**Comment by romani** [comment] 2019-06-25 05:35
let me close this issue to let new issue arrive.

**Closed by romani** 2019-06-25 05:35 UTC
Labels: approved, javadoc

**Comment by unhuman** [comment] 2019-06-28 15:25
I encountered this issue and was thankful to find this thread.

Looks like if there's a description after the throws that it evokes this problem

For example:

`@throws SomeException`

works just fine, but...

`@throws SomeException if something happened`

Gives the error above...  Which is certainly confusing.

**Comment by romani** [comment] 2019-06-29 14:18
@unhuman , please try to reproduce issue by our CLI on latest version.

**Comment by krichter722** [comment] 2019-08-30 14:04
@romani I can reproduce the issue on the CLI and with up-to-date version on GitLab CI as well (link above). On the CLI the output is (I don't know how to get rid of the german output, the messages say the same as the posted english exception messages):

```
> java -jar /tmp/checkstyle-8.23-all.jar -c src/checkstyle/fileupload_checks.xml src/main/java/richtercloud/maven/checkstyle/plugin/clazz/information/Interface0.java 
Beginne Prüfung...
[ERROR] /mnt/data/home/examples/checkstyle/maven-checkstyle-plugin-clazz-information/src/main/java/richtercloud/maven/checkstyle/plugin/clazz/information/Interface0.java:25:8: Kann für das Tag 'richtercloud.maven.checkstyle.plugin.clazz.information.Exception0' keine Klasseninformation zu @throws laden. [JavadocMethod]
[ERROR] /mnt/data/home/examples/checkstyle/maven-checkstyle-plugin-clazz-information/src/main/java/richtercloud/maven/checkstyle/plugin/clazz/information/Interface0.java:27:27: Kann für das Tag 'Exception0' keine Klasseninformation zu @throws laden. [JavadocMethod]
Prüfung beendet.
Checkstyle endet mit 2 Fehlern.
```

**Comment by romani** [comment] 2019-08-30 14:41
@krichter722 , I appreciate your help to reproduce issue.
Let's open new issue and just follow issue template, it will show you how to make out put in English. Please try to minimize config to have only one Check and remove from input files all non required code to reading it

**Comment by krichter722** [comment] 2019-08-31 07:55
@romani In #6802 which has been closed without a solution because the reporter used the workaround to downgrade the Maven plugin you said

> no way to disable class loading: https://checkstyle.org/config_javadoc.html#JavadocMethod

(https://github.com/checkstyle/checkstyle/issues/6802#issuecomment-502491764). Does it make sense to open a new bug, then? For me it seems like a regression was introduced which makes classloading not working for the described cases. If it can't be disabled, there's no sense in a new report, right? That being said, I'm looking forward to contributing to getting this fixed and open yet another report with the template.

**Comment by romani** [comment] 2019-08-31 14:52
>which has been closed without a solution 

Looks like I closed issue by mistake, as I was able to reproduce it, but after some other discussion, I was in impression that issue is incomplete.

>regression was introduced which makes classloading not working for the described cases

It never worked well, and will not work, that is why we deprecating it.

>If it can't be disabled, there's no sense in a new report, right?

We can simply remove classpath resolution at all from Check as it produce not reliable functionality.

>I'm looking forward to contributing to getting this fixed and open yet another report with the template.

Thanks a lot for help, let's close all old issues, create new with steps to reproduce, and clear goal - disable completely classpath resolution, to avoid false positives. As second maintainer agree on it, I will help to expedite it, we will welcome a PR from you.

**Comment by krichter722** [comment] 2019-08-31 15:53
Thanks for your detailed feedback. Looks like the solution is already planned or in progress. I'll simply no longer use the feature in question. Btw, I didn't have a clue that this functionality was deprecated. Maybe it can be made more clear - I have no idea how, though.

I'll probably have no resources for supporting you in the removal of classpath resolution. However, I appreciate your invitation to send a PR.

**Comment by jamesonwilliams** [comment] 2020-01-21 07:55
I encountered this issue while applying Checkstyle via a plugin in an Android `build.gradle`.

When `apply plugin 'checkstyle'` is used, the Checkstyle version is determined by the Gradle version. (See [discussion](https://stackoverflow.com/a/47728884/695787).) I was using Gradle = `5.4.1`, so [I was using Checkstyle `8.17`](https://github.com/gradle/gradle/blob/v5.4.1/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java#L39).

To use the latest version of Checkstyle - the one that [includes a fix for this current issue with `JavadocMethod`](https://github.com/checkstyle/checkstyle/issues/7329), I added the following in my Gradle script:
```
checkstyle {
    toolVersion '8.28' // Or the current latest.
}
```
