### ISSUE TITLE
NullPointerException at FinalLocalVariableCheck.findClassOrMethodInWhichItIsDefined

### ISSUE THREAD

**Issue by Bhavik3** [checkstyle/checkstyle#1257] opened 2015-06-28 16:09 UTC
Configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.1//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_1.dtd">
<module name="Checker">
    <property name="fileExtensions" value="java"/>
    <module name="TreeWalker">
        <module name="FinalLocalVariable"/>
    </module>
</module>
```

File to be Analyzed:
````
enum InputFinalLocalVariableNameShadowingEnum{
    test;
    final String foo1 = "error";
    InputFinalLocalVariableNameShadowingEnum()
    {
        String foo = foo1;
        foo += foo1;
    }
}
````

Output on CLI:
```
Jun 28, 2015 9:31:49 PM com.puppycrawl.tools.checkstyle.TreeWalker processFiltered
SEVERE: NullPointerException occurred during the analysis of file testing.java.
java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.findClassOrMethodInWhichItIsDefined(FinalLocalVariableCheck.java:266)
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.isSameVariables(FinalLocalVariableCheck.java:281)
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.removeVariable(FinalLocalVariableCheck.java:312)
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.visitToken(FinalLocalVariableCheck.java:173)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:393)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:482)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:322)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:195)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:260)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:249)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:90)

Starting audit...
/home/bhavik/Documents/checkstyle-rough-work/testing.java:0: Got an exception - null
Audit done.
Checkstyle ends with 1 errors.
```

**Comment by romani** [comment] 2015-06-28 17:04
merged, thanks a lot !!!

**Comment by JanPesta** [comment] 2015-09-24 22:11
I have to reopen this - I have still NPX in FinalLocalVariableCheck with 6.10.1
```
d:\CheckstyleTest>java -jar checkstyle-6.10.1-all.jar -c testconfig.xml EnumTest.java
Exception in thread "main" java.lang.NullPointerException
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.findClassOrConstructorOrMethodInWhichItIsDefined(FinalLocalVariableCheck.java:283)
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.isSameVariables(FinalLocalVariableCheck.java:299)
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.removeVariable(FinalLocalVariableCheck.java:330)
        at com.puppycrawl.tools.checkstyle.checks.coding.FinalLocalVariableCheck.visitToken(FinalLocalVariableCheck.java:203)
        at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:392)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:503)
        at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:334)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:209)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:265)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:271)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:121)
```
Class file:
```
package com.enumtest;

public enum EnumTest 
{
    FIRST,
    SECOND,
    THIRD,
    FOURTH;

    /**
     * @return next state bringing the system down
     */
    public EnumTest getDownState()
    {
        return downState;
    }

    /**
     * @return next state bringing the system up
     */
    public EnumTest getUpState()
    {
        return upState;
    }

    private EnumTest downState;
    private EnumTest upState;

    static
    {
        EnumTest downState = null;
        for (final EnumTest state : EnumTest.values())
        {
            state.downState = downState;
            if (downState != null)
            {
                downState.upState = state;
            }
            downState = state;
        }
    }
}
```
Configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
  <metadata name="net.sf.eclipsecs.core.comment" value="required"/>
  <property name="severity" value="warning"/>
  <module name="TreeWalker">
    <metadata name="net.sf.eclipsecs.core.comment" value="required; tab: 4; file extension: java"/>
    <property name="tabWidth" value="4"/>
    <module name="FinalLocalVariable">
      <metadata name="net.sf.eclipsecs.core.comment" value="variables (parameters not included)"/>
    </module>
  </module>
</module>
```

**Comment by romani** [comment] 2015-09-24 22:39
Thanks a lot for reporting this in clear form !

**Comment by rnveach** [comment] 2015-09-24 23:36
I will fix this.
The issue is FinalLocalVariableCheck is looking for the top class when it finds a variable with another assignment (in example "downState = state;"), and is skipping over the Enumeration class definition and going past the head of the tree, resulting in a NPE.

**Comment by romani** [comment] 2015-09-25 12:56
merged.

**Closed by romani** 2015-09-25 12:56 UTC
Labels: approved, high demand
