### ISSUE TITLE
Serious performance problem in All Javadoc Check that are based on ANTLR parser

### ISSUE THREAD

**Issue by mkordas** [checkstyle/checkstyle#1064] opened 2015-05-10 08:56 UTC
Analysis of Checkstyle code (659 files) with [checkstyle_checks.xml](../blob/master/config/checkstyle_checks.xml) currently lasts more than minute. 

When [AtclauseOrder](../blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java) check is disabled, then analysis completes in 7 seconds on my machine

Thanks for Csaba Kozák for reporting.

**Comment by romani** [comment] 2015-05-10 17:16
That is know tradeoff between reliable parsing and speed. For each java doc style comment, and we have only them, we run full functional javadoc parser.

I am ready to any suggestions how to make it better, that is how we finished summer 2014.
I decided to come back to that problem after moratorium period, unfortunate bugs in existing Checks are more painful for current users.

AtClauseOrder was introduced to main library only to show that we could satisfy almost all that described in Google Java Style.

**Comment by mkordas** [comment] 2015-05-10 18:08
All right, I see. I've tried some profiling in VisualVm and there isn't anything obvious that could be improved without rewriting the checks.

My proposition is to at least warn users in documentation about known performance problem in each impacted check, what do you think?

**Comment by romani** [comment] 2015-05-10 20:36
> My proposition is to at least warn users in documentation about known performance problem in each impacted check, what do you think?

https://groups.google.com/forum/#!topic/checkstyle-announce/StXqTc3pyWI
Yes, I am agree on updating all Checks documentation that do javadoc parsing, by such note.
But we need to explain users that such performance hit is good as checks are reliable and will produce minimum of false positives.
Problems from existing javadoc implementations are enormous: https://github.com/checkstyle/checkstyle/issues?q=is%3Aissue+is%3Aopen+javadoc+label%3Ajavadoc , https://sourceforge.net/p/checkstyle/bugs/ . It is not reasonable event try to fix them - they just need to be reimplemented to use slow but reliable parsing (eventually we will find way to make it quick).


> All right, I see. I've tried some profiling in VisualVm and there isn't anything obvious that could be improved without rewriting the checks.

I planned to come back to that problem during: https://github.com/checkstyle/checkstyle/wiki/Checkstyle-GSoC-2015-Project-Ideas#project-name-sun-code-convention-and-documentation-comments-style-guide . May be next year we will be more lucky to get a grant from Google to focus one student for long time on one problem.

**Comment by isopov** [comment] 2015-05-13 20:46
When trying to apply the same methodology as in #136 and checking the checkstyle sources itself with only AtClauseOrder check 50 GB memory is allocated. Checking checkstyle with another config (I took config from my work - it is just an ordinary config with 25 checks) gives only 482 MB memory allocated. 

I used the following command to run (on latest Java8 release):
`java -Xmx1g -Xms1g -XX:+UnlockCommercialFeatures -XX:+FlightRecorder -XX:StartFlightRecording=duration=1800s,settings=profile,filename=recording.jfr -jar target/checkstyle-6.7-SNAPSHOT-all.jar -c ./at_clause_config.xml src > test_output`

Don't know if it may help investigation.

**Comment by romani** [comment] 2015-07-09 20:42
https://groups.google.com/forum/#!topic/checkstyle-devel/At_bx7gdkA0

**Comment by romani** [comment] 2016-02-10 14:45
with javadoc Checks we are in 150 times slower on guava sources -  http://roman-ivanov.blogspot.com/2016/02/performance-problem-while-using-checks.html

**Comment by rnveach** [comment] 2016-03-23 15:11
new discussion at: https://groups.google.com/forum/#!topic/checkstyle-devel/Uyu-vO50eAQ

The cause of the slowdown is in the grammar for `text` ([JavadocParser.g4#L920](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/grammars/javadoc/JavadocParser.g4#L920)) when it calls `adaptivePredict`.
The reason for the slowness is `a decision in your grammar which requires a very large amount of look ahead and/or is ambiguous or context-sensitive` ([Source](http://stackoverflow.com/questions/14726229/antlr4-bad-performance-when-calling-getinterpreter-adaptivepredict)).

I will put my temporary fix to a PR until a more appropriate fix is made.

**Comment by romani** [comment] 2016-05-01 03:04
one fix if merged, it doe snot mean that this fix is last optimization, but I am closing the issue for now.
New issue need to be opened.

**Closed by romani** 2016-05-01 03:04 UTC
Labels: approved, bug

**Comment by romani** [comment] 2016-05-01 03:05
thanks a lot to @rnveach  for his detailed analysis and testing.
