### ISSUE TITLE
SuppressionCommentFilter being ignored

### ISSUE THREAD

**Issue by nhojpatrick** [checkstyle/checkstyle#7470] opened 2020-01-13 19:13 UTC
Check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck

```
/var/tmp $ javac YOUR_FILE.java
#[[MAKE SURE THERE IS NO OUTPUT]]

/var/tmp $ cat config.xml
<checkstyleRules>
    <module name="Checker">
        <module name="LineLength">
            <property name="fileExtensions" value="java"></property>
            <property name="max" value="120"></property>
            <property name="ignorePattern"
                      value="^package.*|^import.*|.*LOGGER.*|^.*\@Given\(.*"></property>
        </module>
        <module name="TreeWalker">
            <module name="SuppressionCommentFilter">
                <property name="offCommentFormat" value="AUTOGENERATED START"></property>
                <property name="onCommentFormat" value="AUTOGENERATED END"></property>
            </module>
            <module name="SuppressionCommentFilter">
                <property name="offCommentFormat" value="CHECKSTYLE:OFF"></property>
                <property name="onCommentFormat" value="CHECKSTYLE:ON"></property>
            </module>
        </module>
    </module>
</checkstyleRules>

/var/tmp $ cat YOUR_FILE.java
package testing;
public class Testing {
    private static final String qwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnm = "";
    //CHECKSTYLE:OFF
    private static final String mnbvcdrtyuiuytrewqasdesxcvghbnmkoiuyhmnbvcdrtyuiuytrewqasdesxcvghbnmkoiuyhmnbvcdrtyuiuytrewqasdesxcvghbnmkoiuyhmnbvcdrtyuiuytrewqa = "";
    //CHECKSTYLE:ON
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
[INFO] --- maven-checkstyle-plugin:3.1.0:check (checkstyle-check) @ testing ---
[INFO] Starting audit...
[ERROR] TESTING/src/main/java/testing/Testing.java:3: Line is longer than 120 characters (found 168). [LineLength]
[ERROR] TESTING/src/main/java/testing/Testing.java:5: Line is longer than 120 characters (found 168). [LineLength]
Audit done.
```

---------------

Describe what you expect in detail.

I've got some auto generated code with is longer than 120 characters, luckly it's nested within;
//------------------------- AUTOGENERATED START -------------------------
//-------------------------- AUTOGENERATED END --------------------------

But checkstyle is still reporting issues, so I tried just using CHECKSTYLE:OFF and CHECKSTYLE:ON. The file Testing.java I'm aware 2 lines are longer than 120 characters but using SuppressionCommentFilter I'm only expecting 1 error to be reported, line 3 which is not withing the comment filter block.

I've tried moving the module elements but I get nesting errors.

My issue is how can I turn all checkstyle checking for a given block, that is surrounded by comment tags?

--------------

Still not clear ???
see example - https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

ATTENTION: FAILURE TO FOLLOW THE ABOVE TEMPLATE WILL RESULT IN THE ISSUE BEING CLOSED.

**Comment by rnveach** [comment] 2020-01-13 19:54
duplicate of https://github.com/checkstyle/checkstyle/issues/7287

**Closed by rnveach** 2020-01-13 19:54 UTC
