### ISSUE TITLE
NPE in MissingDeprecatedCheck

### ISSUE THREAD

**Issue by adangel** [checkstyle/checkstyle#7534] opened 2020-02-04 19:15 UTC
Check documentation: https://checkstyle.org/config_annotation.html#MissingDeprecated

```
/var/tmp $ javac Test.java
/var/tmp $ cat config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Check Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <property name="severity" value="warning"/>
  <module name="TreeWalker">
    <module name="MissingDeprecated">
      <property name="severity" value="warning"/>
    </module>
  </module>
</module>

/var/tmp $ cat Test.java
/**
 * Wrong header
 */
// test

package pkg;


/**
 * @deprecated do not use
 */
@Deprecated
public class Test {
}

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-8.29-all.jar -c config.xml Test.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Test.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:304)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:216)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:400)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:324)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:187)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:124)
Caused by: java.lang.NullPointerException
	at com.puppycrawl.tools.checkstyle.utils.AnnotationUtil.findFirstAnnotation(AnnotationUtil.java:220)
	at com.puppycrawl.tools.checkstyle.utils.AnnotationUtil.getAnnotation(AnnotationUtil.java:194)
	at com.puppycrawl.tools.checkstyle.utils.AnnotationUtil.containsAnnotation(AnnotationUtil.java:70)
	at com.puppycrawl.tools.checkstyle.checks.annotation.MissingDeprecatedCheck.visitJavadocToken(MissingDeprecatedCheck.java:136)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck.walk(AbstractJavadocCheck.java:352)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck.processTree(AbstractJavadocCheck.java:337)
	at com.puppycrawl.tools.checkstyle.checks.javadoc.AbstractJavadocCheck.visitToken(AbstractJavadocCheck.java:304)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:342)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:449)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:283)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:165)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)
	... 5 more
Checkstyle ends with 1 errors.

```

---------------

There should be no null pointer exception, even though there are two formal comments at the top level of the class.

To avoid the NPE, I can change the first formal comment into a normal comment or remove the single line comment. Both changes make the NPE go away.

**Attention:**
Update https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties#L19 to use latest version of pmd

**Comment by rnveach** [comment] 2020-02-04 19:36
I can duplicate the exception.

**Comment by rnveach** [comment] 2020-02-04 19:59
The issue is directly related to #7430 . The block comment was not being recognized as a javadoc because of the line comment separating it and the javadoc.

**Comment by rnveach** [comment] 2020-02-05 04:57
Even though the exception happens in the utility, I believe the issue is in the check itself.

https://github.com/checkstyle/checkstyle/blob/ae9edbd4a8645c8cc1a99ad6890dd0006700d1cb/src/main/java/com/puppycrawl/tools/checkstyle/checks/annotation/MissingDeprecatedCheck.java#L172
When looking for the parent node of the javadoc (more specifically the target), we return the single line comment instead of the package definition. This is not the parent, and thus leads to weird results as we pass this unexpected token to the utility.

`getParent` should return the package definition and thus that is where the fix should be.

**Comment by baron1405** [comment] 2020-02-18 02:08
I can confirm that with 8.29, having a line comment in between a Javadoc command and its code causes the NPE. For example the following causes the NPE in a package-info.java:
```
/**
 * Hello world
 */
// Let's throw an NPE
package com.cthing.foobar;
```

**Comment by romani** [comment] 2020-02-18 02:26
@baron1405 , can you share real life reason to have comments like this? Is it for good reason? Or just coincidence?

**Comment by adangel** [comment] 2020-02-18 20:05
I had this case when upgrading checkstyle in PMD. We have a license header comment - and unfortunately used formal comments for that. The fix is of course, to use simple comments. So, the priority is very low.
But nevertheless, I think checkstyle shouldn't stumble across such files.

**Comment by nmancus1** [comment] 2020-02-27 19:39
I would like to work on this, but I'm not sure where to start. Could someone point me in the right direction?

**Comment by rnveach** [comment] 2020-02-27 19:44
Please see my comments at https://github.com/checkstyle/checkstyle/issues/7534#issuecomment-582240489 and https://github.com/checkstyle/checkstyle/issues/7534#issuecomment-582240489 . It details my notes on the issue and where the fix should be.

This issue is not marked for GSoC or as easy, so if you are unfamilar with checkstyle it may be too hard.

**Comment by nmancus1** [comment] 2020-02-28 03:11
I believe I have fixed NPE issue, however, when running `mvn clean verify` I get this:
`[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.annotation.MissingDeprecatedCheck: lines covered ratio is 0.96, but expected minimum is 1.00
[WARNING] Rule violated for class com.puppycrawl.tools.checkstyle.checks.annotation.MissingDeprecatedCheck: branches covered ratio is 0.96, but expected minimum is 1.00`

Can you offer any advice regarding these warnings?

**Comment by romani** [comment] 2020-03-03 22:12
@adangel , can we ask you to update pmd sources to have special maven property for checkstyle (we will substitute it to SNAPSHOT version). We are going to use your project in our regression testing to prevent problem such unfortunate issue on your code base.

**Comment by adangel** [comment] 2020-03-06 10:32
@romani I've added the property "checkstyle.version":
https://github.com/pmd/pmd/blob/68872bec2429c10b3c94e5ef1352ad74771dbf05/pom.xml#L95

(actually introduced checkstyle.plugin.version and reused checkstyle.version for checkstyle....)

**Comment by romani** [comment] 2020-03-06 16:11
@adangel, thanks a lot, I hope will will not make problems to pmd in future.

Please upgrade checkstyle maven plugin to 3.1.1 , we have PR already to break some compatibility.

Please share a command on how to run checkstyle only on pmd, we will use it in testing.

I appreciate your help and collaboration.

**Comment by adangel** [comment] 2020-03-07 08:58
Thanks for fixing and taking care of this bug.

I've updated the plugin. You should be able to run just checkstyle on pmd with `./mvnw checkstyle:check`.

**Comment by rnveach** [comment] 2020-03-09 13:05
Disabled until item not done: https://github.com/checkstyle/checkstyle/pull/7556#issuecomment-596511705

**Comment by romani** [comment] 2020-03-09 13:15
fix is merged.

**Closed by romani** 2020-03-09 13:15 UTC
Labels: approved, bug, high demand

**Comment by romani** [comment] 2020-03-09 13:17
@rnveach , I moved uncommenting of CI item to separate issue.
