### ISSUE TITLE
RedundantModifier flags public constructor that are really needed in serialized class

### ISSUE THREAD

**Issue by maisonobe** [checkstyle/checkstyle#2508] opened 2015-11-02 15:47 UTC
After issue #1537, RedundantModifier flags public constructors in non-public classes.
It seemed fair at first but if such a class isserialized and deserialized, this triggers a runtime error
at deserialization (java.io.ClassException : no valid constructor, thrown by java.io.ObjectStream).

The class was simply a class with package scope, intended to be used for a field in a public class
in the same package.

Perhaps public constructors without parameters in serializable classes should be considered important and not flagged, or perhaps this corner case should be explained in the documentation so people can
filter them explicitly with suppress comment filtering.
##

**Comment by mkordas** [comment] 2015-11-02 20:22
@maisonobe
Is error thrown when you just change constructor visibility from public to package-private? If yes, how frameworks can access package-private class but cannot invoke their package-private constructors?

**Comment by maisonobe** [comment] 2015-11-02 20:33
Yes, the error is triggered when the constructor does not have any modifier, i.e. when it is package-private. I guess this is a corner case and that deserialization is handled in a special way under the hood, either by the JVM itself or using reflection. It seems to really look for a public constructor without argument and to complain if none is found.

**Comment by mkordas** [comment] 2015-11-02 20:39
Can you check if marking constructor as `protected` works fine? If yes, we'll just need to update documentation.

**Comment by maisonobe** [comment] 2015-11-02 20:51
Sure.
... a few minutes pass ...
It doesn't work. Same error is triggered: no valid constructor.

If you want to see the problem in its context, it happens in the Apache Commons Math project  at http://git-wip-us.apache.org/repos/asf/commons-math.git. You can look in the master branch, class org.apache.commons.math4.ode.nonstiff.DormandPrince853StepInterpolator and run in the junit tests the test DormandPrince853StepInterpolatorTest.serialization(). In order for checkstyle not to complain, I had to set up filtering (look at checkstyle.xml in the top level folder). Beware that our current pom.xml file 1) does not refer to the current checkstyle version and 2) is not configured to run mvn checkstyle:checkstyle (it only generates reports with mvn site yet). So the checkstyle warning appears only when I run the tool externally or through Eclipse.

**Comment by mkordas** [comment] 2015-11-02 21:38
Thanks, I can reproduce exception locally. First, we need to understand why `protected` is not enough. To be honest I have no idea... Maybe we should ask on StackOverflow?

**Comment by rnveach** [comment] 2015-11-02 22:09
@mkordas 
"protected" probably isn't enough because the class creating the instance, "java.io.ObjectStream", isn't part of the package of the class he's trying to create.
All code is still restricted by the modifer rules, even with reflection, unless they are specifically disabled. Ex: "constructor.setAccessible(true);"

I wrote a little test and I get this exception when trying to instance a protected constructor: java.lang.IllegalAccessException: Class Test can not access a member of class rveach.Foo with modifiers "protected"

**Comment by cesar1000** [comment] 2016-04-18 04:04
The Java Object Serialization Specification establishes that an Externalizable class needs to have a public no-arg constructor:

https://docs.oracle.com/javase/6/docs/platform/serialization/spec/serial-arch.html#7185

RedundantModifier should always allow a public constructor in classes that implement Externalizable.

I tried to use @SuppressWarnings to avoid the error, but couldn't manage to make it work, so I'm suppressing full files.

**Comment by romani** [comment] 2016-04-18 23:59
> RedundantModifier should always allow a public constructor in classes that implement Externalizable.

Please beware that checkstyle have limitations in desugn and can not know class hierarcy. Please use suppressions for complicated cases.

> I tried to use @SuppressWarnings to avoid the error, but couldn't manage to make it work, so I'm suppressing full files.

Please make simple file and config and share it on maillist to let smb help you.

**Comment by cesar1000** [comment] 2016-04-19 00:02
Yeah, I understand. Let's me give that a try. Thanks!

**Comment by romani** [comment] 2016-11-11 00:04
issues is closed as no way to resolved it, such cases should be suppressed.

**Closed by romani** 2016-11-11 00:04 UTC
