### ISSUE TITLE
Option to do not separete static imports

### ISSUE THREAD

**Issue by WonderCsabo** [checkstyle/checkstyle#1369] opened 2015-07-13 21:37 UTC
I already saw #12 which tries to fit CS for Eclipse's default import formatter. But there is one difference: Eclipse do not adds blank lines between groups in static imports, but CS expect to do so. I have this configuration, which should mimic Eclipse:
```xml
<module name="ImportOrder">
    <property name="groups" value="/^javax?\./,org"/>
    <property name="ordered" value="true"/>
    <property name="separated" value="true"/>
    <property name="option" value="top"/>
    <property name="sortStaticImportsAlphabetically" value="true"/>
</module>
```

However, it adds an error to the last import, which is properly formatted by Eclipse:

```java
import static com.sun.codemodel.JExpr.invoke;
import static com.sun.codemodel.JMod.PRIVATE;
import static com.sun.codemodel.JMod.PUBLIC;
import static com.sun.codemodel.JMod.STATIC;
import static javax.lang.model.element.ElementKind.CONSTRUCTOR;
import static org.androidannotations.helper.ModelConstants.generationSuffix;
```

`'org.androidannotations.helper.ModelConstants.generationSuffix' should be separated from previous imports.`

**Comment by WonderCsabo** [comment] 2015-07-14 09:08
@romani i have a POC fix for this here https://github.com/WonderCsabo/checkstyle/commit/63a01083b9b53de63b9c62c7ce1f4c9c1c714340. If you think it is a good solution, i can wrap up a PR later.

**Comment by romani** [comment] 2015-07-15 05:21
Thanks a lot, let me redirect your work to another contributor, I am extremely over occupied with other tasks on a project.

@ivanov-alex , please take a look and do code-review.

**Comment by WonderCsabo** [comment] 2015-07-15 18:09
@romani okay for me. I am waiting for @ivanov-alex to verify my approach before creating a full PR with tests and docs, then.

**Comment by ivanov-alex** [comment] 2015-07-17 04:47
@WonderCsabo Looks good, but it appears we have a defect on our side (not every group on static imports triggers violation). I will address a problem and have a closer look on how your changes work with that.

**Comment by WonderCsabo** [comment] 2015-07-17 06:18
Great, thanks.

**Comment by ivanov-alex** [comment] 2015-07-17 09:47
Hi again!
@WonderCsabo , I have entered #1398 for that and I think that there should be no separation violation on a file in your example.
Could you please provide more information on what are you trying to achieve? 
1) Do you just need CS to stop showing false positives on files like that? All static imports will be in one group (default Eclipse formatting, at least on my version).
2) Or you need ability to split static imports into several groups?

**Comment by WonderCsabo** [comment] 2015-07-17 09:52
I want to achieve 1). I thought my patch did exactly that.

**Comment by ivanov-alex** [comment] 2015-07-17 20:46
Well, that is not 100% correct.
What you are trying to achieve is an expected behaviour. However, due to defect, you were not able to experience it. I understand that you were treating actual behaviour as an expected one and were trying to extend it one step further.
Your patch is not solving all aspects of our problem described in #1398 (because it will require separator after "import static com.sun.codemodel.JMod.STATIC;" in addition to current violations). 
But it helped us locate a problem and address it.

Patch we going to apply for the defect will solve problem (1) without adding the option. Static imports will be on one group without separators.

**Comment by WonderCsabo** [comment] 2015-07-17 22:51
Okay, thanks, that is totally good for me.

**Comment by ivanov-alex** [comment] 2015-07-22 06:53
@WonderCsabo we have merged the changes. Could you please check if it solved your problem? You will need to build snapshot from the master.

**Comment by WonderCsabo** [comment] 2015-07-22 07:40
Sure, I am afk till Sunday, then I test it.

**Comment by romani** [comment] 2015-07-25 05:31
I am closing that issue as #1398 is closed, @WonderCsabo as you find smth strange we could do reopen.

**Closed by romani** 2015-07-25 05:31 UTC
Labels: approved

**Comment by WonderCsabo** [comment] 2015-07-27 10:14
It seems this fix works for me as expected.

BTW, i think you should push snapshot builds with each commit on `master` to [Sonatype's OSS snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/). That way testing could be easier for users (no need for building CS locally).

**Comment by romani** [comment] 2015-07-29 06:46
yes, one day I will figure out how to do that automatically by CI (Travis).

**Comment by WonderCsabo** [comment] 2015-07-29 07:16
No need for that, lots of people already figured that out. :) For example check [our project](https://github.com/excilys/androidannotations) (*.travis.yml*, *settings.xml*). If you want i can send a PR.

**Comment by romani** [comment] 2015-09-12 14:10
@WonderCsabo , right now we have a time to make it happen, please provide PR as you have experience with that.

All work should be done in scope of #2167
