### ISSUE TITLE
Java parser bug

### ISSUE THREAD

**Issue by boris-petrov** [checkstyle/checkstyle#6837] opened 2019-06-19 16:07 UTC
```java
try (SomeOtherClass.STATIC_FIELD) {
```

This line leads to such an error:

```
[ant:checkstyle] /home/boris/project/SomeFile.java:40:44: expecting IDENT, found ')'
```

**Comment by rnveach** [comment] 2019-06-19 17:38
@boris-petrov please see https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F . Can you provide us a compilable example.

**Comment by romani** [comment] 2019-06-19 17:42
Boris, I would appreciate if you share with us why you did not follow requested template. What wording we can improve ? Following to it is must, and resolve bunch conversation

**Comment by strkkk** [comment] 2019-06-19 18:17
it is duplicate of #6332

**Comment by rnveach** [comment] 2019-06-20 03:22
Closing as it is a duplicate

**Closed by rnveach** 2019-06-20 03:22 UTC
Labels: antlr

**Comment by boris-petrov** [comment] 2019-06-20 06:42
@rnveach, @romani - I'm sorry I didn't follow the template. I was in a hurry and didn't want to forget this issue while I thought it was important. I'll try to be more careful next time. Thank you for your time!
