### ISSUE TITLE
NullPointerException with ModifiedControlVariable on 6.6

### ISSUE THREAD

**Issue by bananetomate** [checkstyle/checkstyle#1080] opened 2015-05-14 19:10 UTC
Hi, I think there's a problem with ModifiedControlVariable in version 6.6. I've narrowed the problem to the following test case:

**Configuration**:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<!--
    This configuration file was written by the eclipse-cs plugin configuration editor
-->
<module name="Checker">
  <property name="severity" value="warning"/>
  <module name="TreeWalker">
    <property name="tabWidth" value="4"/>
    <module name="ModifiedControlVariable"/>
  </module>
</module>
```

**Test class**:
```
/*
 * This file is copyright 2002-2015
 *
 * Blablabla
 */
package com.company.whatever.metadata;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Metadata model object.
 * <p>
 * Refer to {@code metadata.xsd} for XML structure.
 */
@XmlRootElement(name = "metadata")
@XmlAccessorType(XmlAccessType.FIELD)
public final class Metadata implements Serializable {

    private static final long serialVersionUID = 1L;


}
```

**Testing with 6.5**
```
PS C:\dev\apps\checkstyle> java -jar .\checkstyle-6.5-all.jar -c Example-checkstyle.xml .\TestClass.java
Starting audit...
Audit done.
```

**Testing with 6.6**
```
PS C:\dev\apps\checkstyle> java -jar .\checkstyle-6.6-all.jar -c Example-checkstyle.xml .\TestClass.java
May 14, 2015 3:04:11 PM com.puppycrawl.tools.checkstyle.TreeWalker processFiltered
SEVERE: NullPointerException occurred during the analysis of file .\TestClass.java .
Starting audit...
C:\dev\apps\checkstyle\.\TestClass.java:0: Got an exception - null
Audit done.
Could not execute Checkstyle: Checkstyle ends with 1 errors.
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Checkstyle ends with 1 errors.
        at com.puppycrawl.tools.checkstyle.Main.processCommandLine(Main.java:160)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:59)
usage: java com.puppycrawl.tools.checkstyle.Main [options] -c <config.xml>
            file...
 -c <arg>   Sets the check configuration file to use.
 -f <arg>   Sets the output format. (plain|xml). Defaults to plain
 -o <arg>   Sets the output file. Defaults to stdout
 -p <arg>   Loads the properties file
 -v         Print product version and exit
```

**Removing the `name = "metadata"` fixes the problem (but is obviously not a solution in a real project)**
```
...
@XmlRootElement()
...
```

```
PS C:\dev\apps\checkstyle> java -jar .\checkstyle-6.6-all.jar -c Example-checkstyle.xml .\TestClass.java
Starting audit...
Audit done.
```

**Comment by mkordas** [comment] 2015-05-15 16:46
Duplicate of #1012, will be fixed in [6.7](https://github.com/checkstyle/checkstyle/milestones/6.7)

**Closed** 2015-05-15 17:02 UTC
Labels: approved, high demand
