### ISSUE TITLE
Checkstyle throwing exception on parsing Lombok based sources

### ISSUE THREAD

**Issue by olivergierke** [checkstyle/checkstyle#5349] opened 2017-12-12 11:21 UTC
Using Checkstyle 7.3 in a Sonar build and a codebase using Lombok, Checkstyle produces an exception with the message:

```
Unexpected container AST: ANNOTATION…
```

The offending line it is pointing to is [this](https://github.com/spring-projects/spring-data-commons/blob/9f220d5c159cc78b0d701829b3074366a4e8fa08/src/main/java/org/springframework/data/mapping/model/AbstractPersistentProperty.java#L65), i.e.:

```java
private final @Getter(onMethod = @__(@Nullable)) Method getter;
```

See the usage of Lombok's way of making sure the getter method generated for the field carries the `@Nullable` annotation.

I currently work around the issue by delomboking the sources and let Sonar (and thus Checkstyle) operate on that but that causes sources ending up that are not the actual ones and essentially any git blame information missing.

**Comment by rnveach** [comment] 2017-12-12 12:44
probably a duplicate of #4633

**Comment by olivergierke** [comment] 2017-12-12 12:51
While it certainly looks related, I don't think it's the same issue. In #4633, the core issue seems to be curly braces not being parsed correctly. That's not in play here.

**Comment by rnveach** [comment] 2017-12-12 12:54
> the core issue seems to be curly braces not being parsed correctly

don't go by the final exception, as antlr will try to continue parsing even if it should have failed sooner.
Removing the line with `@lombok.Getter(onMethod = @__(@Override, @Deprecated))` from that issue's code parses with no issue, so both are related to this lombok code.

**Comment by ignaciolarranaga** [comment] 2018-02-14 19:54
I have the same issue trying to suppress a warning for example (which probably shouldn't be even required since it is already marked as private):
```
@NoArgsConstructor(access = PRIVATE, onConstructor = @__(
    @SuppressWarnings("checkstyle:HideUtilityClassConstructor"))
)
```

**Comment by rnveach** [comment] 2018-02-18 19:50
This is not the same as #4633 . This has only 1 annotation inside another. #4633 has multiple annotation inside an annotation, without `{}` which is required by the JLS.

This issue is valid since it can be generated using valid Java code.
````
import static java.lang.annotation.ElementType.CONSTRUCTOR;
import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.LOCAL_VARIABLE;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.PARAMETER;
import static java.lang.annotation.ElementType.TYPE;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.lang.reflect.Method;

public class TestClass {
	private final @Getter(onMethod = @__(@AnnotationTest1)) Method getter = null;
}

@Target({ TYPE, FIELD, METHOD, PARAMETER, CONSTRUCTOR, LOCAL_VARIABLE })
@Retention(RetentionPolicy.SOURCE)
@interface Getter {
	__ onMethod();
}

@Target({ TYPE, FIELD, METHOD, PARAMETER, CONSTRUCTOR, LOCAL_VARIABLE })
@Retention(RetentionPolicy.SOURCE)
@interface __ {
	AnnotationTest1[] value();
}

@Target({ TYPE, FIELD, METHOD, PARAMETER, CONSTRUCTOR, LOCAL_VARIABLE })
@Retention(RetentionPolicy.SOURCE)
@interface AnnotationTest1 {
}
````

**Comment by rnveach** [comment] 2018-02-18 19:54
@olivergierke 
> Using Checkstyle 7.3 in a Sonar build and a codebase using Lombok

I have no problems parsing your example in the latest checkstyle version.
Please check if you have the same issue using Checkstyle's CLI.
If you don't then it is an issue with an old sonar version and not Checkstyle.

**Comment by romani** [comment] 2018-03-08 14:23
Issue need to be reported as required with javac, our cli output on latest version.

**Closed by romani** 2018-03-08 14:23 UTC
