### ISSUE TITLE
Improper report of right curly should be on newline when actual problem is right parenthi

### ISSUE THREAD

**Issue by RickPoleshuck** [checkstyle/checkstyle#3791] opened 2017-02-02 17:55 UTC
```
*************** Source File *******************
package com.test;

import java.io.FileInputStream;
import java.io.InputStream;

/**
 * Created by Rick Poleshuck on 2/2/2017.
 */
public class Main {
  public static void main(final String args) throws Exception {
    try (
        InputStream is = new FileInputStream("test")) {

    }
  }
}
```

```
*************** pom.xml *******************
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.test</groupId>
    <artifactId>checkstyle-bug</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>2.17</version>
                <dependencies>
                    <dependency>
                        <groupId>com.puppycrawl.tools</groupId>
                        <artifactId>checkstyle</artifactId>
                        <version>7.5</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

```
*************** Output *******************
[ERROR] src\main\java\com\test\Main.java:[12,53] (blocks) RightCurly: '}' at column 53 should have line break before.
```

```
*************** Expected *******************
[ERROR] src\main\java\com\test\Main.java:[12,53] (blocks) RightParen: ')' at column 53 should have line break before.
```

**Comment by rnveach** [comment] 2017-02-02 18:01
duplicate of #3776 , the issue was fixed and will be in hot-fix release.

@romani I am going to leave this open since this is the 4th time people we are reporting this issue.
Maybe make a special label for this kind of repeat fixed issue that hasn't been released yet.

**Comment by romani** [comment] 2017-02-02 18:29
agree, lets keep it open till hotfix release.
hot fix release will be on February 5th.

**Comment by romani** [comment] 2017-02-09 17:37
release 7.5.1 is done - http://checkstyle.sourceforge.net/releasenotes.html#Release_7.5.1

**Closed by romani** 2017-02-09 17:37 UTC
