### ISSUE TITLE
Resolve Pitest Issues - JavadocMethodCheck (6)

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7978] opened 2020-03-28 16:01 UTC
Child issue of https://github.com/checkstyle/checkstyle/issues/7797 ,

https://github.com/checkstyle/checkstyle/blob/f9131f9536c71d963c83aab1550b7a0371aa9ff5/.ci/pitest.sh#L187

**Comment by DXTkastb** [comment] 2020-04-01 20:14
I'm on it.

**Comment by DXTkastb** [comment] 2020-04-02 17:58
**Pitest report:**
https://dxtkastb.github.io/checkstyle/reports/javadoc/pit-reports/202003280119/com.puppycrawl.tools.checkstyle.checks.javadoc/JavadocMethodCheck.java.html

**Surviving Mutation:**

line :408           
 if (dotIdx == -1) {
 1. negated conditional → SURVIVED

**Hardcoded Branch:**
https://github.com/DXTkastb/checkstyle/blob/7e200cb325fa9bc5a0078f3bba9127f7fe7516de/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocMethodCheck.java#L408

**Pitest regression report:**
https://dxtkastb.github.io/checkstyle/reports/javadoc/reports/diff/index.html

**Code analysis:**
The regression report did not provide much help. 

            int dotIdx =  .lastIndexOf('$');
            if (dotIdx == -1) {
                // perhaps just a class
                dotIdx = currentClassName.lastIndexOf('.');
            }
            if (dotIdx == -1) {
                // looks like a topmost class
                currentClassName = "";
            }

the dotIdx stores the index of $ ( ex: currentClassName: Xyz$Abc , Abc is inner class of Xyz)

if there is no inner class then dotIdx= -1, which satisfies the 1st condition but then ` dotIdx = currentClassName.lastIndexOf('.');` again stores value of -1. I find this statment out of question because currentClassName will not contain character '.' ever. As per my understanding of this check ,values stored in currentClassName are like:(if nested inner classes)
ClassA$ClassB$ClassC.....

The same rule is followed for Enums and Interfaces.

@rnveach Please review.

**Comment by strkkk** [comment] 2020-04-04 10:17
Fix is merged

**Closed** 2020-04-04 10:16 UTC
Labels: approved, gsoc third issue
