### ISSUE TITLE
Resolve Pitest Issues - AvoidStaticImportCheck

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7801] opened 2020-03-08 18:42 UTC
Child issue of https://github.com/checkstyle/checkstyle/issues/7797 ,

This issue specifically focuses on the line https://github.com/checkstyle/checkstyle/blob/abf829f542023e089c741c55f73098cae52dcb12/.ci/pitest.sh#L76

**Comment by gaurabdg** [comment] 2020-03-09 10:09
I am on it.

**Comment by gaurabdg** [comment] 2020-03-10 16:50
## 1. Pitest: 
https://gaurabdg.github.io/checkstyle-tester-reports/pitest-reports/AvoidStaticImport/com.puppycrawl.tools.checkstyle.checks.imports/AvoidStaticImportCheck.java.html#org.pitest.mutationtest.report.html.SourceFile@46d29511_161

## 2. Mutated Branch: 

https://github.com/gaurabdg/checkstyle/blob/d85bcf9cba167c98c29bfe188fd9578aca149046/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStaticImportCheck.java#L162
Since the mutation was `removed conditional - replaced equality check with true → SURVIVED`, the if statement was removed to set the execution of all the statements to always true.

## 3. Regression Report:

https://gaurabdg.github.io/checkstyle-tester-reports/AvoidStaticImport/diff/index.html
Used only `guava` and `elastic-search` to add their file specific import excludes.
Module used in config file:
```
    <module name="AvoidStaticImport">
        <property name="excludes" value="com.google.common.base.*,com.google.common.collect.*,
                java.util.stream.Collectors.*,org.elasticsearch.xpack.ql.type.DataTypes.*"/>
    </module>
```
## 4. Regression and Code Logic Analysis

`if(exclude.endsWith(".*"))` is redundant, since even if this check wasn't there and let's assume the exclude was a random member, it would yield true for the second condition but not for the first condition in `if (classOrStaticMember.startsWith(excludeMinusDotStar)&& !classOrStaticMember.equals(excludeMinusDotStar))`. and hence not move forward. For this reason even if we remove the condition it there are no differences in regression and instead mutation coverage increases.

**Comment by gaurabdg** [comment] 2020-03-10 16:51
@rnveach Please review.

**Comment by gaurabdg** [comment] 2020-03-11 08:33
@rnveach Added an UT. Please review

**Comment by rnveach** [comment] 2020-03-11 22:05
1.
Pitest report looks good and matches line in issue.

2.
Mutated branch is acceptable.
> the if statement was removed to set the execution of all the statements to always true.

I would personally keep the if and just change the complete condition to `true`. Ex: `if (true) {`.
This keeps the difference looking cleaner and straight forward on what is being changed.

**Comment by rnveach** [comment] 2020-03-11 22:14
4.
Since you have found a UT and started a PR, I feel you understand pitest well enough for what needs to be done. This is usually the hardest part when regression fails us. Without a regression example, it is hard to create cases and even scarier to remove code when we are not sure how well it is used or not.

If you had not found a test case, we would be walking through the code for a negative case trying to determine if a case could not be created or the code changed that satisfy the original condition in a new way.

In this case the condition was changed to `if (true)` so we know the code supports the true condition and doesn't have an issue there with pitest. When I say a negative case, we would be stepping through the code with the condition as `if (false)` with a case that would only be getting hit with `if (true)`. I hope this makes sense for future contributors, but I feel you did this even if my words fail.

**Comment by romani** [comment] 2020-03-12 00:34
fix is merged.

**Closed by romani** 2020-03-12 00:34 UTC
Labels: approved, gsoc third issue, miscellaneous

**Comment by gaurabdg** [comment] 2020-03-12 04:12
> I would personally keep the if and just change the complete condition to `true`. Ex: `if (true) {`.
> This keeps the difference looking cleaner and straight forward on what is being changed. You don't want to accidentally delete more code than necessary as that could cause all types of issues. Checks and CI should not be a concern for mutation branches that is just for testing.

Okay, I removed it because of the checks. I'll keep in mind from now on.

> Since you have gone on to do more analysis it is not an issue but you should find some way to include all projects in regression. You can have multiple modules in 1 regression run so it isn't an issue. See https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#checkstyle-pitest-regression
> 
> It is only with running regression on as many projects as possible do we go through all the weird code and such out there to help us solve this issue.

I thought that supplying random excludes to each project separately wouldn't help me find anything, so went on to analyse the edge cases instead. But I'll keep this in mind from now on.
