### ISSUE TITLE
JavadocPackage: NullPointerException when relative path is used to run checkstyle CLI

### ISSUE THREAD

**Issue by chris21k** [checkstyle/checkstyle#5127] opened 2017-09-19 07:31 UTC
```
/var/tmp $ javac HelloWorld.java
/var/tmp $ cat HelloWorld.java
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.2-all.jar \
-c /sun_checks.xml HelloWorld.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing HelloWorld.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:523)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:437)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:210)
Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.util.concurrent.ConcurrentHashMap$KeySetView.add(ConcurrentHashMap.java:4595)
        at com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocPackageCheck.processFiltered(JavadocPackageCheck.java:73)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
        ... 4 more
Checkstyle ends with 1 errors.
```

---------------

With checkstyle 8.2 the above using the provided sun_checks.xml throws a NullPointerException . 8.1 does not schow this problem. Same behavior under win and linux.

```
$ java -Duser.language=en -Duser.country=US -jar checkstyle-8.1-all.jar -c /sun_checks.xml HelloWorld.java
Starting audit...
[ERROR] /var/tmp/HelloWorld.java:0: File does not end with a newline. [NewlineAtEndOfFile]
[ERROR] /var/tmp/HelloWorld.java:0: Missing package-info.java file. [JavadocPackage]
[ERROR] /var/tmp/HelloWorld.java:1: Missing a Javadoc comment. [JavadocType]
[ERROR] /var/tmp/HelloWorld.java:1:1: Utility classes should not have a public or default constructor. [HideUtilityClassConstructor]
[ERROR] /var/tmp/HelloWorld.java:2:5: Missing a Javadoc comment. [JavadocMethod]
[ERROR] /var/tmp/HelloWorld.java:2:29: Parameter args should be final. [FinalParameters]
Audit done.
Checkstyle ends with 6 errors.
```
Thx,
Chris

**Comment by rnveach** [comment] 2017-09-19 11:32
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html#put(K,%20V)
> put
Throws:
NullPointerException - if the specified key or value is null

https://github.com/checkstyle/checkstyle/blob/ff85e714498a63c4060121f0625be5c76b741a5a/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java#L72-L73

Since the file is in a directory with a parent, I think the exception occurs if you give a short relative path.
@chris21k Do you still get an exception if instead of giving it the file `HelloWorld.java`, you give it the full path `/var/tmp/HelloWorld.java`?

**Comment by chris21k** [comment] 2017-09-20 12:51
Providing the full path for HelloWorld.java helps (under Linux and Win). However, the relative path should suffice, as it did with Checkstyle versions before 8.2, as far as I know. The relative path also is ok while using google_checks.xml. Please fix.

Thanks, Chris

**Comment by rnveach** [comment] 2017-09-20 13:35
Thanks for confirming, `JavadocPackage` needs to be fixed at the code mentioned above.

> The relative path also is ok while using google_checks.xml.

Google doesn't use `JavadocPackage`, which is why it isn't affected.

**Comment by romani** [comment] 2017-09-21 01:52
@chris21k , how did you find such problem ?

**Comment by chris21k** [comment] 2017-09-22 10:10
@romani, I am maintaining a (strongly modified) Praktomat (https://github.com/KITPraktomatTeam/Praktomat/) web instance for advanced programming courses at an university. There Checkstyle is one Plugin/Checker which is used in a sandbox of each code submission to give feedback to the submitter, decline acceptance of the submission, or/and to give feedback to me about code quality for giving grades. Thereby we use the Sun Code Conventions. How Praktomat calls Checkstyle (console command) and prepares the sandbox directed me to the above problem. I never have any control about a (good) package structure of the submissions, as I can give only advices to the students, which they don't always follow :)

Checkstyle is great! Many thanks!

Chris

**Comment by LeeiFrankJaw** [comment] 2017-10-07 14:02
I found the same problem when configuring checkstyle for [jdee](https://github.com/jdee-emacs). I commented issue [58](https://github.com/jdee-emacs/jdee/issues/58#issuecomment-333488926) and created a workaround pull request [134](https://github.com/jdee-emacs/jdee/pull/134) both at that repository.

**Comment by chris21k** [comment] 2017-10-08 07:53
Unfortunately, the new release 8.3 does not fix the problem.

**Comment by rnveach** [comment] 2017-10-08 12:59
@chris21k No one has worked on this issue, so of course it isn't fixed.

**Comment by AADudkin** [comment] 2017-10-16 13:51
I'm on it

**Comment by romani** [comment] 2017-10-26 13:11
@AADudkin , as such NPE was introduced from 8.1 to 8.2, do you know what change caused it ?

**Comment by rnveach** [comment] 2017-10-26 13:18
@romani Look at the blame for the 2 lines I posted as the cause for the NPE.
The combination of both caused the exception.

**Comment by romani** [comment] 2017-10-26 13:32
problem is due to inaccurate refactoring at https://github.com/checkstyle/checkstyle/commit/ff85e714498a63c4060121f0625be5c76b741a5a
ConcurrentHashMap collection throw NPE, but previous collection HashSet, worked fine with nulls, and before this commit all was fine.
sources of ConcurrentHashMap - http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/util/concurrent/ConcurrentHashMap.java#l1010

@AADudkin , are sure that we can reproduce this problem at any other FileSet Check ? please prove by CLI.

**Comment by rnveach** [comment] 2017-11-23 18:23
Fix was merged

**Closed by rnveach** 2017-11-23 18:23 UTC
Labels: approved
