### ISSUE TITLE
when enum name equals class name will cause unused import but import is correct

### ISSUE THREAD

**Issue by dnlixiaoxin** [checkstyle/checkstyle#12530] opened 2022-12-14 14:38 UTC
I have read check documentation: https://checkstyle.org/config_xxxxxx.html#NameOfAffectedCheck
I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash

/var/tmp $ cat config.xml
#[
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="UnusedImports"/>
  </module>
</module>

]

/var/tmp $ cat YOUR_FILE.java

enum MsgType

[
@AllArgsConstructor
public enum MsgType {
    TXT(1, "text"),
    MsgType(999, "MsgType"),
    ;

    @Getter
    private final int type;
    @Getter
    private final String desc;

    private static final Map<Integer, MsgType> TYPE_MAP = Maps.newHashMap();

    static {
        Arrays.stream(MsgType.values()).forEach(msgType -> TYPE_MAP.put(msgType.getType(), msgType));
    }

    public static MsgType getByType(int type) {
        return TYPE_MAP.get(type);
    }
}
]

class MsgType
[
import static com.monarch66.message.constant.MsgType.MsgType;

public class MsgType {

    public void inline() {
        int type = MsgType.getType();
    }

}

]

/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml YOUR_FILE.java
#[

src/main/java/com.monarch66.message/service/MsgType.java:[3,15] (imports) UnusedImports:  - com.monarch66.message.constant.MsgType.MsgType

]
```
when enum name equals class name will cause unused import but this. is correct

---

Still not clear ???
see example - https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F

ATTENTION: FAILURE TO FOLLOW THE ABOVE TEMPLATE WILL RESULT IN THE ISSUE BEING CLOSED.

**Comment by rnveach** [comment] 2022-12-14 15:20
Duplicate of https://github.com/checkstyle/checkstyle/issues/12529

**Closed by rnveach** 2022-12-14 15:20 UTC
