### ISSUE TITLE
Java 8 Grammar: annotations on varargs parameters

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#3238] opened 2016-06-02 11:10 UTC
Taken from PR #3230 when working on Issue #3033 from a run on OpenJDK 8/9.

```
$ cat TestClass.java
import java.lang.annotation.ElementType;
import java.lang.annotation.Target;

public class TestClass {
    public void m5(@Nullable String @Nullable ... vararg) {}
}

@Target(ElementType.TYPE_USE)
@interface Nullable {
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
    </module>
</module>

$ java -jar checkstyle-6.19-all.jar -c TestConfig.xml TestClass.java
Starting audit...
TestClass.java:5:47: unexpected token: ...
Audit done.
```

Input is compilable with java 8 javac.
##

**Comment by romani** [comment] 2016-06-02 12:37
> Input is compilable with java 8 javac.

next time please prove this in console output.

**Comment by romani** [comment] 2018-07-01 23:32
such syntax is now appeared at [guava](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Verify.java#L122).

I am raising priority.

**Comment by strkkk** [comment] 2019-06-04 11:40
I couldn't reproduce this in 8.20 version, probably it was fixed.
```
$ cat TestClass.java
import java.lang.annotation.ElementType;
import java.lang.annotation.Target;

public class TestClass {
    public void m5(@Nullable String @Nullable ... vararg) {}
}

@Target(ElementType.TYPE_USE)
@interface Nullable {
}

$ cat conf.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
    </module>
</module>

$ java -jar checkstyle-8.20-all.jar -c conf.xml TestClass.java
Starting audit...
Audit done.

```

**Comment by rnveach** [comment] 2019-06-04 11:44
@strkkk Some things in Checkstyle have changed since my initial report. TreeWalker does nothing if it doesn't have any children module. If you add a module or print the tree, you will see the exception still occurs.

**Comment by sanyarnd** [comment] 2019-07-30 08:48
Issue is still present in `8.23`

**Comment by frankbenoit** [comment] 2019-09-08 08:11
Issue is still present in `8.24`

**Comment by romani** [comment] 2020-01-24 23:16
fix is merged

**Closed by romani** 2020-01-24 23:16 UTC
Labels: antlr, approved, bug, high demand

**Comment by romani** [comment] 2020-02-24 01:11
@esilkensen , please contact me in gitter chat or send me email.
