### ISSUE TITLE
ImportOrder: allow static imports be separated by local groups when they are at the top/bottom

### ISSUE THREAD

**Issue by djydewang** [checkstyle/checkstyle#5279] opened 2017-11-20 14:22 UTC
```
➜  cat config.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <module name="TreeWalker">
        <module name="ImportOrderCheck">
            <property name="groups" value="java, javax" />
            <property name="separated" value="true" />
            <property name="ordered" value="true" />
            <property name="option" value="bottom" />
         </module>
    </module>
</module>
```

```
cat InputImportOrderGapBetweenStaticGroups.java
import static java.lang.Math.abs;
import static java.lang.Math.cos; // Attention: gap below

import static javax.xml.transform.TransformerFactory.newInstance;

public class InputImportOrderGapBetweenStaticGroups { }

bbg@king-Lenovo:~/checkstyletest$ java -Duser.language=en -Duser.country=US -jar checkstyle-8.4-all.jar -c test.xml InputImportOrderGapBetweenStaticGroups.java
Starting audit...
[ERROR] /home/bbg/checkstyletest/InputImportOrderGapBetweenStaticGroups.java:4: Extra separation in import group before 'javax.xml.transform.TransformerFactory.newInstance' [ImportOrder]
Audit done.
Checkstyle ends with 1 errors.
```
Checkstyle do exactly what is required.

But the feature of separating static imports when they are at top/bottom seems is required from conversation of [Issue #5176](https://github.com/checkstyle/checkstyle/issues/5176#issuecomment-340625283).
So, we can add a option named `separatedStaticImports` which means whether static imports grouped by top or bottom option are separated by local groups.
Example1:
```
<module name="ImportOrder">
    <property name="option" value="top"/>
    <!-- simple imports -->
    <property name="groups" value="/^java\./,javax,org"/>
    <property name="ordered" value="true"/>
    <property name="separated" value="true"/>
    <!-- static imports -->
    <property name="sortStaticImportsAlphabetically" value="true"/>
    <property name="separatedStaticImports" value="false"/>
</module>
```
Then CheckStyle's behavior is same as before checkstyle8.3, all static imports as one group.

Example2:
```
<module name="ImportOrder">
    <property name="option" value="top"/>
    <property name="groups" value="/^java\./,javax,org"/>
    <!-- simple imports -->
    <property name="ordered" value="true"/>
    <property name="separated" value="true"/>
    <!-- static imports -->
    <property name="sortStaticImportsAlphabetically" value="true"/>
    <property name="separatedStaticImports" value="true"/>
</module>
```
Static imports at top should be seaparated by local groups.And static imports should be sorted in the groups alphabetically.

Example3:
```
<module name="ImportOrder">
    <property name="option" value="top"/>
    <property name="groups" value="/^java\./,javax,org"/>
    <!-- simple imports -->
    <property name="ordered" value="true"/>
    <property name="separated" value="true"/>
    <!-- static imports -->
    <property name="sortStaticImportsAlphabetically" value="false"/>
    <property name="separatedStaticImports" value="false"/>
</module>
```
When you specify package groupings inside ImportOrder, that same ordering is applied to the single group of static imports.

I think it is keeping with original design of sortStaticImportsAlphabetically at [Issue #12](https://github.com/checkstyle/checkstyle/issues/12)
`To clarify, when static imports are grouped into a single block of text without any empty lines between them, I want them to be sorted alphabetically rather than in the package order.`
but also satisfy requirement of sorting/separate static imports by local groups.

**Comment by romani** [comment] 2017-12-02 00:51
@djydewang , thanks a lot for compact report and analysis.

please rename property to `separatedStaticImports` in issue description to looks similar to `separated` property.

> Then CheckStyle's behavior is same as before

please update this text with some range of checkstyle versions , you probably mean `before checkstyle 8.3`

**Comment by romani** [comment] 2017-12-02 00:53
@djydewang , can you help us to resolve this issue ?

**Comment by djydewang** [comment] 2017-12-02 11:47
I am on it.

**Comment by cesar1000** [comment] 2018-01-05 11:19
Hey, thanks for the work on this fix! What's the current status? Is it close to merging?

**Comment by romani** [comment] 2018-01-13 00:17
@djydewang ,


> I think it is keeping with original design of sortStaticImportsAlphabetically at Issue #12
>>To clarify, when static imports are grouped into a single block of text without any empty lines between them, I want them to be sorted alphabetically rather than in the package order.


Looks like this is reason of problem. Statics should have separate property for grouping to let users forec them to be in the same groups as simple imports but if user define static grouping like "" (no groups),  we just put all of them in one group and apply sortStaticImportsAlphabetically to sort them if required.

**Comment by romani** [comment] 2018-01-13 14:27
> groupsStatic is ignored when sortStaticImportsAlphabetically=true

right now - yes, but ones we introduce this property it should not.
I only proposing it to satisfy request:
>>  when static imports are grouped into a single block of text without any empty lines between them, I want them to be sorted alphabetically rather than in the package order.

> And It's strange that the order of the static import groups is different from that of the normal imports when sortStaticImportsAlphabetically=false

right now yes, users request static and non-statics to be managed separately, we already have sorting properties for both, we are going to have `separate` for both, so it is clear that are just about to have grouping properties for both.

----------------

To make good decision, we need to come back to original proposal #12  and make a decision to support it or not. I personally dislike such style, but if IDEs(Eclipse, Idea, Netbeans) allow it (separate groups for static and non-static imports) we should support it too.

@djydewang , please share your thoughts on this.

**Comment by djydewang** [comment] 2018-01-13 14:36
@romani

> but if IDEs(Eclipse, Idea, Netbeans) allow it (separate groups for static and non-static imports) we should support it too.

@eric-milles has asked for it. https://github.com/checkstyle/checkstyle/issues/5176#issuecomment-355064255

So our CS should support this behaviour(separate groups for static and non-static imports).

**Comment by romani** [comment] 2018-01-13 14:44
ok, we are on the same page , that good.

Should we do two new options in same issue or in two different issues ?  from my perspective two issues are easy to validate in PR.

@djydewang , what is your ideas on this ?

**Comment by djydewang** [comment] 2018-01-13 14:56
I agree with two issue.
Adding `groupsStatic` property to CS may require refactoring a lot of code in ImportOrder moudle.

**Comment by romani** [comment] 2018-01-13 16:19
you are welcome to do all required changes.
Right now you might be the the only person who know this code best of all.

**Comment by djydewang** [comment] 2018-01-13 16:28
Please check regression reports in PR again to confirm that CS's behaviour is valid now:)

**Comment by liutikas** [comment] 2018-01-31 00:58
We (Android team at Google) got hit by this too. We moved from Checkstyle 8.1 -> 8.7 and now we are getting a bunch of warnings from ImportOrder about "Extra separation in import group before".

Do we know what caused the regression? I tried to read this issue, but I do not seem to understand how the behavior has changed from previously working to now being broken. Did we simply stop looking at `separated` property for static imports?

Here is the config we use:
```
<module name="ImportOrder">
  <property name="severity" value="error"/>
  <message key="import.ordering" value="Wrong order for {0} import. Use Ctrl+Shift+O (Eclipse) or Ctrl+Alt+O (Intellij) to sort imports. https://source.android.com/setup/code-style#order-import-statements"/>
  <property name="groups" value="android, com.android, dalvik, com, gov, junit, libcore, net, org, java, javax"/>
  <property name="ordered" value="true"/>
  <property name="option" value="top"/>
  <property name="separated" value="true"/>
</module>
```

**Comment by davidburstromspotify** [comment] 2018-01-31 14:49
We (Android team at Spotify) also got hit by this.

**Comment by cesar1000** [comment] 2018-02-03 23:08
Same for Twitter for Android. We're stuck with 8.2 until this is fixed.

**Comment by romani** [comment] 2018-03-17 14:09
@cesar1000, @davidburstromspotify, @liutikas 

sorry for delay in response.
if such opensource project exists ..... please send me link to project that enforce import order by checkstyle, and command on how to run checkstyle from command line. 
We will use it in our CI process to make sure that we will not do such terrible regression any more.

**Comment by cesar1000** [comment] 2018-03-17 18:52
I'm not aware of an open source project that uses this particular import ordering. Would you be able to test for it in a unit test running on a file that uses both static and non-static imports in multiple groups?

**Comment by romani** [comment] 2018-03-18 13:11
> Would you be able to test for it in a unit test running on a file that uses both static and non-static imports in multiple groups?

we will have too, it is non-disputable part of process, we are already over-demanding for this (100% ut coverage, 100% pitest, ...).
But regressions still happening, as Check is very diverse in functionality and it is hard keep whole context in one head. We had such problems in other Checks and regression testing on real projects helps a lot.

@davidburstromspotify, do you have some project that is blocked at Spotify ? I see bunch of projects of github, but it is hard to get to know which we can use.

**Comment by davidburstromspotify** [comment] 2018-03-18 22:13
The Android app sources are blocked on this issue, and they are closed source, sorry. I agree with @cesar1000, I think a unit test should be sufficient.

**Comment by cesar1000** [comment] 2018-03-19 15:20
Yeah, I can see how that's useful if you happen to have a live project for regression testing. Unfortunately, we don't currently have any open source project on github that use this configuration.

**Comment by romani** [comment] 2018-05-31 04:04
@cesar1000 , @liutikas , @davidburstromspotify ,

Can we ask you a favor to share your ImportOrder exact config and several examples(different by style) of imports that you have in files (we do not need your private code, and even names of classes, but I hope you can share imports block).
We are close to finish , thanks to @pbludov, but testing is huge struggle. Before we ask you to test on your projects, we would rather make sure that your configs and imports are passing testing.

Thanks in advance.

**Comment by liutikas** [comment] 2018-05-31 04:16
Here is our [config](https://android.googlesource.com/platform/prebuilts/checkstyle/+/master/default-treewalker-checks.xml#158) and`ImportOrder` in particular:

```
<module name="ImportOrder">
  <property name="severity" value="error"/>
  <message key="import.ordering" value="Wrong order for {0} import. Use Ctrl+Shift+O (Eclipse) or Ctrl+Alt+O (Intellij) to sort imports. https://source.android.com/setup/code-style#order-import-statements"/>
  <property name="groups" value="android, androidx, com.android, dalvik, com, gov, junit, libcore, net, org, java, javax"/>
  <property name="ordered" value="true"/>
  <property name="option" value="top"/>
  <property name="separated" value="true"/>
</module>
```

and here is an example imports
```
import static android.graphics.drawable.Icon.TYPE_ADAPTIVE_BITMAP;
import static android.graphics.drawable.Icon.TYPE_BITMAP;
import static android.graphics.drawable.Icon.TYPE_DATA;
import static android.graphics.drawable.Icon.TYPE_RESOURCE;
import static android.graphics.drawable.Icon.TYPE_URI;

import static androidx.annotation.RestrictTo.Scope.LIBRARY;
import static androidx.annotation.RestrictTo.Scope.LIBRARY_GROUP;

import android.app.ActivityManager;
import android.content.ContentResolver;
import android.content.Context;
import android.content.Intent;
import android.content.pm.ApplicationInfo;
import android.graphics.Shader;
import android.graphics.drawable.BitmapDrawable;
import android.os.Parcelable;
import android.text.TextUtils;
import android.util.Log;

import androidx.annotation.ColorInt;
import androidx.annotation.DrawableRes;
import androidx.annotation.IdRes;
import androidx.annotation.IntDef;
import androidx.annotation.RestrictTo;
import androidx.annotation.VisibleForTesting;
import androidx.core.content.ContextCompat;
import androidx.core.content.res.ResourcesCompat;
import androidx.core.util.Preconditions;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.reflect.InvocationTargetException;
import java.nio.charset.Charset;
```

and other set:
```
import static android.app.slice.Slice.HINT_ACTIONS;
import static android.app.slice.Slice.HINT_ERROR;
import static android.app.slice.Slice.HINT_SUMMARY;
import static android.app.slice.Slice.HINT_TITLE;
import static android.app.slice.SliceItem.FORMAT_TEXT;

import static androidx.annotation.RestrictTo.Scope.LIBRARY;
import static androidx.slice.builders.ListBuilder.ICON_IMAGE;
import static androidx.slice.builders.ListBuilder.INFINITY;
import static androidx.slice.builders.ListBuilder.LARGE_IMAGE;
import static androidx.slice.core.SliceHints.SUBTYPE_MIN;

import android.app.PendingIntent;
import android.net.Uri;

import androidx.annotation.ColorInt;
import androidx.annotation.NonNull;
import androidx.core.graphics.drawable.IconCompat;
import androidx.slice.Clock;
import androidx.slice.Slice;
import androidx.slice.builders.SliceAction;

import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
```

Hopefully this is sufficient.

**Comment by davidburstromspotify** [comment] 2018-05-31 06:44
This is our configuration, still based on Checkstyle 8.1:

```
        <module name="ImportOrder">
            <property name="groups" value="android,com,net,junit,org,java,javax"/>
            <property name="ordered" value="true"/>
            <property name="separated" value="true"/>
            <property name="option" value="bottom"/>
        </module>
```

And an import snippet:

```
import com.spotify.x.R;

import javax.inject.Inject;

import static android.support.test.espresso.action.ViewActions.click;
import static android.support.test.espresso.matcher.ViewMatchers.isDisplayed;
import static android.support.test.espresso.matcher.ViewMatchers.withContentDescription;
import static android.support.test.espresso.matcher.ViewMatchers.withText;

import static com.spotify.X.o;

import static org.hamcrest.core.AllOf.allOf;
```

**Comment by cesar1000** [comment] 2018-06-03 19:07
And this is our configuration:

```
        <module name="ImportOrder">
            <property name="groups" value="android,com.twitter,com,junit,net,org,java,javax"/>
            <property name="ordered" value="true"/>
            <property name="separated" value="true"/>
            <property name="caseSensitive" value="true"/>
            <property name="option" value="bottom"/>
        </module>
```

And some imports:

```
import android.os.SystemClock;
import android.support.test.InstrumentationRegistry;
import android.support.test.runner.AndroidJUnit4;
import android.test.suitebuilder.annotation.LargeTest;

import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import static com.twitter.android.utils.EspressoHelpers.goBack;
import static com.twitter.android.utils.EspressoHelpers.swipeAwayAndWait;
import static com.twitter.android.utils.EspressoHelpers.swipeDown;
import static com.twitter.android.utils.EspressoHelpers.tapOnHomeTab;
import static com.twitter.android.utils.EspressoHelpers.tapOnTweetWithText;

import static org.assertj.core.api.Assertions.assertThat;
```

**Comment by busbey** [comment] 2018-06-18 18:28
Can someone provide a summary of what the work to fix this currently looks like? over in Apache HBase we're blocked on upgrading to the latest Checkstyle by this ([HBASE-20749](https://issues.apache.org/jira/browse/HBASE-20749)) and I'm interested if there's anything we could do to help move it forward.

**Comment by romani** [comment] 2018-06-20 05:34
@busbey , fix is in progress , details are at #5839 , unfortunately fix does not looks like simple a lot of conner cases.

**Comment by romani** [comment] 2018-06-20 06:47
@busbey , can you share a command on how you run checkstyle on HBase project and build is failed when violation is present.

**Comment by romani** [comment] 2018-07-04 03:50
@liutikas , 

> Here is our config andImportOrder in particular:

do you know any project at https://android.googlesource.com or https://android.googlesource.com/platform/ that use https://android.googlesource.com/platform/prebuilts/checkstyle/+/master/default-treewalker-checks.xml , so we can test them our self?
We almost ready with fix, just need to recheck fix on bigger scope of files before we ask you to test fix on your private projects.

**Comment by romani** [comment] 2018-07-05 07:50
@cesar1000 , @liutikas , @davidburstromspotify , @busbey ,

Looks like we restored functionality to support cases that you have.
Before we merge fix and release it, it would be awesome is you make test executions on your side to confirm no problems.
Fix is located at #5993.
To get jar, please do:
```
git clone https://github.com/Softus/checkstyle.git
git checkout issue-5279
mvn install -Pno-validations
# use 8.12-SNAPSHOT version in your project
```
Attention: unfortunately config need to be changed
androind team counfig should be - https://github.com/checkstyle/checkstyle/pull/5993/commits/3e805d1193a06a6ce864c5dff0f808810ff226a0#diff-8cbdbd6fcb09b75292e7f30f3b2e49e4R6
Spotify team - https://github.com/checkstyle/checkstyle/pull/5993/commits/3e805d1193a06a6ce864c5dff0f808810ff226a0#diff-19b84c994ece9dad308ccbbf8febdeaeR6
twitter team - https://github.com/checkstyle/checkstyle/pull/5993/commits/3e805d1193a06a6ce864c5dff0f808810ff226a0#diff-6ecfe25d96396315ec8b1aebe20d0256R6
All you need to make `separatedStaticGroups=true` and `staticGroups=<copy of groups property value>`

As you confirm, I will do merge and try to release it sooner than we usually do releases.

**Comment by davidburstromspotify** [comment] 2018-07-05 09:04
@romani Thank you, I can confirm that it works as intended for Spotify. Looking forward to the release!

**Comment by seanmmills** [comment] 2018-07-05 18:41
@romani, I confirm this works for my projects as well.  Great news!

**Comment by madrob** [comment] 2018-07-05 21:18
@romani I tried for HBase following your instructions, looks like we're still getting new errors. I think what we see is a different but related error, please don't consider us blocking on this change. We can follow up separately to sort things out.

**Comment by romani** [comment] 2018-07-05 22:15
@madrob , please share command by which you run checkstyle on your(hbase) project, we will take a look.

**Comment by madrob** [comment] 2018-07-05 22:59
@romani it's pretty gross right now, but we're working to improve it. This should get you the output you need, I think, without having to sit through a full build.

```
git clone git@github.com:apache/hbase.git
cd hbase
mvn clean install -pl .,hbase-checkstyle
mvn checkstyle:checkstyle -pl hbase-common -am -Dcheckstyle.consoleOutput=true | grep ERROR > /tmp/checkstyle8.2
git checkout HBASE-20749 # Includes WIP attempt at upgrading checkstyle versions
mvn clean install -pl .,hbase-checkstyle
mvn checkstyle:checkstyle -pl hbase-common -am -Dcheckstyle.consoleOutput=true | grep ERROR > /tmp/checkstyle8.12
```

This is the same issue I was concerned about in #5863 and https://groups.google.com/forum/#!topic/checkstyle/IVRI2CLk8k4

I _think_ the problem is our use of the \* group, but I haven't spent long enough to try to fix it. The relevant part of our config (with patch applied) is:

```
<module name="ImportOrder">
  <property name="groups"
                value="com,java,*,org.apache.hbase.thirdparty,org.apache.hadoop.hbase.shaded"/>
  <property name="staticGroups"
                value="com,java,*,org.apache.hbase.thirdparty,org.apache.hadoop.hbase.shaded"/>
  <property name="option" value="top" />
  <property name="ordered" value="true"/>
  <property name="sortStaticImportsAlphabetically" value="true"/>
  <property name="separatedStaticGroups" value="true"/>
</module>
```

And you'll see a bunch of new ImportOrder violations in the `checkstyle8.12` output.

The problem is that we have imports like this in JitterScheduledThreadPoolExecutorImpl.java

```
import java.util.concurrent.TimeoutException;

import org.apache.yetus.audience.InterfaceAudience;
```

These both fall under the same * group, so checkstyle doesn't expect blank lines in between. But if I split * into "java,org" we have other places that don't have the blank line, so it's a mess. The behavior before didn't care about blank lines inside of groups, so it's maybe the same cause of the issue we see, but a different fix than what we have here.

Really, we might be better off using the suppressions that you described to me before.

**Comment by romani** [comment] 2018-07-06 01:02
@pbludov , if close to PC , please recheck hbase case, I will be out for next couple hours

**Comment by busbey** [comment] 2018-07-06 02:10
That's essentially what hbase does now, but we do it by comparing checkstyle violations before and after each new contribution rather than formally excluding and failing the build on new ones. (We do turn on build failing per-module when cleanup finishes in one place.)

**Comment by romani** [comment] 2018-07-06 02:32
@madrob or @busbey , there is no HBASE-20749 branch on github.
I just updated version in parent pom, and now I see a difference.

**Comment by madrob** [comment] 2018-07-06 03:08
Blah, sorry, that should have been `git clone git@github.com:madrob/hbase.git`

**Comment by romani** [comment] 2018-07-06 06:46
@madrob , @busbey ,

by changes like
```
$ git diff
diff --git a/hbase-checkstyle/src/main/resources/hbase/checkstyle-suppressions.xml b/hbase-checkstyle/src/main/resources/hbase/checkstyle-suppressions.xml
index 1679496..7d58bef 100644
--- a/hbase-checkstyle/src/main/resources/hbase/checkstyle-suppressions.xml
+++ b/hbase-checkstyle/src/main/resources/hbase/checkstyle-suppressions.xml
@@ -1,7 +1,7 @@
 <?xml version="1.0"?>
 <!DOCTYPE suppressions PUBLIC
-    "-//Puppy Crawl//DTD Suppressions 1.0//EN"
-    "http://www.puppycrawl.com/dtds/suppressions_1_0.dtd">
+    "-//Checkstyle//DTD SuppressionFilter Configuration 1.2//EN"
+    "https://checkstyle.org/dtds/suppressions_1_2.dtd">
 <!--
   TODO Update to use the message suppression filter once we can update
   to checkstyle 8.6+
@@ -46,6 +46,7 @@
   <suppress checks="EmptyBlockCheck" files="TBoundedThreadPoolServer.java"/>
   <suppress checks="EqualsHashCode" files="StartcodeAgnosticServerName.java"/>
   <suppress checks="MethodLength" files="Branch1CoprocessorMethods.java"/>
+  <suppress files=".*" checks="ImportOrder" message="Extra separation in import group before"/>
 <!--
   TODO use message filter once we can upgrade to checkstyle 8.6+
   <suppress checks="IllegalImport" message="org\.apache\.htrace\.core"/>
```

you can suppress all violations for extra separatations.

**Comment by romani** [comment] 2018-07-06 06:47
@cesar1000 , @liutikas , please try to find time to test our fix.

**Comment by cesar1000** [comment] 2018-07-07 01:08
The fix works for us! Thanks for the thoroughness, @romani

**Comment by romani** [comment] 2018-07-07 02:55
@liutikas , please confirm how it works for you.

It would be awesome to reply on https://github.com/checkstyle/checkstyle/issues/5279#issuecomment-402355360

**Comment by romani** [comment] 2018-07-12 03:20
fix is merged.

@liutikas , It would be awesome if you reply on https://github.com/checkstyle/checkstyle/issues/5279#issuecomment-402355360 .

**Closed** 2018-07-12 03:21 UTC
Labels: approved, new feature

**Comment by cesar1000** [comment] 2018-07-12 03:31
Awesome, thanks!!

**Comment by liutikas** [comment] 2018-08-08 17:26
> do you know any project at https://android.googlesource.com or https://android.googlesource.com/platform/ that use https://android.googlesource.com/platform/prebuilts/checkstyle/+/master/default-treewalker-checks.xml , so we can test them our self?
We almost ready with fix, just need to recheck fix on bigger scope of files before we ask you to test fix on your private projects.

This project (and this branch):
https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev

it uses:
https://android.googlesource.com/platform/prebuilts/checkstyle/+/master/android-style.xml
(which pulls in default-copyright-check.xml, default-javadoc-checks.xml, etc using xml entity linking.
