### ISSUE TITLE
Clarify misleading command line tool (CLI) output

### ISSUE THREAD

**Issue by rs23** [checkstyle/checkstyle#1062] opened 2015-05-08 05:20 UTC
When the version 6.6 command line tool reports Audit errors, it appends the message "Could not execute Checkstyle: ...", which is untrue. After that it dumps a stack trace and prints usage hints, which are pointless in this situation. 

For batch processing it would be useful to map problems to the exit code, like 0 = checkstyle fine, no problems found, <0 = checkstyle failed, >0 checkstyle ok, but found Audit errors.

**Comment by romani** [comment] 2015-05-09 00:04
In 6.6 we did unfortunate regression, see details of #1018 , please recheck 6.7-snapshot version [how to generate binaries](https://github.com/checkstyle/checkstyle/wiki/Build-all-jars-and-generate-maven-site).

> For batch processing it would be useful to map problems to the exit code, like 0 = checkstyle fine, no problems found, <0 = checkstyle failed, >0 checkstyle ok, but found Audit errors.

That is good idea, to differ "<0" and ">0" codes. If you need that functionality please feel free to do PR, Here is place to fix - https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Main.java#L100 , please do not forget about UTs.

**Comment by Bhavik3** [comment] 2015-06-10 16:30
Solution:
Found CLI violation >> exit(-1)

Found other error (but not CLI violations) >> exit(-2)

Found Audit violations >> exit(0)

Found Audit errors >> exit(numOfErrors)

Is this fine?

**Comment by romani** [comment] 2015-06-10 18:45
looks like typo 

> Found Audit violations >> exit(0)

should be "Found NO Audit violations >> exit(0)"

the rest is fine,please proceed with implementation and UTs for that.

**Comment by rs23** [comment] 2015-06-11 02:03
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi,

Same comment, exit(0) should signal no problems.

- --RS

Roman Ivanov wrote, On 2015-06-10 20:45:
> looks like typo
> 
> Found Audit violations >> exit(0)
> 
> should be "Found NO Audit violations >> exit(0)"
> 
> the rest is fine,please proceed with implementation and UTs for
> that.
> 

- -- 
Reinhard Schiedermeier - Fakultät für Informatik und Mathematik
Hochschule München / Munich University of Applied Sciences
http://sol.cs.hm.edu/rs -- PGP encrypted mail preferred
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iD8DBQFVeOxSjBZT6ATauAsRAhJFAKCP8E9JrdqSgRTHpSjKH+wfg6CLMACeMOYH
FhugCsUYzhoQw8gqJofM8fs=
=8T8R
-----END PGP SIGNATURE-----

**Comment by romani** [comment] 2015-06-14 16:38
merged.

**Closed by romani** 2015-06-14 16:38 UTC
Labels: approved, high demand
