### ISSUE TITLE
Add support for enhanced instanceof

### ISSUE THREAD

**Issue by strkkk** [checkstyle/checkstyle#7290] opened 2019-11-29 07:11 UTC
```
$ cat TestClass.java
public class TestClass {
 {
 	Object o = "";
	if (o instanceof String s) { // jep 305
		System.out.println(s.toLowerCase());
	}
 }
}

/var/tmp $ java  -jar checkstyle-8.20-all.jar -t TestClass.java
com.puppycrawl.tools.checkstyle.api.CheckstyleException: IllegalStateException 
occurred while parsing file TestClass.java
Caused by: TestClass.java:4:26: expecting RPAREN, found 's'
```
Link to [JEP](https://openjdk.java.net/jeps/305)
It is for java 14

https://docs.oracle.com/en/java/javase/14/docs/specs/patterns-instanceof-jls.html#jls-6.3.1

**Comment by romani** [comment] 2019-11-29 22:56
This syntax usage might result in bunch of regressions in existing Checks that try to analyze scope of variables.

**Comment by nmancus1** [comment] 2020-03-28 20:53
Is this what you would expect?

```
➜  Issue-7290 cat TestClass.java                                          
public class TestClass {
 {
 	Object o = "";
	if (o instanceof String s) { // jep 305
		System.out.println(s.toLowerCase());
	}
 }
}
➜  Issue-7290 java -jar checkstyle-8.31-SNAPSHOT-all.jar -t TestClass.java
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> TestClass [1:13]
`--OBJBLOCK -> OBJBLOCK [1:23]
    |--LCURLY -> { [1:23]
    |--INSTANCE_INIT -> INSTANCE_INIT [2:1]
    |   `--SLIST -> { [2:1]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [3:2]
    |       |   |--MODIFIERS -> MODIFIERS [3:2]
    |       |   |--TYPE -> TYPE [3:2]
    |       |   |   `--IDENT -> Object [3:2]
    |       |   |--IDENT -> o [3:9]
    |       |   `--ASSIGN -> = [3:11]
    |       |       `--EXPR -> EXPR [3:13]
    |       |           `--STRING_LITERAL -> "" [3:13]
    |       |--SEMI -> ; [3:15]
    |       |--LITERAL_IF -> if [4:1]
    |       |   |--LPAREN -> ( [4:4]
    |       |   |--EXPR -> EXPR [4:7]
    |       |   |   `--LITERAL_INSTANCEOF -> instanceof [4:7]
    |       |   |       |--IDENT -> o [4:5]
    |       |   |       |--TYPE -> TYPE [4:18]
    |       |   |       |   `--IDENT -> String [4:18]
    |       |   |       `--IDENT -> s [4:25]
    |       |   |--RPAREN -> ) [4:26]
    |       |   `--SLIST -> { [4:28]
    |       |       |--EXPR -> EXPR [5:20]
    |       |       |   `--METHOD_CALL -> ( [5:20]
    |       |       |       |--DOT -> . [5:12]
    |       |       |       |   |--DOT -> . [5:8]
    |       |       |       |   |   |--IDENT -> System [5:2]
    |       |       |       |   |   `--IDENT -> out [5:9]
    |       |       |       |   `--IDENT -> println [5:13]
    |       |       |       |--ELIST -> ELIST [5:34]
    |       |       |       |   `--EXPR -> EXPR [5:34]
    |       |       |       |       `--METHOD_CALL -> ( [5:34]
    |       |       |       |           |--DOT -> . [5:22]
    |       |       |       |           |   |--IDENT -> s [5:21]
    |       |       |       |           |   `--IDENT -> toLowerCase [5:23]
    |       |       |       |           |--ELIST -> ELIST [5:35]
    |       |       |       |           `--RPAREN -> ) [5:35]
    |       |       |       `--RPAREN -> ) [5:36]
    |       |       |--SEMI -> ; [5:37]
    |       |       `--RCURLY -> } [6:1]
    |       `--RCURLY -> } [7:1]
    `--RCURLY -> } [8:0]

```

I haven't ran regression on this yet, but if this is the expected tree, I can start on this. `mvn clean verify` builds no problem with my changes.

**Comment by strkkk** [comment] 2020-03-29 09:12
@nmancus1 thank you.
Can you please show what is the difference between usual instanceof and enhanced one?
Is it only last ident?

**Comment by nmancus1** [comment] 2020-03-29 12:58
That's correct, I've just modified the `relationalExpression` rule to catch an optional `IDENT` after the `typeSpec`.  I though that would be the simplest way to implement this with the least amount of other changes.

**Comment by strkkk** [comment] 2020-03-29 15:03
May be it will be better to make this part as VARIABLE_DEF token?
Usually, code like `String s;` is parsed as variable definition.
I seems better, but I guess there is gonna be more regression in this case.

**Comment by nmancus1** [comment] 2020-03-29 18:18
@strkkk How would this be:

```
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> TestClass [1:13]
...
    |       |--LITERAL_IF -> if [4:1]
    |       |   |--LPAREN -> ( [4:4]
    |       |   |--EXPR -> EXPR [4:7]
    |       |   |   `--LITERAL_INSTANCEOF -> instanceof [4:7]
    |       |   |       |--IDENT -> o [4:5]
    |       |   |       `--VARIABLE_DEF -> VARIABLE_DEF [4:18]
    |       |   |           |--MODIFIERS -> MODIFIERS [4:18]
    |       |   |           |--TYPE -> TYPE [4:18]
    |       |   |           |   `--IDENT -> String [4:18]
    |       |   |           `--IDENT -> s [4:25]
    |       |   |--RPAREN -> ) [4:26]
    |       |   `--SLIST -> { [4:28]
...
    `--RCURLY -> } [8:0]



```

**Comment by strkkk** [comment] 2020-03-29 20:49
I like this approach more.
@romani @rnveach @pbludov what do you think, how AST should look like?

**Comment by nmancus1** [comment] 2020-04-01 05:47
The ANTLR grammar regression test is still running, but here's the results of the normal regression tests, using `checktstyle_checks.xml`, broken into three parts:
https://nmancus1.github.io/Issue-7290/diff_1/index.html
https://nmancus1.github.io/Issue-7290/diff_2/index.html
https://nmancus1.github.io/Issue-7290/diff_3/index.html

I will update this comment with a link to the grammar regression test when it is complete.

**Comment by pbludov** [comment] 2020-04-03 19:42
> how AST should look like?

Note that the docs says this is a __pattern__ rather than a variable def:
```
RelationalExpression:
     ...
     RelationalExpression instanceof ReferenceType
     RelationalExpression instanceof Pattern

Pattern:
     ReferenceType Identifier
```
So the tree should be more complicated:
```
|--EXPR -> EXPR [4:7]
|   `--LITERAL_INSTANCEOF -> instanceof [4:7]
|       |--IDENT -> o [4:5]
|       `--PARRERN_DEF -> PARRERN_DEF [4:18]
|           `--VARIABLE_DEF -> VARIABLE_DEF [4:18]
|               |--MODIFIERS -> MODIFIERS [4:18]
|               |--TYPE -> TYPE [4:18]
|               |   `--IDENT -> String [4:18]
|               `--IDENT -> s [4:25]
```

In the future, the pattern matching may grow to something like

```(java)
if (o instanceof Point(x,y) && x > 0)
```
in this case there still be the `PATTERN_DEF` node and some kind of `RECORD_DEF` of something like that.

**Comment by nmancus1** [comment] 2020-04-04 12:20
> Note that the docs says this is a pattern rather than a variable def

This is a good point. Regarding `RECORD_DEF`; that should then replace `VARIABLE_DEF`, in the tree you've constructed, correct?

**Comment by pbludov** [comment] 2020-04-04 13:01
> This is a good point. Regarding `RECORD_DEF`; that should then replace `VARIABLE_DEF`, in the tree you've constructed, correct?

I'm not sure. Either replace it or wrap it. From a [possible](https://cr.openjdk.java.net/~briangoetz/amber/pattern-match.html#pattern-matching-and-records) future point of view, the wrap is better.

In this case, we have the ability to extend the patterns. And all existing checks like [VariableName](https://checkstyle.org/config_coding.html#VariableName) will handle such variables.  Especially [HiddenField](https://checkstyle.org/config_coding.html#HiddenField) - it is important to catch code like this:
```(java)
class Foo {
  String name;
  void method(Object obj) {
     if (obj instanceof String name) {
         bar(name); // (String)obj
     } else {
         bar(name); // this.name
     }
  }
}
```
On the other hand, the check [VisibilityModifier](https://checkstyle.org/config_design.html#VisibilityModifier) (and, possible other) need to be updated to ignore matching variables as well.

The bad news is that we can't do regression tests, because we're going to test code that doesn't exist yet.

**Comment by nmancus1** [comment] 2020-06-04 16:54
Additional information about and examples of enhanced instanceof with pattern matching for mentors:
1. https://www.baeldung.com/java-pattern-matching-instanceof
2. https://blog.solidsoft.pl/2020/03/03/improved-instanceof-operator-in-java-14/
     this article has a nice tie in with groovy, as well. 
3. https://javaalmanac.io/features/instanceof-patterns/
4. https://cr.openjdk.java.net/~briangoetz/amber/pattern-match.html#pattern-matching-and-records
Also, please see above [JEP](https://openjdk.java.net/jeps/305) link.

**Comment by pbludov** [comment] 2020-07-07 20:33
Fix is merged.

**Closed by pbludov** 2020-07-07 20:33 UTC
Labels: antlr, approved
