### ISSUE TITLE
Update wiki to page to mention latest pitest profiles.

### ISSUE THREAD

**Issue by Vyom-Yadav** [checkstyle/checkstyle#11728] opened 2022-06-12 04:36 UTC
Update https://github.com/checkstyle/checkstyle/wiki/How-to-run-certain-phases-and-validations#how-to-generate-pitest-report to reflect changes done in #11707

**Comment by romani** [comment] 2022-06-12 04:59
We need to just mention that `.ci/pitest.sh --list` prints all

**Comment by nick-mancuso** [comment] 2022-06-29 13:16
Duplicate of https://github.com/checkstyle/checkstyle/issues/11765 (other issue is already approved, otherwise I would close that one)

**Closed by nick-mancuso** 2022-06-29 13:16 UTC
