### ISSUE TITLE
Update AbstractChecks to log DetailAST - JavadocStyle

### ISSUE THREAD

**Issue by rnveach** [checkstyle/checkstyle#7740] opened 2020-03-01 16:11 UTC
Child of https://github.com/checkstyle/checkstyle/issues/5777

This issue specifically focuses on JavadocStyle.

**Comment by wltan** [comment] 2020-03-13 09:43
@rnveach,
Some of the violations are currently impossible to log using DetailAST as there is simply no corresponding node attached to it inside comments.

I believe you brought this issue up some time ago in https://github.com/checkstyle/checkstyle/issues/5777#issuecomment-389868308 but I couldn't find any clear resolution from the discussion there. What's the current status for this problem? Do we have to reimplement the check using the Javadoc AST first?

**Comment by romani** [comment] 2020-03-13 14:32
@wltan ,

yes, javadocs check should be skipped for now.
you can update line https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L334 all other violations are placed on line wihtout any AST (they should be skipped, we will deal with this later).

after fixing this single place, please move Check to list `Also, the filter does not support Javadoc checks: ` of https://checkstyle.org/config_filters.html#SuppressionXpathFilter

**Comment by wltan** [comment] 2020-03-14 05:06
Understood, I am on it.

**Comment by wltan** [comment] 2020-03-14 07:31
> after fixing this single place, please move Check to list `Also, the filter does not support Javadoc checks: ` of https://checkstyle.org/config_filters.html#SuppressionXpathFilter

@romani There are some problems when I tried to do the above. `XpathRegressionTest` wants me to remove from `INCOMPATIBLE_CHECK_NAMES` and also add to `INCOMPATIBLE_JAVADOC_CHECK_NAMES`. However adding to the latter set causes more problems, because `JavadocStyleCheck` inherits from `AbstractCheck` and not `AbstractJavadocCheck`.
```
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.507 s <<< FAILURE! - in com.puppycrawl.tools.checkstyle.internal.XpathRegressionTest
[ERROR] validateIncompatibleJavadocCheckNames  Time elapsed: 0.253 s  <<< FAILURE!
com.google.common.truth.AssertionErrorWithFacts:
INCOMPATIBLE_JAVADOC_CHECK_NAMES should contains all descendants of AbstractJavadocCheck
missing (1): JavadocStyle
---
expected   : [AtclauseOrder, JavadocBlockTagLocation, SingleLineJavadoc, JavadocStyle, MissingDeprecated, JavadocTagContinuationIndentation, SummaryJavadoc, NonEmptyAtclauseDescription, JavadocParagraph]
but was    : [AtclauseOrder, SingleLineJavadoc, JavadocBlockTagLocation, MissingDeprecated, JavadocTagContinuationIndentation, SummaryJavadoc, NonEmptyAtclauseDescription, JavadocParagraph]
        at com.puppycrawl.tools.checkstyle.internal.XpathRegressionTest.validateIncompatibleJavadocCheckNames(XpathRegressionTest.java:216)
```
It's possible to make this error go away by specifically adding `JavadocStyle.class` to the individual UT, but I'm not sure if that's the best way to go about doing things. See: https://github.com/wltan/checkstyle/commit/d9bd46d118b64aa972ee33fbbd2a884cb67dce62#diff-b6cb26ed1119a622d1bb75564fff0561R214

What are your thoughts on this?

**Comment by rnveach** [comment] 2020-03-14 10:57
@romani @wltan 

> JavadocStyleCheck inherits from AbstractCheck and not AbstractJavadocCheck.

This is not a javadoc check.
https://github.com/checkstyle/checkstyle/blob/0a6a8f3a9dcb209f87d6d324761da28395237254/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L180
When we say Javadoc check, we mean it extends `AbstractJavadocCheck`. There shouldn't be anything stopping the conversion. It is possible this check may not be as simple as the other issues if it uses custom classes to hold the violation line.

I suggest first start by posting the links to the logs that are in this check to make a list. Figure out how complex each one is. Start with the straight forward easy ones and point out to us the ones you need guidance on. We need specifics of your issues to help you.

**Comment by wltan** [comment] 2020-03-14 11:54
There are seven calls to `log` in `JavadocStyleCheck`:
## 1 
https://github.com/checkstyle/checkstyle/blob/3953912f63bf368a5c586f276dca0d996cca3124/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L334

This one is easy. Remove the `.getLineNo()`, update the tests and that's about it. This is also the violation mentioned in https://github.com/checkstyle/checkstyle/issues/7740#issuecomment-598749259.

## 2
https://github.com/checkstyle/checkstyle/blob/3953912f63bf368a5c586f276dca0d996cca3124/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L362-L371

This is trickier. Although it is tempting to just use `ast` from the method parameters, from the javadoc of `checkComment` (which calls `checkFirstSentenceEnding`) we can see that `ast` is not the correct node pointing to the violation:

https://github.com/checkstyle/checkstyle/blob/3953912f63bf368a5c586f276dca0d996cca3124/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L321-L322

## 3
https://github.com/checkstyle/checkstyle/blob/3953912f63bf368a5c586f276dca0d996cca3124/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L378-L384

The method does not provide any `DetailAST` node whatsoever. I'm not very familiar with the AST parsing so maybe there is a way to find and obtain a node representing the comment somehow? Same for the second case above I suppose.

## 4, 5, 6, & 7
https://github.com/checkstyle/checkstyle/blob/3953912f63bf368a5c586f276dca0d996cca3124/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L488-L489
https://github.com/checkstyle/checkstyle/blob/3953912f63bf368a5c586f276dca0d996cca3124/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L500-L503
https://github.com/checkstyle/checkstyle/blob/3953912f63bf368a5c586f276dca0d996cca3124/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L527-L528
https://github.com/checkstyle/checkstyle/blob/3953912f63bf368a5c586f276dca0d996cca3124/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L567-L570

These four calls get their data from a `HtmlTag` object. To my knowledge there is no way that you can retrieve similar line and column information using only `DetailAST` nodes, as the normal Java AST does not look inside comments.

**Comment by wltan** [comment] 2020-03-14 12:03
@rnveach What I'm having trouble with is complying with this instruction specifically:
> after fixing this single place, please move Check to list `Also, the filter does not support Javadoc checks: ` of https://checkstyle.org/config_filters.html#SuppressionXpathFilter

It appears that there is a test in place that ensures only subclasses of `AbstractJavadocCheck` (i.e. only javadoc checks) are allowed in the list.
https://github.com/checkstyle/checkstyle/blob/1d152188dcae6b1cd4fe5a414bff576b51f69c06/src/test/java/com/puppycrawl/tools/checkstyle/internal/XpathRegressionTest.java#L206-L216
Since `JavadocStyle` is not a javadoc check, I can't place it there, and from your comment I suppose it never should be there in the first place. Is that right?

**Comment by rnveach** [comment] 2020-03-14 12:29
> Since JavadocStyle is not a javadoc check, I can't place it there, and from your comment I suppose it should never be there in the first place. Is that right?

Correct.

> There are seven calls to log in JavadocStyleCheck:

I recommend starting a PR for 1. It looks the easiest. It will not make the entire check xpath complaint so documentation cannot be updated. The check is only xpath complaint when all logs send the AST, and we will need a test for each individual log call.

For 2 and 3, examine the stack of the TextBlock comment (where it comes from, what it is assigned from, how it is passed along to the final method, etc.) and see if it is being generated from an AST that can be passed to the method. If this does not work let us know why with more specifics.

For 4 through 7, do the same thing as 2 and 3 for the HtmlTag object. Is the object being generated by giving it an AST or does it location it is being generated have access to the AST? I could see us expanding this object to hold the AST for us to use in violations. If this is how we proceed, then my follow-up question is can we just remove the line/column in the object and fully rely on the AST.

**Comment by rnveach** [comment] 2020-03-14 13:02
@romani ping

> This is also the violation mentioned in #7740 (comment).

I missed this part of @romani 's comment.

> you can update line https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L334 all other violations are placed on line wihtout any AST (they should be skipped, we will deal with this later).

I am not sure if he realized this isn't a AbstractJavadocCheck or he did and is thinking of the future where this will eventually be converted into a AbstractJavadocCheck . Basically this check uses an outdated regular expression parser and is known to have issues. He said to add it to `Javadoc checks` in the documentation but this is for AbstractJavadocChecks and it isn't one yet.

There is no telling when this check will be converted. It will probably be a big task.

He did agree on changing the 1 log, but I don't see much benefit especially if we don't announce to the users we partially support this check.

**Comment by romani** [comment] 2020-03-14 13:33
@wltan , after private conversation with @rnveach  ...

Please do:
1) Provide update for https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L334  ONLY. Please provide test for it.
2) please move Check to list `Also, the filter does not support suppression inside javadoc reported by Javadoc checks: ` (ATTENTION I propose change wording a bit, to be precise) of https://checkstyle.org/config_filters.html#SuppressionXpathFilter . We should make it clear for user that it is still not supported as majority of violations we do not able to suppress.
3) update UTs to allow JavadocStyleCheck to be in list with other Javadoc Checks (just do hardcoded addition of its name to list of all JavadocChecks), https://github.com/checkstyle/checkstyle/issues/7740#issuecomment-599048431 . So there should be a list all Checks AbstractJavadocCheck  and all our old implementations (JavadocMethod, JavadocStyle, JavadocType).

**Comment by wltan** [comment] 2020-03-15 07:04
> 1. Provide update for https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java#L334  ONLY. Please provide test for it.

Noted. Just to clarify, when you say "provide test for it" do you mean update the UTs only? Or add the Xpath test as well?

> 2. please move Check to list `Also, the filter does not support suppression inside javadoc reported by Javadoc checks: ` (ATTENTION I propose change wording a bit, to be precise) of https://checkstyle.org/config_filters.html#SuppressionXpathFilter . We should make it clear for user that it is still not supported as majority of violations we do not able to suppress.

Noted, I've changed this on my end. Will make the PR once the point above is clarified.

> 3. update UTs to allow JavadocStyleCheck to be in list with other Javadoc Checks (just do hardcoded addition of its name to list of all JavadocChecks), [#7740 (comment)](https://github.com/checkstyle/checkstyle/issues/7740#issuecomment-599048431) . So there should be a list all Checks AbstractJavadocCheck  and all our old implementations (JavadocMethod, JavadocStyle, JavadocType).

Noted. I've added JavadocStyleCheck for now, but for the other two (JavadocMethodCheck, JavadocTypeCheck) I'll add them when I get to the respective issues #7739 and #7741.

**Comment by romani** [comment] 2020-03-15 22:59
> update the UTs only? Or add the Xpath test as well?

provide Xpath IT test for it. in UT area we already have 100 coverage by tests.
We need verificaction that reporting on line:column helps to suppress by Xpath.

**Comment by romani** [comment] 2020-03-19 14:46
fix is merged.

**Closed by romani** 2020-03-19 14:46 UTC
Labels: approved, bug, gsoc second issue
