### ISSUE TITLE
LineLengthCheck cannot be suppressed with SuppressWithNearbyCommentFilter in checkstyle 8.24+

### ISSUE THREAD

**Issue by sebthom** [checkstyle/checkstyle#7460] opened 2020-01-10 20:32 UTC
Check documentation: https://checkstyle.org/config_sizes.html#LineLength

```
/var/tmp $ javac Test.java

/var/tmp $ cat config.xml
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<module name="Checker">
   <module name="LineLength">
      <!-- https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/sizes/LineLengthCheck.html -->
      <property name="max" value="40" />
      <property name="fileExtensions" value="java, js, xml"/>
   </module>
   <module name="TreeWalker">
      <module name="SuppressWithNearbyCommentFilter">
         <property name="commentFormat" value="CHECKSTYLE:IGNORE ([^ ]+) FOR NEXT LINE" />
         <property name="checkFormat" value="$1" />
         <property name="influenceFormat" value="1" />
      </module>
   </module>
</module>
```
```bash
/var/tmp $ cat Test.java
```
```java
class Test {
    // CHECKSTYLE:IGNORE LineLength FOR NEXT LINE
    public static final String TEXT = "THIS IS A TOOOOOOOOOOOOOOOOOOOOOOOOOOO LONG LINE";
}
```
```bash
/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar checkstyle-8.28-all.jar -c config.xml Test.java
Starting audit...
[ERROR] /var/tmp/Test.java:3: Line is longer than 80 characters (found 89). [LineLength]
Audit done.
Checkstyle ends with 1 errors.
```

---------------
Since the checkstyle [8.24](https://checkstyle.sourceforge.io/releasenotes.html#Release_8.24) LineLength checks cannot be declared below the TreeWalker module anymore. As a side effect a `SuppressWithNearbyCommentFilter` declared within the TreeWalker module cannot be used anymore to suppress LineLength violations. Using the `SuppressWithNearbyCommentFilter` outside the TreeWalker module also doesn't work.

How can I change the checkstyle config to achieve the same behaviour as in checkstyle 8.23 or lower with the given example?

--------------

**Comment by romani** [comment] 2020-01-10 20:56
This topic become hot .....

@sebthom , problem is that such Check changed parent module, so filters of TreeWalker (SuppressWithNearbyCommentFilter is one of them) is not applicable any more ( #2116) , see migration notes at #2116 on how to resolve issues right now (far from ideal workaround) .    

will be fixed one somebody implement - https://github.com/checkstyle/checkstyle/issues/7064
we are welcoming PRs.

I am closing this issue, because such behavior by design.

**Closed by romani** 2020-01-10 20:56 UTC

**Comment by romani** [comment] 2020-01-11 05:03
@sebthom, if you have problem to update configs, please keep sharing problem, we might help to ease problem.

**Comment by sebthom** [comment] 2020-01-11 13:37
For now I am disabling the check in the maven checkstyle plugin via
```xml
   <properties>
      <checkstyle.violation.ignore>LineLength</checkstyle.violation.ignore>
   </properties>
```
but leave it enabled in Eclipse. This ways the CI server can build the projects again.
