### ISSUE TITLE
Add Check Support for Java 17 Sealed Classes: VariableDeclarationUsageDistanceCheck

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#15076] opened 2024-06-21 01:10 UTC
child of #14969

check doc: https://checkstyle.org/checks/coding/variabledeclarationusagedistance.html#VariableDeclarationUsageDistance

---

I was struggling on how the following method is generated. 

https://github.com/checkstyle/checkstyle/blob/63747be122cf4e89b111f11d268b5853f9d88b52/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java#L1034-L1045

I searched through the PR when this code was introduced I got that this is to handle some test cases that have local class and sealed class can't be local class.

https://github.com/checkstyle/checkstyle/pull/12822#discussion_r1183653396

---

```
PS D:\CS\test> cat src/Test.java                                                
public class Test {
    void test() {
        sealed class test {

        }
    }
}
PS D:\CS\test> javac src/Test.java                                              
src\Test.java:3: error: sealed or non-sealed local classes are not allowed
        sealed class test {
        ^
1 error
PS D:\CS\test> 

```

---
We are ok here. This can be closed.

**Comment by rnveach** [comment] 2024-06-26 17:40
It seems to me a `sealed` class shouldn't impact this check. I assume we don't need inputs either.

> I was struggling on how the following method is generated.

This was added in https://github.com/checkstyle/checkstyle/commit/63747be122cf4e89b111f11d268b5853f9d88b52 .

It looks like it was intended to ignore `final` variables, but the method by itself does more than this as it triggers on any `modifier` token which I believe a lot of things have.

In the scheme of this check, I don't understand this well either.

**Comment by nrmancuso** [comment] 2024-06-28 14:25
We can close this issue, there is no work to be done here.

**Closed by nrmancuso** 2024-06-28 14:25 UTC
