### ISSUE TITLE
DetailAST should invalidate its methods cache (aka lazy-load)

### ISSUE THREAD

**Issue by MEZk** [checkstyle/checkstyle#3466] opened 2016-09-24 10:52 UTC
**Problem description:**

Methods from DetailAST such as getBranchTokenTypes, branchContains, getColumnNo, getLineNo, getChildCount use lazy-load approach. These methods can be invoked by the checks which are not subscribed to receive AST with comment nodes first and  than be invoked by the checks which are  subscribed to get AST with comment nodes. As a result the inner state of the DetailAST object might be "cached" without comment nodes in AST after the first invocation as the methods use lazy-load.  Such methods will return invalid results when they are invoked for the AST which can be accessed in checks that are subscribed to receive comment nodes and for which are not. 

**Possible sollution:**

One way forward to resolve the problem is to invalidate DetailAST methods "cache".

Resolving of the issue will allow us to fix #3102 .

**Comment by romani** [comment] 2016-09-30 22:14
fix is merged

**Closed by romani** 2016-09-30 22:14 UTC
Labels: approved, bug

**Comment by rnveach** [comment] 2016-09-30 22:36
@romani Fix invalidated `branchTokenTypes` cache but it did not invalidate `childCount` which was also in issue's description.
Since we also cache `childCount` and don't reset it on add children/siblings methods, it will keep count from non-comment trees into comment trees, as long as we don't call `setFirstChild` which is the only method to invalidate it currently. To avoid calling `setFirstChild`, issue can be seen with code samples like `public /* comment */ static void method () {}` where a comment/javadoc is between 2 other nodes.

Shouldn't it be added to this issue?

**Comment by romani** [comment] 2016-10-01 00:22
We did not found problem with childCount , ut was extended to check count.

If you still see a problem, please reproduce it with UT and do PR , could be done in separate issue.

**Comment by rnveach** [comment] 2016-10-01 00:30
`getChildCount` was called on `METHOD_DEF` in UT while the comments are located as a child of `MODIFIERS` in input. So the UT isn't directed at the correct location to show this issue.
I will create PR to showcase.
