### ISSUE TITLE
Xpath results are not sorted in document order

### ISSUE THREAD

**Issue by timurt** [checkstyle/checkstyle#6988] opened 2019-08-17 06:10 UTC
Current xpath implementation works well (I hope:) ), but I faced one problem, 
When you want to access xpath results by index `[index]` and you care about ordering of the results, but results are sorted in alphabetic order. Logically results should ordered as they appear in document

**XML Path Language (XPath)** [link](https://www.w3.org/TR/1999/REC-xpath-19991116/#dt-document-order)

> There is an ordering, document order, defined on all the nodes in the document corresponding to the order in which the first character of the XML representation of each node occurs in the XML representation of the document after expansion of general entities. Thus, the root node will be the first node. Element nodes occur before their children. Thus, document order orders element nodes in order of the occurrence of their start-tag in the XML (after expansion of entities). The attribute nodes and namespace nodes of an element occur before the children of the element. The namespace nodes are defined to occur before the attribute nodes. The relative order of namespace nodes is implementation-dependent. The relative order of attribute nodes is implementation-dependent. Reverse document order is the reverse of document order.

**XSLT 2.0 and XPath 2.0 Programmer's Reference by Michael Kay, page 492**

> The nodes in a sequence can always be sorted into document order. For elements from the same document, document order is the same as the order of the start tags in the original source. In terms of the tree structure, a node is ordered after its preceding siblings, and these are ordered after their parent node.

The following test demonstrates such situation with sorting and indexing

Example
```
/var/tmp $ cat InputXpathMapperAst.java
package com.puppycrawl.tools.checkstyle.xpath.xpathmapper;

public class InputXpathMapperAst {

    /**
     * Returns if current node has children.
     * @return if current node has children
     */
    public void callSomeMethod() {
        int variable = 123;
        String another = "HelloWorld";
        String[] array = new String[3];
        for (String cycle : array) {

        }
    }

    /**
     * Returns if current node has children.
     * @return if current node has children
     */
    public String getSomeMethod() {
        return "HelloWorld";
    }
}
```
```
/var/tmp $ java -jar checkstyle-8.24-SNAPSHOT-all.jar -J InputXpathMapperAst.java
...
    |   `--SLIST -> { [9:33]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [10:8]
    |       |   |--MODIFIERS -> MODIFIERS [10:8]
    |       |   |--TYPE -> TYPE [10:8]
    |       |   |   `--LITERAL_INT -> int [10:8]
    |       |   |--IDENT -> variable [10:12]
    |       |   `--ASSIGN -> = [10:21]
    |       |       `--EXPR -> EXPR [10:23]
    |       |           `--NUM_INT -> 123 [10:23]
    |       |--SEMI -> ; [10:26]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [11:8]
    |       |   |--MODIFIERS -> MODIFIERS [11:8]
    |       |   |--TYPE -> TYPE [11:8]
    |       |   |   `--IDENT -> String [11:8]
    |       |   |--IDENT -> another [11:15]
    |       |   `--ASSIGN -> = [11:23]
    |       |       `--EXPR -> EXPR [11:25]
    |       |           `--STRING_LITERAL -> "HelloWorld" [11:25]
    |       |--SEMI -> ; [11:37]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [12:14]
    |       |   |--MODIFIERS -> MODIFIERS [12:14]
    |       |   |--TYPE -> TYPE [12:14]
    |       |   |   `--ARRAY_DECLARATOR -> [ [12:14]
    |       |   |       |--IDENT -> String [12:8]
    |       |   |       `--RBRACK -> ] [12:15]
    |       |   |--IDENT -> array [12:17]
    |       |   `--ASSIGN -> = [12:23]
    |       |       `--EXPR -> EXPR [12:25]
    |       |           `--LITERAL_NEW -> new [12:25]
    |       |               |--IDENT -> String [12:29]
    |       |               `--ARRAY_DECLARATOR -> [ [12:35]
    |       |                   |--EXPR -> EXPR [12:36]
    |       |                   |   `--NUM_INT -> 3 [12:36]
    |       |                   `--RBRACK -> ] [12:37]
    |       |--SEMI -> ; [12:38]
    |       |--LITERAL_FOR -> for [13:8]
    |       |   |--LPAREN -> ( [13:12]
    |       |   |--FOR_EACH_CLAUSE -> FOR_EACH_CLAUSE [13:13]
    |       |   |   |--VARIABLE_DEF -> VARIABLE_DEF [13:13]
    |       |   |   |   |--MODIFIERS -> MODIFIERS [13:13]
    |       |   |   |   |--TYPE -> TYPE [13:13]
    |       |   |   |   |   `--IDENT -> String [13:13]
    |       |   |   |   `--IDENT -> cycle [13:20]
    |       |   |   |--COLON -> : [13:26]
    |       |   |   `--EXPR -> EXPR [13:28]
    |       |   |       `--IDENT -> array [13:28]
    |       |   |--RPAREN -> ) [13:33]
    |       |   `--SLIST -> { [13:35]
    |       |       `--RCURLY -> } [15:8]
    |       `--RCURLY -> } [16:4]
...

```

XpathMapperTest
```
@Test
public void testOrdering() throws Exception {
    final String xpath = 
       "(//METHOD_DEF[./IDENT[@text='callSomeMethod']]/SLIST/*)[1]";
    final RootNode rootNode = getRootNode("InputXpathMapperAst.java");
    final DetailAST[] actual = convertToArray(getXpathItems(xpath, rootNode));
    final DetailAST expectedVariableDefNode = getSiblingByType(
           rootNode.getUnderlyingNode(), TokenTypes.CLASS_DEF)
            .findFirstToken(TokenTypes.OBJBLOCK)
            .findFirstToken(TokenTypes.METHOD_DEF)
            .findFirstToken(TokenTypes.SLIST)
            .getFirstChild();
    final DetailAST[] expected = {expectedVariableDefNode};
    assertArrayEquals("Result nodes differ from expected", expected, actual);
}
```

As you can see first result must be `VARIABLE_DEF [10:8]`, because it appears earlier in document
But our xpath returns `for [13:8]`, simply because of lexicographic order

I think problem is in [here](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/xpath/AbstractNode.java#L147), maybe this method should be rewritten based on line/column and tree level
```
 @Override
    public int compareOrder(NodeInfo nodeInfo) {
        return getLocalPart().compareTo(nodeInfo.getLocalPart());
    }
```

@rnveach @romani

**Comment by romani** [comment] 2019-08-17 23:32
@timurt , 

> The nodes in a sequence can always be sorted into document order ...

please update description to define from where you quoted this text.

**Comment by timurt** [comment] 2019-08-25 05:47
@romani 
> please update description to define from where you quoted this text.

> Please try to minimize test input to keep only part that show a problem, it will minimize a tree. Please use most recent version of jar to report issue. It is better to avoid horizontal scrolling.

done

**Comment by romani** [comment] 2019-10-07 06:04
@timurt,
I cannot reproduce issue by CLI:
```
$ cat -n InputXpathMapperAst.java | head -n 12
     1	public class InputXpathMapperAst {
     2	
     3	    /**
     4	     * Returns if current node has children.
     5	     * @return if current node has children
     6	     */
     7	    public void callSomeMethod() {
     8	        int variable = 123;
     9	        String another = "HelloWorld";
    10	        String[] array = new String[3];
    11	        for (String cycle : array) {
    12	

$ java -jar checkstyle-8.25-all.jar -b "//METHOD_DEF[./IDENT[@text='callSomeMethod']]/SLIST/VARIABLE_DEF[0]" InputXpathMapperAst.java 

$ java -jar checkstyle-8.25-all.jar -b "//METHOD_DEF[./IDENT[@text='callSomeMethod']]/SLIST/VARIABLE_DEF[1]" InputXpathMapperAst.java 
CLASS_DEF -> CLASS_DEF [1:0]
`--OBJBLOCK -> OBJBLOCK [1:33]
    |--METHOD_DEF -> METHOD_DEF [7:4]
    |   `--SLIST -> { [7:33]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [8:8]

$ java -jar checkstyle-8.25-all.jar -b "//METHOD_DEF[./IDENT[@text='callSomeMethod']]/SLIST/VARIABLE_DEF[2]" InputXpathMapperAst.java 
CLASS_DEF -> CLASS_DEF [1:0]
`--OBJBLOCK -> OBJBLOCK [1:33]
    |--METHOD_DEF -> METHOD_DEF [7:4]
    |   `--SLIST -> { [7:33]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [9:8]

$ java -jar checkstyle-8.25-all.jar -b "//METHOD_DEF[./IDENT[@text='callSomeMethod']]/SLIST/VARIABLE_DEF[3]" InputXpathMapperAst.java 
CLASS_DEF -> CLASS_DEF [1:0]
`--OBJBLOCK -> OBJBLOCK [1:33]
    |--METHOD_DEF -> METHOD_DEF [7:4]
    |   `--SLIST -> { [7:33]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [10:14]

```

Am I miss something ?

FYI:Xpath that you have test method is invalid ... `Unexpected token ")" beyond end of expression`

**Comment by romani** [comment] 2019-12-12 23:47
@timurt , ping

**Comment by timurt** [comment] 2020-01-05 11:01
@romani 
Sorry for late response, 
Ok, I will try to reproduce issue and check if problem still exists

**Comment by timurt** [comment] 2020-01-06 06:47
@romani 
in your example try `java -jar checkstyle-8.29-SNAPSHOT-all.jar -b "//METHOD_DEF[./IDENT[@text='callSomeMethod']]/SLIST/*"  InputXpathMapperAst.java `

Output will be
```
CLASS_DEF -> CLASS_DEF [3:0]
`--OBJBLOCK -> OBJBLOCK [3:33]
    |--METHOD_DEF -> METHOD_DEF [9:4]
    |   `--SLIST -> { [9:33]
    |       |--LITERAL_FOR -> for [13:8]
---------
CLASS_DEF -> CLASS_DEF [3:0]
`--OBJBLOCK -> OBJBLOCK [3:33]
    |--METHOD_DEF -> METHOD_DEF [9:4]
    |   `--SLIST -> { [9:33]
    |       `--RCURLY -> } [16:4]
---------
CLASS_DEF -> CLASS_DEF [3:0]
`--OBJBLOCK -> OBJBLOCK [3:33]
    |--METHOD_DEF -> METHOD_DEF [9:4]
    |   `--SLIST -> { [9:33]
    |       |--SEMI -> ; [12:38]
---------
CLASS_DEF -> CLASS_DEF [3:0]
`--OBJBLOCK -> OBJBLOCK [3:33]
    |--METHOD_DEF -> METHOD_DEF [9:4]
    |   `--SLIST -> { [9:33]
    |       |--SEMI -> ; [11:37]
---------
CLASS_DEF -> CLASS_DEF [3:0]
`--OBJBLOCK -> OBJBLOCK [3:33]
    |--METHOD_DEF -> METHOD_DEF [9:4]
    |   `--SLIST -> { [9:33]
    |       |--SEMI -> ; [10:26]
---------
CLASS_DEF -> CLASS_DEF [3:0]
`--OBJBLOCK -> OBJBLOCK [3:33]
    |--METHOD_DEF -> METHOD_DEF [9:4]
    |   `--SLIST -> { [9:33]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [10:8]
---------
CLASS_DEF -> CLASS_DEF [3:0]
`--OBJBLOCK -> OBJBLOCK [3:33]
    |--METHOD_DEF -> METHOD_DEF [9:4]
    |   `--SLIST -> { [9:33]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [11:8]
---------
CLASS_DEF -> CLASS_DEF [3:0]
`--OBJBLOCK -> OBJBLOCK [3:33]
    |--METHOD_DEF -> METHOD_DEF [9:4]
    |   `--SLIST -> { [9:33]
    |       |--VARIABLE_DEF -> VARIABLE_DEF [12:14]
```

As you can see, `LITERAL_FOR -> for [13:8]` appears earlier than `VARIABLE_DEF -> VARIABLE_DEF [10:8]`, but logically results must be sorted by line number first and then by column number as they appear in AST tree

I didn't find any bad consequences of this bug yet, maybe it will not cause any problem
But I found that our implementation doesn't match Xpath documentation

should we fix it?

**Comment by romani** [comment] 2020-01-07 14:42
> But I found that our implementation doesn't match Xpath documentation

lets sync

> logically results must be sorted by line number first and then by column number as they appear in AST tree .... should we fix it?

yes, it would be awesome to fix it.

**Comment by romani** [comment] 2020-01-07 14:43
@timurt , issue is approved.

**Comment by rnveach** [comment] 2020-04-18 13:10
Fix was merged

**Closed** 2020-04-18 13:10 UTC
Labels: approved, xpath
