### ISSUE TITLE
indentation mismatch  with Google formatter over code blocks under switch

### ISSUE THREAD

**Issue by NathanEckert** [checkstyle/checkstyle#14294] opened 2024-01-18 14:59 UTC
I have read check documentation:
- https://checkstyle.org/checks/blocks/leftcurly.html
- https://checkstyle.org/checks/misc/indentation.html

I have downloaded the latest checkstyle from: https://checkstyle.org/cmdline.html#Download_and_Run
I have executed the cli and showed it below, as cli describes the problem better than 1,000 words

```bash
/var/tmp $ javac mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java

/var/tmp $ cat minimal-rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
  "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
  "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="LeftCurly">
      <property name="tokens"
        value="ANNOTATION_DEF, CLASS_DEF, CTOR_DEF, ENUM_CONSTANT_DEF, ENUM_DEF,
                      INTERFACE_DEF, LAMBDA, LITERAL_CATCH, LITERAL_DEFAULT,
                      LITERAL_DO, LITERAL_ELSE, LITERAL_FINALLY, LITERAL_FOR, LITERAL_IF,
                      LITERAL_SWITCH, LITERAL_SYNCHRONIZED, LITERAL_TRY, LITERAL_WHILE, METHOD_DEF,
                      OBJBLOCK, STATIC_INIT, RECORD_DEF, COMPACT_CTOR_DEF"/>
    </module>
    <module name="Indentation">
      <property name="basicOffset" value="2"/>
      <property name="braceAdjustment" value="2"/>
      <property name="caseIndent" value="2"/>
      <property name="throwsIndent" value="4"/>
      <property name="lineWrappingIndentation" value="4"/>
      <property name="arrayInitIndent" value="2"/>
    </module>
  </module>
</module>

/var/tmp $ cat mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java
package com.example.checkstyle;

public class CheckstyleScope {
  private static void indentationIssue(Condition condition) {
    switch (condition) {
      case TRUE:
        {
          System.out.println("True");
          break;
        }
      case FALSE:
        {
          System.out.println("False");
          break;
        }
      default:
        System.out.println("Other");
    }

    {
      System.out.println("True");
    }
  }

  private enum Condition {
    TRUE,
    FALSE
  }
}


/var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US"
/var/tmp $ java $RUN_LOCALE -jar ~/Downloads/checkstyle-10.12.7-all.jar -c ./minimal-rules.xml mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java
Starting audit...
[ERROR] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:14:9: 'block lcurly' has incorrect indentation level 8, expected level should be 6. [Indentation]
[ERROR] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:15:11: 'block' child has incorrect indentation level 10, expected level should be 8. [Indentation]
[ERROR] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:16:11: 'block' child has incorrect indentation level 10, expected level should be 8. [Indentation]
[ERROR] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:17:9: 'block rcurly' has incorrect indentation level 8, expected level should be 6. [Indentation]
[ERROR] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:19:9: 'block lcurly' has incorrect indentation level 8, expected level should be 6. [Indentation]
[ERROR] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:20:11: 'block' child has incorrect indentation level 10, expected level should be 8. [Indentation]
[ERROR] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:21:11: 'block' child has incorrect indentation level 10, expected level should be 8. [Indentation]
[ERROR] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:22:9: 'block rcurly' has incorrect indentation level 8, expected level should be 6. [Indentation]
Audit done.
Checkstyle ends with 8 errors.

```

---
If I modify the rules to change to `<property name="braceAdjustment" value="0"/>`,
I manage to get ride of some errors but new ones appears:

```bash
/var/tmp $ java -jar ~/Downloads/checkstyle-10.12.7-all.jar -c ./minimal-rules.xml mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java 
Starting audit...
[ERROR] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:27:5: 'block lcurly' has incorrect indentation level 4, expected level should be 6. [Indentation]
[ERROR] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:29:5: 'block rcurly' has incorrect indentation level 4, expected level should be 6. [Indentation]
Audit done.
Checkstyle ends with 2 errors.
```

The file was previously formatted with google-java-format (https://github.com/google/google-java-format/releases/tag/v1.19.2):

```bash
/var/tmp $ java -jar ~/Downloads/google-java-format-1.19.2-all-deps.jar --replace mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java
```

Might be linked with https://github.com/checkstyle/checkstyle/issues/3612, https://github.com/checkstyle/checkstyle/issues/3899 and https://github.com/checkstyle/checkstyle/issues/9326

**Comment by romani** [comment] 2024-01-18 16:21
>If I modify the rules to change to

Please change your description example to have single config and just reference what is not correct violations to your mind.

**Comment by NathanEckert** [comment] 2024-01-18 16:47
> > If I modify the rules to change to
> 
> Please change your description example to have single config and just reference what is not correct violations to your mind.
> 

There is no non-logical violation, it's just that I cannot configure checkstyle to have no violation, as the options are contradictory

> > The file was previously formatted with google-java-format:
> 
> Please share link to description of this tool. Keep in mind there are bunch interpretations of Google Style, different tools might treat Google style wording differently.

I added the link to download the formatter

**Comment by romani** [comment] 2024-01-18 16:56
So all you try to do is to make checkstyle produce no violations on code that is formatted by another tool?

**Comment by NathanEckert** [comment] 2024-01-18 21:11
> So all you try to do is to make checkstyle produce no violations on code that is formatted by another tool?

Sort of, but I would expect to be able to configure checkstyle, such as if the formatter is the google implementation of google-java-format, no error is generated.

For example, if I take the official file of this repo available here https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml, and ran the formatter, I still get the following checkstyle errors:

```bash
Starting audit...
[WARN] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:10:1: Missing a Javadoc comment. [MissingJavadocType]
[WARN] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:14:9: '{' at column 9 should be on the previous line. [LeftCurly]
[WARN] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:19:9: '{' at column 9 should be on the previous line. [LeftCurly]
[WARN] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:27:5: 'block lcurly' has incorrect indentation level 4, expected level should be 6. [Indentation]
[WARN] /home/path/mymodule/src/main/java/com/example/checkstyle/CheckstyleScope.java:29:5: 'block rcurly' has incorrect indentation level 4, expected level should be 6. [Indentation]
Audit done.
```

**Comment by romani** [comment] 2024-01-19 03:20
We never tested our Check against this tool, there are numerous interpretations of vague Google style wording.
Please be aware of https://github.com/checkstyle/checkstyle/labels/indentation

If you be able make input java file (after auto formatting) to run against checkstyle 
config, and it will be clear violation of what  Check is declaring to do, I can approve issue.

I can not approve issue by fact that we are not compliant in behavior with some other tool.

**Comment by NathanEckert** [comment] 2024-01-19 10:13
I am not claiming that `checkstyle` is not compliant to google-java-format (as it is a different tools, I don't expect it it to work out of the box).
However, I would expect to be able to configure it so it does on my specific code snippet. I was also surprised that the rule file provided is not compatible with the google provided implementation of the google-java-codestyle formatter.

This issue I am opening is two fold:
- Lack of configurability so that no error is raised for the provided formatted code snippet
- Issue with the provided `google_checks.xml` file as it is not compliant with `google-java-format` (this one is more debatable as you mentioned as there are different interpretation of what the google java guideline is, however I would expect `google-java-format` to be the reference implementation)

**Comment by romani** [comment] 2024-01-19 16:35
>however I would expect google-java-format to be the reference implementation)

google-java-format appears [year](https://github.com/google/google-java-format/releases?page=3) after checkstyle [provided](https://github.com/checkstyle/checkstyle/commits/c17bf06af9334ea1f6096868e591e6ee62774540/google_checks.xml?browsing_rename_history=true&new_path=src/main/resources/google_checks.xml&original_branch=master) style validation. But now a day better to be starting looking on each other. Did you consider google-java-format to have a defect?

Let's focus on checkstyle Check requirements and problems.

Let's make statement of problem like:
I have this java code, it is according to Google style (some quotes from style guide) , I run latest Checkstyle with embedded google config in checkstyle jar and see violation and I think this is not good.

In such wording it be easier to accept issue.

**Comment by NathanEckert** [comment] 2024-01-19 17:03
> Did you consider google-java-format to have a defect?

I did consider it but ruled it out, as https://google.github.io/styleguide/javaguide.html#s4.1-braces does not mention anonymous scope, so implementations are free do to whatever they want, so one my want to configure a validation tool such as the code snippet provided does not raise any error.

**Comment by romani** [comment] 2024-01-20 03:28
Please create issue on Google style to clarify it, if they update doc as google-java-format doing in some version (latest for today) we can change checkstyle config and Check to match their rules.

And I hope new version of formatter will change behavior.

**Comment by cushon** [comment] 2024-01-22 16:38
This is a bug in checkstyle's implementation of Google Java Style.

> Let's make statement of problem like:
> I have this java code

```java
package com.example.checkstyle;

public class CheckstyleScope {
  private static void indentationIssue(Condition condition) {
    switch (condition) {
      case TRUE:
        {
          System.out.println("True");
          break;
        }
      case FALSE:
        {
          System.out.println("False");
          break;
        }
      default:
        System.out.println("Other");
    }

    {
      System.out.println("True");
    }
  }

  private enum Condition {
    TRUE,
    FALSE
  }
}
```

> it is according to Google style (some quotes from style guide)

From https://google.github.io/styleguide/javaguide.html#s4.1.2-blocks-k-r-style

> for nonempty blocks and block-like constructs:
> 
> * No line break before the opening brace, except as detailed below.
>
> ...
>
> Exception: In places where these rules allow a single statement ending with a semicolon (;), a block of statements can appear, and the opening brace of this block is preceded by a line break. Blocks like these are typically introduced to limit the scope of local variables, **for example inside switch statements.**

Also, from https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation

> Each time a new block or block-like construct is opened, the indent increases by two spaces. When the block ends, the indent returns to the previous indent level.

---

> I run latest Checkstyle with embedded google config in checkstyle jar and see violation

```
java -jar checkstyle-10.12.7-all.jar -c '/google_checks.xml' C CheckstyleScope.java
Starting audit...
[WARN] /tmp/tmp.9gS8F8iysU/CheckstyleScope.java:3:1: Missing a Javadoc comment. [MissingJavadocType]
[WARN] /tmp/tmp.9gS8F8iysU/CheckstyleScope.java:7:9: '{' at column 9 should be on the previous line. [LeftCurly]
[WARN] /tmp/tmp.9gS8F8iysU/CheckstyleScope.java:12:9: '{' at column 9 should be on the previous line. [LeftCurly]
[WARN] /tmp/tmp.9gS8F8iysU/CheckstyleScope.java:20:5: 'block lcurly' has incorrect indentation level 4, expected level should be 6. [Indentation]
[WARN] /tmp/tmp.9gS8F8iysU/CheckstyleScope.java:22:5: 'block rcurly' has incorrect indentation level 4, expected level should be 6. [Indentation]
Audit done.
```

---

> and I think this is not good.

The line breaks between e.g. `case TRUE:` and `{` are required, the `LeftCurly` finding is incorrect, the line break is required by https://google.github.io/styleguide/javaguide.html#s4.1.2-blocks-k-r-style. This was previously reported in https://github.com/checkstyle/checkstyle/issues/6392, it looks like the incorrect 'Indentation' diagnostics from that bug were fixed but not the 'LeftCurly' diagnostic.

The 'Indentation' findings above are also incorrect. Checkstyle accepts the indentation below, which is disallowed by https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation.

```diff
*** CheckstyleScope.java.bak    2024-01-22 08:34:18.473151354 -0800
--- CheckstyleScope.java        2024-01-22 08:34:26.561141138 -0800
***************
*** 16,26 ****
        default:
          System.out.println("Other");
      }

!     {
!       System.out.println("True");
!     }
    }

    private enum Condition {
      TRUE,
--- 16,26 ----
        default:
          System.out.println("Other");
      }

!       {
!         System.out.println("True");
!       }
    }

    private enum Condition {
      TRUE,
```

**Comment by romani** [comment] 2024-03-16 23:19
@cushon , thanks a lot for detailed report.
yes, checkstyle style guide coverage is outdated .... we are stuck in 2018 year https://checkstyle.org/styleguides/google-java-style-20180523/javaguide.html there were no such exception for case blocks.

**Comment by Zopsss** [comment] 2024-09-23 18:33
@romani @rdiachenko after removing `braceAdjustment` from Indentation module, false-positives errors gets removed:

```xml
    <module name="Indentation">
      <property name="basicOffset" value="2"/>
      <property name="braceAdjustment" value="2"/>
      <property name="caseIndent" value="2"/>
      <property name="throwsIndent" value="4"/>
      <property name="lineWrappingIndentation" value="4"/>
      <property name="arrayInitIndent" value="2"/>
    </module>
```

```java
public class Test { { // false-negative
    System.out.println("Testing");
  }

  {
    System.out.println("Testing");
  }

  int bbb = 9; { // should be separated by a blank line
    System.out.println("Testing");
  }

  int aaa = 9;
  { // should be separated by a blank line
    System.out.println("Testing");
  }

  {
    System.out.println("Testing");
  } int testtttt = 00;

  int ccc = 9;

  { // good
    System.out.println("Testing");
  }

  void test() {
    int b = 9; { // false-negative
      System.out.println("Testing");
    }

    Test t = new Test(); { // false-negative
      System.out.println("Testing");
    }
  }

  Test(int x) {
    int b = 9; { // false-negative
      System.out.println("Testing");
    }

    Test t = new Test(); { // false-negative
      System.out.println("Testing");
    }
  }

  static {
  }

  static
  { // violations (LeftCurlyEol), false-positive ( #14294 )
  } // false-positive ( #14294 )

  void test2() {
    switch (a == 2) {
      case true:
      { // violations (LeftCurlyNl), false-positive ( #14294 )
      } // false-positive ( #14294 )

      break;

      default:
      { // violations (LeftCurlyNl), false-positive ( #14294 )
      } // false-positive ( #14294 )

      break;
    }
  }

  Runnable runnable = () -> {
    while (condition()) {
      method();
    }
  };

  Runnable runnable2 = () ->
  { // violations (LeftCurlyEol), false-positive ( #14294 )
    while (condition()) {
      method();
    }
  }; // false-positive ( #14294 )

  private boolean condition() {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("Unimplemented method 'condition'");
  }

}
```

without removing `braceAdjustment`:

```
$ java -jar .\checkstyle-10.18.1-all.jar -c .\google_checks_lcurly.xml .\Test.java
Starting audit...
[WARN] C:\checkstyle testing\.\Test.java:1:1: Missing a Javadoc comment. [MissingJavadocType]
[WARN] C:\checkstyle testing\.\Test.java:9:16: 'INSTANCE_INIT' should be separated from previous line. [EmptyLineSeparator]
[WARN] C:\checkstyle testing\.\Test.java:14:3: 'INSTANCE_INIT' should be separated from previous line. [EmptyLineSeparator]
[WARN] C:\checkstyle testing\.\Test.java:20:3: '}' at column 3 should be alone on a line. [RightCurlyAlone]
[WARN] C:\checkstyle testing\.\Test.java:20:5: 'VARIABLE_DEF' should be separated from previous line. [EmptyLineSeparator]
[WARN] C:\checkstyle testing\.\Test.java:52:3: 'static initialization lcurly' has incorrect indentation level 2, expected level should be 4. [Indentation]
[WARN] C:\checkstyle testing\.\Test.java:52:3: '{' at column 3 should be on the previous line. [LeftCurlyEol]
[WARN] C:\checkstyle testing\.\Test.java:53:3: 'static initialization rcurly' has incorrect indentation level 2, expected level should be 4. [Indentation]
[WARN] C:\checkstyle testing\.\Test.java:58:7: 'block lcurly' has incorrect indentation level 6, expected level should be 8. [Indentation]
[WARN] C:\checkstyle testing\.\Test.java:59:7: 'block rcurly' has incorrect indentation level 6, expected level should be 8. [Indentation]
[WARN] C:\checkstyle testing\.\Test.java:61:7: 'block' child has incorrect indentation level 6, expected level should be 8. [Indentation]       
[WARN] C:\checkstyle testing\.\Test.java:64:7: 'block lcurly' has incorrect indentation level 6, expected level should be 8. [Indentation]      
[WARN] C:\checkstyle testing\.\Test.java:65:7: 'block rcurly' has incorrect indentation level 6, expected level should be 8. [Indentation]      
[WARN] C:\checkstyle testing\.\Test.java:67:7: 'block' child has incorrect indentation level 6, expected level should be 8. [Indentation]       
[WARN] C:\checkstyle testing\.\Test.java:78:3: 'block lcurly' has incorrect indentation level 2, expected level should be 4. [Indentation]      
[WARN] C:\checkstyle testing\.\Test.java:78:3: '{' at column 3 should be on the previous line. [LeftCurlyEol]
[WARN] C:\checkstyle testing\.\Test.java:82:3: 'block rcurly' has incorrect indentation level 2, expected level should be 4. [Indentation]      
Audit done.
```

after removing it:

```xml
    <module name="Indentation">
      <property name="basicOffset" value="2"/>
      <!-- <property name="braceAdjustment" value="2"/> -->
      <property name="caseIndent" value="2"/>
      <property name="throwsIndent" value="4"/>
      <property name="lineWrappingIndentation" value="4"/>
      <property name="arrayInitIndent" value="2"/>
    </module>
```

```
$ java -jar .\checkstyle-10.18.1-all.jar -c .\google_checks_lcurly.xml .\Test.java
Starting audit...
[WARN] C:\checkstyle testing\.\Test.java:1:1: Missing a Javadoc comment. [MissingJavadocType]
[WARN] C:\checkstyle testing\.\Test.java:9:16: 'INSTANCE_INIT' should be separated from previous line. [EmptyLineSeparator]
[WARN] C:\checkstyle testing\.\Test.java:14:3: 'INSTANCE_INIT' should be separated from previous line. [EmptyLineSeparator]
[WARN] C:\checkstyle testing\.\Test.java:20:3: '}' at column 3 should be alone on a line. [RightCurlyAlone]
[WARN] C:\checkstyle testing\.\Test.java:20:5: 'VARIABLE_DEF' should be separated from previous line. [EmptyLineSeparator]
[WARN] C:\checkstyle testing\.\Test.java:52:3: '{' at column 3 should be on the previous line. [LeftCurlyEol]
[WARN] C:\checkstyle testing\.\Test.java:61:7: 'block' child has incorrect indentation level 6, expected level should be 8. [Indentation]
[WARN] C:\checkstyle testing\.\Test.java:67:7: 'block' child has incorrect indentation level 6, expected level should be 8. [Indentation]
[WARN] C:\checkstyle testing\.\Test.java:78:3: '{' at column 3 should be on the previous line. [LeftCurlyEol]
Audit done.
```

diff of both outputs:

```diff
$ diff -u withProperty.txt withoutProperty.txt 
--- withProperty.txt    2024-09-24 00:00:54.612087500 +0530
+++ withoutProperty.txt 2024-09-24 00:01:31.217213700 +0530
@@ -5,16 +5,8 @@
 [WARN] C:\checkstyle testing\.\Test.java:14:3: 'INSTANCE_INIT' should be separated from previous line. [EmptyLineSeparator]
 [WARN] C:\checkstyle testing\.\Test.java:20:3: '}' at column 3 should be alone on a line. [RightCurlyAlone]
 [WARN] C:\checkstyle testing\.\Test.java:20:5: 'VARIABLE_DEF' should be separated from previous line. [EmptyLineSeparator]
-[WARN] C:\checkstyle testing\.\Test.java:52:3: 'static initialization lcurly' has incorrect indentation level 2, expected level should be 4. [Indentation]
 [WARN] C:\checkstyle testing\.\Test.java:52:3: '{' at column 3 should be on the previous line. [LeftCurlyEol]
-[WARN] C:\checkstyle testing\.\Test.java:53:3: 'static initialization rcurly' has incorrect indentation level 2, expected level should be 4. [Indentation]
-[WARN] C:\checkstyle testing\.\Test.java:58:7: 'block lcurly' has incorrect indentation level 6, expected level should be 8. [Indentation]     
-[WARN] C:\checkstyle testing\.\Test.java:59:7: 'block rcurly' has incorrect indentation level 6, expected level should be 8. [Indentation]     
 [WARN] C:\checkstyle testing\.\Test.java:61:7: 'block' child has incorrect indentation level 6, expected level should be 8. [Indentation]      
-[WARN] C:\checkstyle testing\.\Test.java:64:7: 'block lcurly' has incorrect indentation level 6, expected level should be 8. [Indentation]     
-[WARN] C:\checkstyle testing\.\Test.java:65:7: 'block rcurly' has incorrect indentation level 6, expected level should be 8. [Indentation]     
 [WARN] C:\checkstyle testing\.\Test.java:67:7: 'block' child has incorrect indentation level 6, expected level should be 8. [Indentation]      
-[WARN] C:\checkstyle testing\.\Test.java:78:3: 'block lcurly' has incorrect indentation level 2, expected level should be 4. [Indentation]     
 [WARN] C:\checkstyle testing\.\Test.java:78:3: '{' at column 3 should be on the previous line. [LeftCurlyEol]
-[WARN] C:\checkstyle testing\.\Test.java:82:3: 'block rcurly' has incorrect indentation level 2, expected level should be 4. [Indentation]     
 Audit done.
```

I haven't checked the other cases yet so Im not so sure if this can negatively impact in other places

**Comment by Zopsss** [comment] 2024-09-27 09:55
@rdiachenko @romani

**Comment by romani** [comment] 2024-10-11 22:06
@Zopsss, please share checkstyle snapshot behavior on this code.

**Comment by romani** [comment] 2024-10-12 04:16
latest behavior:
```
$ java -jar checkstyle-10.18.3-SNAPSHOT-all.jar -c /google_checks.xml Test.java 
Starting audit...
[WARN] /var/tmp/Test.java:1:1: Missing a Javadoc comment. [MissingJavadocType]
[WARN] /var/tmp/Test.java:18:5: 'block lcurly' has incorrect indentation level 4, expected level should be 6. [Indentation]
[WARN] /var/tmp/Test.java:20:5: 'block rcurly' has incorrect indentation level 4, expected level should be 6. [Indentation]
Audit done.
```

**Comment by romani** [comment] 2024-10-12 12:32
this works on such example, but we need bigger regression testing 
```
$ cat config.xml 
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
  <module name="TreeWalker">
    <module name="SuppressionXpathSingleFilter">
      <property name="checks" value="Indentation"/>
      <property name="query" value="//SLIST/SLIST"/>
    </module>
    <module name="SuppressionXpathSingleFilter">
      <property name="checks" value="Indentation"/>
      <property name="query" value="//SLIST/SLIST/RCURLY"/>
    </module>
    <module name="Indentation">
      <property name="basicOffset" value="2"/>
      <property name="braceAdjustment" value="2"/>
      <property name="caseIndent" value="2"/>
      <property name="throwsIndent" value="4"/>
      <property name="lineWrappingIndentation" value="4"/>
      <property name="arrayInitIndent" value="2"/>
    </module>
  </module>
</module>

$ cat Test.java 
public class Test {
  private static void indentationIssue(int condition) {
    {
      System.out.println("True");
    }
  }
}

$ java -jar checkstyle-10.18.3-SNAPSHOT-all.jar -c config.xml Test.java 
Starting audit...
Audit done.

```

**Comment by romani** [comment] 2024-10-19 14:08
fixed by https://github.com/checkstyle/checkstyle/pull/15771

There are a bit more false-negatives appears for code blocks in result of fix, but we will address them separately at https://github.com/checkstyle/checkstyle/issues/15769

**Closed by romani** 2024-10-19 14:08 UTC
Labels: approved, indentation, google style, false positive
